- core/pom.xml
jnr-posix 3.0.9 depends on jnr-constants 0.8.6, but jruby-core is still
specifying 0.8.5.
> (MAINT) fix jnr-constants version in pom

- core/src/main/java/org/jruby/util/cli/OutputStrings.java
I don't know if not including `--dev` in the output when running `ruby --help` is an oversight or intentional. I didn't know about it before today, and a big part of that is that it's not shown when you run `ruby --help`.
> Add --dev to the output of --help

- tool/jt.rb
Would this be useful to people not as used to the code base as we are?
You should set `function jt { ruby tool/jt.rb $@; }` then run `jt help`.
@thomaswue @nirvdrum @eregon
> [Truffle] jt tool.

- core/src/main/java/org/jruby/RubyArray.java
This fixes #2437 and follows MRI approach for RubyArray hash method,  however for consistency across the codebase I have made use of SipHashInline and PerlHash unlike MRI which makes use of MurMurHash.
> Follow MRI implementation for RubyArray hash

- core/src/main/java/org/jruby/RubyThreadGroup.java
Possibly fixes #2446, we don't need synchronise for a locally created RubyArray .
> No need to synchronise a newly created local RubyArray

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/TypeConverter.java
As of 2.0, MRI raises "no implicit conversion..." `TypeError` in certain situations. I've tried to make respective changes to `TypeConverter`. While not being sure it's 100%  right, at least the following also seems to behave correctly with the patch.
```bash
$ rbenv shell 2.0.0-p598
$ ruby -e '"a" + 1'
no implicit conversion of Fixnum into String (TypeError)
$ rbenv shell jruby-9.0.0.0-dev
$ ruby -e '"a" + 1'
TypeError: can't convert Fixnum into String
```
The String part addresses then `test_start_with?`and `test_end_with?` in test_string.rb
> Implicit type conversion error + String#start_with? and #end_with? error

- core/src/main/ruby/jruby/java/core_ext/object.rb
Fixed #2324 by getting rid of flatten! as hinted by @headius. I thought about writing a test for the method, too, as I couldn't find any. Too bad, I couldn't find a way to run a single test in tests/jruby either. Is that the right place for such tests? Help appreciated.
> Replace array flattening with manual handling in java_import

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/StringSupport.java
- spec/regression/GH-1675_casecmp_on_UTF16LE_encoded_string_spec.rb
This commit fixes issue #1675 on jruby-1_7 branch. I wrote a rspec test using the available encodings in addition to UTF-16LE. See *GH-1675_casecmp_on_UTF16LE_encoded_string_spec.rb* for details.
> Fix for issue 1675 on jruby-1_7: String#casecmp on UTF-16LE encoded string

- core/src/main/ruby/jruby/kernel/gc.rb
Calling `GC::Profiler.total_time` dumps the headers used by `GC::Profiler.result` when the `GC::Profiler::NotifiedProfiler` is being used. Given the method doesn't dump anything, it looks like this isn't needed and could be dropped.
> Remove unnecessary puts for GC::Profiler.total_time

- core/src/main/java/org/jruby/RubyYielder.java
Fixes an old issue #2376 with RubyYielder class.
This fix passes Rubyspecs and MRI specs, however let me know if there any changes required.
> Fixed yielded arrays of 1 element bug when using Enumerator#first

- core/src/main/java/org/jruby/util/IdUtil.java
While working on #2319 I found this unused var in IdUtil class, since the issue is already fixed I thought I should send a PR for this. 
JVM should already optimise dead code, so I am guessing it won't really add much.
> Removed unused var

- core/src/main/java/org/jruby/util/ConvertBytes.java
Addresses issue #2360 for base <= 10, both MRI and Rubyspecs test suites pass.
Running the benchmark provided without the patch
```
Calculating -------------------------------------
#to_i with an integer in a string
141.004k i/100ms
#to_i with a float in a string
157.672k i/100ms
#to_i with an empty string
172.789k i/100ms
#to_i with an integer and extra text
134.750k i/100ms
-------------------------------------------------
#to_i with an integer in a string
17.907M (±17.1%) i/s -     86.153M
#to_i with a float in a string
14.668M (±12.6%) i/s -     72.056M
#to_i with an empty string
32.909M (±24.9%) i/s -    153.437M
#to_i with an integer and extra text
7.122M (±11.9%) i/s -     34.900M
```
Running with the patch
```
Calculating -------------------------------------
#to_i with an integer …
```
> Improved String#to_i performance for base <= 10 

- core/src/main/java/org/jruby/RubyEnumerator.java
This PR implements Enumerator#feed and addresses #1571.  However the behaviour is not same as MRI because of the difference in implementation of next in JRuby and MRI.
Here is an example to demonstrate the difference,
**MRI**
```Ruby
a = [1, 2, 3]
m = a.to_enum(:map!)
m.next # a -> [1, 2, 3], returns 1
m.next # a -> [nil, 2, 3], returns 2
m.next # a -> [nil, nil, 3], returns 3
m.next # a -> [nil, nil, nil],  throws StopIteration exception and calls the yield/method
```
**JRuby**
```Ruby
a = [1, 2, 3]
m = a.to_enum(:map!)
m.next # a -> [nil, 2, 3], returns 1
m.next # a -> [nil, nil, 3], returns 2
m.next # a -> [nil, nil, nil], returns 3
m.next # a -> [nil, nil, nil],  throws StopIteration exception and doesn't call yield/method
```
So basically when you call next first time in MRI, it …
> Implemented Enumerator#feed method

- core/src/main/java/org/jruby/internal/runtime/methods/IRMethodArgs.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
This PR partially addresses issue #2512 (still need to fix the arity bit), 
here is the difference it output (using the method provided by the issue)
```Ruby
[[:key, :arg1], [:key, :arg2]]
```
After the patch
```Ruby
[[:key, :arg1], [:keyreq, :arg2]]
```
> Parse keyreq correctly in RubyMethod args

- core/src/main/java/org/jruby/RubyKernel.java
- test/mri/excludes/TestVariable.rb
Fixes #2129 by removing the duplicate variables and matching the order across different scopes to MRI.
> Fixed a bug with local_variables ordering and duplicate variables

- test/jruby/test_kernel.rb
Opening a new PR since last one was merged, but this fixes the order to match MRI.
> Forgot to match the order of JRuby local variables spec to MRI

- truffle/src/main/java/org/jruby/truffle/nodes/methods/arguments/CheckArityNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/methods/arguments/ReadKeywordArgumentNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/methods/arguments/ReadKeywordRestArgumentNode.java
- truffle/src/main/java/org/jruby/truffle/runtime/RubyArguments.java
To get to know the keyword implementation, I did a little bit clean up:
To reduce duplicate code between CheckArityNode, ReadKeywordArgumentNode,
ReadKeywordRestArgumentNode move the getKeywordsHash method into
RubyArguments - where all the other argument helper functions live.
> [Truffle] deduplicate getKeywordsHash into RubyArguments

- truffle/src/main/java/org/jruby/truffle/translator/LoadArgumentsTranslator.java
When calling a method having a keyword argument that is not used in the method body the frame descriptor cannot find a frame slot and returns `null`.
Example:
```ruby
def method(a: 1)
end
method(a: 2)
```
With assertions enabled it returns the following:
```
> JAVA_OPTS="-ea" ./bin/jruby -X+T -e "def method(a: 1); end; method(a: 2)"
Truffle internal error: java.lang.AssertionError
java.lang.AssertionError
at org.jruby.truffle.nodes.methods.locals.FrameSlotNode.<init>(FrameSlotNode.java:27)
at org.jruby.truffle.nodes.methods.locals.WriteLocalVariableNode.<init>(WriteLocalVariableNode.java:25)
at org.jruby.truffle.nodes.methods.locals.WriteLocalVariableNodeFactory$WriteLocalVariableBaseNode.<init>(WriteLocalVariableNodeFactory.java:81)
at …
```
> [Truffle] Fix null FrameSlot when kwarg is not used

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyObject.java
- test/jruby/test_object_id.rb
In the process of debugging an [unrelated issue](https://github.com/avdi/naught/issues/65#issuecomment-71541149), I came across an inconsistency between JRuby and CRuby: the `#itself` and `#object_id` methods are defined on `BasicObject` instead of `Object`.
I am not an expert :coffee: programmer nor am I particularly familiar with the JRuby codebase, however I’ve made an attempt to fix this issue myself, as it appears to be mostly a :scissors: and :spaghetti: job.
I’ve also attempted to add a test to prevent this behavior from regressing, however I may have put it in the wrong place, as JRuby appears to have multiple test suites.
I’ve also taken the liberty to remove the `Object#id` method, which was deprecated when Ruby 1.9 was released and removed from CRuby in version 1.9.3.
> Move methods from BasicObject to Object

- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyObject.java
[I was previously unaware](https://github.com/jruby/jruby/pull/2520) that Ruby does not define any methods directly on the `Object` class. [`Object` is merely `BasicObject` with `Kernel` mixed in.](https://twitter.com/sferik/status/560537968624951297)
This pull request makes this right.
> Move #itself and #object_id from Object to Kernel

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- spec/regression/GH-2524_bigdecimal_loss_of_precision_with_different_excution_order_spec.rb
This commit fixes issue #2524 on master.  Improved algorithm to set the precision of BigDecimal#op_quo19_20 method.
> Fix for issue 2524 on master: [BigDecimal] Loss of precision with different execution order 

- core/src/main/java/org/jruby/util/unsafe/UnsafeHolder.java
It was breaking `StampedVariableAccessor`, resulting in
not sinchronized access to instance variables
when `StampedVariableAccessor` was used.
> Re-enblig memory fences

- core/src/main/java/org/jruby/RubyDir.java
- test/mri/excludes/TestDir.rb
* Make Dir#inspect and Dir#path work with empty path.
* Remove redundant test exclusions and replace "needs investigation"
with a proper description for others.
> Minor fixes to Dir methods

- core/src/main/java/org/jruby/RubyStruct.java
- spec/regression/GH-2182_struct_inspect_has_ascii_encoding_spec.rb
This commit fixes issue #2182 on jruby-1_7 branch. Inspect method of Struct with utf8 string member should return a utf8 string.
> Fix for issue 2182 on jruby-1_7 : Struct#inspect with utf8 encode string member

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- spec/regression/GH-2524_bigdecimal_loss_of_precision_with_different_excution_order_spec.rb
This commit fixes issue #2524 on jruby-1_7 branch. Improved algorithm to set the precision of BigDecimal#op_quo19_20 method.
> Fix for issue 2524 on jruby-1_7: [BigDecimal] Loss of precision with different execution order 

- core/src/main/java/org/jruby/RubyHash.java
Previously, if `any?` returned true early (or threw an exception) the hash would be marked as still iterating, and thus prevent updates.
Expressed in Ruby code, the following results in "can't add a new key into hash during iteration" errors:
```ruby
h = {1 => 2}; h.any? { true }; h[2] = 1
h = {1 => 2}; h.any? { raise } rescue nil; h[2] = 1
```
I would have liked to put them into tests, but wasn't completely sure were would be most appropriate.
> Exit iterator when `RubyHash#any?` short-circuits

- core/src/main/java/org/jruby/RubyString.java
- test/test_primitive_to_java.rb
currently one can `42.to_java(:char)` to get a char (java.lang.Character) instance put it's certainly not the most obvious way to do it.
this PR adds support for converting strings of length 1 to (native) char objects e.g. `'A'.to_java(:char)`
> support for easy (Ruby) String to (Java) char conversion

- core/src/main/java/org/jruby/ir/IRManager.java
- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/ir/passes/OptimizeDelegationPass.java
If an explicit block is captured as a proc, but its only usage is
converting it back to a block and passing it through, we can skip the
conversion entirely, and just pass through the original block.
This pass looks for all explicit block conversions, and checks if
they're ever used in any context besides being passed as a block. If
not, we rewrite all uses of the proc to pass the block through instead.
The dead code elimination will remove the proc as an unused variable.
It may be possible to implement this without adding another compiler
pass, but I had trouble finding a place where it fit nicely, especially
since it needs to run before the LiveVariableAnalysis.
I believe the same optimization could occur to skip array allocation for splatted args, and hash allocation for double splatted …
> Skip block-to-proc conversion for explicit block syntax when possible

- core/src/main/java/org/jruby/lexer/yacc/StringTerm.java
- core/src/test/java/org/jruby/lexer/yacc/StringTermTest.java
- core/src/test/java/org/jruby/test/MainTestSuite.java
I create this pull request #2210, since the pull request #2064 for 1_7 branch can not be merged into master branch. This pull request improves handling of non ascii character after backslash of `org.jruby.lexer.yacc.StringTerm` class on master.  This change fixes #1069 and #1390.
> Fix for issue 1069 and 1390 on master: improve handling of non ascii character after backslash

- spec/truffle/tags/core/bignum/size_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/BignumNodes.java
Used RubyBignum as a reference for size implementation: 
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyBignum.java#L891
> [Truffle] Fixed Bignum#size implementation

- spec/truffle/tags/core/symbol/swapcase_tags.txt
- spec/truffle/tags/core/symbol/upcase_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/SymbolNodes.java
Reference String#upcase for implementation
> [Truffle] Implemented Symbol#upcase, added final in Symbol#swapcase

- spec/truffle/tags/core/symbol/capitalize_tags.txt
- spec/truffle/tags/core/symbol/casecmp_tags.txt
- spec/truffle/tags/core/symbol/comparison_tags.txt
- spec/truffle/tags/core/symbol/downcase_tags.txt
- spec/truffle/tags/core/symbol/encoding_tags.txt
- spec/truffle/tags/core/symbol/intern_tags.txt
- spec/truffle/tags/core/symbol/length_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/SymbolNodes.java
Fixing Symbol#<=>, Implementing Symol#capitalize, Symbol#casecmp,  Symbol#downcase, Symbol#encoding, Symbol#intern
> [Truffle] Fixing Symbol#<=>, Implementing Symbol Methods

- spec/truffle/tags/core/symbol/length_tags.txt
- spec/truffle/tags/core/symbol/size_tags.txt
- spec/truffle/tags/core/symbol/versions/encoding_1.9_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/SymbolNodes.java
- truffle/src/main/java/org/jruby/truffle/runtime/RubyContext.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/RubySymbol.java
- truffle/src/main/java/org/jruby/truffle/translator/BodyTranslator.java
to RubySymbol. Previously all were encoding as ASCII. A few string only methods are here to keep it backward compatible. I wasn't sure how to facture out the method calls to these.
I think SymbolNode could be considered to use ByteList instead of a String in the future.
> [Truffle] Passing through encoding information from SymbolNode

- spec/truffle/tags/core/encoding/aliases_tags.txt
- spec/truffle/tags/core/encoding/ascii_compatible_tags.txt
- spec/truffle/tags/core/encoding/compatible_tags.txt
- spec/truffle/tags/core/encoding/default_external_tags.txt
- spec/truffle/tags/core/encoding/list_tags.txt
- spec/truffle/tags/core/encoding/locale_charmap_tags.txt
- spec/truffle/tags/core/encoding/name_list_tags.txt
- spec/truffle/tags/core/regexp/escape_tags.txt
- spec/truffle/tags/core/regexp/quote_tags.txt
- spec/truffle/tags/core/regexp/union_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/EncodingNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/InteroplatedRegexpNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/RegexpNodes.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/RubyRegexp.java
- truffle/src/main/java/org/jruby/truffle/translator/BodyTranslator.java
to be able to return more correct options from the options method.
> [Truffle] Including RegexpOptions in RubyRegexp 

- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/common/IRubyWarnings.java
People seem to do that a lot after Sandi's book and not many of them
realize it actually produces a warning in CRuby.
Tried getting TestModule#test_attr out of the CRuby excluded failures,
because it was the only existing test I saw hinting of the behaviour,
however it also test that attribute names can't be a invalid
identifiers, which seems to go fine in JRuby.
> Produce a warning on private attribute accessors

- spec/truffle/tags/core/symbol/element_reference_tags.txt
- spec/truffle/tags/core/symbol/match_tags.txt
- spec/truffle/tags/core/symbol/slice_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/MatchDataNodes.java
- truffle/src/main/ruby/core/rubinius/bootstrap/string.rb
- truffle/src/main/ruby/core/rubinius/common/symbol.rb
String#num_bytes was added as a regular method because adding it as an attr_reader did not appear to work.
> [Truffle] Adding Implementations for Symbol#slice specs.

- spec/truffle/tags/core/array/repeated_permutation_tags.txt
- spec/truffle/tags/core/array/rindex_tags.txt
- truffle/src/main/ruby/core/rubinius/common/array.rb
- truffle/src/main/ruby/core/shims.rb
> [Truffle] Adding Array#repeated_permutations to array.rb

- spec/truffle/tags/core/array/at_tags.txt
- spec/truffle/tags/core/array/sample_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/ArrayNodes.java
I removed lowerFixnumParameter because it wasn’t handling double.
I’m not sure if the guard is needed?
> [Truffle] Adding #to_int to Array#at paramters.

- spec/truffle/tags/core/random/equal_value_tags.txt
- spec/truffle/tags/core/random/new_tags.txt
- spec/truffle/tags/core/random/rand_tags.txt
- spec/truffle/tags/core/random/seed_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/RandomPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/RubiniusPrimitiveManager.java
- truffle/src/main/ruby/core.rb
- truffle/src/main/ruby/core/rubinius/common/random.rb
Hey @chrisseaton @nirvdrum could you guys take a look?
Thanks!
> [Truffle] - Initial implementation of Ruby Random class.

- spec/truffle/tags/core/array/plus_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/ArrayGuards.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/ArrayNodes.java
I started to refactor this because I got the following error when adding #to_ary:
https://gist.github.com/bjfish/5c6e32592ecb1715a5fd
Please review.
Did I remove any specializations that were need?
Any other updates I should make here right now?
> [Truffle] Refactoring Array#+ to handle more cases and adding #to_ary

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/ir/operands/DynamicSymbol.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/test/java/org/jruby/test/TestRubyHash.java
- spec/regression/GH-2591_double-quoted_UTF8_hash_key_has_the_wrong_encoding_spec.rb
This commit fixes issue #2591 on master. Double-quoted UTF8 hash key encoding should be UTF8. @enebo and @headius please review my PR. Thanks!
> Fix for issue 2591 on master : double-quoted UTF8 hash key encoding

- spec/truffle/tags/core/string/element_reference_tags.txt
- spec/truffle/tags/core/string/slice_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/cast/TaintResultNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/StringNodes.java
@chrisseaton @eregon This is one of the proposed solutions for dealing with the need to skip tainting for certain specializations.  I don't particularly like using exceptions this way, but using a wrapper object would likely add much greater overhead.  The third alternative is to not use the CoreMethod option for tainting at all, but rather have each specialization that needs it use the `TaintResultNode` in place; this seems both error-prone (easy to forget one) and verbose.
I'm doing this as a PR to get feedback.  No hard feelings if you think this is terrible.
> [Truffle] Don't taint from self in String#[](String).

- README.md
@enebo, is this address one you want to publish ( as you do on your profile ) or is there a better one... or just remove this entirely?
> @enebo Address in README.md no longer works.

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyNumeric.java
- test/jruby/test_respond_to.rb
RubyBasicObject assumes that if respond_to? is undefined, it can just fast-track
method lookups. We have to also check for respond_to_missing?; failure to do so causes
Javaland respondsTo() calls to fail when an object defines respond_to_missing? (despite
the documentation's admonishment to not use it)
The practical case for this is ActiveSupport::Duration in ActiveSupport 4.2.1
> Support respond_to_missing? in respondsTo() lookups

- spec/truffle/tags/core/float/round_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/FloatNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/FloatPrimitiveNodes.java
- truffle/src/main/ruby/core/rubinius/common/float.rb
I don’t believe this is used in any benchmarks but wasn’t 100% sure.
> [Truffle] Move Float#round to float.rb

- truffle/src/main/java/org/jruby/truffle/nodes/core/FixnumNodes.java
For example, `jruby -X+T -e 'puts 1 < Rational(“1.3”)’`
> [Truffle] Adding fallback Specialization for Fixnum#<.

- lib/ruby/truffle/mri/timeout.rb
I’d like to add this stub to satisfy a require in the MRI tests.
> [Truffle] timeout stub

- lib/ruby/truffle/mri/open3.rb
- spec/truffle/tags/library/open3/popen3_tags.txt
- spec/truffle/truffle.mspec
I’d like to add this to be able to run MRI tests which have a require to this.
> [Truffle] Adding open3 to stdlib.

- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/StringPrimitiveNodes.java
I believe somewhere while running the MRI tests an edge case is causing the AST to change to use some specialization which returns long frequently (possibly Fixnum#-). I’d like to add these specializations to handle long. I’ve added a TODO to indicate these should be reviewed later on for correctness.
> [Truffle] Adding additional long handling for multiple specializations.

- pom.rb
- pom.xml
- test/pom.rb
- test/pom.xml
With workarounds (after current MRI test issues are fixed) `mvn -Ptruffle-mri-test` completes with:
```
[exec] Finished tests in 43.266000s, 38.5291 tests/s, 3727.0836 assertions/s.
[exec] 
[exec] 1667 tests, 161256 assertions, 0 failures, 0 errors, 1
```
> [Truffle] Add MRI test profile to pom files.

- lib/ruby/1.9/io/linux_console.rb
Adding ppc64 as supported platform for tty for branch jruby-1_7.
> Enabling tty for powerpc64 (1_7)

- core/src/main/java/org/jruby/RubySymbol.java
- spec/regression/GH-2896_symbol_inspect_spec.rb
This commit fixes issue #2896 on master and closes #2713. 
This patch is partial ports of the MRI *rb_str_symname_p* and *rb_enc_symname_p*.
Please review, @enebo.  If this patch is OK, I also hope that this patch is applied to 1_7 branch.
Thanks!
> Fix for issue 2896 on master : Symbol#inspect with utf8 encode string

- BUILDING.md
As was discussed in IRC
/cc @headius
> Add JAVA_HOME env line for mac os x building prerequisites

- core/src/main/java/org/jruby/RubyDir.java
- test/mri/excludes/TestFind.rb
The change affects at least Dir.new, Dir.open and Dir.entries.
Errno::EACCES is now raised unless access to the directory is
permitted.
> Make Dir raise Errno::EACCES

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- spec/regression/GH-2868_big_decimal_can_not_be_copied_spec.rb
It required to make `isNAN`, `infinitySign` and `zeroSign` fields non-final, but I think it makes not much difference as `value` isn't final already.
> Implementation of initialize_copy for BigDecimal (fix #2868)

- core/src/main/java/org/jruby/RubyRational.java
- core/src/main/java/org/jruby/util/Numeric.java
- test/mri/excludes/TestFixnum.rb
The patch adds special case handling for `0**n` and `1**n` to match the
MRI behavior. For example, the following cases are affected:
```ruby
0**Rational(1, 2) # => 0/1 instead of 0.0
0**Rational(-1, 2) # => ZeroDivisionError instead of Infinity`
1**Rational(1, 2) # => 1/1 instead of 1.0
```
> Fix power of 0 and 1 issues in Rational

- core/src/main/java/org/jruby/RubyFile.java
- test/mri/excludes/TestPathname.rb
The methods now support filename, mode, permissions and options as
separate parameters.
The actual logic seems to be there already. For example, the following now has the same behavior as MRI 1.9+.
```ruby
File.open('test', 'w', 0777, cr_newline: true) { |f| f.puts 'test' }
```
> Allow File.open and File.new with 4 arguments

- core/src/main/java/org/jruby/ext/socket/RubySocket.java
- core/src/main/java/org/jruby/ext/socket/SocketUtils.java
Added the reverse_lookup parameter to Socket.getaddrinfo. This was added in Ruby 1.9.
> Socket.getaddrinfo reverse_lookup

- lib/ruby/truffle/truffle/bigdecimal.rb
- spec/truffle/tags/library/bigdecimal/coerce_tags.txt
- spec/truffle/tags/library/bigdecimal/comparison_tags.txt
- spec/truffle/tags/library/bigdecimal/eql_tags.txt
- spec/truffle/tags/library/bigdecimal/finite_tags.txt
- spec/truffle/tags/library/bigdecimal/gt_tags.txt
- spec/truffle/tags/library/bigdecimal/infinite_tags.txt
- spec/truffle/tags/library/bigdecimal/minus_tags.txt
- spec/truffle/tags/library/bigdecimal/multiply_tags.txt
- spec/truffle/tags/library/bigdecimal/nan_tags.txt
- spec/truffle/tags/library/bigdecimal/new_tags.txt
- spec/truffle/tags/library/bigdecimal/nonzero_tags.txt
- spec/truffle/tags/library/bigdecimal/plus_tags.txt
- spec/truffle/tags/library/bigdecimal/precs_tags.txt
- spec/truffle/tags/library/bigdecimal/sign_tags.txt
- spec/truffle/tags/library/bigdecimal/to_f_tags.txt
- spec/truffle/tags/library/bigdecimal/uminus_tags.txt
- spec/truffle/tags/library/bigdecimal/uplus_tags.txt
- spec/truffle/tags/library/bigdecimal/zero_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/BigDecimalNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/BignumNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/FloatNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/fixnum/FixnumNodes.java
> [Truffle] Add special values of BigDecimal

- core/src/main/java/org/jruby/RubyString.java
This fixes #3019, where in certain cases it's possible to end up with
RubyString instances backed by very large unique ByteLists where only
a tiny portion of the bytes in the ByteList are actually needed.
What was happening is `modify` was being called on RubyString
instances too eagerly, resulting in unnecessary duplication of their
underlying ByteList instances instead of sharing when possible.
The two changes here are in `RubyString#newFrozen` and
`RubyString#resize` and I believe are more correct based on the C
implementation of these methods.
For `RubyString#newFrozen`, which roughly corresponds to
`rb_str_new_frozen` in
C (https://github.com/ruby/ruby/blob/v2_2_2/string.c#L932), the logic
looks to me to return the shared string and I don't see it calling
`str_make_independent`, …
> Don't call modify() on RubyStrings so eagerly when freezing them

- test/objectspace.index
- test/slow.index
This has been broken since July 2014 when some tests were moved from
test/ to test/jruby/. Thus, once reenabled some of these tests have
failures.
If for some reason they were purposely left disabled then we need to remove the test:slow_suites matrix from .travis.yml.
> Fix the slow test indexes so test:slow_suites runs tests again

- lib/ruby/shared/rubygems.rb
- lib/ruby/shared/rubygems/remote_fetcher.rb
CVE-2015-4020 was announced today. It is described here:
https://www.trustwave.com/Resources/Security-Advisories/Advisories/TWSL2015-009/?fid=6478.
The security vulnerability has been addressed in rubygems 2.4.8. As
jruby 1.7 has 2.4.6 included, this commit updates it to 2.4.8.
> Update rubygems to 2.4.8 to mitigate CVE-2015-4020

- truffle/src/main/java/org/jruby/truffle/nodes/core/TruffleInteropNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/CachedForeignDispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/CachedForeignGlobalDispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/UnresolvedDispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/interop/InteropNode.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/ArrayForeignAccessFactory.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/BasicForeignAccessFactory.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/HashForeignAccessFactory.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/RubyBasicObject.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/RubyMethodForeignAccessFactory.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/StringForeignAccessFactory.java
I am in process of redesigning com.oracle.truffle.api.interop API. Once that gets into development version of Truffle, JRuby+Truffle will need to be adopted. This pull request shows what changes I had to do make things running.
> Adopting to Redesigned Truffle Inter-operability API

- core/src/main/java/org/jruby/internal/runtime/methods/WrapperMethod.java
Ref: #3040
WrapperMethod can in some cases wrap a WrapperMethod, which causes `getRealMethod()` to return the wrapped WrapperMethod rather than the actual method at the bottom of the wrapping. This causes `Helpers.methodToArgumentDescriptors` to use the wrong logic for getting ArgumentDescriptors resulting in an NPE.
cc @enebo
> Fix getRealMethod for WrapperMethod which wraps a WrapperMethod

- core/src/main/java/org/jruby/RubySymbol.java
- spec/regression/GH-3035_spec.rb
This commit fixes issue #3035 on master. This changes the hash calculation method of SymbolTable entry.  The hash code of *javaStringHashCode(ByteList iso8859)* is calculated by Java's String class *hashCode()* with **ISO-8859-1** charset. @enebo please review my PR. Thanks!
> Fix for issue 3035 on master : change the hash code calculation method of SymbolTable entry.

- core/src/main/java/org/jruby/util/JRubyFile.java
- core/src/test/java/org/jruby/test/TestKernel.java
https://github.com/jruby/jruby/issues/2964
On windows the mvn -Ptest fails due to incorrect substitution of '/' and '\'.
See the write up for more details.
Cris Shupp
Greg Bowman
> This is a fix for bug ID 2964.  The URL to see the write up is here:

- truffle/src/main/java/org/jruby/truffle/nodes/core/TrufflePrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/runtime/subsystems/ThreadManager.java
- truffle/src/main/ruby/core/shims.rb
@chrisseaton @nirvdrum @pitr-ch 
This is the very simple commit to remove the GIL (cleanup will be done later when merged).
I tried a few trivial parallelism problems, a parallel `richards` benchmark and a few benchmarks from [NPB](http://www.nas.nasa.gov/publications/npb.html) ([Ruby version](http://www-hiraki.is.s.u-tokyo.ac.jp/members/tknose/)).
Multi-threaded programs need to be properly synchronized or they might crash in various ways (as in standard JRuby).
> [Truffle] No more global lock!

- core/src/main/java/org/jruby/RubyRange.java
Closes #3163
MRI checks if the EXCL flag is Qnil to see if the range has been initalized. This doesn't work
in Java because we use a boolean which can't have a nil value. Instead, introduce a new isInited
flag which is used to track the initialization state of the Range, which corrently permits #dup
while not permitting reinitialization of a Range.
> Fix RubyRange#initialize_copy mistakenly erroring on #dup'ing a range

- core/src/main/java/org/jruby/util/JRubyClassLoader.java
- test/test_load.rb
`JRubyClassLoader` doesn't define packages for classes found in JARs in JARs in JRuby 1.7 (it works as expected on master). The following example demonstrates the behavior:
```sh
mkdir -p src/{main,nested} bin build
echo "package main; class Main { }" > src/main/Main.java
echo "package nested; class Nested { }" > src/nested/Nested.java
javac -sourcepath src -d bin src/*/*.java
jar cf build/main.jar -C bin main
jar cf build/nested.jar -C bin nested
jar uf build/main.jar -C build nested.jar
ruby -rbuild/main -rnested -e'[Java::Main::Main, Java::Nested::Nested].each { |c| printf("%s.java_class.package # => %s\n", c.name, c.java_class.package) }'
```
In the example, a JAR containing the class `main.Main` and another JAR containing the class `nested.Nested` created. The Ruby script then loads …
> Define packages for classes in nested JARs

- test/mri/ruby/test_proc.rb
For #3173 and to check against future regression.
This was broken in 9.0.0.0 but seems to be fixed in 9.0.1.0.
> Add MRI test for proc visibility

- truffle/src/main/java/org/jruby/truffle/runtime/subsystems/FeatureManager.java
For classloader and core features, add the feature to the collection of
loaded features before performing the load to break endless recursion in
the presence of cyclic dependencies.
This brings the behavior of core and classloader features in line with file features. I am encountering a cyclic dependency when doing ahead of time compilation. Since I include all ruby files in the image, features that would have been resolved as files instead are found with the classloader.
A quick way to expose this issue is to add `require_relative 'core.rb'` to truffle/src/main/ruby/core.rb.
> [Truffle] Add to loadedFeatures before loading

- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/IOPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/runtime/sockets/NativeSockets.java
This helps with ahead of time compilation. I can generate the bindings for NativeSockets during compilation, but only primitive, array, or string arguments are currently supported. Boxing the integer in an array has the same result when using jnr-ffi, it is translated into a int*.
> [Truffle] Change signature of NativeSockets.accept

- core/src/main/java/org/jruby/RubyRange.java
- test/mri/ruby/test_range.rb
With my previous commit, RangeError: bignum too big to convert into `long' was the result when running (0...2**64).max
This commit ports handling for non-RubyFixnums from the 1.7.20 branch.
Addresses, https://github.com/jruby/jruby/issues/3118
.. follow-up on PR #3196
> Fixing RangeError with code from 1.7 branch

- truffle/src/main/java/org/jruby/truffle/nodes/cast/CmpIntNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/EncodingNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/ExceptionNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/KernelNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/MethodNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/ProcessNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/QueueNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/RegexpNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/SizedQueueNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/StringNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/ThreadNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/TimeNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/array/ArrayBuilderNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/array/ArrayNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/exceptions/TopLevelRaiseHandler.java
- truffle/src/main/java/org/jruby/truffle/nodes/globals/GetFromThreadLocalNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/EncodingConverterPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/IOBufferPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/IOPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/PointerPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/PosixNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/RubiniusLastStringReadNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/StatPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/StringPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/TimePrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/VMPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/runtime/subsystems/ThreadManager.java
- truffle/src/main/java/org/jruby/truffle/translator/DeadNode.java
This pull request lowers the number of methods available for runtime
compilation from over 33,000 to less than 15,000. Some methods that
could not be annotated with TruffleBoundary were split in order to
introduce a boundary.
I used a static analysis tool to determine what methods were causing a large number of other methods to be included for runtime compilation and added Truffle boundaries to limit this.
> [Truffle] Limit the number of methods available for runtime compilation

- core/src/main/java/org/jruby/RubyGlobal.java
- spec/ruby/core/env/shared/to_hash.rb
That makes it so that it duplicates rather than returning the same object to make compatible with MRI
fixes #3162
> add to_h to the class used for ENV

- core/src/main/java/org/jruby/ext/digest/BubbleBabble.java
Hey guys
Before:
```
bin/jruby -rdigest -e "p Digest.bubblebabble ''"
"xx"
```
After:
```
bin/jruby -rdigest -e "p Digest.bubblebabble ''"
"xexax"
```
MRI:
```
ruby -rdigest/bubblebabble -e "p Digest.bubblebabble ''"
"xexax"
```
and http://web.mit.edu/kenta/www/one/bubblebabble/spec/jrtrjwzi/draft-huima-01.txt
> Test Vectors
>
>   ASCII Input       Encoding
>   ------------------------------------------------------------------
>   `' (empty string) `xexax'
Fixes #2956
> Fix Digest bubblebabble incorrect output on empty string

- maven/jruby-jars/jruby-jars.gemspec
"Homepage" link shown at https://rubygems.org/gems/jruby-jars is 404 Not Found.
> Fix homepage of jruby-jars.gemspec

- truffle/src/main/java/org/jruby/truffle/nodes/core/ClassNodes.java
This is necessary for ahead of time compilation since createLayout uses
reflection. If we create the layout in a static variable, the static
initialization will take place during image generation.
> [Truffle] Create layout as a static variable

- spec/java_integration/ant/ant_spec.rb
The changes in 55f56c9 were not equivalent. Le sigh.
> Resolves broken spec when `ANT_HOME` is set

- truffle/src/main/java/org/jruby/truffle/runtime/RubyContext.java
Currently, if the input file name is something like "./hello.rb", the assertion at https://github.com/jruby/jruby/blob/master/truffle/src/main/java/org/jruby/truffle/runtime/loader/SourceLoader.java#L37 will fail. Getting the canonical name for the file fixes this.
> [Truffle] Canonicalize input file name

- truffle/src/main/java/org/jruby/truffle/translator/MethodTranslator.java
These changes make it possible to lazily parse methods in ahead of time compiled images. During image generation method bodies are elided from the core source files and stored in a separate data structure. When the file is initially parsed, the method body is replaced with a node to perform the lazy parsing. When this node is executed, it performs the parsing and then replaces itself with the code of the method.
> [Truffle] Allow for lazy parsing

- core/src/main/java/org/jruby/util/collections/Java7ClassValue.java
- spec/regression/embedded_runtime_leak_spec.rb
Commit 09f15f902ee14a848387b9f126cb731941a0a8be enabled the
Java7ClassValue implementation by default which exposed a runtime
memory leak in the embedded use case. This fixes that leak by wrapping
values stored in the java.lang.ClassValue instance with a
WeakReference.
> Fix an embedded runtime memory leak in Java7ClassValue

- core/src/main/java/org/jruby/RubyTime.java
As per Ruby's Time#zone [1] UTC should be used instead of GMT
since Ruby 1.8. The spec also expects UTC. 
spec/ruby/core/time/zone_spec.rb:
```ruby
it "returns UTC when called on a UTC time" do
Time.now.utc.zone.should == "UTC"
end
```
This also fixes #3304.
[1] http://ruby-doc.org/core-2.2.3/Time.html#method-i-zone
> return UTC instead of GMT (fixes #3304)

- core/src/main/java/org/jruby/RubyObjectSpace.java
- hs_err_pid364.log
- truffle/src/main/ruby/core/rubinius/common/object_space.rb
The issue was that _id2ref function was retruing nil value. I fixed it to throw a RangeError. Please correct me if I am wrong at any point.
> Issue #3324

- core/src/main/java/org/jruby/RubyFixnum.java
- spec/ruby/core/enumerable/find_index_spec.rb
This is a bug which I found while testing one of my gems on JRuby. Please have a look!
> "[2].to_enum.find_index(2.0)" returns 0 (to match MRI behavior)

- lib/ruby/shared/jruby/compiler/java_class.rb
- spec/java_integration/jrubyc/java/implements_spec.rb
Using multiple interfaces with java_implements is broken, and the specs that tests for this are also broken.  This fixes it.
It also appears that many of the jrubyc specs are broken enough though they pass. Those are not fixed here.  In general, it appears the specs attempt to do a regexp match against the generated Java code, but the tests pass not because the generated code is correct, but because the generated code includes a copy of the spec source code in the `source` variable.  Thus, the regexp is matching itself and not the generated Java code.
It would appear that the call to `JRuby::Compiler::JavaGenerator.generate_java` results in the whole spec being included in the `source` variable rather than just the source for the Ruby code being compiled to Java.
E.g. 
```
public class …
```
> Fix java_implements for multiple interfaces

- core/src/main/java/org/jruby/util/io/SelectorPool.java
- spec/regression/embedded_runtime_leak_spec.rb
This fixes a runtime leak in embedded scenarios where a runtime may
never get garbage collected because it has a thread blocked on a
select call. This leak exists in JRuby 1.7.x as well, but for some
reason I'm seeing it more often in JRuby 9.x when running TorqueBox 3
integration tests. Perhaps there is more IO that uses select in 9.x
than 1.7.x?
Here's a gist with a fairly simple reproducer and results on 1.7.21, 9.0.0.0, and 9.0.1.0-SNAPSHOT with this patch applied - https://gist.github.com/bbrowning/3cbb3901d4facd7fc99f
> Close any open selectors when tearing down a runtime.

- bench/java/bench_java_overloaded_invocation.rb
- core/src/main/java/org/jruby/java/dispatch/CallableSelector.java
- core/src/main/java/org/jruby/java/invokers/RubyToJavaInvoker.java
- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/util/collections/IntHashMap.java
The move to IntHashMap in RubyToJavaInvoker improved throughput
for multiple-arity calls, but since IntHashMap is not synchronized
this could cause corrupted data under concurrent load as seen in
CallableSelector to encapsulate the cache and synchronize access
to it. I believe this is a minimum effort to make the cache access
safe and fix #3394.
I have not measured the impact of this synchronization in a high
concurrency setting. It may indeed turn out to be more overhead
and a worse bottleneck than using ConcurrentHashMap with Integer
objects. Unfortunately there's no middle ground here unless we
build or adopt some concurrency-friendly int-based map.
Another heavy option would be to maintain two references to
IntHashMap in RubyToJavaInvoker, copying from a synchronized
writable copy to …
> Refactor Java invoker cache logic to allow encapsulation, sync.

- truffle/src/main/java/org/jruby/truffle/PolyglotEngineMain.java
I've removed the TruffleVM from main development line of Truffle. Consider stop using it.
> Removing no longer needed import of a deprecated class

- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipWriter.java
- spec/regression/GH-1371_gzip_spec.rb
GZIPOutputStream was passing one of its internal byte buffers to IOOutputStream#write, which in turn used those bytes to back the ByteList for its output.  So every subsequent time GZIPOutputStream wrote to that buffer, it overwrote the bytes behind the back of all the previous chunks of output.
Ensure that IOOutputStream is working on a copy of the bytes it gets from GZIPOutputStream to fix this issue.
Fixes #1371
Let me know if there's any questions, and thanks again!
> Fix GzipWriter output

- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/util/io/OpenFile.java
Running httpclient test with JRuby master dumps NPE log. Stacktrace says
TCPServer#accept -> IO#select accesses unprotected field 'fd' in
OpenFile. This commit changes IO#select to check if a file is closed or
not first.
I don't have a short reproducer. Following is the step to reproduce.
```
% git clone https://github.com/nahi/httpclient.git
% cd httpclient
% jruby -Ilib test/test_httpclient.rb -n test_keepalive_disconnected
Loaded suite test/test_httpclient
Started
shed in 0.141 seconds.
1 tests, 21 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
7.09 tests/s, 148.94 assertions/s
Exception in thread "Ruby-0-Thread-4:
/Users/nahi/git-private/jruby/lib/ruby/stdlib/test/unit/testcase.rb:697" java.lang.NullPointerException
at …
```
> Fix TCPServer#accept NPE log

- core/src/main/java/org/jruby/runtime/profile/builtin/ProfilePrinter.java
- rakelib/test.rake
- spec/profiler/json_profile_printer_spec.rb
- spec/profiler/runtime_spec.rb
`first` flag was incorrectly set, resulting in a leading comma for json profile output.
Also remove some calls to rspec's `have`, which has been removed from rspec since the profiler specs were last run.
@headius, with this the spec/profiler specs are green for 1.7.  Do you want to re-enable on Travis?
> Fix JsonProfilePrinter

- core/src/main/java/org/jruby/javasupport/binding/Initializer.java
- test/jruby/test_higher_javasupport.rb
fixes #3262 ... its a non-backward compatible change thus fired up here to decide
> remove support for aliasing Java indexed getters as Ruby readers

- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/util/RubyDateFormatter.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/TimePrimitiveNodes.java
In order to fix #3303 and as requested in #3309 I have extracted the zone name logic into its own method (RubyTime.getRubyTimeZoneName) and reused it in RubyDateFormatter.
> Fix 3303 refactor zoneHelper into getRubyTimeZoneName

- core/src/main/java/org/jruby/RubyFile.java
- test/jruby/test_file.rb
> normalize path (windows)

- core/src/main/java/org/jruby/util/io/EncodingUtils.java
- spec/regression/GH-3402_spec.rb
This commit fixes issue #3402 on master.
@enebo and @headius please review my PR. Thanks!
> Fix for issue 3402: String#encode with :replace option does not return correct value

- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/ruby/jruby/kernel/enumerable.rb
- test/mri/ruby/test_enum.rb
Enumerable#chunk and Enumerable#slice_before no longer takes the initial_state argument [Feature #10958]
> remove "initial_state" argument of Enumerable#{slice_before,chunk}

- core/src/main/java/org/jruby/exceptions/RaiseException.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
`jruby -Xlog.backtraces=true ...` currently logs backtraces in multiple log records, 
this can easily become an issue e.g. when multiple threads are logging backtraces at the same time.
this PR fixes the logging to produce one multi-line log item per backtrace and to use the JRuby format. seems that it could be useful for JRuby 1.7.x but in case of compatibility worries, I'm happy to target 9K only.
> log exception backtrace in one log record

- core/src/main/java/org/jruby/RubyArray.java
- test/mri/ruby/test_array.rb
Implements Array#bsearch_index. The binary search is now a private method which returns an int
index, and the public #bsearch and #bsearch_index methods utilize it to return an appropriate
IRubyObject instance.
This is functionally identical to how the MRI changes were implemented.
> [ruby-2.3] Feature #10730: Implement Array#bsearch_index

- core/src/main/java/org/jruby/RubyHash.java
- test/mri/ruby/test_hash.rb
Implements Hash#<=, #<, #>=, #>. Tests copied from the MRI commit.
I'd like review on RubyHash.hash_le to make sure it's implemented as efficiently as possible.
> [ruby-2.3] Feature #10984 - Hash comparison operators

- core/src/main/java/org/jruby/RubyIO.java
- test/mri/ruby/test_io.rb
- test/mri/socket/test_basicsocket.rb
- test/mri/zlib/test_zlib.rb
IO#close now silently returns nil if called on an already-closed IO object.
> [ruby 2.3 Feature #10718] IO#close should not raise IOError on closed IO objects.

- core/src/main/ruby/jruby/kernel/enumerable.rb
- test/mri/ruby/test_enum.rb
Implemented as #slice_when, but slice when block does not match rather than when it does.
Also added merged over ruby spec for it.
> [ruby-2.3 feature #10769] add Enumerable#chunk_while, spec for it

- core/src/main/java/org/jruby/util/io/EncodingUtils.java
- test/mri/ruby/test_io.rb
Allows for setting arbitrary flags for sysopen. Also cleaned up some unnecessary `context.runtime` calls.
> [ruby-2.3 Feature #11253] Add support for :flags option for IO#open

- core/pom.xml
- core/src/main/java/org/jruby/java/invokers/RubyToJavaInvoker.java
- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/util/collections/NonBlockingHashMapLong.java
the high-scale lib has been added as a dependency fairly recently on 9K as well as 1.7.23
it was introduced to use `NonBlockingHashMapLong` as an alternative of `IntHashMap` (due #3394)
turns out that the library can not work without `Unsafe` (and thus broke Android support in 1.7.x see #3554) while JRuby allows to boot and run when `sun.misc.Unsafe` is not available. thus the proposal here is to port the `NonBlockingHashMapLong` over (the com.boundary:hish-scale-lib received no commit in more than a year) and tune it to be usable without `Unsafe` (fixing #3554)
this also resolves #3555 - packaging issue as .jar includes patch(es) of JDK class(es)
> port NonBlockingHashMapLong from high-scale-lib

- core/src/main/java/org/jruby/ext/thread/Queue.java
- core/src/main/java/org/jruby/ext/thread/SizedQueue.java
Context:
* discussion on https://gitter.im/ruby-concurrency/concurrent-ruby,
* https://bugs.ruby-lang.org/issues/11822.
The implementation is now based on Doug Lea’s `LinkedBlockingQueue`.
Concurrency wise, this is now dual locked (head/tail) linked queue,
since Ruby std lib queues have blocking operations a completely
lock-free queue is not practical endeavor.
> [Ruby 2.3] Concurrency improvements to Queue/SizedQueue 

- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/IRVisitor.java
- core/src/main/java/org/jruby/ir/operands/OperandType.java
- core/src/main/java/org/jruby/ir/operands/SymbolProc.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter6.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/runtime/Binding.java
Does this seem like a good optimization? Are there any gotchas I've missed?
* Use a dummy binding rather than creating new every time.
* Cache the resulting proc at create site.
The second optimization results in a given &:foo in code only
creating a single Proc, ever, and caching it at that point in the
code. This is based on the observation that symbol procs typically
are used to iterate over homogeneous collections of objects, so
caching the proc allows its cache to stay populated and local to
the related code. This also eliminates the allocation of a Block,
BlockBody, and RubyProc for each encounter, which improves perf
also for heterogeneous collections with poor cacheability.
Benchmark:
```ruby
loop {
puts Benchmark.measure {
ary = [1,2,3,4]
1_000_000.times {
ary.each(&:object_id)
} …
```
> Various literal to_proc'ed Symbol optimizations.

- core/src/main/java/org/jruby/RubyException.java
- core/src/main/java/org/jruby/exceptions/RaiseException.java
- core/src/test/java/org/jruby/exceptions/TestRaiseException.java
`RaiseException(Ruby runtime, RubyClass type, String msg, IRubyObject backtrace, boolean native)` constructor despite accepting an `IRubyObject` **backtrace** parameter (and not just `RubyArray`), passing a nil does not end up with the `RubyException#backtrace` being `nil` but rather an empty array which is not fortunate as in user-land its easy to dismiss and confusing.
like to use the constructor for optional "lightweight" exception raising such as jruby/jruby-openssl#55
p.s. I'd like to consider backporting these changes to **jruby-1_7** if there's no objections to that.
> forcing a nil (no) backtrace with Java APIs

- README.md
Good day!
First of all, great thanks for the great project!
While glancing over the `README.md` I have noticed this small typo: `.. to allow you to uses Java classes ..` => `.. to allow you to use Java classes ..`.
Kind Regards,
Oleksii
> Fix small typo in readme: 'to uses' -> 'to use'

- core/src/main/java/org/jruby/java/invokers/ConstructorInvoker.java
- spec/java_integration/fixtures/CachedInJava.java
- spec/java_integration/object/singleton_spec.rb
- spec/java_integration/types/construction_spec.rb
This fixes #3576
I added a few related specs while I was at it (only the constructor one failed before my changes though).
I noticed the warning at `spec/READ_ME_FIRST.txt`, but wasn't sure if that applied to the `java_integration` specs, so if I should have added my spec elsewhere, please let me know.
> Cache proxies of newly constructed Java objects

- core/src/main/java/org/jruby/ext/thread/SizedQueue.java
- spec/ruby/library/thread/sizedqueue/num_waiting_spec.rb
Introduced in d13405b222f6d98177.
JRuby 1.7 and MRI 2.2.3:
```ruby
>> sq = SizedQueue.new(1)
=> #<SizedQueue:0x61f8bee4>
>> sq.push(1)
=> nil
>> Thread.new { sq.push(2) }
=> #<Thread:0x7fac631b run>
>> sq.num_waiting
=> 1
```
JRuby 9.0.4.0:
```ruby
>> sq = SizedQueue.new(1)
=> #<SizedQueue:0x103f852>
>> sq.push(1)
=> #<SizedQueue:0x103f852>
>> Thread.new { sq.push(2) }
=> #<Thread:0x4ae82894 sleep>
>> sq.num_waiting
=> 0
```
P.S. I'm not specialized in Java, but it seems to work.
> Fix SizedQueue#num_waiting regression

- core/src/main/java/org/jruby/java/invokers/ConstructorInvoker.java
- spec/java_integration/types/wrapping_spec.rb
Replicate the logic from org.jruby.javasupport.Java which determines whether an object should be cached.
I added some specs to ensure the caching is properly honored. If I comment out the new conditional, you can see that one of the new specs will correctly fail:
```
$ jruby -S rspec spec/java_integration/object/singleton_spec.rb spec/java_integration/types/wrapping_spec.rb
......F........
Failures:
1) A Java method returning/receiving uncoercible Java types with persistence off doesn't cache the proxy when directly constructed
Failure/Error: expect(object_proxy_cache.get(object)).to be_nil
expected: nil
got: #<Java::JavaLang::Object:0x38c6f217>
Finished in 0.103 seconds (files took 0.916 seconds to load)
15 examples, 1 failure
Failed examples:
rspec …
```
> Fix cache-constructed-proxies

- core/src/main/java/org/jruby/runtime/load/LoadService.java
#3341 has two simple tests which produces deadlocks on the current master branch.
this PR does fix it to the extend that I do not see deadlocks anymore.
@headius please review and I would some input on tests, i.e. it should be possible to run those tests from #3341 on CI but I am not if this makes sense
> treat deadlocks as circular require - as MRI does it

- core/src/main/java/org/jruby/ext/securerandom/SecureRandomLibrary.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
`ThreadContext.secureRandom` field was introduced as an optimization for the `SecureRandomLibrary`
... however as its a final field initialized on `new ThreadContext` all Ruby thread allocations potentially pay the cost of creating a secure random generator. which under some circumstances might get slow as they all seed themselves using a shared seeder (from a single source of entropy e.g. /dev/random under *nix).
numbers show a noticeable improvement on Ubuntu (rng-pack installed thus I rarely deplete /dev/random) :
100_000 threads BEFORE :
```
Rehearsal ----------------------------------------------------------
Thread.new [100000x]    12.840000   6.640000  19.480000 ( 10.336762)
Thread.start [100000x]  12.490000   5.760000  18.250000 (  9.539517) …
```
>  lazy secure random

- core/src/main/java/org/jruby/RubyTime.java
Based on Issue https://github.com/jruby/jruby/issues/3702
In CRuby when a timezone is not found with %Z option nothing is returned.
In strftime method when a timezone is not found, return an empty string as opposed to UTC +X
> Fix strftime %Z to act like CRuby

- lib/ruby/1.9/win32/registry.rb
We discovered this with a customer yesterday. DNS resolving (using `Resolv::DNS#getaddresses`) failed. It turned out that the underlying problem was that the way `win32/registry.rb` retrieves error messages from Windows is flawed, under certain circumstances.
The bug only appears if:
- `JAVA_OPTS` includes `-Dfile.encoding=UTF-8`
- The environment you run it on is a _non-English_ Windows installation, or more specifically: a Windows installation where the error message(s) include some non-ASCII character. The specific use case here is a Swedish Windows installation, where the error message for error number 2 (File not found) reads as "Filen du söker finns inte", or something similar. (The debugging here was complicated by the fact that I don't have a Swedish Windows myself, only the …
> Workaround for JRuby bug with UTF-8 encoding on non-English Windows

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/java/codegen/RealClassGenerator.java
- spec/java_integration/fixtures/Reflector.java
- spec/java_integration/reify/become_java_spec.rb
- spec/java_integration/types/coercion_spec.rb
- test/jruby/test_higher_javasupport.rb
just in time for 9.1 as this might be considered a "breaking" change at the binary (Java reflective) level.
the change is pretty much explained in the commit message: 2f363d0766417c1decc4045add9e5c80242c8a13
> previously all method arities ended up as var-args : `foo(IRubyObject[] args)`
>
> now for fixed arities we'll have correct number of args e.g. `foo(IRubyObject arg1)`
> ... we still generate var-args: `foo(IRubyObject[] args)` for all non-fixed arity sizes!
most users, of Ruby user-types entering Java land, complained about the previous behaviour - so this is a welcoming change. Ruby fixed arities will now be much more intuitive on the Java side.
// cc @Lan5432 
... if you're interested you could confirm whether this resolves some/all of the related issues :
- fixes …
> improved method arities on become_java!

- core/src/main/java/org/jruby/RubyInstanceConfig.java
- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/util/cli/Options.java
Hi,
I'm working on ruby (JRuby only) binding for Apache Spark. I have finished a working prototype which enables REAL closure serialization (IRClosure and variables in dynamic scopes) on JRuby:
https://github.com/chyh1990/jruby-spark/blob/master/src/main/java/com/sensetime/utils/ProcToBytesService.java
It's actually a java extension, which bring marshalling to `Proc`.
But I found JRuby do not matain children static scopes by default.
Set `jruby.ir.writing` to true can solve this problem, but it will write out a lot of IR files. So I add 
an option to force children static scopes registration, which enable IR writing on the fly.
I think it will be amazing to enable closure serialization on JRuby, which makes it possible to write
a fully functional Ruby-Spark binding.
> Add option to enable ir writing on-the-fly

- bin/jruby-cext-c
- lib/ruby/truffle/cext/ruby.h
- truffle/src/main/c/cext/.jruby-cext-build.yml
- truffle/src/main/c/cext/ruby.c
- truffle/src/main/java/org/jruby/truffle/core/CoreLibrary.java
- truffle/src/main/java/org/jruby/truffle/interop/CExtNodes.java
Depends on https://github.com/graalvm/sulong/pull/157
This is a sketch of how I think we could support the Ruby C API using interop. When we used Truffle C, we had several intrinsic nodes, so Ruby functionality implemented in Truffle C. I guess we want to avoid that? Otherwise we'll have to define an API that Sulong provides to register those intrinsics. If we can do it with just normal interop that's probably better.
We have a header that describes the Ruby C API.
We then have a library that implements that in terms of the interop functions that Sulong can provide. That library is compiled into a `.su` and shipped with JRuby+Truffle, and loaded whenever the first C extension is loaded.
Most of the C API is implemented by `INVOKE`ing methods that are implemented by JRuby+Truffle, in a …
> Truffle cext sketch

- truffle/src/main/java/org/jruby/truffle/core/array/ArrayNodes.java
- truffle/src/main/java/org/jruby/truffle/core/kernel/KernelNodes.java
- truffle/src/main/java/org/jruby/truffle/core/string/StringNodes.java
- truffle/src/main/java/org/jruby/truffle/language/LazyRubyRootNode.java
- truffle/src/main/java/org/jruby/truffle/language/SnippetNode.java
- truffle/src/main/java/org/jruby/truffle/language/dispatch/CallDispatchHeadNode.java
- truffle/src/main/java/org/jruby/truffle/language/loader/CodeLoader.java
- truffle/src/main/java/org/jruby/truffle/language/parser/Parser.java
- truffle/src/main/java/org/jruby/truffle/language/parser/jruby/TranslatorDriver.java
We use `ruby("...")` to execute Ruby inline in Java, when that's more convenient than creating a load of nodes. It parses each time like MRI's `eval` and so obviously doesn't compile and is very slow.
This new node allows us to use snippets on the relatively fast path. It compiles the expression once and then calls. It supports inlining etc.
I think it's fast enough to use without worrying too much. I can't really tell though as I think the Ruby code we call using in the first case I've tried it is slow.
I was hoping that using it with `@Cached` would be really elegant, but because the DSL doesn't support string literals I'm afraid that's not quite the case and we need a helper method. I wish we could write something like `@CachedStrings("string.concat_internal(other)", "string", …
> [Truffle] Compiled Ruby snippets in Java.

- core/src/main/java/org/jruby/RubyFixnum.java
> Fixes Fixnum#bitLength when the value is negative.

- core/src/main/java/org/jruby/NativeException.java
- core/src/main/java/org/jruby/RubyException.java
- core/src/main/java/org/jruby/exceptions/RaiseException.java
- core/src/test/java/org/jruby/javasupport/TestJava.java
- core/src/test/java/org/jruby/test/ThrowingConstructor.java
- test/jruby/test_backtraces.rb
- test/org/jruby/javasupport/test/name/Sample.java
wasn't able to find a test/spec or a reason why `RaiseException` did (for `NativeException`) : 
```
-    private static String buildMessage(Throwable exception) {
-        StringBuilder sb = new StringBuilder();
-        StringWriter stackTrace = new StringWriter();
-        exception.printStackTrace(new PrintWriter(stackTrace));
-
-        sb.append("Native Exception: '").append(exception.getClass()).append("'; ");
-        sb.append("Message: ").append(exception.getMessage()).append("; ");
-        sb.append("StackTrace: ").append(stackTrace.getBuffer());
-
-        return sb.toString();
-    }
```
**9.1** sounds like a good place to break away from that message building - which would actually only be seen very rarely (effectively almost never without hacks) even without the patch as …
> cleanup NativeException

- core/src/main/java/org/jruby/java/proxies/JavaInterfaceTemplate.java
- spec/java_integration/interfaces/interface_new.rb
- spec/java_integration/methods/naming_spec.rb
> Removing 'new' class method from interfaces #3275

- core/src/main/java/org/jruby/RubyNameError.java
If the `NameError#to_s` is called before `NameError#receiver` is called, the NameError object will [lose the source of the receiver object](https://github.com/jruby/jruby/blob/b856557/core/src/main/java/org/jruby/RubyNameError.java#L223) and the `NameError#receiver` method will raise an ArgumentError when it shouldn't:
```ruby
error = (1.foo rescue $!)
error.receiver # => 1
error.to_s     # => NameError: ... <= This call replaces the internal `message` object
error.receiver # => ArgumentError: no receiver is available
```
This commit changes the initializer to retrieve the receiver object so that the behavior of the method will be consistent.
> Fix a bug where NameError#receiver raises an ArgumentError after #to_s is called

- core/src/main/java/org/jruby/RubyFixnum.java
Making sure the behaviour matches MRI https://github.com/ruby/ruby/blob/trunk/numeric.c#L4280
Thanks @jkr2255
> Fixnum#bit_length - uses bit inversion when the value is negative

- core/pom.rb
- core/pom.xml
- lib/pom.rb
- lib/pom.xml
- maven/jruby-complete/pom.rb
- maven/jruby-dist/src/main/assembly/common.xml
- maven/jruby/pom.rb
- truffle/pom.rb
- truffle/pom.xml
* jars should have them in META-INF
* bin tarball/zip should have them in top level
Right now there's still a gap, namely aggregate NOTICE files for those artifacts that bundle 3rd party ASL licensed dependencies. I've done this before in other maven-based projects, but navigating JRuby's build is taking me a bit of time.
> [packaging] ensure licensing info is included in artifacts

- .gitignore
- mx.jruby/mx_jruby.py
- mx.jruby/suite.py
Majority of Graal/Truffle projects is using `mx` build tool. JRuby is an exception. The goal of this pull request is to provide an `mx` facade that delegates execution to existing `mvn` goals, but behaves like a normal `mx` from outside and thus simplifies including of JRuby in other `mx` based projects.
With the current changes I can run the build and it successfully connects Truffle with JRuby and builds both:
```bash
$ mx clean
$ mx build
```
> [Truffle] mx clean and mx build work for JRuby

- core/src/main/java/org/jruby/RubyStruct.java
- test/jruby/test_name_error.rb
When a NameError is raised from `Struct#[]`, the `NameError#receiver` method should return the receiver object rather than raising `ArgumentError: no receiver is available`.
Actual:
```ruby
(Struct.new(:does_exist).new(nil)[:doesnt_exist] rescue $!).receiver
```
Expected:
```ruby
(Struct.new(:does_exist).new(nil)[:doesnt_exist] rescue $!).receiver
```
> Fixed a bug where NameError#receiver didn't return receiver when it's caused by Struct#[]

- core/src/main/java/org/jruby/RubyModule.java
- spec/ruby/core/module/define_method_spec.rb
- spec/ruby/core/module/fixtures/classes.rb
- spec/tags/ruby/core/module/define_method_tags.txt
- spec/truffle/tags/core/module/define_method_tags.txt
Fixes for #3854 and a few others, perhaps.
> Test define method visibility

- core/src/main/java/org/jruby/util/RubyDateFormatter.java
- core/src/main/java/org/jruby/util/RubyTimeOutputFormatter.java
See https://bugs.ruby-lang.org/issues/4456. I'm not certain MRI
has a hard limit in place, but that's the approach I went with.
The original test that started failing (usually timing out) is
from MRI's TestTimeExtension#test_huge_precision:
```
def test_huge_precision
bug4456 = '[ruby-dev:43284]'
assert_normal_exit %q{ Time.now.strftime("%1000000000F") }, bug4456
end
```
We attempted to honor that giant padding width blindly, usually
running out of memory or timing out while the GC thrashed.
> Limit padding width for strftime.

- core/src/main/java/org/jruby/util/ShellLauncher.java
> fix quoted paths

- lib/pom.rb
This might be trivial since it's not enable at this moment, but I just wanted to let you know that this version includes a fix for a bug where most of DYM's features didn't work on JRuby 9.1.0.0.
#3480
> Upgrade the version of the did_you_mean gem to 1.0.1

- .travis.yml
Travis CI has deployed code to take certain extra factors into
consideration when computing cache names.
Our jobs in the build matrix should each receive unique cache names
and we should be able to avoid cache corruption
See https://github.com/jruby/jruby/commit/a60bd1ffaf5fc59542532397a6c946826a4d52aa
> Enable caching

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyStruct.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- core/src/main/java/org/jruby/util/MurmurHash.java
Dunno if anyone wants to review this (e.g. @enebo or @kares) but it appears to have passed all tests and eliminates some really ugly misfeatures of the original port.
Note that I have not removed the old impl in case an external library uses it.
> Test new recursion

- core/src/main/java/org/jruby/util/cli/Options.java
- core/src/main/ruby/jruby/kernel/gem_prelude.rb
- lib/pom.rb
- lib/pom.xml
This enables did_you_mean and installs it during the build. Fixes #3480.
@mkristian I could not figure out how to make this work without being a default gem. We do not have any logic to preinstall gems that aren't default, do we?
This also includes the `Gem.clear_paths` hack to address too-early booting of RubyGems in embedded scenarios.
> Enabled did_you_mean, install during build, and clear gem paths

- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/ir/instructions/CheckArityInstr.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
...unfortunately...
In the process of getting the JIT to work properly without the AddLocalVarLoadStore pass, I ran into an issue with Block getting set into DynamicScope and blowing up (caused by OptimizeDelegation, fixed in 88a8896782b17dd797964f368f6b5796d3b66065). In fixing that I realized that this particular method was always requiring a dynamic scope, for no obvious reason:
```ruby
def popen3(*cmd, **opts, &block)
in_r, in_w = IO.pipe
opts[:in] = in_r
in_w.sync = true
out_r, out_w = IO.pipe
opts[:out] = out_w
err_r, err_w = IO.pipe
opts[:err] = err_w
popen_run(cmd, opts, [in_r, out_w, err_w], [in_w, out_r, err_r], &block)
end
```
It turned out that arity-checking of keyword arguments forced a DynamicScope so it could get to StaticScope. However, all Ruby bodies have direct access …
> Kwargs should not need dynamic scope, since we have static handy.

- core/src/main/java/org/jruby/ir/IRManager.java
- core/src/main/java/org/jruby/ir/passes/OptimizeDelegationPass.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/runtime/DynamicScope.java
This was a good experiment, but we're not properly ensuring the
heap variables are being loaded live when needed, causing examples
like that in #3891 to fail to propagate changes across threads.
By implementing LocalVariable load/store logic in JIT and turning
off the "Add" pass, we basically revert heap vars to always being
read/written immediately, as in JRuby 1.7.25.
It may be possible to improve the pass so that it localizes the
loads and stores better and ensures we don't miss updates we
should see, but this commit will test whether the "nuclear option"
passes all our suites.
cc @subbuss @enebo
> Disable the AddLocalVarLoadStore pass to fix #3891.

- core/src/main/java/org/jruby/RubyInstanceConfig.java
Additional fix for issue exposed by #3901. Devices, like ttys,
pipes, fifos and the like may be neither file nor symlink, but
still readable as script source. The restriction here is
unnecessary.
Ping @mkristian... I softened this test but I'm not sure why it was so restrictive in the first place. Is this change ok?
> Soften this restriction to just readable resources.

- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/ir/instructions/ZSuperInstr.java
This appears to pass all tests, and I could find no path from ZSuper's interpret method to anything requiring DynamicScope.
> ZSuper does not require caller's binding/scope.

- core/src/main/java/org/jruby/ir/instructions/CallBase.java
- core/src/main/java/org/jruby/ir/instructions/ZSuperInstr.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter6.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
This improves things in a few ways:
* JIT and interpreter are calling through most of the same APIs.
* Fewer transient objects for calls with splats.
* Less duplication of code.
There are other ways we could split the super dispatch paths
apart to reduce overhead and allocation. This patch puts us on
that path.
> Unify super and call splatting logic in interpreter and JIT.

- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/util/io/OpenFile.java
This attempts to fix some sporadic readpartial tests and specs in the suite, specifically in this case a failure in MRI's `test_readpartial.rb` in `test_open_pipe`. Our old old would never properly wait for the pipe to become readable and would keep spinning and trying to do nonblocking reads followed by waitReadable that never waited. As a result we could have interrupts happen at unexpected times, leaving IO in a weird state that probably caused sporadic `close` errors like in https://travis-ci.org/jruby/jruby/jobs/132959357
> waitReadable should block

- spec/truffle/specs/truffle/array/steal_storage.rb
- spec/truffle/specs/truffle/array/take_ownership_of_store_spec.rb
- truffle/src/main/java/org/jruby/truffle/core/CoreLibrary.java
- truffle/src/main/java/org/jruby/truffle/core/array/TruffleArrayNodes.java
- truffle/src/main/ruby/core/array.rb
This is intended to be a faster version of Array#replace when we know that the source array won't be used anywhere else.
While escape analysis may very well catch some of these, I don't think it would catch all of them (e.g., the mergesort! case). And this will work in the interpreter as well.
@jruby/truffle
> [Truffle] Added a new internal method for taking ownership of an array store from another array.

- .travis.yml
* In general install failures are either
network issues which will not solve in the next 5 minutes
or compilation issues which needs a proper fix.
> Travis: Do not retry the install step.

- core/src/main/java/org/jruby/FlagRegistry.java
- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyMatchData.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/ext/stringio/StringIO.java
- core/src/main/java/org/jruby/util/StringSupport.java
- core/src/main/resources/org/jruby/runtime/Constants.java
tldr: this is a registry for all flags we use against Ruby objects in JRuby. The goal is to maximize utilization of the flags and ensure we do not overlap.
See the first commit and the doco for FlagRegistry.
My intent with this is to begin exploring more specialized subclasses of key Ruby core classes. For example, we might want to have a RubyArrayOne that only holds one value initially in a field rather than an array. If it grows, we would set a "failed" flag that would indicate we need to fall back to using the values array rather than the one field. Rather than putting this as a boolean on the class, increasing object size, we can  use flags. But I wanted a better mechanism to ensure I'm not overlapping other flags higher in the hierarchy, as our use of them broadens.
> Flag registry

- core/src/main/java/org/jruby/util/cli/Options.java
- test/truffle/compiler/pe/language/global_pe.rb
- truffle/src/main/java/org/jruby/truffle/core/CoreLibrary.java
- truffle/src/main/java/org/jruby/truffle/language/globals/GlobalVariableStorage.java
- truffle/src/main/java/org/jruby/truffle/language/globals/GlobalVariables.java
- truffle/src/main/java/org/jruby/truffle/language/globals/ReadGlobalVariableNode.java
- truffle/src/main/java/org/jruby/truffle/language/globals/WriteGlobalVariableNode.java
@jruby/truffle @thedarkone So here is my attempt to make global variables constants if they are not changed too often. The logic is unfortunately more complex than I expected, so I would appreciate a review :smiley:
> [Truffle] Make global variables constants if they are rarely changed

- lib/ruby/stdlib/rubygems/config_file.rb
- lib/ruby/stdlib/rubygems/defaults/jruby.rb
This trims off a bit of startup time by not loading more of RG
than is necessary. Pending release of rubygems/rubygems#1644 (and install of that release into JRuby).
Before:
```
[] ~/projects/jruby $ time jruby -e 1
real	0m2.397s
user	0m6.476s
sys	0m0.310s
[] ~/projects/jruby $ time jruby --dev -e 1
real	0m1.884s
user	0m2.717s
sys	0m0.223s
```
After:
```
[] ~/projects/jruby $ time jruby -e 1
real	0m2.181s
user	0m5.681s
sys	0m0.295s
[] ~/projects/jruby $ time jruby --dev -e 1
real	0m1.733s
user	0m2.493s
sys	0m0.214s
```
> Use platform defaults from defaults file rather than eager load.

- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/util/io/SelectExecutor.java
- core/src/main/java/org/jruby/util/io/SelectorPool.java
(Note this is the same as https://github.com/jruby/jruby/pull/3951 but targeting master, sorry for the confusion!)
This PR fixes https://github.com/jruby/jruby-openssl/issues/93
To summarize: I found that many times when you get a `Selector` from `SelectorPool`, it already had old keys in it, and that was causing problems as reported in the issue. Something somewhere was returning selectors without cleaning up its keys properly, I think possibly [this line](https://github.com/jruby/jruby/blob/915993886ae6663586d893b7d237f750068aceb5/core/src/main/java/org/jruby/util/io/SelectExecutor.java#L290) (perhaps the key needs to be cancelled even if its invalid or it may still show up in `selectedKeys()` under certain conditions?). Its also possible that some gem out there I don't know about uses …
> Ensure that Selectors from SelectorPool don't have old keys in them

- truffle/src/main/java/org/jruby/truffle/language/loader/FeatureLoader.java
Modifying the code to compile in current Truffle as well as in the one which is not going to throw IOException from PolyglotEngine.eval and similar method.
Getting ready for smooth integration of https://github.com/jtulach/truffle/commit/cd6ebeca83404f05e6302c6f7e8b5cde7a32e441
> Adjusting the code to not expect IOException from PolyglotEngine.eval

- core/src/main/java/org/jruby/ir/IRBuilder.java
After reporting issue #4051 I decided to look at the generated IR and noticed that trace instructions were being added without line numbers. This led to the observed issue there stack traces generated inside `set_trace_func` did not have the correct line numbers.
For the `LINE` and `CALL` events the fix is straightforward: just add a line number instruction **before** the trace instruction, as the line number was already known statically by the `IRBuilder`.
Unfortunately, for the `RETURN` and `END` events the parser does not include this information and thus there's no simple way of adding line number instructions before those. I think that particular fix is a bit beyond my capabilities so I added some `FIXME`s so at least this doesn't get forgotten.
Nevertheless, and happily, the partial …
> Partially fix set_trace_func line numbers

- core/src/main/java/org/jruby/util/CompoundJarURLStreamHandler.java
This commit ensures that the stream which is opened for a `URL` within
`CompoundJarURLStreamHandler` is explicitly closed before it falls out
of scope.  Previously, the stream would still eventually be closed but
only after Garbage Collection.
> Explicitly close input stream in CompoundJarURLStreamHandler

- core/src/main/java/org/jruby/ext/io/wait/IOWaitLibrary.java
- core/src/main/java/org/jruby/ext/socket/RubySocket.java
- test/jruby/test_socket.rb
Before commit `Socket.tcp(host, port, connect_timeout: 0.1)`
ignored timeout option. This happened because `connect_internal`
mistakenly responded with `:wait_readable` instead `:wait_writable`.
After fixing it this code started to constantly fail with timeout error.
Checking for `OP_CONNECT` in `IO#wait_writable` fixed this issue.
Added adopted spec from MRI, because it's excluded by other reasons.
> Fix Socket.tcp connect_timeout option

- core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java
- lib/pom.rb
- lib/pom.xml
- lib/ruby/include/ruby.h
- lib/ruby/stdlib/mkmf.rb
In the project I'm working on we've successfully been using Capybara with JRuby. We've considered switching drivers to Capybara WebKit as it is emerging as one of the faster Capybara drivers. In our case we have measured it is between 2 and 3 times faster (compared to Selenium/Firefox and Poltergeist/PhantomJS).
It has a quirk, though. It uses `mkmf` to build some C code. The code in question is not a native extension and does not depend in any way on Ruby's C extension API. But because of the lack of `mkmf` it will not install under JRuby. It will run just fine if a pre-built gem is manually copied, though.
There is this discussion: https://github.com/thoughtbot/capybara-webkit/issues/725, but nothing seems to have come out of it. Further - a friend who develops [this …
> Make JRuby compatible with capybara-webkit (and possibly other gems)

- core/src/main/java/org/jruby/util/JRubyClassLoader.java
This commit just adds a simple `LOG.debug` message to output the contents of an `IOException` that might be caught by the JRubyClassLoader during a `findClass` call.  We were encountering the `IOException` in cases where our process ran out of file descriptors, leading the `classUrl.openStream` call to fail.  This manifested in our application as a `NoClassDefFoundError` downstream but because the `IOException` is swallowed higher up, it was initially hard for us to able to determine what the root cause was.  Being able to see this new debug message in the log output would significantly help with our ability to diagnose this kind of problem.
> Write a log message when findClass IOException is caught

- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/internal/runtime/AbstractIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMetaClassBody.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/WrapperMethod.java
These commits remove all remaining uses of WrapperMethod, which fixes issues like #3708 and #3869.
See the commits for the longer story, but basically WrapperMethod does not pass through the "new" impl class to the contained method, which results in it supering up the wrong hierarchy.
I have a few concerns, which is why I opened a PR for review:
* Methods that were wrapped before will now be their own true instances of the original method.
* Because we now attempt to dup rather than wrap, I had to modify duping of IR-based methods to always use clone. This makes them have the same serial number, so that transplanted methods (e.g. those in #3869) will still be `==` and `eql?`. The wrapper previously made them appear to be two methods with the same serial, so this may be ok...but if we …
> No more wrapper

- spec/ruby/core/enumerator/first_spec.rb
- spec/ruby/core/enumerator/lazy/map_spec.rb
- spec/ruby/core/enumerator/yielder/append_spec.rb
JRuby seems to have two bugs related to Enumerators yielding Arrays. They can be reproduced when comparing the following code snippets which correctly return `true` for MRI, but `false` on JRuby.
1. `<<` should be an alias for `.yield`
```ruby
Enumerator.new {|y| y.yield([1])}.to_a == [[1]] # MRI: true, JRuby: true
Enumerator.new {|y| y << [1]}.to_a ==  [[1]] # MRI: true, JRuby: false ([[[1]]] instead)
```
2. `map` on lazy Enumerators should not unwrap Arrays
```ruby
Enumerator.new {|y| y.yield([1])}.map {|e| e}.to_a == [[1]] # MRI: true, JRuby: true
Enumerator.new {|y| y.yield([1])}.lazy.map {|e| e}.to_a == [[1]] # MRI: true, JRuby: false ([1] instead)
```
I added corresponding specs, but I'm not sure if they're in the right place and format.
> Expose two Enumerator-related bugs

- core/src/main/java/org/jruby/RubyEnumerator.java
- core/src/main/ruby/jruby/java.rb
- core/src/main/ruby/jruby/java/java_8.rb
- test/jruby/test_enumerator.rb
feels like a good fit and this makes enumerator usable with Java 8 (with some boilerplate) : 
`java.util.Spliterators.spliterator(enum.to_java, enum.size || -1, charactestistics)`
... ideally some more integration would be handy but JRuby would need compiling under Java 8 for easy : `[1, 2, 3, 4, 5].each.to_java.stream` or `Enumerator.new { ... }.to_java.spliterator` implementations.
esp. since the Enumeration's size and the spliterator characteristic are depend on internals. so this would like get revisited after a potential compilation switch in another release.
Ruby enumerator (and thus Ruby array) usability with 8 streaming is confirmed with test-cases.
> RubyEnumerator implements java.util.Iterator

- core/pom.rb
- core/pom.xml
> workaround compilation problems with unsafe-mock.jar

- truffle/src/main/java/org/jruby/truffle/core/binding/BindingNodes.java
- truffle/src/main/java/org/jruby/truffle/core/regexp/MatchDataNodes.java
- truffle/src/main/java/org/jruby/truffle/core/regexp/RegexpNodes.java
- truffle/src/main/java/org/jruby/truffle/core/rope/RopeNodes.java
- truffle/src/main/java/org/jruby/truffle/core/rubinius/RegexpPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/core/string/StringNodes.java
- truffle/src/main/java/org/jruby/truffle/language/globals/ReadMatchReferenceNode.java
- truffle/src/main/java/org/jruby/truffle/language/parser/jruby/BodyTranslator.java
- truffle/src/main/java/org/jruby/truffle/language/parser/jruby/Translator.java
- truffle/src/main/java/org/jruby/truffle/language/threadlocal/GetFromThreadLocalNode.java
- truffle/src/main/ruby/core/enumerable.rb
- truffle/src/main/ruby/core/enumerator.rb
- truffle/src/main/ruby/core/regexp.rb
- truffle/src/main/ruby/core/string.rb
- truffle/src/main/ruby/core/symbol.rb
@jruby/truffle 
This fixes $~ to be frame-local (and thread-local), which addresses some issues where values were leaking in places they shouldn't have been. I don't think I've handled every case accurately, but I do think this is more accurate than what we had before and all specs continue to pass.
Since it was a bit involved, I'd appreciate a careful review.
> Truffle fix match backref

- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/ir/instructions/AttrAssignInstr.java
- core/src/main/java/org/jruby/ir/instructions/CallBase.java
- core/src/main/java/org/jruby/ir/instructions/specialized/OneArgOperandAttrAssignInstr.java
- core/src/main/java/org/jruby/runtime/Helpers.java
This deprecates the "invoke" forms in Helpers and RubyClass that depended on having a Ruby frame pushed to get "self" for visibility checking. Improper use of this method (in this case, frame was eliminated) caused #4134.
This PR is expected to be applied after #4138, which fixes #4134 by changing attribute assigns to use a CallSite like any other invocation.
> Deprecate framed invoke

- core/src/main/java/org/jruby/ext/socket/Option.java
- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
- core/src/main/java/org/jruby/ext/socket/SocketType.java
- core/src/main/java/org/jruby/ext/socket/SocketUtils.java
- spec/tags/ruby/library/socket/option/bool_tags.txt
- spec/tags/ruby/library/socket/option/inspect_tags.txt
- spec/tags/ruby/library/socket/option/int_tags.txt
- spec/tags/ruby/library/socket/option/linger_tags.txt
- spec/tags/ruby/library/socket/option/new_tags.txt
This PR includes:
- full (I hope) `Socket::Option` support;
- passing `Socket::Option` as `setsockopt` argument;
- fix for the #4040;
- properly handles socket prefixed options/levels (`SOL_LEVEL`, `SO_OPTION`) (fix for the #3438); 
- properly handles unsupported socket constants;
> Full Socket::Option support

- lib/ruby/stdlib/logger.rb
When check the OS platform, the RUBY_PLATFORM return 'java' in JRuby.
It is better to use RbConfig::CONFIG['host_os'] .
fixes #4147
> Fix for #4147

- core/src/main/java/org/jruby/ext/securerandom/SecureRandomLibrary.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
- core/src/main/java/org/jruby/util/cli/Options.java
This PR backports recent SecureRandom entropy fixes from 9k to 1.7. See #1405.
We had a 1.7 user in #jruby today with entropy problems.
> Backport securerandom

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyInterrupt.java
- core/src/main/java/org/jruby/RubySignal.java
- core/src/main/java/org/jruby/RubySignalException.java
- spec/tags/ruby/core/exception/signal_exception_tags.txt
- test/mri/excludes/TestSignal.rb
> Implement SignalException class

- spec/truffle/tags/core/encoding/replicate_tags.txt
- truffle/src/main/java/org/jruby/truffle/core/encoding/EncodingManager.java
- truffle/src/main/java/org/jruby/truffle/core/encoding/EncodingNodes.java
- truffle/src/main/java/org/jruby/truffle/core/exception/CoreExceptions.java
- truffle/src/main/ruby/core/encoding.rb
- truffle/src/main/ruby/core/type.rb
Work In Progress.
I've got one known failure here which I think is due to the following from `encoding.rb` not recognizing the encodings added at runtime. I'm still thinking about a fix for this. I'll probably replace these with a primitive for the few places these are used.
```
EncodingList = Encoding.list.freeze
EncodingMap = build_encoding_map
```
Please review @nirvdrum
> [Truffle] Encoding#replicate

- appveyor.yml
AppVeyor added Maven 3.3.9 as a pre-installed package, so we don't have to install manually anymore. It is available in their build image of [September 19, 2016](https://www.appveyor.com/updates/)
refs: 
- https://github.com/jruby/jruby/issues/4075#issuecomment-241072333
- appveyor/ci#998
> Simplify appveyor.yml, Maven is now a pre-installed package

- core/src/main/java/org/jruby/RubyClass.java
- spec/java_integration/fixtures/Reflector.java
- spec/java_integration/fixtures/Service.java
- spec/java_integration/fixtures/ServiceAnnotation.java
- spec/java_integration/reify/become_java_spec.rb
In https://github.com/jruby/jruby/commit/84eb04f62f0bac367aa6f162bdaadf56c0beb9c8 the java class names for anonymous classes were changed to have a colon in them.  This causes problems when java tries to use reflection to get the classname because colon isn't a valid classname character. 
The error from java is:
```
Failure/Error: Unable to find java.lang.Class.createAnnotationData(java/lang/Class.java to read failed line
Java::JavaLangReflect::GenericSignatureFormatError:
Signature Parse error: expected '<' or ';' but got :
Remaining input: :0x2b80e5a9;
```
This PR just changes the classname back to using an underscore instead of a colon.
> Fix Java::JavaLangReflect::GenericSignatureFormatError when reflecting reified annotation values

- core/src/main/ruby/jruby/bigdecimal.rb
The comparison is very expensive, because it first tries to convert the operand (which is a constant Integer 0 here) into a BigDecimal. This in turn is very expensive (because the Integer is first converted into a String, and then, for operating on that String, a java.util.regex.Pattern object is compiled (in line https://github.com/felixvf/jruby/blob/cc79119315496ea019496affe7a6a79ebc1dbed9/core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java#L533)). Using #nonzero? should speed-up the loop considerably.
> Replace BigDecimal#!= by BigDecimal#nonzero?.

- lib/ruby/stdlib/rubygems/commands/query_command.rb
Fixes #4019
rubygems/rubygems#1685 didn't get into release so I added it manually like in https://github.com/jruby/jruby/commit/bdb4a3688987487d1dece6f88f5aa7c7ce786719
> Apply patch from rubygems/rubygems#1685

- core/pom.rb
- core/pom.xml
- truffle/src/main/java/org/jruby/truffle/platform/posix/JNRTrufflePosix.java
Depends on https://github.com/jnr/jnr-posix/pull/82.
So far I'm just using this for Truffle, but that shows it works. I'm not sure what priority you want to give using your Java method for this compared to the JNR version in JRuby classic.
> [Truffle] Use the new getgroups POSIX call.

- core/src/main/java/org/jruby/compiler/impl/SkinnyMethodAdapter.java
- f2i() should be mapped to F2I, instead of F2D. Note that F2I is a valid constant in org.objectweb.asm.Opcodes.
- The incorrect mapping appears to be a copy-paste editing error from the above f2d() method.
- Due to the error, when float-to-integer narrowing numeric conversion should occur, float-to-double widening numeric conversion was being done, which can have a negative impact on performance and memory usage.
> Fix the incorrect opscode mapping in f2i()

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
This should reduce the overhead of inspecting by avoiding the
intermediate StringBuilder/char[] and subsequent conversion to
byte[]. There are a few extra objects created along the way
(java.lang.String.getBytes, RubyString for class name, etc) but
overall memory use should reduce around 3x: a US-ASCII
string would need 2x byte size in the StringBuilder, and the
builder is still alive when we create the eventual byte[] for a
total of 3x max memory use during inspect.
Relates to #4127, but does not constitute a fix for memory issues
there.
> Inspect directly into a RubyString and avoid StringBuilder/char[].

- core/src/main/java/org/jruby/util/Sprintf.java
The logic in our double-based sprintf logic attempts to round
values manually by inspecting a long-form version of the double.
If we need to round, and the next digit is a five, it will round
toward zero (truncate) iff that five is the last digit in the long
unrounded string. This appears to have been an attempt to mimic
C printf's behavior of rounding "true half" to even in the
presence of inaccurately-represented IEEE754 decimals.
This commit changes the pre-formatting to actually format with the
specified precision, allowing NumberFormat's default HALF_EVEN
logic to to the work for us.
Fixes #4157.
> Format initial string to specific precision, so rounding works.

- core/src/main/java/org/jruby/RubyEnumerable.java
- spec/regression/GH-4218_enumerable_drop_should_not_change_identities.rb
This fixes #4218 in JRuby 1.7.
In 06f0441 (JRUBY-6892) `Enumerable#drop` was changed to call `#dup` on every element that ended up in the result, but that might not work. Not all objects correctly implement `#dup`, or are even allocatable.
`#take` was not changed, and looking at the differences between `#take` and `#drop` the only thing that stood out was that the signature of the #each call was different. Changing from `Arity.NO_ARGUMENTS` to `Arity.ONE_REQUIRED` make the issue that 06f0441 tried to fix go away.
> Don't dup every element in Enumerator#drop (1.7)

- core/src/main/java/org/jruby/runtime/profile/builtin/InvocationSet.java
- core/src/main/java/org/jruby/runtime/profile/builtin/MethodData.java
- core/src/main/java/org/jruby/runtime/profile/builtin/ProfilePrinter.java
this makes building custom tooling easier
http://pastebin.com/XhNYdMtD
> public org.jruby.Runtime.Profile.Builtin::MethodData

- core/src/main/java/org/jruby/AbstractRubyMethod.java
- core/src/main/java/org/jruby/PrependedModule.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/internal/runtime/methods/DynamicMethod.java
> Prepend must set method's "defined class" to the new bottom.

- core/src/main/java/org/jruby/util/Sprintf.java
Reverts jruby/jruby#4159
This fix was a little half-baked and introduced new failures: https://travis-ci.org/jruby/jruby/jobs/171807663#L1394
> Revert "Format initial string to specific precision, so rounding works."

- core/src/main/java/org/jruby/ir/dataflow/analyses/DefinedVariableNode.java
- spec/compiler/general_spec.rb
> Also perform uninitialized check on temp locals.

- core/src/main/java/org/jruby/RubyEnumerable.java
- spec/regression/GH-4218_enumerable_drop_should_not_change_identities.rb
This fixes #4218 in JRuby 9K.
In 06f044124bef7856340b2bb7bdad6bac7d68f771 (JRUBY-6892) `Enumerable#drop` was changed to call `#dup` on every element that ended up in the result, but that might not work. Not all objects correctly implement `#dup`, or are even allocatable.
`#take` was not changed, and looking at the differences between `#take` and `#drop` the only thing that stood out was that the signature of the #each call was different. Changing from `Signature.NO_ARGUMENTS` to `Signature.ONE_REQUIRED` make the issue that 06f044124bef7856340b2bb7bdad6bac7d68f771 tried to fix go away.
> Don't dup every element in Enumerator#drop (9K)

- core/src/main/java/org/jruby/runtime/IRBlockBody.java
instead treat `null` as `NONE`
this is more of a cosmetic issue where on Tomcat JRuby 9K prints a lot of SEVERE warning due Tomcat's leak detection : 
```
04-Oct-2016 11:45:01.304 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [sblending] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@1311e832]) and a value of type [org.jruby.EvalType] (value [NONE]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
04-Oct-2016 11:45:01.304 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [sblending] created a …
```
> do not eagerly set eval-type in a thread-local

- lib/ruby/stdlib/io/console.rb
to have 'better' MRI compatibility (see #4275)
> make ttymode and ttymode_yield helpers private

- README.md
This PR adds a link to ruby-lang.org's web page on Ruby version managers.
> README: Ruby version manager docs link

- core/src/main/java/org/jruby/RubyFile.java
This PR adds the class methods `File.empty?` (and `File.zero?`). I included `File.zero?` because `File.empty?` in the docs links to `File.zero?`. https://ruby-doc.org/core-2.4.0_preview3/File.html#method-c-empty-3F (I'm guessing one is an alias of the other)
See #4293 where feature is originally mentioned.
This PR gets the test `test_empty_p` in "test/mri/ruby/test_file_exhaustive.rb" to pass. I figured that I didn't need to add any other tests since this functionality is tested by the MRI tests. Let me know if I do need to add more tests.
I did run into an issue while testing with just that file. If I ran just this command
```
bin/jruby test/mri/ruby/test_file_exhaustive.rb -n test_empty_p
```
I get an error about missing `assert_file`.
```
Error: test_empty_p(TestFileExhaustive): …
```
> Add File.empty?

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerable.java
Adds `Enumerable#sum` and `Array#sum` from [Feature #12217](https://bugs.ruby-lang.org/issues/12217).
I'm parking this PR here in its current state to encourage discussion and feedback.
> Feature#12217 Enumerable/Array sum

- core/src/main/java/org/jruby/RubyMath.java
There is a cornercase in Math.lgamma if the input is a negative zero.
This patch fixes it by adding that explicit corner case to the if
statement.
> Fixed Math.lgamma with input -0.0

- core/src/main/java/org/jruby/RubyDir.java
This PR adds support for the method `Dir.empty?` requested in #4293
This PR gets the test `test_empty?` in "test/mri/ruby/test_dir.rb" passing.
There are a couple lines I want to point out that I will do so in comments.
> Add `Dir.empty?`

- .travis.yml
`teavis-rubies` now uses 3 Mac jobs to create archives for various OS
releases.
This is a bit wasteful if multiple builds pass in a short period.
Instead, Travis CI is now running a nightly build of jruby-head
(around 22:30 UTC). This will happen regardless of the state of the
`master` branch.
> Disable notifying travis-rubies of passing [skip ci]

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerable.java
This changes `Array#sum` and `Enumerable#sum` to use Kahan's compensated summation algorithm, so we have the same rounding artifacts as MRI.
It also includes some of the MRI's cascading coercion behaviour in `Array#sum`
Now all tests in `test/mri/ruby/test_array.rb` and `test/mri/ruby/test_enum.rb` pass, except for those depending on 'mathn' which I can't test because of an unrelated issue.
Consider this a regression fix for #4297
> fix Array#sum and Enumerable#sum

- core/src/main/java/org/jruby/RubyHash.java
- test/mri/ruby/marshaltestlib.rb
When we set `default_proc` to nil, we also have to update the internal flag.
Fixes https://github.com/jruby/jruby/issues/4302
@enebo
> Fix marshaling Hash with default_proc set to nil

- spec/ruby/optional/capi/spec_helper.rb
It looks like `mkmf` will always look for all c files in the directory. So, I copied the c spec to a temp directory for compilation. This appears to be working. It may run a little slower than the previous method since I had to run `extconf.rb` with another jruby+truffle (or the makefile would contain values from previous extension).
cc: @chrisseaton
> [Truffle] Compile c specs with extconf make

- core/pom.rb
- core/pom.xml
- spec/regression/GH-3799_spec.rb
As a result of debugging I found out that `SystemCallError` that happens during `syswrite` is actually `"Resource temporarily unavailable"` that corresponds to `EAGAIN`. So first idea of fix was to put `select` somewhere. Related fix for `IO#sysread` gave me hope that I'm moving in right direction. 
As a result I did similar fix as in 857b76f461acb5cbb67d582b864145e617ccaee8
> Fix IO#syswrite. Fixes #3799

- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubyFileTest.java
- core/src/main/java/org/jruby/ext/pathname/RubyPathname.java
* Add `Pathname#empty?`
* Remove `empty?` implementation on `File` since `FileTest` will assign its implementation of `empty?` to `File` (see `RubyFileTest.FileTestFileMethods`)
* Add `FileTest.empty?`
The last two steps were down in this PR in order to base the implementation of `Pathname#empty?` on the MRI implementation (which uses `Dir.empty?` and `FileTest.empty?`. see https://ruby-doc.org/stdlib-2.4.0_preview3/libdoc/pathname/rdoc/Pathname.html#method-i-empty-3F).
This PR gets the failing test in "test/mri/pathname/test_pathname.rb"  to pass. The tests in "test/mri/ruby/test_file_exhaustive.rb" are also still passing after the changes to `File`.
See #4293
> Add `Pathname#empty?`

- spec/tags/ruby/core/hash/default_proc_tags.txt
With https://github.com/jruby/jruby/pull/4321 merged, we no longer have to skip that ruby spec.
@enebo
> Skip less specs

- spec/truffle/tags/language/hash_tags.txt
- truffle/src/main/java/org/jruby/truffle/core/hash/EnsureSymbolKeysNode.java
- truffle/src/main/java/org/jruby/truffle/parser/BodyTranslator.java
This should raise a type error:
```
h = {1 => 2, b: 3}
{"a" => "b", **h}
```
As far as I can tell, this ConcatHashLiteralNode is used for merging hashes with the splat `**` operator. I observed that the pair matching the `pair.getKey() == null` statement in the body translator is what is to be merged into the hash literal. These null key pairs need to check that all their keys are symbols after they are executed. So, I added an array of booleans to track which hashes were being merged in to pass to the concat node.
This is done here in MRI:
`core_hash_merge_kwd`
https://github.com/ruby/ruby/blob/22c0994bc8b34e4b8b80de3259363b0f27c24988/vm.c#L2675
> [Truffle] Hash merge check for splatted elements

- spec/truffle/tags/language/optional_assignments_tags.txt
- truffle/src/main/java/org/jruby/truffle/language/constants/ReadConstantNode.java
- truffle/src/main/java/org/jruby/truffle/parser/BodyTranslator.java
This fixes all the remaining optional variable assignment specs. I think what I did makes sense, but I'd appreciate at least another pair of eyes looking over the changes.
@jruby/truffle
> [Truffle] Fix optional assignment specs

- core/src/main/java/org/jruby/RubyProc.java
This makes the FIXME comment match the code next to it. 
See 4e4935ed6fad1b71111ff2da96a489570870a725
> trivial: restkwargs => kwargs in FIXME comment

- core/src/main/java/org/jruby/Ruby.java
When trying to exit with a hard exit (exit!), runtime teardown is
performed by the shutdown hook thread added in Main.internalRun(), which
is run on a different thread.
This poses a problem when using ruby-debug, as it grabs a lock while
processing debug events [1], and thus if you try to exit! while trying to
process debug events (for instance if you're debugging interactively
with pry and you want to exit), you'll get a deadlock looking something
like this:
```
"Thread-1" - Thread t@11
java.lang.Thread.State: BLOCKED
at org.jruby.debug.DebugEventHook.eventHandler(DebugEventHook.java:91)
- waiting to lock <3b88136f> (a org.jruby.debug.DebugEventHook) owned by "main" t@1
at org.jruby.runtime.EventHook.event(EventHook.java:30)
at org.jruby.Ruby.callEventHooks(Ruby.java:3179)
at …
```
> Fix deadlock when tearing down runtime during debugging

- appveyor.yml
This fiddle-with-the-appveyor-build PR tries to get around the issue in AppVeyor that Maven options are handed in a way that generates warnings on Java 8.
Example of build with warnings: https://ci.appveyor.com/project/jnr/jruby/build/2880/job/shniu1cn7yluu99o#L1692
The changes are:
- set JAVA_OPTS and MAVEN_OPTS as "global" environment variables (for all of the matrix participants)
- invalidate cache of downloaded Maven artifacts when the `pom.rb` changes
See #4075.
> AppVeyor: set MAVEN_OPTS=-Xmx3g

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- test/mri/bigdecimal/test_bigdecimal.rb
I'm not sure that `catch (ArithmeticException e)` is the best way to fix it, but at least this would emulate MRI behaviour (read #4324 for more context)
Fixes #4324 
@enebo @headius
> Fix unexpected java.lang.ArithmeticException when converting Rational to BigDecimal

- test/jruby/test_kernel.rb
Adds a regression test for 69da0af4f5af2615640f5575ef80ba288fb4eb5f reported in in #4361.
> Add regression test for shell exit

- core/src/main/java/org/jruby/RubyKernel.java
First of all, thanks for JRuby! 😄 
I was just wandering around JRuby's code and I found this array of ints which I think can be replaced by a simple `int`.
Maybe it was done for something that I don't fully understand... what do you think?
> change status array of ints to an int

- core/src/main/java/org/jruby/Ruby.java
While benchmarking a barebones rails application I was seeing a lot of
lock contention. When I looked into it, all threads were spending a lot
of time waiting to grab the mutex on the `dedupMap` inside
`Ruby.freezeAndDedupString()`.
This happened because activesupport uses
`defined?(@somevar) && @somevar` a lot while filling the
output template, and thus threads were spending a lot of time in the
`Ruby.getDefinedMessage()` method fighting to dedup the same strings
over and over and over again.
To fix this, instead of deduping when they are accessed, let's dedup the
defined messages when they are initially populated inside the
definedMessages map. This way we get the same effect, but only dedup
once.
This fix has a considerable effect on single-thread performance:
```ruby
require …
```
> Optimize getDefinedMessage by deduping during initialization

- truffle/src/main/java/org/jruby/truffle/options/ArgumentProcessor.java
- truffle/src/main/java/org/jruby/truffle/options/RubyInstanceConfig.java
This continually confuses non-Ruby users who just run `ruby` and expect to see something.
I could be convinced to not commit this.
> [Truffle] Run irb instead of reading from stdin by default.

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- test/mri/bigdecimal/test_bigdecimal.rb
Expected: MRI can `round(0)` Infinity:
```
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
BigDecimal("Infinity").round(0)
=> #<BigDecimal:7fad7f83d798,'Infinity',9(18)>
```
But JRuby-master raises an error:
```
jruby 9.1.7.0-SNAPSHOT (2.3.1) 2016-12-12 fd9515b Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]
BigDecimal("Infinity").round(0)
FloatDomainError: Computation results to 'Infinity'
org/jruby/ext/bigdecimal/RubyBigDecimal.java:1368:in `round'
```
We raised an error when the method was called with no argument, but we checked it in the wrong way so `round(0)` was broken.
@enebo @headius
> Fix bigdecimal infinity round

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/runtime/ivars/StampedVariableAccessor.java
- core/src/main/java/org/jruby/util/unsafe/UnsafeHolder.java
This commit replaces the unsafe-mock dependency -- which caused
various build problems living in boot classpath -- with a new
library that just shims the three Unsafe methods added in Java 8:
fullFence, loadFence, and storeFence. This allows us to eliminate
all calls to those methods from JRuby proper as well as the build
tricks.
Fixes #4103.
> Remove unsafe-mock from our build altogether.

- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMetaClassBody.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java
These commits add more call paths through a few of our DynamicMethod subclasses for Ruby methods, to reduce the number of stack frames they consume. This improves JIT stack depth for the examples in #3810 by nearly 50%, with a somewhat smaller gain for the interpreter (which has more frames).
> Improve stack depth

- core/src/main/java/org/jruby/javasupport/DummyForJavaUtil.java
- core/src/main/java/org/jruby/javasupport/JavaUtil.java
In #4266, we noticed a difference what methods JRuby finds in Java-classes between JRuby-jar being in boot classpath and in the normal classpath. This change removes that difference.
The reason for the difference is that all classes in boot classpath are privileged and `AccessController#checkPermission(Permission)` will always return `true` to them, whereas for others the result depends on security policy in effect.
In normal (at least Oracle) JVM installations, the policy doesn't allow `suppressAccessChecks`, _but_ call to `AccessibleObject#setAccessible(boolean)` will still succeed as there's no `SecurityManager` set.
I posit that trying to call `setAccessible` is a better way to see if we might later on succeed in calling `setAccessible` than checking the permission.
> Check permission to AccessibleObject#setAccessible(boolean) a better way

- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRNoProtocolMethod.java
- core/src/main/java/org/jruby/ir/Compiler.java
- core/src/main/java/org/jruby/ir/passes/AddCallProtocolInstructions.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/parser/StaticScope.java
- core/src/test/java/org/jruby/test/TestRubyBase.java
This PR adds call protocol to script bodies. This fixes recent compiler regressions caused by ripping the non-protocol logic out of CompiledIRMethod (#4382).
It appears the only scopes which do not get call protocol now are eval scopes and singleton class scopes (IRMetaClassBody). The former is never jitted and never put into CompiledIRMethod or any other context where its protocol is not already handled. The latter had its own CompiledIRMetaClassBody whose sole difference was to do pre/post call protocol, so it is renamed to reflect that.
> Add call protocol to script body and separate non-protocol metas.

- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRNoProtocolMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/InvokeDynamicMethodFactory.java
- core/src/main/java/org/jruby/ir/Compiler.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/passes/AddCallProtocolInstructions.java
- core/src/main/java/org/jruby/ir/persistence/IRWriter.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/parser/StaticScope.java
- core/src/main/java/org/jruby/runtime/Signature.java
- core/src/test/java/org/jruby/test/TestRubyBase.java
This PR cleans up method jit by only emitting one body regardless of whether there's a specific-arity path or not. Previously, both variable and specific paths were emitted in full. With this PR, the variable path will call the specific path. This reduces bytecode generated for a given method body by up to 50%, including all contained blocks and metaclass bodies.
> Specific arity jit cleanup

- tool/truffle/options.yml
- truffle/src/main/java/org/jruby/truffle/options/Options.java
- truffle/src/main/java/org/jruby/truffle/options/OptionsCatalog.java
- truffle/src/main/java/org/jruby/truffle/parser/LazyTranslationNode.java
- truffle/src/main/java/org/jruby/truffle/parser/MethodTranslator.java
- truffle/src/main/java/org/jruby/truffle/parser/TranslatorEnvironment.java
Add support for lazy translation, as a first step towards lazy parsing and maybe serialisation.
It's quite effective on its own though. For `-e 14` minimum heap goes from 35 to 27 MB (saves 8 MB), total allocation from 177.85 MB ± 2.75 MB to 125.78 MB ± 2.2 MB (saves 52 MB), time from 3.47 to 3.13 s (saves 0.34 s).
We can't turn it on however, as it interferes with Truffle instrumentation. I think that's a Truffle bug and I'll be using this new lazy translation as a test case to show that. It's off by default for that reason. There might be a couple of other bugs that are ours which I'll look at after the Truffle issues is fixed.
Contains some work by Brian Belleville.
> [Truffle] Lazy translation

- core/src/main/java/org/jruby/ext/stringio/StringIO.java
> Make StringIO thread-safe by synchronizing against ptr.

- core/src/main/java/org/jruby/runtime/Helpers.java
Are there any cases where null names make sense/should be allowed? If so we probably need to be more specific than this patch.
Solves problem of #4426
> Don't allow null method names

- .travis.yml
- core/src/main/java/org/jruby/Ruby.java
This includes a fix for #4416 (setting top-level module when running with -X+C) and enables the `test:jruby:aot` suite to verify the AOT mode.
> Set toplevel module

- core/src/main/java/org/jruby/compiler/FullBuildTask.java
- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/runtime/MixedModeIRBlockBody.java
tbh I am super bothered I cannot figure out a test case to at least occasionally fail.   I explain the basic issue in #4304 (more specifically https://github.com/jruby/jruby/issues/4304#issuecomment-266764789).   Summarized as two threads both decide to build something and one is a child closure and the other is a parent of that closure.  We get a sequence like:
1. child starts
2. parent starts
3. parent accesses childs CFG
4. child changes CFG
5. parent accesses childs CFG
6. BB is missing
This code will ask hard scope to full build itself for blocks and the two entry points to building on IRScope will built the closures before the parent.  It does not appear to infinite loop so yay?  I could not see anything bust with this change and I think the intent is clear but I am unsure in best …
> compile back to hard scope when closure compile/build requested

- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
This is a complete removal of the error logic, but it did not fail the suites I ran locally. Open for comments or concerns @enebo @subbuss.
> Kill the LocalJumpError logic for break in lambda. Fixes #4369.

- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java
`Hash#compare_by_identity` is more of a writer (does call a setter)
... looks esp. weird since there's a java get/setCompareByIdentity
> RubyHash's compare_by_identify Java method naming is confusing

- core/src/main/java/org/jruby/javasupport/JavaUtil.java
- core/src/main/java/org/jruby/javasupport/binding/ClassInitializer.java
- core/src/main/java/org/jruby/javasupport/binding/Initializer.java
- core/src/main/java/org/jruby/javasupport/binding/InterfaceInitializer.java
- core/src/main/java/org/jruby/javasupport/binding/MethodInstaller.java
- core/src/main/java/org/jruby/javasupport/binding/Priority.java
- test/jruby/test_higher_javasupport.rb
- test/org/jruby/test/BetaSingleton.java
discovered during the investigation of #4432 (this addresses a different issue)
turns out the priority logic for setting up Java methods into Ruby land did not handle potential alias-ing conflicts for getters (same priority).
[this test would periodically fail](https://github.com/jruby/jruby/compare/master...kares:test-ji-is3?expand=1#diff-2a4dade2791e9bb085bbfbd439a2d9d6R719) (more on travis-ci than locally always using the same JVM installation) ... JRuby already dealt with the non-determinstic case get/is issue before while generating wrappers: #3470
here we're making sure we always do the same setup for (unusual) cases with multiple getters for the same property e.g. getFoo() and isFoo() : 
* `foo` is aliased to `getFoo()` (current state is that this is not always true and might point …
> [ji] deterministic Java bean-style method aliases

- core/src/main/java/org/jruby/util/io/SelectorPool.java
When we updated our server from 9.1.2.0 to 9.1.7.0 we started seeing a file descriptor leak which, if left for long enough, would run the machine out of file descriptors.
We tracked down the problem to https://github.com/jruby/jruby/pull/3952 which changed how SelectionKeys were closed.  
It looks like if exceptions aren't caught while calling `cancel` on the SelectionKeys then the loop can exit early and leave some keys un-cancelled.
When we went back to the same key cancelling code that was used in 9.1.2.0 the problem went away.
> Make sure to iterate over all keys when cancelling keys in a SelectorPool

- core/pom.rb
- core/pom.xml
See https://github.com/jnr/jnr-unixsocket/pull/38
Fixed code from jnr-enxio is not used anymore after updating to
jnr-unixsocket 0.15.
Regression spec accidentally passes on TravisCI and Ubuntu xenial.
In the meantime there are bug reports that issue still
reproduces in some environments. Personally I caught it under macOS.
> Fix #3799 again.

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubySymbol.java
- test/mri/ruby/test_string.rb
- test/mri/ruby/test_symbol.rb
* Adds implementation of `casecmp?` based on downcasing the string and comparing
* Adds unit tests for `casecmp?` from MRI
There is a test failing in each of the tests (the last assertion in each method) I brought over. This is because the MRI implementation (https://github.com/ruby/ruby/commit/ad619e02c465eebd15fa57dc658f8e042decdebb) of `casecmp?` relies on passing the `:fold` option to `downcase` however that option has not been added yet in JRuby. It is referenced in #4293 though.
I decided to keep the failing tests in for completeness since they will need to be fixed anyway for 2.4 support. I figured that this PR would be fine without those specific cases supported but maybe it would be better to wait until `:fold` is implemented.
See #4293
> Implement `String#casecmp?` and `Symbol#casecmp?`

- core/src/main/java/org/jruby/java/dispatch/CallableSelector.java
Using proc#hash as the cache key means that you're only
guaranteed to get a cache hit if exactly the same proc is
being passed. Using arity.hashCode instead should satisfy the
original reason for hashing the proc (disambiguate signatures
based on the arity of the proc) while preventing cache misses.
Also note that this was causing a memory leak: each time we get a cache miss it creates a new cache entry, and the cache is unbounded. 
Tried to add a test for this, but it doesn't seem like CallableSelectorTest runs / works.
> Use arity hashCode instead of proc#hash in CallableSelector

- core/src/main/java/org/jruby/compiler/BlockJITTask.java
- core/src/main/java/org/jruby/compiler/MethodJITTask.java
- core/src/main/java/org/jruby/ir/targets/InvokeSite.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitorMethodContext.java
- core/src/main/java/org/jruby/util/JavaNameMangler.java
Originally, varargs and specific-arity paths were emitted in toto
as their own JVM method bodies. With recent changes, the varargs
path now calls the specific-arity path, causing an extra
synthetic entry in the JVM stack trace. This confounded the
backtrace miner, since it had no marker with which to omit the
synthetic version, and so Kernel#caller and friends contained an
additional invalid entry. This in turn caused require_relative to
fail to find the caller's path, resulting in a nil path value
passed to File.realpath, which triggered this bug.
It likely only affected invokedynamic because our indy logic must
be calling no-arg methods via the varargs path (a separate issue
to be fixed).
My modification here explicitly separates the synthetic varargs
name from the specific-arity name …
> Separate varargs and specific-arity names in JIT. Fixes #4482

- core/src/main/java/org/jruby/ir/targets/ConstantLookupSite.java
Added this while debugging an issue, figured it'd be useful
upstream. Adds the method name to the log statement + adds
logging for searchModuleForConst. Spelling out the method
name is useful to distinguish between lexicalSearchConst
and searchConst, but also makes it easier to map the log
statements with the origin method when you're not familiar
with the code.
Happy to change the format of the logs if there's any objections, 
this is just what I ended up using.
> Improve some of the debug logging in ConstantLookupSite.

- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
- spec/ruby/library/socket/basicsocket/close_write_spec.rb
`shutdownInternal` was always shutting down the read side, even when we were trying to close the write side of the socket.
Fixes #4500.
> Allow reads after calling BasicSocket#close_write.

- core/src/main/java/org/jruby/runtime/scope/ManyVarsDynamicScope.java
We use JRuby `ScriptingContainer` in a tomcat servlet web
application.  After application reloading in tomcat, JRuby
runtime initialization fails with the error message.
"BUG: could not initialize constructor handle"
`MethodHandles.publicLookup().findConstructor()` fails with
`IllegalAccessException` in static initialization block.
The initialization does not work well with tomcat reloading.
As a workaround `MethodHandles.lookup()` without access check
works fine.
> Fix JRuby embed crash after application reloading

- core/src/main/java/org/jruby/RubyModule.java
This was assigning to the local variable, so the `MethodHandle` would be created ever time this is called.
> Actually cache the idTest on the module.

- core/src/main/java/org/jruby/RubyArray.java
> Implemented optional buffer argument for Array#pack

- lib/ruby/stdlib/ffi/libc.rb
- lib/ruby/stdlib/fiddle/jruby.rb
- test/mri/fiddle/helper.rb
After having some trouble getting Mittsu working in JRuby, I thought I'd have a look at JRuby's Fiddle implementation. There are quite a number of inconsistencies and straight-up broken bits, so I thought I'd take a crack at some of them. This is not a conclusive fix or anything, but hopefully I can get it working enough for most.
Here are the list of the bigger changes:
1. `TYPE_PTRDIFF_T` was not defined. This has been voiced before (#3477). I had a look, and other types such as `TYPE_SIZE_T`, etc. were also missing. I've added all the missing types, basing their byte sizes and alignment on `TYPE_VOIDP`
2. Make `Fiddle::Pointer` behave more like MRI
a. `#[]` now gets the correct number of bytes, regardless of null-terminators
b. Added `Pointer#[]=`
c. `#to_s` and `#to_str` should behave …
> Fix some issues with Fiddle

- lib/ruby/stdlib/resolv.rb
When resolving names using compressed IPv6-only DNS servers, it could
happen that when processing the response of a name query, the IP of the
sender is not compressed so using a simple string comparison is not
safe.
This patch encapsulates the from address and the address of the sender in
IPAddr objects so the comparison is safe and just works in all cases.
This fixes #3663.
> Use ipaddr to compare the sender's address

- core/src/main/java/org/jruby/java/dispatch/CallableSelector.java
- test/jruby/test_higher_javasupport.rb
- test/org/jruby/javasupport/test/name/Sample.java
for (backwards) safety this has lower priority than an exact match
and thus is not expected to cause any regressions
resolves #1643
> [ji] support 'native' method arguments (e.g. org.jruby.RubyObject)

- core/src/main/java/org/jruby/RubyUnboundMethod.java
This fixes #4477 by not using the origin module/class to test bindable hierarchy but instead using the actual implementation module. I'm not sure why it was doing the latter before, but it meant that any methods captured from a module were not bindable to class hierarchies that included that module (since the module was hidden behind a Prepended or IncludedModule origin).
This seems like the proper logic, but I'm doing it as a PR to check CI before pushing forward for 9.1.8.0.
There may be tests for this we don't pass but I could not find them.
> Use actual impl module to test bindability. Fixes #4477.

- core/src/main/java/org/jruby/RubyEnumerable.java
> Don't yieldSpecific to allow arrays through normal block params.

- core/src/main/java/org/jruby/runtime/Block.java
- core/src/main/java/org/jruby/runtime/BlockBody.java
- core/src/main/java/org/jruby/runtime/IRBlockBody.java
- core/src/main/java/org/jruby/runtime/MixedModeIRBlockBody.java
resolves #4529 
a follow-up on #4215 + a FIXME fixed that I've bumped into way too often :)
... any chance to get this in for 9.1.9.0 - getting a lot of log on TC // cc @headius @enebo
> do not set eval-type NONE value in a thread-local

- core/src/main/java/org/jruby/RubyFile.java
This prevents in-classloader paths from expanding using real
filesystem paths that may resolve symlinks.
Fixes #4145.
> When canonicalizing classpath URIs, use a bogus root path.

- core/src/main/java/org/jruby/ext/ffi/Platform.java
jruby should be updated to support new JDK version string scheme -- [JEP 223](http://openjdk.java.net/jeps/223).
before this JEP, java.version property was 1.X.Y_Z, where X is major version number of JDK, now it is '$VNUM(-$PRE)?(\+($BUILD)?(-$OPT)?)?' where VNUM is $MAJOR.$MINOR.$SECURITY.
> support new JDK version string scheme

- core/src/main/java/org/jruby/ext/ffi/Platform.java
This PR is to add support for the AARCH64/ARM64 in JRuby FFI.
> Add AARCH64 support in FFI

- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- test/jruby/test_case.rb
... instead of falling back to lookupswitch
noticed (while fixing #4429) that only "perfect" consecutive fixnum cases generate a *tableswitch*
javac does some [table/lookup space cost calc to decide](http://hg.openjdk.java.net/jdk8/jdk8/langtools/file/30db5e0aaf83/src/share/classes/com/sun/tools/javac/jvm/Gen.java#l1153), here just a simple size bound (of 32) is implemented
`case 0, 10, 20, 30` will generate a table-switch (filling in 'wholes' e.g. case 1: default)
while `case 0, 10, 50` will generate a lookup-switch just like before
> JIT fixnum cases (with a value span <= 32) as a tableswitch

- core/src/main/java/org/jruby/RubyProcess.java
- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/ruby/jruby/kernel/process.rb
This adds a `pid` method to threads returned by `Process.detach`,
as described in the open3.rb documentation. The thread is a
`Process::Waiter` to be consistent with standard Ruby.
I haven't worked in Java much before, so please let me know if there's
anything I'm missing.
Before:
```
>> JRUBY_VERSION
=> "9.1.4.0"
>> pid = Process.spawn('sleep 10')
=> 58487
>> thr = Process.detach(_)
=> #<Thread:0x45752059@(irb):3 run>
>> thr.pid
NoMethodError: undefined method `pid' for #<Thread:0x45752059@(irb):3 dead>
```
After:
```
>> JRUBY_VERSION
=> "9.1.9.0-SNAPSHOT"
>> pid = Process.spawn('sleep 10')
=> 59018
>> thr = Process.detach(_)
=> #<Process::Waiter:0x5acf93bb@(irb):3 run>
>> thr.pid
=> 59018
```
> Return Process::Waiter with pid in Process.detach

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerator.java
~ cherry-picked from master, so that feed and some others are available
resolves #1571
> (peazy) enumerator backports for 1.7

- core/src/main/java/org/jruby/RubyModule.java
While benchmarking a @Talkdesk JRuby application during our recent
hackaton, I noticed quite a lot of thread contention in a workload where
there should be no shared data.
Stack traces showed that there was contention while performing writes to
the method lookup cache:
```
java.lang.Thread.State: BLOCKED (on object monitor)
at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1027)
- waiting to lock <0x00000000e1565058> (a java.util.concurrent.ConcurrentHashMap$Node)
at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
at org.jruby.RubyModule.addToCache(RubyModule.java:1467)
at org.jruby.RubyModule.searchWithCache(RubyModule.java:1315)
at org.jruby.RubyModule.searchWithCache(RubyModule.java:1269)
at …
```
> Fix wrong method lookup cache used when class is prepended

- core/src/main/java/org/jruby/ir/targets/InvokeSite.java
Fixes #4596.
JRuby currently does not cache anything for method_missing calls
(i.e. calls to methods that do not exist on the target class's
method table). Instead, after discovering the missing method, it
proceeds down a slow lookup path, dispatching to method_missing
with a symbolic method name.
However this logic still attempts to acquire a SwitchPoint from
the target class, since that SP must be acquired before the
initial method lookup to ensure proper invalidation ordering.
Normally, this isn't a problem. If the class is still relatively
static, the SwitchPoint will be created once, and then the cost
of calling method_missing is the same as for non-indy. However for
type very rapidly. This led to a large number of unused
SwitchPoint being created, one for each class. And since the …
> Also increment thresholds in indy sites for method_missing.

- README.md
This PR updates the instruction about the README to point to latest stable where a version is mentioned.
> README: latest stable JRuby in install instruction

- core/src/main/java/org/jruby/util/JRubyClassLoader.java
Previously, the JRubyClassLoader would make a .deleteOnExit() call for
the temp directory and each temp file it needed to create.  This results
in the string for each registered path being stored in a hash that
increases each time a new URL is loaded or new ScriptingContainer is
created.
This commit removes the .deleteOnExit() calls and instead registers a
shutdown hook just after the temp directory is initially created.  At
shutdown time, the hook would delete any remaining files and the temp
directory itself.  This should effectively result in the same user
behavior as before but with the benefit of the temp path strings no
longer taking up an increasing amount of memory the longer the process
runs.
> Use shutdown hook to delete temp files instead of File.deleteOnExit

- core/src/main/java/org/jruby/ext/socket/RubyUDPSocket.java
- core/src/main/java/org/jruby/runtime/Helpers.java
See https://github.com/jruby/jruby/pull/4608#issuecomment-305386816
> Also fix EMSGSIZE on Alpine Linux. Relates to #4606

- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java
- spec/ruby/library/zlib/gzipreader/gets_spec.rb
- spec/ruby/library/zlib/gzipreader/ungetbyte_spec.rb
- spec/ruby/library/zlib/gzipreader/ungetc_spec.rb
I've had a stab at implementing the `unget*` methods for `Zlib::GzipReader`. The implementation is a bit limited in that the maximum number of bytes that can be "ungot" is hardcoded, since I'm using a `PushbackInputStream`. Also, it doesn't attempt to do anything clever with encoding (although I don't see that as a problem because `getc` [doesn't either](https://github.com/jruby/jruby/blob/9.1.10.0/core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java#L488-L489)).
Let me know what you think!
Closes #4631
> Implement Zlib::GzipReader #ungetbyte and #ungetc

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- spec/ruby/library/bigdecimal/gt_spec.rb
- spec/ruby/library/bigdecimal/gte_spec.rb
- spec/ruby/library/bigdecimal/lt_spec.rb
- spec/ruby/library/bigdecimal/lte_spec.rb
Hi, 
this fixes #4572 
Any feedback would be appreciated 
Thanks for the project!
andrea
> Fix Float::INFINITY BigDecimal comparison

- test/pom.rb
It fails with:
```
[INFO] --- gem-maven-plugin:1.0.10:initialize (default) @ jruby-tests ---
[INFO] ERROR:  Loading command: install (LoadError)
[INFO]  Unsupported platform: unknown-linux
[INFO] ERROR:  While executing gem ... (NoMethodError)
[INFO]     undefined method `invoke_with_build_args' for nil:NilClass
[INFO]
```
> Fix bootstrapping on AARCH64

- core/src/main/java/org/jruby/RubyFile.java
has been attempted at cbf9a7d156f42eb640b3a20e100793b516bf58c9
... using a fake root path, however on Windows /SMT expands as C:\SMT
got a bit inspired by `C:/fakepath` which browsers use but than I wasn't 100% sure
@headius' previous `/THIS_IS_A_FAKE_PATH_FOR_JRUBY` is probably a 'safer' bet ?
added '__' at the end so its more obvious if this is slightly off again (`classpath:BY\path` was confusing)
closes #4630 (also #4645)
> help classpath: canonicalization on Windows to fully resolve #4145

- README.md
This PR updates the README so that it refers to the latest release of JRuby when explaining how to install it using `rbenv`.
See #4622 for a PR that does the same thing for last version.
> README: Mention jruby-9.1.10.0 in rbenv note

- core/src/main/java/org/jruby/RubyTime.java
- spec/ruby/core/time/dup_spec.rb
- spec/ruby/core/time/localtime_spec.rb
- spec/ruby/core/time/shared/gmtime.rb
This is a fix for #4655 that replicates the MRI behaviour of frozen `Time` objects.
It adds three tests to `spec/ruby/core/time` that cover the MRI behaviour of frozen `Time` objects – I've tried to match the style of the existing tests and copied tests for the same behaviour in `Array`. I hope it looks ok.
The actual fix is very simple, in `#utc` and #localtime` I've added a check that will throw a `RuntimeError` when the instance is frozen.
There are two additional public methods that mutate `Time` objects, but they're not Ruby methods, and I'm unsure about whether or not they should throw errors:
* [`RubyTime#updateCal(DateTime)`](https://github.com/iconara/jruby/blob/d02707acaee08a36e5b37888d2a493e059539f74/core/src/main/java/org/jruby/RubyTime.java#L456-L458)
* …
> Make Time#utc and #localtime raise RuntimeError when the object is frozen

- core/src/main/java/org/jruby/ext/securerandom/RubySecureRandom.java
- core/src/main/java/org/jruby/ext/securerandom/SecureRandomLibrary.java
- lib/ruby/stdlib/securerandom.rb
- spec/ruby/library/securerandom/random_number_spec.rb
securerandom.rb imported from MRI's 2.3 stable line
re-implemented `random_number` (native in C-Ruby now) in Java to handle ranges
resolves #4607
> SecureRandom update to match Ruby 2.3

- core/src/main/java/org/jruby/RubyKernel.java
- test/jruby/test_jar_complete.rb
... if `File#getAbsolutePath()` is used - which seems like its not necessary
and we can pretty much just do what MRI does `File.dirname(__FILE__)`
##
wonder if caller is actually necessary in `__dir__` // cc @headius @enebo 
- initially it was caller-less https://github.com/jruby/jruby/commit/3efc72f47bace5aad4719362fa370c46e76fe1ee#diff-73ba50d02cf75f651e0b9d581d6bd4d5R1867
- caller has been added at https://github.com/jruby/jruby/commit/5fc06a0480011a5c35339a68116dd81d88b1876d#diff-e2320b4f8ce4644f50eb844d06a5de2eR1930
as adviced in https://github.com/jruby/jruby/issues/4611#issuecomment-307215241
> @kares I think we need the same special-case logic here, or better, make this call hopefully-existing logic that does the right thing already.
... this is relying on the existing …
> __dir__ won't work with embed paths such as uri:classloader: (#4611)

- core/src/main/java/org/jruby/RubyBasicObject.java
Although not used by default, the Reificator class at https://github.com/jruby/jruby/blob/9.1.10.0/core/src/main/java/org/jruby/RubyClass.java#L1583 checks which version of callMethod it should use, and needs all three versions: no argument, one argument, and more than one argument.
One of these overrides did not exist, and thus would result on a
```
java.lang.NoSuchMethodError: rubyobj.BrokenReify.callMethod(Ljava/lang/String;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;
```
when running an example with -Xreify.classes=true
```ruby
class BrokenReify
def initialize_copy(other)
super
end
end
puts BrokenReify.new.clone
```
With this fix, the above example starts instead giving a java.lang.StackOverflowError due to another bug/bad interaction of the …
> Fix missing callMethod override

- core/src/main/java/org/jruby/util/JarCache.java
> Also allow access control to trigger quiet bail out of jar index.

- core/src/main/java/org/jruby/RubyClass.java
- lib/ruby/stdlib/jruby/compiler.rb
- lib/ruby/stdlib/jruby/compiler/java_class.rb
- spec/jrubyc/java/constructor_spec.rb
- spec/jrubyc/java/files/method_visibility.rb
- spec/jrubyc/java/method_spec.rb
`jrubyc --java` generation updated to be a little smarter - trying to respect Ruby's visibility rules.
... `private, protected, public` as well as their `private :method, ...` counterparts now seamlessly 'work'
private Ruby methods (without an explicit `java_signature '...'` which is allowed to force generation) are no longer generated. also protected methods map to Java protected visibility by default.
(kind of) resolves #4469   (still undecided about what to do with with `xxx?` and `yyy!` methods)
> [jrubyc] respect Ruby visibility rules (do not generate private methods)

- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java
- spec/ruby/library/zlib/gzipreader/readpartial_spec.rb
In MRI it's ok to explicitly pass a nil buffer to `#readpartial`. However, JRuby currently throws a `TypeError`.
This adds a nil-check to bring JRuby in line with MRI's behaviour.
> Handle nil buffer in Zlib::GzipReader#readpartial

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/ir/instructions/BuildLambdaInstr.java
- core/src/main/java/org/jruby/ir/instructions/CallBase.java
- core/src/main/java/org/jruby/ir/instructions/ClosureAcceptingInstr.java
- core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/ArrayDerefInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter6.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter7.java
- core/src/main/java/org/jruby/ir/targets/InvokeSite.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/ir/targets/NormalInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/SelfInvokeSite.java
For #4686 and #4577.
The strategy here is as it was in 1.7: mark literal blocks as "escaped" when the call they were originally passed to returns. Break operations can then immediately trigger a LocalJumpError and be rescued in all the various ways reported in #4686 and #4577.
This does not fix super calls because the additional work is nontrivial (pushing literal-closure param through a lot of code in interpreter and JIT) and the exposure surface is pretty small for super PLUS literal closure PLUS break PLUS escaping of that block.
> Fix break not turning into LocalJumpError soon enough

- core/src/main/java/org/jruby/RubyIO.java
- spec/tags/ruby/core/io/set_encoding_tags.txt
Also untagged the now passing corresponding spec and checked if StringIO does the right thing (it does).
> IO#set_encoding should return self (fixes #4712)

- core/src/main/java/org/jruby/RubyHash.java
In Hash#fetch, the old error message assumed the key was a symbol. Instead we
inspect it like in MRI. This closes https://github.com/jruby/jruby/issues/4729.
> Fix error message in Hash#fetch

- core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java
- core/src/main/java/org/jruby/runtime/InterpretedIRBlockBody.java
- core/src/main/java/org/jruby/runtime/MixedModeIRBlockBody.java
Just some trivial spots I found recently:
* Some of those `promoteToFullBuild` (and analogously named) methods can be made `private` since they aren't used in child classes
* Removed dead import `import org.jruby.EvalType;`
* Fixed logger for `MixedModeIRBlockBody` (it was using the wrong class to bind to)
* Removed two redundant sets of the callcount to `-1` (`callCount = -1;` is not necessary since `context.runtime.getJITCompiler().buildThresholdReached(context, this);` will do this:
```java
public void buildThresholdReached(ThreadContext context, final Compilable method) {
final RubyInstanceConfig config = context.runtime.getInstanceConfig();
// Disable any other jit tasks from entering queue
method.setCallCount(-1);
```
=> sets the `-1` here either way.
> MINOR: cleanup setting callcounts for JIT

- core/src/main/java/org/jruby/ir/instructions/CallBase.java
Just two trivial things I found while researching something else:
* Removed some dead imports
* Added `final` to three fields that are never mutated anywhere to make this class a little easier to follow when trying to debug concurreny issues like #4739 :)
> MINOR: Add missing `final`s and cleanup dead imports in `org.jruby.irinstructions.CallBase`

- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/ext/tempfile/Tempfile.java
- spec/java_integration/addons/io_spec.rb
... with `file.to_java java.io.File`
> [ji] support converting Ruby File -> Java File

- core/src/main/java/org/jruby/internal/runtime/AbstractIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/runtime/Signature.java
The required arg count is constant for a compiled method:
* Made all steps of getting this number `final` (they obviously are final already in the execution)
* cached the `required` count
* Had to work around the fact that the `Signature` is `null` at times (in which case the `required` number isn't used down the line)
Saves us `3` bytes on this method, which can't hurt here? :)
left is this version, right is `master`
> MINOR: Cache required arg count in CompiledMethodIR

- core/src/main/java/org/jruby/RubyArgsFile.java
- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
- core/src/main/java/org/jruby/ext/socket/RubySocket.java
- core/src/main/java/org/jruby/ext/tempfile/Tempfile.java
- spec/java_integration/addons/io_spec.rb
... also some minor improvements -> avoid converting to Java string
`to_java(java.io.InputStream)` returns the very same as the existing `io.to_input_stream` does
it just seems to make sense for the Java side of RubyIO to use it like a Closeable/Flushable object
> [ji] make RubyIOs Java Closeable/Flushable + to_java to return stream

- core/src/main/java/org/jruby/ast/ListNode.java
`master` doesn't compile right now:
* JDK 7 needs `remove` implemented since it doesn't have the `default` here
* `java.lang.IndexOutOfBoundsException` needs a `String` input to the constructor
> Fix Broken Compilation

- core/src/main/ruby/jruby/kernel/file.rb
introduced by
https://github.com/jruby/jruby/commit/fd5e4140fb61e361027a28990865df61143214cf
9.1.13.0 also contains this error
> File.symlink? fix typo

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/specialized/RubyArrayOneObject.java
- core/src/main/java/org/jruby/specialized/RubyArrayTwoObject.java
Some cleanups I came across debugging `RubyArray` performance recently :)
* remove dead imports from `RubyArray`
* Extract the `USE_PACKED_ARRAYS == true` paths to a single `if` branch to be more JIT friendly here
* especially `isPackedArray` will be nicely dead code eliminated now for the `Collection` case and we save an expensive `size` call here and there (+ bytecode becomes smaller :))
* Make 2 methods `static` that had no instance reference anywhere
* Remove dead cast
* Removed redundant array creation for varargs method with one arguement
* Remove dead imports from packed array types
* Replaced slower collection to array conversion `list.toArray(new IRubyObject[list.size()]))` with the faster version `collection.toArray(IRubyObject.NULL_ARRAY)`
* …
> MINOR: Dry up RubyArray and improve performance in a few spots

- core/src/main/java/org/jruby/ir/passes/CompilerPass.java
- core/src/main/java/org/jruby/ir/passes/LiveVariableAnalysis.java
- core/src/main/java/org/jruby/ir/passes/OptimizeDynScopesPass.java
`LiveVariableAnalysis` didn't have a `getDependencies` method => the `DEPENDENCIES` constant was never used and `OptimizeDynScopesPass` not returned as a dependency:
* Added the `getDependencies` method
* Made `DEPENDENCIES` `private` here and in the parent to make this a little less confusing (other children of `CompilerPass` use the same approach => `private` rules out any inheritance weirdness imo :))
Also:
* Removed dead field `listeners` from `CompilerPass`
* Made `NO_DEPENDENCIES` in `CompilerPass` private since none of the child compiler passes use it (if they don't override `getDependencies` they get no dependencies => no need to use the constant in children)
> Fix DEPENDENCY constant missing getter on LiveVariableAnalysis

- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyRange.java
Just a random spot that can be dried up I found during profiling :)
The method has exactly the same code as the removed block (apart from two `final`s).
> MINOR: Dry up RubyRange#fixnumEach

- bench/src/main/java/org/jruby/benchmark/JavaInterfaceBenchmark.java
- core/src/main/java/org/jruby/ir/passes/LocalOptimizationPass.java
- core/src/main/java/org/jruby/java/codegen/RealClassGenerator.java
It seems when compiling Ruby implementations of Java interfaces, we were generating bytecode that runs any non-primitive type through `convertJavaToUsableRubyObject`.
This seems unnecessary to me if we know that we're dealing with an `IRubyObject` type of argument => we can save that call and the loading of the `Ruby` runtime argument, right?
I included the benchmark I used to verify that this comes with a positive performance impact (for me it showed about a `5%` speed-up).
>  Generate smaller bytecode when using Ruby type on implemented Java Interface + Benchmark

- core/src/main/java/org/jruby/java/codegen/RealClassGenerator.java
Same as #4777 but for the return type.
There is no point in running the typecast if the return type is an `IRubyObject` :)
That said ... small disclaimer:
I'm a little unsure I didn't make a mistake here, functionally this seems fine in my testing (and is fairly straightforward imo) but the performance gain is much bigger than that from #4777.
The `org.jruby.benchmark.JavaInterfaceBenchmark#benchHalfRubyVersion` benchmark goes from `0.036ops/ns` to `0.045ops/ns` for me, which seems like an unexpectedly huge increase.
> PERFORMANCE: Smaller bytecode for interface impl returns

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/ext/set/EnumerableExt.java
- core/src/main/java/org/jruby/ext/set/RubySet.java
- core/src/main/java/org/jruby/ext/set/RubySortedSet.java
- core/src/main/java/org/jruby/ext/set/SetLibrary.java
- core/src/main/ruby/jruby/set.rb
- spec/ruby/library/set/sortedset/add_spec.rb
- spec/ruby/library/set/sortedset/initialize_spec.rb
- spec/ruby/library/set/sortedset/to_a_spec.rb
- test/jruby/test_set.rb
work towards having `Set/SortedSet` natively instead of `set.rb`
had these changes lying around for a long-time (mostly waiting to target 9.2)
primarily this has been motivated for premium Java Integration features : 
`Set implements java.util.Set` and `SortedSet implements java.util.SortedSet`
but there's also a significant gain in performance.
set.rb is rather loosely written with some ugly-ness such as patching/features-detection on `SortedSet.new`
for maximum compatibility sets are backed by a `Hash` like before (and serializes the same as before), this is important for some older versions of Sprockets when under Rails switching between MRI and JRuby.
`SortedSet` uses Java's `TreeSet` implementation for ordering as it was available and performs better than the pieces in *set.rb*
some …
> native implementation of set.rb

- core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java
One performance improvement and one potential bugfix here:
Performance improvement:
* `DynamicMethodBox` adds a needless level of indirection. Moved the fields directly into `MixedModeIRMethod`
* Stopped making a copy of `actualMethod` for `null` check and invocation. I think this is fine, there is no place in the code that could possibly set a `null` here as far as I can see, right?
Bugfix:
* `volatile int callCount` is not safe for use as a counter here I think. It is incremented in a synchronized block (`box.callCount++`) in the jit method, but can also be set without synchronization from `setCallCount(int callCount)`.
* Fixed by synchronizing all write access to `callCount`
---------------
With indy on, this gets me from `0.055 ops/ns` (`master`) to `0.061ops/ns` (this branch) for the …
> Faster MixedModeIRMethod#call

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/instructions/BuildLambdaInstr.java
- core/src/main/java/org/jruby/ir/instructions/CallBase.java
- core/src/main/java/org/jruby/ir/instructions/ClosureAcceptingInstr.java
- core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/ArrayDerefInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/Bootstrap.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter6.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter7.java
- core/src/main/java/org/jruby/ir/targets/InvokeSite.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/ir/targets/NormalInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/SelfInvokeSite.java
This backports the fixes for #4694 and #4804 from 9.2 (master) to 9.1 (jruby-9.1).
> Backport LocalJumpError and EQQ fixes from 9.2

- core/src/main/java/org/jruby/RubyThread.java
- spec/tags/ruby/core/thread/status_tags.txt
> Fix spec of Thread#status for an externally killed thread that sleeps

- core/src/main/java/org/jruby/ext/ripper/RipperLexer.java
This PR fixes a typo in a comment in the Ripper code-base: a reference to an MRI function which had a typo.
> Fix typo in a method name comment

- COPYING
codehaus.org is gone. I think this is the correct yydebug url, now?
> Update yydebug's url

- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/ext/ffi/StructLayout.java
- core/src/main/java/org/jruby/ext/ripper/RipperLexer.java
- core/src/main/java/org/jruby/ir/interpreter/FullInterpreterContext.java
- core/src/main/java/org/jruby/ir/operands/SymbolProc.java
- core/src/main/java/org/jruby/util/Pack.java
- core/src/main/java/org/jruby/util/io/ChannelStream.java
Hello!
As part of the investigation that led to #4844, I integrated Error Prone (http://errorprone.info) into the JRuby compiler. (See configuration in https://github.com/nglorioso/jruby/commit/ae3a5cb605b2b8b31ba0fae66332086ce01730f9).
This found a number of bugs (ranging in severity/nagginess). I'm happy to revert or change any of these, but all of them represent real defects:
RubyEnumerable - each_with_index19 is trivially infinitely-recursive. I assumed that each_with_index is appropriate
StructLayout/SymbolProc - `hashCode()` ends up RSHIFT'ing an int value by 32 bits, which always ends up resulting in 0. I changed to 16 bits, but if you needed a stable hash code, I can change to XOR 0
RipperContext/FullInterpreterContext - Array.toString() is unhelpful for error messages. Manually …
> Fix issues discovered using Error Prone

- core/src/main/java/org/jruby/ext/ripper/HeredocTerm.java
- core/src/main/java/org/jruby/ext/ripper/RipperLexer.java
- core/src/main/java/org/jruby/ext/ripper/RipperParser.java
- core/src/main/java/org/jruby/ext/ripper/RipperParser.y
- core/src/main/java/org/jruby/ext/ripper/RipperParserBase.java
- core/src/main/java/org/jruby/ext/ripper/StringTerm.java
- core/src/main/java/org/jruby/lexer/LexingCommon.java
- core/src/main/java/org/jruby/lexer/yacc/HeredocTerm.java
- core/src/main/java/org/jruby/lexer/yacc/StringTerm.java
- test/jruby/test_ripper.rb
- test/mri.index
- test/mri/excludes/TestRipper/Filter.rb
- test/mri/excludes/TestRipper/Generic.rb
- test/mri/excludes/TestRipper/ParserEvents.rb
- test/mri/excludes/TestRipper/Ripper.rb
- test/mri/excludes/TestRipper/Sexp.rb
Same as #4898, but targeted on jruby-9.1 branch instead.
The main difference is that it skips https://github.com/jruby/jruby/pull/4898/commits/1763e4e3c1a5d121cec042663d60bc5309c6d379 that aligned the main parser and Ripper parser, as it seems the misalignment doesn't exist on this branch.
> Improve compatibility with MRI's Ripper for JRuby 9.1

- core/src/main/java/org/jruby/RubyInteger.java
- test/mri/ruby/test_integer.rb
Hi folks,
I was taking a look at open jruby issues and how to contribute with adding Ruby 2.5 support, so I prepared this small pull request.
I believe this is not a priority right now since Ruby 2.5 is not released yet, but I decided to contribute anyway, so I'm eager to receive feedback and check if I'm going in the right direction with this.
Please consider this as a WIP, since I could not see the results of the introduced tests in Travis although is working fine for me when I manually tested it in jirb.
Thanks,
> Implement Integer.sqrt

- core/src/main/java/org/jruby/ext/ripper/HeredocTerm.java
- core/src/main/java/org/jruby/ext/ripper/RipperLexer.java
- core/src/main/java/org/jruby/ext/ripper/RipperParserBase.java
- core/src/main/java/org/jruby/ext/ripper/StringTerm.java
- core/src/main/java/org/jruby/lexer/LexingCommon.java
- core/src/main/java/org/jruby/lexer/yacc/HeredocTerm.java
- core/src/main/java/org/jruby/lexer/yacc/StringTerm.java
- test/jruby/test_parsing.rb
- test/jruby/test_ripper.rb
This addresses additional (beyond #4898) parsing inconsistencies between MRI and JRuby (and JRuby's main Ruby parser and Ripper parser).
The additional tests introduced did not pass in the original JRuby version(s), but did pass when running through MRI.
> Miscellaneous parsing fixes

- test/jruby/test_thread.rb
When I run this test class on Travis CI,
some tests fail because on Travis CI
directrory name includes my account name,
so inspected result becomes:
```
<"#<Thread:0x7cf50001@foo@/home/travis/build/yui-knk/jruby/test/jruby/test_thread.rb:368 run>">
```
which does not match `</\#\<Thread\:0x\h+@foo(@[\w\/\._]+\:\d+)?\srun\>/>`.
> Allow "-" for directory name in `TestThread`

- test/mri/excludes/TestModule.rb
Currently `#test_method_added` does not fail.
> Add `#test_method_added` to test targets

- core/src/main/java/org/jruby/RubyMethod.java
- test/mri/excludes/TestMethod.rb
In MRI, `method_clone` uses CLASS_OF method objects
```
clone = TypedData_Make_Struct(CLASS_OF(self), struct METHOD, &method_data_type, data);
```
By this change, `TestMethod#test_clone` will be passed.
> Set MetaClass of cloned object

- test/mri/excludes/TestBasicInstructions.rb
Currently `#test_array_splat` does not fail.
> Include `#test_array_splat` to test targets

- core/src/main/java/org/jruby/RubyArray.java
to support Ruby 2.5, see https://bugs.ruby-lang.org/issues/12746.
#4876 
It seems like tests already existed in
spec/ruby/core/array/append_spec.rb and spec/ruby/core/array/prepend_spec.rb
Supersedes https://github.com/jruby/jruby/pull/4934
> Implement Array#prepend and Array#append aliases

- test/mri/excludes/TestMethod.rb
Currently `#test_singleton_method` does not fail.
> Add `#test_singleton_method` to test targets

- core/src/main/java/org/jruby/RubyDir.java
- spec/ruby/core/dir/glob_spec.rb
https://bugs.ruby-lang.org/issues/13056
Tests c&p from https://github.com/ruby/ruby/commit/52419a6e1032c4fe8fe6f6f6e2858dcd8fa32ba6.
#4876
> Implement Dir.glob base option

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyKeyError.java
- core/src/main/java/org/jruby/util/Sprintf.java
- test/mri/ruby/test_hash.rb
Hi,
This is another feature targeting Ruby 2.5 [1]: KeyError#receiver and KeyError#key (feature #12063).
Note: the tests are copied from MRI.
To implement this I followed the approach used with NameError class, since it has a similar behaviour. If this is not the right approach, just let me know.
> Implement KeyError#receiver and KeyError#key

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/RubyDir.java
- test/mri/ruby/test_dir.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Dir.children (feature #11302).
Notes:
* The tests are copied from MRI.
* I also cherry-picked a commit [2] from master to be able to use Java8 lambda expressions. If that's not OK, this PR could wait until that change is merged in ruby-2.5 branch; if this is the right approach, of course.
2. https://github.com/jruby/jruby/commit/12b9f0f7ee33d88c0ab38b0333ecc4f674a35502
> Implement Dir.children

- core/src/main/java/org/jruby/RubyDir.java
now it throws an ArgumentError like it does in MRI.
Introduced in #4936.
> Fix NullPointerException when option is not :base

- test/mri/excludes/TestEnumerable.rb
Currently `#test_slice_before` does not fail.
> Add `#test_slice_before` to test targets

- core/src/main/java/org/jruby/ext/set/RubySet.java
- spec/ruby/core/set/to_s_spec.rb
to support Ruby 2.5 and stated in this feature https://bugs.ruby-lang.org/issues/13676.
https://github.com/ruby/ruby/commit/d893c123f6b021254b21c920e182d3c64967f5d5.
#4876.
> Alias Set#to_s to inspect

- core/src/main/java/org/jruby/RubyHash.java
- test/mri/excludes/TestHash.rb
In MRI, `Hash#reject`
* creates new hash
* sets keys & values if block returns false
This commit will fix `#test_reject`.
Ref: https://github.com/ruby/ruby/blob/v2_4_0/hash.c#L1328
> Fix `Hash#reject`

- core/src/main/java/org/jruby/RubyHash.java
for Ruby 2.5 support as in https://bugs.ruby-lang.org/issues/8499 stated.
#4876
Tests are already in master, https://github.com/jruby/jruby/blob/7bd10a61c70d7ab271f5a1403b64ef37eaaf036a/spec/ruby/core/hash/slice_spec.rb
Commit: https://github.com/jruby/jruby/commit/75e45222cc109002dbf222f3f7032c40325b75f6#diff-a265476d146c86ed0f4352a5735b7e4b
Do we want to cherry-pick the tests to ruby-2.5 branch?
> Implement Hash#slice method

- core/src/main/java/org/jruby/RubyDir.java
to fix type cast error when last argument is not a hash.
> Check third argument type for Dir.glob

- core/src/main/java/org/jruby/ext/set/RubySet.java
- test/mri/test_set.rb
https://bugs.ruby-lang.org/issues/6589
Tests c&p from https://github.com/ruby/ruby/commit/8c90432af72a59d8934b2c94a1bc847449e1f393.
Supports #4876
> Add Set#reset

- spec/regression/symbol_encoding_spec.rb
Saw this tweet https://twitter.com/headius/status/766771177301774337
So I decided to write a few simple failing tests isolating issues issues discussed in #4070 and #3719. This could also overlap with #3880 so I figured I would mention that too.
Very happy to rename specs since I'm bad at naming them or committing these into ruby/spec if that is appropriate. I just put them here because of similar specs relating to #2896.
> Extra tests for symbol encoding Re: #4070 + #3719 and possibly #3880

- core/src/main/java/org/jruby/RubyDir.java
- test/mri/ruby/test_dir.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Dir.each_child (feature #11302).
Note: The test is copied from MRI.
> Implement Dir.each_child

- core/src/main/ruby/jruby/kernel.rb
- core/src/main/ruby/jruby/kernel/pp.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Kernel#pp by default (feature #14123).
~~Note: the tests are copied from MRI.~~
> Make Kernel#pp available by default

- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/RubyModule.java
In #4879, we got a report of heavy thread contention on the `addSubclasses` method of RubyClass. After investigating the locking involved (at @kares's recommendation), it seems as though much of this locking is excessively restrictive, using a runtime-global lock to prevent multiple threads from modifying any class's list of subclasses at the same time.
The subclasses list is also used heavily by method invalidation, and exploring that end of things showed me many places where we could improve performance.
* The global synchronization may be unnecessary most of these places, so long as the collections being modified are themselves thread-safe.
I have removed most of this but we need much more testing, review, analysis to confirm it's safe.
* The subclass aggregation logic creates many …
> Improvements to subclass management and method cache invalidation

- core/src/main/java/org/jruby/RubyHash.java
- spec/ruby/core/hash/rehash_spec.rb
Duplicate keys where just ignored before and inserted again.
Fix #4958.
> Fix Hash#rehash method for duplicate keys

- core/src/main/java/org/jruby/RubyHash.java
- test/mri/ruby/test_hash.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Hash#transform_keys and Hash#transform_keys! (feature #13583).
Note: the tests are copied from MRI.
> Implement Hash#transform_keys and Hash#transform_keys!

- core/src/main/java/org/jruby/ext/ripper/RipperLexer.java
- core/src/main/java/org/jruby/ext/ripper/StringTerm.java
- core/src/main/java/org/jruby/lexer/LexingCommon.java
- core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
- core/src/main/java/org/jruby/lexer/yacc/StringTerm.java
- core/src/main/java/org/jruby/parser/ParserSupport.java
- test/mri/excludes/TestRipper/Ripper.rb
- test/mri/excludes/TestRipper/Sexp.rb
This represents a stab at implementing the remaining Ripper compatibility as mentioned in #4898.
This uses the fact that Regexp tokenization is handled by a single StringTerm, and thus all tSTRING_CONTENT fragments are easily collectable until the tREGEXP_END comes with the options that we need for validation.
The validation itself is a copied/simplified version of what is performed by the main parser, as large parts the validation depended on the AST structure, which we do not have here.
Technically, this doesn't perform the validation at the same point in time as the main parser, as it performs the validation when encountering the tREGEXP_END token rather than when processing the regexp rule.
I speculate that the difference doesn't really matter given that the only thing we could do …
> Add support for validating Regexp in Ripper

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyInteger.java
- test/mri/ruby/test_integer.rb
Support for Ruby 2.5
See feature https://bugs.ruby-lang.org/issues/4052
> Make Integer#{round,floor,ceil,truncate} always return integer

- core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
- test/mri/excludes/TestStringchar.rb
MRI sets source encoding to character literal.
This commit will fix `#test_char`.
```ruby
p "a".encoding
p ?a.encoding
p ?\M-a.encoding
```
```shell
$ ruby -v /tmp/enc.rb
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
#<Encoding:UTF-8>
#<Encoding:UTF-8>
#<Encoding:UTF-8>
```
> Set encoding for character literal

- core/src/main/java/org/jruby/runtime/encoding/EncodingService.java
`findEncodingNoError` does not raise any error.
> Fix documents

- core/src/main/java/org/jruby/RubyFile.java
- test/mri/ruby/test_file_exhaustive.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]: File.lutime (feature #4052).
Nothing new, it's just a copy of File.utime implementation.
Note: the tests are copied from MRI.
> Add File.lutime

- core/src/main/java/org/jruby/RubyKernel.java
- test/mri/ruby/test_object.rb
Hi folks,
This is another feature targeting Ruby 2.5: Kernel.yield_self (feature #6721).
Note: the tests are copied from MRI.
> Implement Kernel.yield_self

- core/src/main/java/org/jruby/RubyModule.java
- test/mri/excludes/TestClass.rb
This commit will fix `TestClass#test_extend_object`.
> Raise `TypeError` if `#extend_object` is called for no module objects

- core/src/main/java/org/jruby/RubySymbol.java
- test/mri/excludes/TestSymbol.rb
Stop to append byte before inspect string.
For example, when an encoding of `symbolBytes` is UTF_16LE, "a" is
`[0x61, 0x00]`. If we append `":"` (0x3A) to `symbolBytes` before
inspect it, bytes are `[0x3A, 0x61, 0x00]` with UTF_16LE encoding.
This is not what we want to get. This commit chnages the order of
inspecting and appending to avoid this.
Ref: https://github.com/ruby/ruby/blob/v2_5_0/string.c#L10402
> Fix `Symbol#inspect` of UTF_16/UTF_32

- core/src/main/java/org/jruby/RubyRational.java
- test/mri/excludes/Rational_Test.rb
Ref: https://github.com/ruby/ruby/blob/v2_3_0/rational.c#L1104
> Accept `nil` as an argument of `Rational#<=>`

- core/src/main/java/org/jruby/RubyRational.java
- test/mri/excludes/Rational_Test.rb
In MRI
* if the argument is complex with zero imaginary part,
converts it to ratinal
* if the argument is complex with non-zero imaginary part,
converts self to complex
Ref: https://github.com/ruby/ruby/blob/v2_3_0/rational.c#L1171
> Implement `Rational#coerce` with `Complex` object

- core/src/main/java/org/jruby/RubyString.java
- test/mri/ruby/test_string.rb
See feature https://bugs.ruby-lang.org/issues/12694
https://github.com/jruby/jruby/issues/4876
> Ruby 2.5: Add String#delete_prefix and String#delete_prefix!

- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRational.java
1. Remove f_to_r call
MRI does not call `to_r` when `a1` is not a float nor a string.
Ref: https://github.com/ruby/ruby/blob/v2_3_0/rational.c#L2423-L2428
2. Call `#to_r` when `a1` is an integer
Ref: https://github.com/ruby/ruby/blob/v2_3_0/rational.c#L2445-L2446
> Fix `convertCommon`

- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/util/io/ModeFlags.java
- core/src/main/java/org/jruby/util/io/OpenFile.java
- test/mri/ruby/test_file.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1] on File#path method (feature #13568).
Note: The test is copied from MRI.
> Update File#path to raise IOError for files opened with File::Constants::TMPFILE option

- core/src/main/java/org/jruby/RubyIO.java
- test/mri/ruby/test_io.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1] on IO#write method (feature #9329).
> IO#write accepts multiple arguments

- bin/jruby.bash
- bin/jruby.sh
These scripts produce errors when run on FreeBSD (in the context of logstash). Adding the double dash prevents interpretation of the left operand as an option to expr itself. See also https://discuss.elastic.co/t/cannot-install-multiline-filter-on-freebsd-11/106929?source_topic_id=117201.
In particular, the culprit in the logstash issue was line https://github.com/jruby/jruby/blob/4cdf882cf1a17f71620886250e3519d4ab1ef91b/bin/jruby.bash#L247 expanding to "expr -C : .[.*]".
Thanks.
> fix issue where expr fails on freebsd.

- README.md
This PR adds an extra build badge to track the status of the `jruby-9.1` branch.
> README: Add jruby-9.1 branch Travis build badge

- lib/ruby/stdlib/resolv.rb
(This is a cherry-pick of https://github.com/jruby/jruby/pull/4981, here against `jruby-9.1`.) 
---
While https://github.com/jruby/jruby/commit/d1a760e066343e7a4956bbdd7be7975b1eda04cd fixed handling of compressed IPv6 addresses,
it also broke the "freeing" part of it.
Currently every DNS request leaks single request id:
```
require 'resolv'
Resolv::DNS::RequestID.values.map(&:length)
Resolv::DNS.new.getaddress('example.com')
Resolv::DNS::RequestID.values.map(&:length)
```
Given the fact that request ids are chosen from `0x0000..0xffff` range - the app can issue 65535 requests and then will be blocked forever trying to allocate another one.
This commit makes request id caching work by using same data for allocation and freeing.
> Do not leak DNS Request IDs

- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRational.java
This PR is porting of https://github.com/jruby/jruby/pull/5006.
Method names modulo19, op_idiv19 and op_mod19 have been changed on master branch.
So we should porting the commit manually.
I hope this PR fix "test:mri*".
> Fix test coerce2 for master branch

- core/src/main/java/org/jruby/RubyString.java
- test/mri/excludes/TestString.rb
because before it used the wrong index when there was a mulitbyte character in the string.
We now let handle rindex function the index detection.
> Fix String#rpartition for RegEx on Strings with multibyte chars

- core/src/main/java/org/jruby/RubyNumeric.java
- test/mri/ruby/test_float.rb
- test/mri/ruby/test_numeric.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]:
- Numerical comparison operators (< ,<=, >=, >) no longer rescue exceptions of #coerce. Return nil in #coerce if the coercion is impossible.
-  Integer#step does no longer rescue exceptions when given a step value which cannot be compared with #> to 0.
- Range#initialize no longer rescue exceptions when comparing begin and end with #<=> and raise a "bad value for range" ArgumentError but instead let the exception from the #<=> call go through.
All of these from feature #7688 [2].
2. https://bugs.ruby-lang.org/issues/7688
> No longer hide exceptions from coerce method

- core/src/main/java/org/jruby/Ruby.java
- test/mri/-ext-/string/test_enc_associate.rb
- test/mri/date/test_date_marshal.rb
- test/mri/dbm/test_dbm.rb
- test/mri/gdbm/test_gdbm.rb
- test/mri/pathname/test_pathname.rb
- test/mri/ruby/test_array.rb
- test/mri/ruby/test_class.rb
- test/mri/ruby/test_enumerator.rb
- test/mri/ruby/test_eval.rb
- test/mri/ruby/test_hash.rb
- test/mri/ruby/test_lazy_enumerator.rb
- test/mri/ruby/test_literal.rb
- test/mri/ruby/test_marshal.rb
- test/mri/ruby/test_module.rb
- test/mri/ruby/test_object.rb
- test/mri/ruby/test_pack.rb
- test/mri/ruby/test_rand.rb
- test/mri/ruby/test_range.rb
- test/mri/ruby/test_rubyoptions.rb
- test/mri/ruby/test_string.rb
- test/mri/ruby/test_thread.rb
- test/mri/ruby/test_transcode.rb
- test/mri/ruby/test_variable.rb
- test/mri/stringio/test_stringio.rb
- test/mri/test_delegate.rb
- test/mri/test_set.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]:
- Add FrozenError as a subclass of RuntimeError (feature #13224).
FrozenError will be used instead of RuntimeError for exceptions
raised when there is an attempt to modify a frozen object.
For more information, please see feature #13224
Note: The updated tests are copied from MRI.
> Add FrozenError class

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/RubyFile.java
timeval & ufiles only provide microsecond precision. Use timespec & futimens from libc to implement [File.ufile](https://ruby-doc.org/core-2.2.0/File.html#method-c-utime), to provide nanosecond precision.
This PR is required https://github.com/jnr/jnr-posix/pull/107 to be able to use the native function.
```ruby
F = '/tmp/test'
mtime = File.mtime(F)
File.utime(Time.now, mtime, F)
File.mtime(F) == mtime or raise "File.mtime should be == mtime"
```
```
$ touch /tmp/test
$ stat /tmp/test 
File: /tmp/test
Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 802h/2050d      Inode: 430953      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  alexis)   Gid: ( 1000/  alexis)
Access: 2017-09-23 15:50:57.974453385 -0700
Modify: 2017-09-23 15:50:57.974453385 -0700 …
```
> [#4710] nanosecond precision in utime using libc futimens

- core/src/main/java/org/jruby/RubyString.java
When working on https://github.com/jruby/jruby/pull/5039 I noticed one of String tests on #chomp! method was not passing:
```ruby
s = S("").freeze
assert_raise_with_message(FrozenError, /frozen/) {s.chomp!}
```
https://github.com/jruby/jruby/blob/ruby-2.5/test/mri/ruby/test_string.rb#L445
After looking closely, I learned that MRI folks introduced this test on https://github.com/ruby/ruby/commit/80aa1e6218305b2f75c47af368506a7f930f1214.
I'm proposing this change since this is a difference between MRI and JRuby.
Behavior before applying this change:
```
miguel@alice:~/jruby/upstream/jruby$ PATH=$PWD/bin:$PATH jirb
irb(main):001:0> s = String.new("").freeze
=> ""
irb(main):002:0> s.chomp!
=> nil
irb(main):003:0>
```
Behavior after applying this change:
``` …
```
> Add modification check on String#chomp! method with default separator

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/StringSupport.java
- test/jruby/test_string.rb
... otherwise code doing utf8 str scan might fail with array-out-of-index
resolves GH-2036
someone with C knowledge please review, seems to me that MRI handles the case without special care : 
at `rb_memsearch_qs_utf8_hash(byte[] xBytes, final int x)` while `x == xBytes.length`
> align C ported memsearch code - need to handle array[length] properly

- core/src/main/java/org/jruby/Ruby.java
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Deprecate Data class (feature #3072).
> Deprecate Data class

- core/src/main/java/org/jruby/RubyModule.java
- test/mri/ruby/test_module.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]:
- Module#attr, attr_accessor, attr_reader, attr_writer are now public (feature #14132).
> Module#attr, attr_accessor, attr_reader, attr_writer are now public

- core/src/main/java/org/jruby/RubyProcess.java
- test/mri/ruby/test_process.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Process::last_status method (feature #14043).
> Add Process::last_status method

- core/src/main/java/org/jruby/RubyModule.java
- test/mri/ruby/test_module.rb
Hi folks,
This is another feature targeting Ruby 2.5 [1]:
- Module#define_method, alias_method, undef_method, remove_method are now public (feature #14133).
> Module#define_method, alias_method, undef_method, remove_method are now public

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/anno/AnnotationBinder.java
- core/src/main/java/org/jruby/anno/AnnotationHelper.java
- core/src/main/java/org/jruby/anno/JavaMethodDescriptor.java
- core/src/main/java/org/jruby/anno/TypePopulator.java
- core/src/main/java/org/jruby/internal/runtime/methods/InvocationMethodFactory.java
- core/src/main/java/org/jruby/internal/runtime/methods/InvokeDynamicMethodFactory.java
accounts for a slight speed-up - the populator won't execute much 'redundant' code
this isn't the main issue with boot (compared to invokers) but still deserves a hand-craft
> refactor annotation-binder generated populators

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyBoolean.java
- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/RubyNil.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- core/src/main/java/org/jruby/java/proxies/ConcreteJavaProxy.java
- core/src/main/java/org/jruby/java/proxies/JavaProxy.java
- core/src/main/java/org/jruby/javasupport/JavaAccessibleObject.java
- core/src/main/java/org/jruby/javasupport/JavaObject.java
- core/src/main/java/org/jruby/javasupport/JavaPackage.java
- core/src/main/java/org/jruby/javasupport/JavaUtil.java
- core/src/main/java/org/jruby/runtime/builtin/IRubyObject.java
- core/src/test/java/org/jruby/embed/ScriptingContainerTest.java
This change allow callers to skip the cast when calling toJava
on a Ruby object. It was initially done to assist work on #4781
by allowing a simple "throw rubyException.toJava(Throwable.class).
I tested binary compatibility in two ways:
* A full recompile with all generification in place plus testing
standard JRuby commands. This confirms that classes recompiled
against the API but without other use of generics still function
properly.
* A partial recompile with only the generified classes rebuilt.
This tests that classes not compiled against the API still
function properly.
Of course any external JRuby extensions (readline, openssl) will
have been tested by running those standard commands (e.g. irb,
gem install).
> Generify IRubyObject.toJava to make it more pleasant to use.

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/date/DateLibrary.java
- core/src/main/java/org/jruby/ext/date/DateUtils.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/date/RubyDateTime.java
- core/src/main/java/org/jruby/ext/date/TimeExt.java
- core/src/main/java/org/jruby/util/RubyDateFormatter.java
- core/src/main/java/org/jruby/util/RubyDateParser.java
- core/src/main/java/org/jruby/util/RubyTimeOutputFormatter.java
- core/src/main/java/org/jruby/util/StrptimeParser.java
- core/src/main/java/org/jruby/util/TimeZoneConverter.java
- lib/ruby/stdlib/date.rb
- lib/ruby/stdlib/date/format.rb
- spec/tags/ruby/library/date/minus_month_tags.txt
- spec/tags/ruby/library/date/valid_jd_tags.txt
- spec/tags/ruby/library/datetime/hour_tags.txt
- spec/tags/ruby/library/datetime/min_tags.txt
- spec/tags/ruby/library/datetime/minute_tags.txt
- spec/tags/ruby/library/datetime/sec_tags.txt
- spec/tags/ruby/library/datetime/second_tags.txt
- test/jruby.index
- test/jruby/test_date.rb
- test/mri/excludes/TestDateStrftime.rb
- test/mri/excludes/TestSH.rb
still using JODA but all of the JI stuff in date.rb is gone behind ext classes, motivation : 
- for a while its 'hard' to create `Date` instances in AR-JDBC
- some near era conversion had a nasty bug in all 9K which constantly pops up in AR-JDBC
- some isolated AR benchmarks showed its slower than MRI
- there's going to be some nice JI bonuses - `toJava` working as with `RubyTime` etc.
some parts were already in native (formatting) so the base setup was already there.
NOTE: in MRI pretty much all of the date.rb is in native - so there's still space for improvement.
e.g. `_parse` would make sense to end up in .java maybe someone will attempt it afterwards.
p.s. left behind one minor suite failure (argument validation `hour: 24+1.to_r/2`)
while its simple the bigger picture (of MRI argument …
> redo date.rb (most) parts in native

- core/src/main/java/org/jruby/RubyInteger.java
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Integer#allbits?, Integer#anybits? and Integer#nobits? methods (feature #12753).
All associated MRI and ruby/spec tests are passing.
2. https://bugs.ruby-lang.org/issues/12753
> Add Integer#allbits?, Integer#anybits? and Integer#nobits?

- lib/ruby/stdlib/securerandom.rb
[ruby-core:68098] [Feature #10849] proposed by Andrew Butterfield.
SecureRandom.choose and SecureRandom.graph is not included.
(The implementation has SecureRandom.choose but it is private.)
I feel the method name, SecureRandom.choose, doesn't represent
the behavior well.
The actual use cases of SecureRandom.graph is not obvious.
#4876.
> SecureRandom.alphanumeric implemented.

- core/src/main/java/org/jruby/RubyTime.java
https://bugs.ruby-lang.org/issues/13919
#4876
> Time#at receives 3rd argument which specifies the unit of 2nd argument

- core/src/main/java/org/jruby/RubyMethod.java
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Add Method#=== that invokes #call (feature #14142).
The associated MRI test to the feature work as expected:
```ruby
def test_eqq
assert_operator(0.method(:<), :===, 5)
assert_not_operator(0.method(:<), :===, -5)
end
```
```
miguel@alice:~/jruby$ PATH=$PWD/bin:$PATH jruby test/mri/runner.rb -v --color=never --tty=no --excludes=test/mri/excludes -q -n test_eqq -- ruby/test_method.rb
Run options: -v --color=never --tty=no --excludes=test/mri/excludes -q -n test_eqq --
[1/1] TestMethod#test_eqq = 0.02 s
Finished tests in 0.260273s, 3.8421 tests/s, 15.3685 assertions/s.
1 tests, 4 assertions, 0 failures, 0 errors, 0 skips
ruby -v: jruby 9.3.0.0-SNAPSHOT (2.5.0) 2018-03-04 96b264b Java HotSpot(TM) 64-Bit Server VM 25.102-b14 on …
```
> Add Method#=== that invokes #call

- lib/ruby/stdlib/resolv.rb
- test/mri/resolv/test_dns.rb
There's an edge case in resolv.rb that can lead to file descriptor leaks on a highly saturated system (logstash in our case).
(the cliff at the end is from a restart of logstash)
We're using the logstash-filter-dns plugin which [uses timeout](https://github.com/logstash-plugins/logstash-filter-dns/blob/v3.0.7/lib/logstash/filters/dns.rb#L250-L252).
When a timeout fires while [waiting](https://github.com/jruby/jruby/blob/9.1.13.0/lib/ruby/stdlib/resolv.rb#L659-L668) for a [random](https://github.com/jruby/jruby/blob/9.1.13.0/lib/ruby/stdlib/resolv.rb#L817) [port](https://github.com/jruby/jruby/blob/9.1.13.0/lib/ruby/stdlib/resolv.rb#L764), the new object is never returned to the caller. Instead `requester` is [set to nil](https://github.com/jruby/jruby/blob/9.1.13.0/lib/ruby/stdlib/resolv.r …
> Fix file descriptor leak in resolv.rb

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java
Hi folks,
This is another change adding Ruby 2.5 support [1]: Enumerable#any?, all?, none? and one? now accept a pattern argument (feature #11286 [2]).
All associated MRI and ruby/spec tests ~~(except one [3] for #any?)~~ are passing.
2. https://bugs.ruby-lang.org/issues/11286
3. ~~https://github.com/jruby/jruby/blob/3813f0a53c22af8122e8c2b70c7d87ae35323109/spec/ruby/core/enumerable/any_spec.rb#L214~~
> Enumerable#any?, all?, none? and one? now accept a pattern argument

- core/src/main/java/org/jruby/RubyStruct.java
Hi folks,
This is another feature targeting Ruby 2.5 [1]: Add keyword_init option to Struct.new (feature #11925).
> Add keyword_init option to Struct.new

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/Sprintf.java
Hi folks,
This PR should fix most of the remaining failures for String in ruby-2.5 ruby/spec suite.
- https://github.com/jruby/jruby/commit/2e1987d0b7dd7eb5177c73a5eb902df487eaefc1 and https://github.com/jruby/jruby/commit/77cc454b2f5d49b436e09db763aa265cd59607af fix failed assertions like https://github.com/jruby/jruby/blob/f06aa9daa7e23be15e06be953128f5063b42a431/spec/ruby/core/string/delete_prefix_spec.rb#L15.
- https://github.com/jruby/jruby/commit/113bde333d0d8d806a05713820025b6451b87b90 and https://github.com/jruby/jruby/commit/617e7835d3a087186a58e0e1cdc5dbcdf901d1ed fix failed assertions like https://github.com/jruby/jruby/blob/f06aa9daa7e23be15e06be953128f5063b42a431/spec/ruby/core/string/delete_suffix_spec.rb#L77.
- https://github.com/jruby/jruby/commit/49a74b95fbd7a00a22cdeb0a1a …
> Fix failed Ruby 2.5 ruby/spec tests for String

- pom.rb
- pom.xml
... not sure if there was a previous reason to stay so far behind
most changes are bugfixes and more importantly matching up TZ data rules
maybe the time-zone data should get regenerated as well ... https://github.com/jruby/joda-timezones ?
> upgrade joda-time library to latest 2.9.9

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/runtime/JavaSites.java
Hi folks,
This PR should fix remaining failures [1] for Range in ruby-2.5 MRI test suite.
1. https://github.com/jruby/jruby/blob/1b7c3308ba68151b1f5e48cb351155dac58ddc50/test/mri/ruby/test_range.rb#L390
For more information, please see bug #14048.
/cc: #4876
> Range should raise TypeError if necessary method is not defined

- core/src/main/java/org/jruby/runtime/load/LibrarySearcher.java
expand load paths to real paths to get rid of duplicate loading from
symbolic-linked directories. [Feature #10222]
https://github.com/ruby/ruby/commit/b6d3927e16357408720203a949cfa8741b9ebf6c
This fixes
- ``test/mri/ruby/test_require.rb#test_symlink_load_path``
> Require real path

- core/src/main/java/org/jruby/runtime/load/LibrarySearcher.java
Reverts jruby/jruby#5109
I believe this broke some tests that depend on it *not* traversing symlinks, such as here: https://travis-ci.org/jruby/jruby/jobs/359034412
@ChrisBr I am about to merge 2.5 to master, so if you want to take another crack at this, base your PR on master.
> Revert "Require real path"

- core/src/main/java/org/jruby/util/io/EncodingUtils.java
The corresponding MRI tests are already present [here](https://github.com/jruby/jruby/blob/master/test/mri/ruby/test_io_m17n.rb#L1612-L1648).
Implements [Ruby Bug #13350](https://bugs.ruby-lang.org/issues/13350).
> :newline option to File.open implies text mode now. (Part of #5118)

- core/src/main/java/org/jruby/RubyTime.java
Hi!
As I was misunderstanding `nsec` in `RubyTime`, and trapped in the pitfall when manipulating `RubyTime` from Java, I just wondered if I could leave that in Javadoc explicitly. Nothing is described in http://jruby.org/apidocs/org/jruby/RubyTime.html for the time being.
I'm totally fine to get them edited, but wanted at least to describe they're not the entire fraction part. What do you think?
> Javadoc nanosecond-related methods in org.jruby.RubyTime

- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
In CRuby, an uncaught exception messages users with the exception's message, considering if it's overriden or not.
e.g.
```ruby
class A < StandardError
def message
'hello'
end
end
raise A
```
* CRuby stderr: `/tmp/vu4TBd5/647:7:in `<main>': hello (A)`
* JRuby stderr: `A: A\n <main> at /tmp/vu4TBd5/648:7`
This pull request changes JRuby behaviour similar to CRuby's.
* (patched) JRuby stderr: `A: hello\n <main> at /tmp/vu4TBd5/650:7`
Note that if the overriden `message` method raises an exception, it shouldn't message the internal exception, but the external exception, according to CRuby Bug #14566 https://bugs.ruby-lang.org/issues/14566
This pullreq already considers that.
e.g.
```ruby
class A < StandardError
def message
raise 'boom boom!'
end
end
raise A
```
* CRuby stderr: …
> Support overriding `Exception#message`

- core/src/main/ruby/jruby/kernel/enumerable.rb
The second part of the pair was ignored before which resulted e.g.
```
class Foo
include Enumerable
def each
yield 1
yield 1,2
end
end.new.to_enum.uniq -> [1] instead of [1, [1,2]]
```
Fixes test/mri/ruby/test_enum.rb#test_uniq test.
> Fix Enumerable#uniq for entry pair

- core/src/main/java/org/jruby/embed/jsr223/JRubyEngine.java
- core/src/test/java/org/jruby/embed/jsr223/JRubyEngineTest.java
The handling of exc exceptions in the jsr223 JRubyEngine assumes that all exceptions have causes, and that the cause has a non-null message.  This is not always the case and results in a NullPointerException without the original exception.
I added a test for the two cases I know of.
I noticed that all the other tests for the jsr223 JRubyEngine are disabled.  Any reason for that?
> Handle exception cause with null message

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
- lib/ruby/stdlib/fileutils.rb
In MRI, File.rename will raise an EXDEV if the rename is attempted with paths that span devices (mounts). Up until this PR, we would raise EACCES in such a situation, requiring us to modify fileutils.rb to deal with both errors.
Because this is tweaking a very core behavior of File and FileUtils, I'm pushing to a branch to see how it affects our test runs.
This fix is an attempt to deal with at least part of Bundler's vendoring of a non-JRuby fileutils.rb. See bundler/bundler#6532.
> Remove hack for FileUtils.mv due to incorrect error raised from File.rename

- core/src/main/java/org/jruby/RubyBasicObject.java
- spec/jrubyc/java/constructor_spec.rb
- spec/jrubyc/spec_helper.rb
(been deprecated all way back to 1.7) ... so maybe a good time to remove?!
and resolve #1408
> [ji] allow for initialize() to be a valid Java method

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/javasupport/JavaSupportImpl.java
- core/src/main/java/org/jruby/javasupport/ext/JavaExtensions.java
- core/src/main/java/org/jruby/javasupport/ext/JavaIo.java
- core/src/main/java/org/jruby/javasupport/ext/JavaLang.java
- core/src/main/java/org/jruby/javasupport/ext/JavaLangReflect.java
- core/src/main/java/org/jruby/javasupport/ext/JavaNet.java
- core/src/main/java/org/jruby/javasupport/ext/JavaUtil.java
- core/src/main/java/org/jruby/javasupport/ext/JavaUtilRegex.java
- core/src/main/java/org/jruby/util/cli/Options.java
- seems to work fine to the limited testing that I did locally
- the gist is - Java extensions load on demand as Java classes are (first) used
- theoretically we could also add a flag to disable the laziness and behave as before
also ... we could safely add more extensions now and do not have to worry much about bloating load times
did not run any numbers yet, but hopefully we do not do much JI internally on `gem list`, `rake` etc
> [ji] lazy loading of Java (proxy) class extensions

- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/date/RubyDateTime.java
- spec/java_integration/types/coercion_spec.rb
- test/jruby/test_date.rb
e.g. `Time.now.to_java(java.time.LocalDateTime)` and friends with some consumable Java APIs
... backwards compatibility maintained -> `time.to_java` still gives a `java.util.Date` (by default)
> [ji] support Java time APIs with Time/Date/DateTime

- core/src/main/java/org/jruby/RubyString.java
- spec/java_integration/types/coercion_spec.rb
- test/jruby/test_helper.rb
- test/jruby/test_higher_javasupport.rb
found this :paintbrush: at https://github.com/jruby/jruby/pull/3937/files#diff-2f8f0aefd8a8637512ce6c017da265b9
knew I saw a draft of this somewhere but did not find it until I checked some old PRs :)
... there's an opportunity here to have `RubyString implements CharSequence`
this is expected to fit nicely esp. will avoid conversions on logging libraries e.g. log4j2 
(so one doesn't need to do an if check: `logger.debug('foo') if logger.isDebugEnabled`)
but its a breaking change in 2 ways : 
- `RubyString#length` needs to be changed (to return int) -> not expected to be used much
- seeing a `java.lang.CharSequence` by JI will no longer conver to a java string
both seem acceptable for a major release such as 9.2 (we sure can not do this in a minor one)
> [ji] RubyString implements CharSequence

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyObjectSpace.java
- core/src/main/java/org/jruby/ext/jruby/JRubyLibrary.java
- core/src/main/java/org/jruby/util/func/Function1.java
- core/src/main/ruby/jruby/jruby.rb
- lib/ruby/stdlib/jruby/core_ext/class.rb
has been discussed at: https://github.com/jruby/jruby/issues/4741 ... non clashing replacement: `JRuby.subclasses_of(klass, all: false)`
> deprecate jruby/core_ext Class#subclasses

- core/src/main/java/org/jruby/RubyModule.java
> Clone proc blocks as well so they have their own frame etc.

- core/src/main/java/org/jruby/runtime/ivars/VariableAccessor.java
- core/src/main/java/org/jruby/util/cli/Options.java
So it turns out that since we turned on reified instance variables by default, those variables have not been volatile. This is actually good news, since we wanted to move away from a full volatility guarantee on instance variables in favor of explicit declaration (`attr_accessor :foo, volatile: true`) or libraries like concurrent-ruby.
This PR simply flips the switch for the remaining varTable-based instance variables, bringing them in line with field-based instance variables as far as volatility goes.
I have also filed #5186 to finish the reification project and *add back* the ability to turn on volatility as desired. This will be needed in any case to support declarative volatility in a future update to Ruby.
> Non-volatile instance variables

- lib/pom.rb
- lib/pom.xml
... now using `JRuby::Util.load_ext` mechanism for #5205
+ updated JLine to 2.14.6 
contains a couple of interesting features/fixes - wonder why it lagged behind
e.g. OSv support, HP-UX working, avoided (class) memory leaks, printing "Display all 104 possibilities? (y or n)" on a new line, ...
UPDATE: there seems to be one visible regression under Linux - printing space after irb completion
believe we can fix that and also make jruby-readline usable as a standalone gem
... should we eventually also push to RubyGems? (would be great to test out new release under Windows)
> update jruby-readline to new release

- core/src/main/java/org/jruby/RubyRegexp.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
- lib/ruby/stdlib/date/format.rb
as an attempt to speed-up https://github.com/jruby/jruby/issues/5255
... this gets slightly faster on HotSpot, still noticeably slower than MRI (which has these in C)
Graal might be in a better spot doing EA, since the frame writes aren't there ...
> [refactor] improve Date parsing performance

- core/src/main/java/org/jruby/RubyGlobal.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyNil.java
- core/src/main/java/org/jruby/ext/pathname/RubyPathname.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java
- core/src/main/java/org/jruby/runtime/Helpers.java
This is a very early stage of implementing open addressing for JRuby hashes suggested in https://github.com/jruby/jruby/issues/4708. The MRI issue is located here: https://bugs.ruby-lang.org/issues/12142. 
After discussing with @headius, he suggested to open a PR to continue discussion here. Please note that this is far from a mergable state.
I tried a very simple benchmark and recognize a small performance improvement:
```
require 'benchmark'
n = 50_000
small = 1000
tmp = {}
Benchmark.bmbm do |x|
x.report("Add:") { n.times { small.times { |small| tmp[small] = true } } }
x.report("Fetch:") { n.times { small.times { |small| tmp[small] } } }
end
```
Gives me with this PR:
```
Rehearsal ------------------------------------------
Add:     5.880000   0.220000   6.100000 (  5.127261)
Fetch: …
```
> Open addressing algorithm for RubyHash

- BUILDING.md
This PR adds a note to the build documentation that the **required JDK is 8** and later.
- See #5247
> BUILDING.md: Mention Java 8 JDK is required

- bench/src/main/java/org/jruby/benchmark/EncodingBenchmark.java
- core/src/main/java/org/jruby/RubyEncoding.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/runtime/encoding/EncodingService.java
- core/src/main/java/org/jruby/util/RubyDateFormatter.java
first UTF-16 is broken on Java 10+ since it assumes `char[]` value String internals (using Unsafe)
doing that, spotted a few less copy `byte[]`/`char[]` opportunities and started micro-benchmarking
by separating String/CharSequence paths down the encoding pipe there seems to be gains (maybe its likely due HotSpot's JIT assuming the CS method as mono-morphic as they only get a `StringBuilder`)
but since the micro benchmark wasn't assuring (non StringBuilder CharSequence paths do get slower in JMH) I did some AR-JDBC "raw" AR benchmarking ...
surprisingly this seems to make sense as there seems to be a noticeable almost 5% speed gain
> review String -> RubyString UTF (8) encoding

- core/src/main/java/org/jruby/RubyHash.java
This will fix https://github.com/jruby/jruby/issues/5280 as we only use eql? now on a bin and hash collision. Before we didn't check the hash as we did not store it. This will restore similar behavior before the new hash implementation.
> Implement hash cache to fix #5280

- core/src/main/java/org/jruby/RubyHash.java
- spec/tags/ruby/core/hash/initialize_tags.txt
Hi folks,
This change should fix a failed spec for Hash#initialize.
Hash#initialize can be used to reset the default value.
Cheers,
> Fix Hash#initialize spec tagged as failed

- core/src/main/java/org/jruby/RubyEnumerable.java
- spec/tags/ruby/core/enumerable/find_index_tags.txt
Hi folks,
This change should fix the remaining failing specs for Enumerable#find_index.
This change removes the assumption that #each would yield passing always a single object. It could yield without passing parameters, passing one or more objects or yield an explicit array (empty or not).
> Fix some failed Enumerable#find_index specs

- core/src/main/java/org/jruby/RubyHash.java
We used the old bins array to get the index instead of the new one.
This caused that the bins array was wrongly calculated if a
collisions occours and eventually did not found keys in the hash
anymore.
Fix #5304
> Fix Hash#rehash for open addressing

- core/src/main/ruby/jruby/kernel/enumerable.rb
- spec/tags/ruby/core/enumerable/uniq_tags.txt
Hi folks,
This should fix another failed spec for Enumerable#uniq spec.
Use case: when yielded with multiple arguments, returns all yield arguments as an array.
> Fix failed Enumerable#uniq spec when yielded with multiple arguments

- core/src/main/java/org/jruby/RubyArray.java
- spec/tags/ruby/core/enumerable/all_tags.txt
Hi folks,
This change should fix more failing tests with Enumerable#all? when given a pattern argument.
The approach is similar to what is implemented for Enumerable#any? [1]
1. https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyArray.java#L4435-L4440
> Fix remaining failing tests with Enumerable#all? when given a pattern argument

- core/src/main/java/org/jruby/ir/IRBuilder.java
The original logic would continue to check nil for each lazy call,
even after a nil resulted from one of the elements. This new logic
will always branch to the end of the chain if a nil is encountered
anywhere along the way.
This combined with the indy BNil patch produces the best perf for
a benchmark of a long chain of calls against an always-nil value.
> Short-circuit chained lazy calls once a nil is encountered.

- core/src/main/ruby/jruby/kernel/enumerable.rb
- spec/tags/ruby/core/enumerable/slice_when_tags.txt
Enumerables with 1 element
Fixes #5275. Instead of checking for size 1 at the beginning, this change sets a
flag that never gets modified if `each_cons(2)` does not get called.
This happens in the case of 1 element Enumerables. The previous
behavior was fine for Enumerables that respond to `size` but fails
otherwise.
> Fixes underlying logic of slice_when / chunk_while to handle 1 element collections

- core/src/main/java/org/jruby/RubyHash.java
as we store now the hash values, we do not need to recalculate the hashes while resizing again.
Also using System.arraycopy for entries and hashes arrays seems to be faster than manually assigning them inside the loop.
```
benchmark:
10: 'tmp = {}; i = 0; while i < 10; tmp[i.to_s] = i; i += 1; end;'
20: 'tmp = {}; i = 0; while i < 20; tmp[i.to_s] = i; i += 1; end;'
30: 'tmp = {}; i = 0; while i < 30; tmp[i.to_s] = i; i += 1; end;'
40: 'tmp = {}; i = 0; while i < 40; tmp[i.to_s] = i; i += 1; end;'
50: 'tmp = {}; i = 0; while i < 50; tmp[i.to_s] = i; i += 1; end;'
60: 'tmp = {}; i = 0; while i < 60; tmp[i.to_s] = i; i += 1; end;'
70: 'tmp = {}; i = 0; while i < 70; tmp[i.to_s] = i; i += 1; end;'
80: 'tmp = {}; i = 0; while i < 80; tmp[i.to_s] = i; i += 1; end;'
90: 'tmp = {}; i = 0; while i …
```
> Improve RubyHash#resize performance

- test/jruby/test_string.rb
The regression test in https://github.com/jruby/jruby/commit/b0875446c80d496a7f0e4b71183beef0839f4de1 is very good. Unlike the regression test in https://github.com/jruby/jruby/commit/b0875446c80d496a7f0e4b71183beef0839f4de1, however, the AWS S3 SDK receives a string via a regex and encounters the same bug. 
The regression test in this PR mimics the S3 SDK by receiving a string from a regex match and asserts that the string is not mutated via StringIO manipulation.
This regression test fails without https://github.com/jruby/jruby/commit/b0875446c80d496a7f0e4b71183beef0839f4de1 , but succeeds with that fix.
Related to https://github.com/jruby/jruby/issues/5203#issuecomment-408656779. cc/ @kares
> Add Complimentary Regression Test for GH-5203

- core/src/main/java/org/jruby/Ruby.java
Fixes #5190.
CRuby's fstring cache, used for frozen string deduplication, uses
slightly different equalitye logic than the default equality for
strings. Specifically, if two strings have the same 7bit ascii
bytes, but two different ascii-compatible strings, the strings are
still considered to be equal. But for the fstring cache, you can
register the same 7-bit string with different ascii-compatible
encodings and they both live in the cache.
In JRuby, we use a standard JDK collection, ConcurrentHashMap,
that always uses the standard equals() method that works like
normal String equality as described above. We are forced to use
a wrapper, both for storage and for lookup. This patch introduces
that wrapper, and also introduces a thread-local caching mechanism
to reduce the cost of looking up …
> Consider encoding when deduplicating strings.

- core/src/main/java/org/jruby/util/ShellLauncher.java
This PR is to resolve #1183 by replacing the remaining stop calls with interrupt calls.
This may lead to bad behavior in the threads we formerly forced to stop, but it would be better to know that these cases exist than continue to call this bad method.
> Remove thread stop

- core/src/main/java/org/jruby/RubyNil.java
- spec/tags/ruby/core/nil/nilclass_tags.txt
I noticed an small difference between MRI and JRuby specs. According to them, to try to allocate space for a new instance of NilClass should raise a TypeError instead of returning nil.
> Allocate method on NilClass should raise TypeError

- core/src/main/ruby/jruby/kernel/jruby/process_manager.rb
this is a question.
Before this was merged https://github.com/jruby/jruby/pull/5316
shelling on windows was broken
```
irb(main):001:0> `dir`
ArgumentError: wrong number of arguments (1 for 0)
` at uri:classloader:/jruby/kernel/jruby/process_manager.rb:28
` at uri:classloader:/jruby/kernel/jruby/process_manager.rb:50
```
now it works fine, but according to the javadoc ProcessBuilder#environment don't accept an argument
https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#environment()
am I missing something?
```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```
> ProcessBuilder#environment

- core/src/main/ruby/jruby/kernel/enumerable.rb
- spec/tags/ruby/core/enumerable/slice_when_tags.txt
In order to iterate correctly over Enumerable elements, #each_entry method should be used, because that method will convert multiple values from yield to an array, if required.
This is a fix similar to https://github.com/jruby/jruby/pull/5302.
> Fix tagged as failed spec for Enumerable#slice_when

- core/pom.rb
- core/pom.xml
jnr-ffi depends on jnr-x86asm and jnr-a64asm, so the x86
dependency is redundant.
jnr-ffi, jnr-enxio, jnr-unixsocket are updated to latest releases.
> Update JNR projects.

- core/src/main/java/org/jruby/RubyArray.java
```
require 'benchmark/ips'
Benchmark.ips do |x|
x.report('&', "[] & Array.new(200)")
end
```
before
```
&    177.163k (± 5.2%) i/s -    886.145k in   5.015640s
```
after
```
&      2.941M (± 5.4%) i/s -     14.643M in   4.996883s
```
> return early if one of the arrays is empty

- core/src/main/java/org/jruby/ext/zlib/RubyZlib.java
- spec/ruby/library/zlib/crc32_spec.rb
As discussed in https://github.com/jruby/jruby/issues/5290#issuecomment-427845262, The while loop in gf2_matrix_times should terminate after 32 iterations. That means the value of 'start' should be 0 after (start>>32). Trimming the value beyond 32 bits ensures that behavior.
FIX #5290
> [Zlib][CRC32] Trim 'start' value to 32-bit for negative long integers

- core/pom.rb
- core/pom.xml
- pom.rb
- pom.xml
... rest of asm jars seems to be used, for now
@enebo do you need asm-analysis.jar around?
> bump asm version + remove asm-analysis

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/ext/timeout/Timeout.java
- core/src/main/java/org/jruby/runtime/JavaSites.java
- lib/ruby/stdlib/timeout.rb
- test/jruby/test_timeout.rb
Fixes #3834.
* Use Timeout::Error instead of leaky anonymous exception.
* Move executor to instance data from static.
* Clean up redundant, outdated code.
* Move sharable pieces back into timeout.rb.
* Eliminate builtin and load ext from timeout.rb.
> Realign timeout with MRI.

- core/src/main/java/org/jruby/RubyArray.java
maybe I am missing smt but from reviewing parts doesn't bring much value
from the commit desc that introduced it ... seems to be due nil fills after assignment, makes no sense?
`RubyArray` isn't thread-safe to start with and this might help improper concurrent usage
... but only `values` has been volatile and not `begin` or `length` fields - so detection only works with internal array resizing and even than the other thread's view might not be correct, due cached `begin` field
> revert volatile mod from values[] RubyArray store?

- bin/jruby.bash
- bin/jruby.sh
When --jdb flag is passed to jruby, it's using an incorrect value for -sourcepath flag. This makes the debugger unable to show the source code of the class being debugged.
Before:
```
shirley:jruby miguel$ ./bin/jruby --jdb -e '[0][1..50] = 2'
Initializing jdb ...
> stop in org.jruby.RubyRange.begLen0
Deferring breakpoint org.jruby.RubyRange.begLen0.
It will be set after the class is loaded.
> run
run org.jruby.Main -e "[0][1..50] = 2"
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
>
VM Started: Set deferred breakpoint org.jruby.RubyRange.begLen0
Breakpoint hit: "thread=main", org.jruby.RubyRange.begLen0(), line=188 bci=0
main[1] list
Source file not found: RubyRange.java
main[1] exit
shirley:jruby miguel$ 
```
After:
```
shirley:jruby miguel$ ./bin/jruby --jdb …
```
> Use right -sourcepath when jruby is invoked via jdb

- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
reference
https://bugs.ruby-lang.org/issues/15118
see also
https://github.com/jruby/jruby/blob/ae777f0039d1d7f698bb171109a4ae3ac8582b1e/core/src/main/java/org/jruby/ir/IRBuilder.java#L1083
> WIP: respect frozen_string_literal

- core/src/main/java/org/jruby/ir/instructions/PushMethodFrameInstr.java
- core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
- core/src/main/java/org/jruby/ir/passes/AddCallProtocolInstructions.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
Toplevel scopes were only getting defaulted to private visibility
for the startup interpreter, which does not ever use in-IR call
protocol. When the toplevel script body is first optimized to
fullint or compiled to bytecode, call protocol is installed with
no external preamble code to set visibility to private, so the
visibility was defaulting back to public as in non-script scopes.
This change adds visibility to the frame push instruction, so top-
level scripts will use private in their frame push.
This fixes regression in test:jruby:aot test_timeout.rb toplevel
timeout test, which relied on the non-self call to timeout to see
the toplevel private method and trigger method_missing. This began
to fail with my timeout update because the method is now defined
in Ruby code rather than …
> Fix toplevel method visibility in jit/fullint script scopes.

- core/src/main/java/org/jruby/util/Numeric.java
this patch uses a variant of https://en.wikipedia.org/wiki/Binary_GCD_algorithm
https://github.com/ruby/ruby/pull/1596
master
```
Time#subsec      5.377M (±17.9%) i/s -     24.868M in   4.991341s
Time#-     17.696M (± 9.1%) i/s -     86.842M in   4.982315s
Time#round      5.162M (±10.1%) i/s -     25.510M in   4.997497s
Time#to_f     15.985M (± 7.8%) i/s -     78.822M in   4.990285s
Time#to_r      5.143M (± 8.4%) i/s -     25.479M in   4.993259s
Rational#+      8.195M (± 4.6%) i/s -     40.802M in   4.995908s
Rational#-      7.797M (± 5.2%) i/s -     38.806M in   4.999148s
Rational#*     10.606M (± 4.5%) i/s -     52.840M in   4.994995s
```
patch
```
Time#subsec      6.169M (±18.9%) i/s -     27.650M in   4.983793s
Time#-     18.941M (± 9.2%) i/s -     92.775M in   4.980521s
Time#round …
```
> improve gcd performance

- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyInteger.java
```ruby
require 'benchmark/ips'
def sqrt
1000.times do |num|
Integer.sqrt(num)
end
end
Benchmark.ips do |x|
x.report('sqrt') { sqrt }
end
```
master
```
sqrt      9.153k (±20.4%) i/s -     42.000k in   5.027226s
```
patch
```
sqrt     16.244k (±14.2%) i/s -     79.422k in   5.063626s
```
> enable Integer#sqrt

- bin/jruby.bash
This PR will track a few small commits to improve how we start up on Java 9+, with a specific eye for running well on Java 11.
> Improvements for modules on Java 9+

- core/src/main/java/org/jruby/RubyStruct.java
Struct#to_a and Struct#values should return an Array which is independent to the Struct. So subsequent modifications to the struct should not be visible in a previously retrieved values array. In MRI a new Array is created at each call to #values or #to_a.
Fixes https://github.com/jruby/jruby/issues/5372.
> Struct#values should return an array which is independent of the struct

- core/src/main/java/org/jruby/util/Dir.java
This is a workaround for issues found in #5333. I discovered while
researching a fix for that bug that our `glob_helper` appears to
be missing "else" logic for the segment processing that handles
magic characters and unescaping. Put simply, if there's no magic
in the segment it leaves it entirely unprocessed, allowing its
contents to just get rolled into the next segment loop (which may
or may not also have magic). However this leaves escapes in place.
This "fix" basically just omits the magic check for each segment
and allows full processing.
> Always use full logic for processing glob segments.

- core/src/main/java/org/jruby/RubyFile.java
Fixes #5318.
Note that this no longer does the explicit file store check,
because that failed in an unrelated way when running under a
FreeBSD jail. Instead this now relies on the Files subsystem of
JDK to percolate out the original error message, which we should
detect properly and turn into EXDEV.
> Use JDK atomic move to more closely emulate POSIX rename.

- BUILDING.md
- core/pom.rb
- core/src/main/java/org/jruby/util/RegularFileResource.java
- core/src/test/java/org/jruby/runtime/io/RubyIOTest.java
- core/src/test/resources/org/jruby/runtime/io/read_file.rb
This PR addresses https://github.com/jruby/jruby/issues/5287.
Without it, unit test gets stuck on the select call. See [Thread dump](https://gist.github.com/alexis779/b2eae94b3a90f9758e58499dbfeebf2f).
It needs https://github.com/jnr/jnr-enxio/pull/29 feature to avoid `KQSelector` and fallback on `EpollSelector`. We pass `isFile=true` in `NativeDeviceChannel` constructor in the case of a file. This avoids getting stuck on macosx when calling kevent system call at the end of the file.
kqueue does not support EOF. There is no easy way to skip select call to avoid blocking for ever.
We still want to use KQSelector for sockets. Just not vnodes.
> [#5287] Use epoll selector for file IO on macosx

- lib/pom.rb
- lib/pom.xml
This reverts commit e1d02a082998bed5b5167f0950dc3ef4281ad3a2, reversing
changes made to b43b9d86088e842ccb447e3068df425c3ff32590.
This reverts #5225.
The updated jruby-readline appears to be the cause of #5387 so I think we'll need to revert this for 9.2.1 and figure out what went wrong.
> Revert updated jruby-readline

- pom.rb
- pom.xml
This pulls in the latest jffi, which has a new 32-bit ARM binary
rebuilt for hard-float EABI that appears to be typical on modern
ARM Linux distributions.
Fixes #5362.
Fixes #5192.
This will likely fail in travis until the jffi binary has propagated, so the build will need to be restarted.
> Update jffi to 1.2.18 for refreshed 32-bit ARM support.

- core/src/main/java/org/jruby/RubyHash.java
- spec/ruby/core/hash/shift_spec.rb
This fixes #5392.
@ChrisBr Please review this fix! I was not sure if this is the best way to proceed. Other methods that mutate the Hash usually call checkResize, which avoids the issue. Since we're shifting it should not need to grow, so I added the additional length check instead.
> Fix Hash#shift when at capacity

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/internal/runtime/ThreadService.java
This change clears the following on JRuby runtime teardown:
* The thread-local context reference in ThreadService
(dereferenced entirely)
* The mainContext reference in ThreadService
* The mapping from native threads to RubyThread instances.
This should clear all JRuby-specific runtime data attached to
both Ruby and adopted Java threads.
Fixes #3313.
Supersedes #3316.
> Clear references to threads and thread contexts on teardown.

- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- spec/ruby/language/method_spec.rb
Keyword argument processing currently mutates the incoming Hash,
calling delete as arguments are distributed to local variables.
This allows easy support for the keyword rest argument, since it
just gets whatever's left, but it forces us to make this defensive
copy. We also can skip some duping if the keyword arguments are
all literal and not just contained in an opaque hash. Of course
we really just need to wire up straight-through keyword args
dispatch.
Fixes #5267.
> Do a fast dup of args when all symbols, due to kwarg processing.

- core/src/main/java/org/jruby/MetaClass.java
- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- core/src/main/java/org/jruby/runtime/profile/builtin/ProfilePrinter.java
- test/jruby/test_class.rb
JRuby seem to never have `Foo.singleton_class.singleton_class` working as expected
... mostly following super-class hierarchy with singleton classes
this gets the class hierarchy working, not sure what is left to be done for module's singleton
left the "super meta class" logic as it was for now
fixes GH-287 ... an old timer :)
> [fix] singleton meta class

- core/src/main/java/org/jruby/RubyTime.java
Fixes #5400.
As far as I could tell, in MRI they have a tri-state flag on RTIME:
* gmt = 0 means non-UTC format
* gmt = 1 means UTC format
* gmt = 2 means relative offset, non-UTC format
We have a single `isTzRelative` flag that, when combined with the actual zone of the DateTime object, can be used to emulate these three states.
> Only use the UTC formatter if time was not specified as relative.

- core/src/main/java/org/jruby/util/Pack.java
- spec/tags/ruby/core/array/pack/m_tags.txt
- spec/tags/ruby/core/array/pack/u_tags.txt
https://www.ruby-lang.org/en/news/2018/10/17/not-propagated-taint-flag-in-some-formats-of-pack-cve-2018-16396/
```
Array#pack('M')
Array#pack('m')
Array#pack('u')
```
returns a tainted string when a pack argument is tainted
```
Array#pack('p')
Array#pack('P')
```
not implemented on jruby
> taint flag

- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyNil.java
- core/src/main/java/org/jruby/ext/pathname/RubyPathname.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java
- core/src/main/java/org/jruby/runtime/Helpers.java
While verifying JRuby 9.2.1, @enebo discovered that certain
concurrent uses of a simple Rails app were triggering intermittent
errors, and forcing the JIT to run very quickly produced NPEs
under concurrent load. In 6b2fa457 @enebo was able to fix this
by adding a null check, but we could not explain how a null could
appear at that point in the code unless the hash had been
corrupted, perhaps across threads.
Additional testing with a number of contrived scripts seems to
show that the new open-addressing hash (plus its linear mode) is
more fragile under concurrency than the old linked buckets
implementation. This is in a way, by design: the new
implementation reduces indirection and allocation by packing
keys and values into a contiguous area of memory, opening up
potential for more races …
> Temporarily revert open-addressing Hash for concurrency reasons.

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
This implementation supplied 0 for `buckets` which causes the older RubyHash impl to crash when resizing. I believe what was intended was to use a smallest-possible Hash and slowly fill it, so I modified the logic to use the small hash paths.
> Bucket size of zero is not valid. For bucketless, use small.

- bin/jruby.bash
These packages are reflected against so heavily and for so many
low-level Ruby compatibility features that we're opening them up
for now. This was forced because we load some extensions through
a URLClassLoader, and it appears that URLClassLoader-ed libraries
get stricter treatment when it comes to illegal accesess.
The following error resulted from Puma without the java.io opens:
```
=> Booting Puma
=> Rails 5.2.1 application starting in development
=> Run `rails server -h` for more startup options
Exiting
LoadError: load error: puma/java_io_buffer -- java.lang.reflect.InaccessibleObjectException: Unable to make field protected byte[] java.io.ByteArrayOutputStream.buf accessible: module java.base does not "opens java.io" to module org.jruby.dist
require at org/jruby/RubyKernel.java:976 …
```
> Add opens for java.io and java.nio.channels to improve compat.

- lib/pom.rb
- lib/pom.xml
More or less all default and installed gems will completely include themselves
into stdlib artifact which in turn will make them available when making the
jruby-dist package.
What makes me uncertain that this is right is the previous code went through
some pains to not include everything.  I am guessing there is something we don't
want and I am now including it?
Second part of this was unneeded but I removed the ImportedGem class and just
had both gem types use a nested array of arrays leveraging block destructuring.
> An attempt at fixing #5420.

- .travis.yml
- tool/sequel-travis.sh
This PR adds a job based on the CI runs for @jeremyevans Sequel library. I've basically just duplicated his .travis.yml in a shell script that's run along with our other jobs.
> Add a CI job for the "sequel" gem

- core/src/main/java/org/jruby/RubyFloat.java
- spec/tags/ruby/core/float/constants_tags.txt
https://ruby-doc.org/core-2.5.0/Float.html
The smallest positive normalized number in a double-precision floating point.
Usually defaults to 2.2250738585072014e-308.
If the platform supports denormalized numbers, there are numbers between zero and Float::MIN. 0.0.next_float returns the smallest positive floating point number including denormalized numbers.
```
public static final double MIN_VALUE = 0x0.0000000000001P-1022; // 4.9e-324
public static final double MIN_NORMAL = 0x1.0p-1022; // 2.2250738585072014E-308
```
> normalized Float::MIN

- core/src/main/java/org/jruby/util/Numeric.java
Long.numberOfTrailingZeros returns an integer
long result = 1 << int;
fixes
```
-9223372036854775808.gcd(0)
```
returns 1 but it should return 9223372036854775808
> fix overflow in #i_gcd

- core/src/main/java/org/jruby/RubyStruct.java
- spec/ruby/core/struct/new_spec.rb
This includes a fix and spec for initializing a non-kwarg Struct with a splatted Hash-containing array of arguments, as in this snippit that reproduces #5448:
```ruby
Struct.new(:args).new(*[{keyword: :arg}])
```
The Hash should not be interpreted to be keyword init of the Struct, since it is not a kwarg-initializable Struct. We simply weren't checking this flag on one path, and assuming a single Hash arg was always for kwarg init.
> Splatted kwarg struct init

- core/src/main/java/org/jruby/RubyStruct.java
- core/src/main/java/org/jruby/anno/MethodDescriptor.java
We have apparently not been binding multi-arity rest methods well
for some time; the logic to look for "hasVarargs" was not using
the correct class.getName() for an IRubyObject[], resulting in
any variable-arity-or-rest methods always getting routed to the
rest path, because the min/max logic breaks without hasVarargs.
This could regress easily without tests, but I'm not sure of the best way to test that all this generated code is working right.
This was discovered while investigating #5448, which weirdly was caused by this bug to go down a rest path, and then via JavaMethodN.call re-route to a specific-arity version that had a bug.
> Fix multi-arity method binding.

- test/mri/lib/test/unit/assertions.rb
This was added to MRI in ruby/ruby@2ac41230c4.
> Disable RubyGems for MRI subprocess tests to speed them up.

- core/src/main/java/org/jruby/ext/tempfile/Tempfile.java
Fixes #5456.
In #5456, @erikogan shows that his example code worked in 9.1.17.0, but I could find no changes to Tempfile during the past 9 months that would explain the regression.
> Tempfile.open should have arity 3, to allow IO options through.

- core/src/main/java/org/jruby/runtime/Helpers.java
Additional exception types added to the static-typed logic in our IOException-to-Errno detector.
Remnants of #5416 deemed too risky for last-minute.
> Improve errno detect

- test/mri/ruby/test_undef.rb
This probably should have been `#bar` on the instance of class `Undef2` all along, right?
But maybe I'm missing something and a test case needs adding maybe?
> Test for undef'ed method in class hierachy

- core/src/main/java/org/jruby/compiler/JITCompiler.java
- core/src/main/java/org/jruby/compiler/MethodCompiledJITTask.java
- core/src/main/java/org/jruby/compiler/MethodJITClassGenerator.java
- core/src/main/java/org/jruby/internal/runtime/AbstractIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java
- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/runtime/callsite/ProfilingCachingCallSite.java
Allows inliner to work on main scripts which are made with IRCompiledMethod.  I can see a bit of redundancy but I would prefer we address that with a later refactoring (plus inliner is still young enough we may decide we need more in JIT compilation infrastructure).
> Allows CompiledIRMethod to inline methods when it is the host scope.

- core/src/main/java/org/jruby/util/Numeric.java
- spec/ruby/core/integer/gcd_spec.rb
fixes
```
-9223372036854775808.gcd(-9223372036854775808)
```
should return 9223372036854775808 not -9223372036854775808
MRI uses FIXNUM_P macro instead of (x instanceof RubyFixnum), so -9223372036854775808 is properly delegated to a bignum logic
> fix an edge case in gcd calculation

- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubyStruct.java
- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/ext/stringio/StringIO.java
- core/src/main/java/org/jruby/ext/thread/Mutex.java
- core/src/main/java/org/jruby/runtime/ivars/VariableTableManager.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalCache.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalStream.java
- core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java
- spec/tags/ruby/core/marshal/dump_tags.txt
- spec/tags/ruby/core/marshal/load_tags.txt
This PR replaces #4576. I will re-port each fix as necessary.
> Revisit symbol hash and marshal fixes from #4576

- pom.rb
[WARNING] Some problems were encountered while building the effective model for org.jruby:jruby-core:jar:9.2.5.0-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.felix:maven-bundle-plugin @ org.jruby:jruby-parent:9.2.5.0-SNAPSHOT, /jruby/pom.xml, line 338, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jruby:jruby-parent:pom:9.2.5.0-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.felix:maven-bundle-plugin
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] …
> fix duplicate declaration

- core/src/main/java/org/jruby/RubyArray.java
Hi folks, do we have a branch to start to merge changes related to Ruby 2.6 features?
I was reviewing some new features and decided to take a shot with implementing new Array#union method.
The implementation is more or less based on what they did in MRI [1] and is passing all its related tests [2].
For more information, please see feature #14097 [3].
1. https://github.com/ruby/ruby/commit/744e816f55757df92caa49b4787cf06af6120a20
2. https://github.com/ruby/ruby/blob/v2_6_0_preview3/test/ruby/test_array.rb#L1931-L1967
3. https://bugs.ruby-lang.org/issues/14097
> Add Array#union

- core/src/main/java/org/jruby/RubyArray.java
Analogous to #5464.
I was reviewing some new features and decided to take a shot with implementing new Array#difference method.
The implementation is based on what they did in MRI [1] and is passing all its related tests [2].
For more information, please see feature #14097 [3].
1. https://github.com/ruby/ruby/commit/d65d5533ab117b46211917450293f9c602519375
2. https://github.com/ruby/ruby/blob/v2_6_0_preview3/test/ruby/test_array.rb#L279-L298
3. https://bugs.ruby-lang.org/issues/14097
> Add Array#difference

- core/src/main/java/org/jruby/RubyModule.java
- spec/ruby/core/module/name_spec.rb
This duplicates logic in `to_s` that dups the module name before
returning it, but also ensures that any cached module name is
frozen so it can't be modified in place.
Fixes #5480.
> Never return the internal module name as a mutable string.

- core/src/main/java/org/jruby/RubyModule.java
- test/jruby.index
- test/jruby/test_refinement_include.rb
Fixes `Module#refine` regression when using `Module#include` to inject functions.
Compare latest refinement [commit](https://github.com/jruby/jruby/commit/1839880a1eb3c05904bb6f5a8a327ae02e12d59b#diff-b0dc42ec523c3c3de1ac9ff40bc56852L880) with CRuby [rb_using_refinement](https://github.com/ruby/ruby/blob/trunk/eval.c#L1342-L1347).
`RubyModule#setSuperClass` call was dropped. We add it back again.
> [#5288] Overwrite parent class with module wrapper

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/ext/fiber/ThreadFiber.java
- core/src/main/java/org/jruby/internal/runtime/ThreadService.java
... here's an interesting find while trying to upgrade an app stuck on JRuby 1.7.4
the app uses celluloid's actor model and under load degraded considerably (~ 10x).
with celluloid all calls upon actors are executed in fibers, which are kind of heavy under JRuby,
the system ends up operating with ~3000 threads and interestingly thread registration (those are fiber backing threads) accounts for quite some delay as its synchronizing on `ThreadService`.
now, that locking shouldn't be needed since the backing map is already a synchronized collection.
... poked around history and there's no explicit reason for `registerNewThread` to lock on `ThreadService`
pretty much the only thing I could think of that might not work 'exactly' as before is listing threads (`getActiveRubyThreads()`) so I …
> less sync-ing with thread registration

- core/src/main/java/org/jruby/RubyException.java
- core/src/test/java/org/jruby/test/TestRubyException.java
... a regression since the exception hierarchy rewrite in **9.2**
spotted at: https://github.com/sparklemotion/nokogiri/issues/1818
for compat `rubyException.toJava(Object.class)` shall return self
> [fix] RubyException#toJava(Object) shouldn't return null

- core/src/main/java/org/jruby/RubyEncoding.java
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/embed/io/ReaderInputStream.java
- core/src/main/java/org/jruby/embed/io/WriterOutputStream.java
- core/src/main/java/org/jruby/ext/ffi/IOModule.java
- core/src/main/java/org/jruby/ext/ffi/Util.java
- core/src/main/java/org/jruby/ext/ffi/io/FileDescriptorByteChannel.java
- core/src/main/java/org/jruby/ext/socket/RubyUDPSocket.java
- core/src/main/java/org/jruby/ext/socket/RubyUNIXSocket.java
- core/src/main/java/org/jruby/ir/persistence/IRReaderStream.java
- core/src/main/java/org/jruby/ir/persistence/IRWriterStream.java
- core/src/main/java/org/jruby/util/Pack.java
- core/src/main/java/org/jruby/util/ShellLauncher.java
- core/src/main/java/org/jruby/util/StrptimeParser.java
- core/src/main/java/org/jruby/util/io/BufferHelper.java
- core/src/main/java/org/jruby/util/io/ChannelDescriptor.java
- core/src/main/java/org/jruby/util/io/ChannelStream.java
- core/src/main/java/org/jruby/util/io/NullChannel.java
- core/src/main/java/org/jruby/util/io/SelectBlob.java
- core/src/main/java/org/jruby/util/io/SelectExecutor.java
Fixes #5451.
This is basically the same as @ahorek patch in #5459 but I addressed my review comments.
> Fix known binary compat issues with new Java 9 overloads.

- tool/sequel-travis.sh
Previously it would fall back on the system "ruby" command if
JRuby failed to build, producing a false positive.
> Force the sequel build to pass every command.

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/NativeException.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/management/Runtime.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
- core/src/main/java/org/jruby/runtime/backtrace/BacktraceData.java
- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
This PR modifies our logic for building stack traces to be streamable and to use the Java 9 StackWalker API to reduce the load of partial walks.
This is a work in progress.
> Use Java 9 stack walking to reduce the cost of #caller and friends

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/ext/set/RubySet.java
- core/src/main/ruby/jruby/kernel/enumerator.rb
Hi folks,
This PR implements another Ruby 2.6 feature: Add a new #filter alias for #select.
For more information, please see feature #13784 [1].
I believe all the related tests (MRI and ruby/spec) are passing: [2], [3], [4], [5], [6], [7], [8], [9], [10], [11].
For reference, I included a link to the commit introducing the functionality in MRI. [12]
1. https://bugs.ruby-lang.org/issues/13784
2. https://github.com/ruby/ruby/blob/v2_6_0_rc1/spec/ruby/core/array/filter_spec.rb
3. https://github.com/ruby/ruby/blob/v2_6_0_rc1/spec/ruby/core/enumerable/filter_spec.rb
4. https://github.com/ruby/ruby/blob/v2_6_0_rc1/spec/ruby/core/hash/filter_spec.rb
5. https://github.com/ruby/ruby/blob/v2_6_0_rc1/spec/ruby/library/set/filter_spec.rb
6. …
> Ruby 2.6: Add a new #filter alias for #select

- core/src/main/java/org/jruby/ir/passes/AddCallProtocolInstructions.java
This logic was used to ensure that any heap-scoped variable loads
happened before the "pop" logic for those scopes. However another
type of variable, frame-locals like $~ and $_, did not get the
same treatment. This patch ensures that any frame or binding
requirement triggers the return value copy fixup.
Fixes #5503.
> Also fix up return values when frame is present, for backref.

- core/src/main/java/org/jruby/RubyKernel.java
Hi folks,
This PR implements another Ruby 2.6 feature: Add a new #then alias to Kernel#yield_self.
For more information, please see feature #14594 [1].
All its related tests are passing [2].
For reference, I include a link to the commit introducing the functionality in MRI. [3]
1. https://bugs.ruby-lang.org/issues/14594
2. https://github.com/ruby/ruby/blob/v2_6_0_rc1/spec/ruby/core/kernel/yield_self_spec.rb#L5-L7
3. https://github.com/ruby/ruby/commit/d53ee008911b5c3b22cff1566a9ef7e7d4cbe183
> Ruby 2.6: Add a new #then alias to Kernel#yield_self

- core/src/main/java/org/jruby/MetaClass.java
- core/src/main/java/org/jruby/util/cli/Options.java
Singleton objects, usually created via `extend` or `def obj.meth`,
frequently waste CPU cycles and memory. It's also easy to
accidentally trigger an object to become a singleton. These
properties will make it easy to track all singleton classes
created by an application, along with an optional stack trace.
> Add log.singletons and .verbose to track singleton class creation.

- core/src/main/java/org/jruby/RubyInstanceConfig.java
fixes warnings
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
> add java 10, 11 opcodes

- core/src/main/java/org/jruby/ext/date/RubyDate.java
- spec/ruby/library/datetime/add_spec.rb
- spec/ruby/library/datetime/subtract_spec.rb
This patch fixes issue #5493 and adds the test case from the report as a new spec. It also fixes the existing DateTime add/subtract specs to actually use sub-millisecond differences like their descriptions say.
> Fix sub-millisecond datetime difference handling

- lib/ruby/stdlib/resolv.rb
- test/mri/resolv/test_dns.rb
this patch restores the original patch in https://github.com/jruby/jruby/pull/5074
it was merged, but reverted later https://github.com/jruby/jruby/issues/5479
I think we should fork it to avoid regression until https://bugs.ruby-lang.org/issues/15414 is resolved
> backport fd leak in resolv

- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalStream.java
- core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java
- spec/tags/ruby/core/marshal/dump_tags.txt
This PR is for #5523. In that issue, we found that the order a symbol and its encoding are being registered are correct, but when unmarshaling the symbol we register the encoding first. This led to the actual symbol content being treated as the encoding key, and the encoding value became the hash value associated to the original symbol. Then everything was off by one.
There's an issue here, though, in that the symbol is created and registered with our internal tables before its encoding is set correctly. This is also how MRI works, but they don't have issues for obvious reasons.
> Handle symbol dumping properly

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyGlobal.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyStruct.java
Hi folks,
This PR implements another Ruby 2.6 feature: #to_h method in Array, Enumerable, ENV, Hash and Struct classes now can map their elements to new keys and values to a given block.
For more information, please see feature #15143 [1].
I believe all the related tests (MRI and ruby/spec) are passing:i [2], [3], [4], [5], [6], [7], [8], [9], [10], [11].
For reference, I include a link to the commit introducing the functionality in MRI. [12]
1. https://bugs.ruby-lang.org/issues/15143
2. https://github.com/ruby/ruby/blob/v2_6_0_preview3/spec/ruby/core/array/to_h_spec.rb#L38-L41
3. https://github.com/ruby/ruby/blob/v2_6_0_preview3/spec/ruby/core/enumerable/to_h_spec.rb#L47-L53
4. https://github.com/ruby/ruby/blob/v2_6_0_preview3/spec/ruby/core/env/to_h_sp …
> Ruby 2.6: Add #to_h with block argument to Array, Enum, ENV, Hash and Struct

- core/src/main/java/org/jruby/util/io/PopenExecutor.java
- spec/ruby/core/process/spawn_spec.rb
`Process.spawn` is leaving orphaned processes when run inside
`Dir.chdir`:
```ruby
>> JRUBY_VERSION
=> "9.2.0.0"
>> Dir.chdir('/tmp') { Process.spawn('cat') }
=> 88255
```
```bash
$ ps xao pid,ppid,pgid,comm | grep -E ' (cat|sh)'
88255 88092 88092 sh
88256 88255 88092 cat
```
```ruby
>> Process.kill('TERM', 88255)
=> 1
```
```bash
$ ps xao pid,ppid,pgid,comm | grep -E ' (cat|sh)'
88256     1 88092 cat
```
I believe the issue is that adding the `cd` command (for chdir) causes a
second process to start. That process is grouped with the main java one
and doesn't die when its parent (`sh`) is killed.
This change creates a new process group for the `sh` command, which
causes the child process to die when the parent is killed.
I ran into this issue using Foreman to manage some JRuby processes.
> Create new pgroup when spawning process in chdir

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/RubySymbol.java
This uses the logic from #5523 to do the symbol validation within the ID logic. This allows it to raise for both existing symbols and new symbols, but new symbols are neither inserted into the table nor hard-referenced if an error is raised.
Fixes #5169.
> Validate ivar and const symbols from Java before adding to table.

- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/ext/ffi/Enums.java
- core/src/main/java/org/jruby/ext/set/RubySet.java
- core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java
Hi folks,
This PR implements another Ruby 2.6 feature: Make the number of arguments of Hash#merge variable.
For more information, please see feature #15111. [1]
All its related tests are passing. [2]
For reference, I include a link to the commit introducing the functionality in MRI. [3]
1. https://bugs.ruby-lang.org/issues/15111
2. https://github.com/ruby/ruby/blob/v2_6_0_rc2/test/ruby/test_hash.rb#L1162-L1191
3. https://github.com/ruby/ruby/commit/085f5ef95742a1da3fe7e66e9ad36e22afdb3e91
> Ruby 2.6: Hash#merge, Hash#merge! and Hash#update now accept multiple arguments

- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/ext/thread/Mutex.java
- core/src/main/java/org/jruby/util/io/OpenFile.java
- test/jruby/test_thread.rb
these changes are based on reviewing code for #5520 
than there's the actual "wild" fix: https://github.com/jruby/jruby/compare/mutex-fix?expand=1#diff-330867c3ee2ffcb2a20e80af7bf9b4b3R161 ... as this line doing synchronization locking seems to be causing the problem (see explanation at GH-5520)
not entirely sure - why it's happening, yet, maybe it relates to delivering interrupts on the main thread?
to reproduce, just run the test that is added here : 
```
TIMES=100_000 bin/jruby test/jruby/test_thread.rb --name=/latch/
```
.. changing the line back to a blocking collection should make the test fail e.g.
```diff
/** Stack of interrupt masks active for this thread */
-    private final List<RubyHash> interruptMaskStack = new CopyOnWriteArrayList<>();
+    private final List<RubyHash> …
```
> test, review & avoid (regressed) mutex behavior

- core/src/main/java/org/jruby/internal/runtime/methods/DynamicMethod.java
This parameter is set to 0 in
InvocationMethodFactory.createJavaMethodCtor and in the precompiled
INVOKER classes.  This works somehow on the JVM, but fails in the
DalvikVM.
Source for defining annotation parameters:
https://docs.oracle.com/javase/tutorial/java/annotations/declaring.html
> Define a proper annotation parameter for DynamicMethod.Version

- core/src/main/java/org/jruby/RubyRange.java
Hi folks,
This PR iterates on the changes introduced on #5540.
Summary:
- Make Range#min, max, include?, cover?, and === to support endless range
- Range#to_a now raises RangeError if it is endless
- Range#size now returns Float::INFINITY if it is endless
- Range#last and #max raises a RangeError if it is endless
For more information, please see feature #12912. [1]
For reference, I include links to similar commits in MRI: [2] [3] [4] [5].
Thanks for the feedback.
1. https://bugs.ruby-lang.org/issues/12912
2. https://github.com/ruby/ruby/commit/db1bdecb0d925b4668c0735158fce466333848f1
3. https://github.com/ruby/ruby/commit/c19ecf05b4c728951e1a1e223a40ae6883a4f8e0
4. https://github.com/ruby/ruby/commit/342619300ce26f9a134249002270c5d38d5993b3
5. …
> Ruby 2.6: Add support for endless range in more methods

- core/src/main/java/org/jruby/RubyRange.java
Hi folks,
This PR implements another Ruby 2.6 feature: Switch Range#=== to use cover? instead of include?
For more information, please see feature #14575. [1]
All its related tests are passing. [2] [3]
For reference, I include a link to the commit introducing the functionality in MRI. [4]
1. https://bugs.ruby-lang.org/issues/14575
2. https://github.com/ruby/ruby/blob/v2_6_0/test/ruby/test_range.rb#L505-L513
3. https://github.com/ruby/spec/blob/7fa95f66e355c2f122c5edd79e4c5e8f5e42c8f0/core/range/case_compare_spec.rb#L14-L19
4. https://github.com/ruby/ruby/commit/989e07c0f2fa664a54e52a475c2fcc145f06539d
> Ruby 2.6: Switch Range#=== to use cover? instead of include?

- core/src/main/java/org/jruby/RubyTime.java
- test/jruby/test_time.rb
> Fix time precision with fractional seconds as Rational

- core/src/main/java/org/jruby/util/Sprintf.java
- test/jruby.index
- test/jruby/test_sprintf.rb
resolves https://github.com/jruby/jruby/issues/5556
relates to introducing half even rounding (as identified in the issue): https://github.com/jruby/jruby/commit/bc2ba39ed88096f0d3557231e10bb22a84ee9508
... which need some special care to only apply if there's no tail left
credits to @lassiter for identifying the 'breaking' commit + putting up tests
> fix float formating regression (half-even rounding)

- core/src/main/java/org/jruby/ext/date/RubyDate.java
this should match the logic that was in place in 9.1.17.0
... expected to, finally and properly, resolve GH-5418 
(reverts previous attempt #5560 - which reverted d6a93ceff8ef9822c43cbd86f83cfbfa132222f2)
@enebo or @headius when merging please run `test:jruby` and `test:mri:core` on the branch
since CI is UTC - pretty confident it should be all good but just to double check.
> [fix] interpret today TZ-relative but use GJ chrono

- core/src/main/java/org/jruby/RubyTime.java
- spec/tags/ruby/core/time/zone_tags.txt
- test/jruby/test_time.rb
When a time is parsed with a TZ offset, t.zone returned an empty
string instead of nil like MRI. This in turn breaks ActiveSupport
Time.change() which then constructs new time values with the wrong
zone, ignoring the offset.
See jruby/activerecord-jdbc-adapter#980
> Time: fix localtime(), getlocal(), parse() for TZ offset

- core/src/main/java/org/jruby/RubyTime.java
When there is no timezone (empty string), return nil like MRI.
See also jruby/activerecord-jdbc-adapter#980
> Time: minimal fix for Rails Time.change() problem

- core/src/main/java/org/jruby/RubyDir.java
Hi folks,
This PR implements another Ruby 2.6 feature: Add Dir new instance methods #each_child and #children.
For more information, please see feature #13969. [1]
All its related tests are passing. [2]
For reference, I include a link to the commit introducing the functionality in MRI. [3]
1. https://bugs.ruby-lang.org/issues/13969
2. https://github.com/ruby/ruby/blob/v2_6_0_rc2/test/ruby/test_dir.rb#L268-L278
3. https://github.com/ruby/ruby/commit/6a3a7e9114c3ede47d15f0d2a73f392cfcdd1ea7
> Ruby 2.6: Add Dir instance methods #each_child and #children

- core/src/main/java/org/jruby/RubyBinding.java
Hi folks,
This PR implements another Ruby 2.6 feature: Add new method Binding#source_location.
For more information, please see feature #14230. [1]
For reference, I include a link to the commit introducing the functionality in MRI. [2]
1. https://bugs.ruby-lang.org/issues/14230
2. https://github.com/ruby/ruby/commit/571e48b74422f5caa8ff6d91faf7e1a6bf4d2dc1
> Ruby 2.6: Add new method Binding#source_location

- .travis.yml
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> [ci skip] Travis: Drop unused setting sudo: false

- core/src/main/java/org/jruby/IncludedModuleWrapper.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/util/ByteListHelper.java
- spec/tags/ruby/core/kernel/autoload_tags.txt
- spec/tags/ruby/core/module/autoload_tags.txt
- test/jruby/autoloaded.rb
- test/jruby/test_autoload.rb
The Kernel versions of `autoload` use the caller's frame to
determine the target module, where we were just detecting that
`autoload` was called against Kernel and then defining the
autoload on Object's singleton class.
test/jruby/test_autoload.rb has also been modified to match Ruby
2.5 behavior.
Fixes #5466.
> Autoload fixes

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubySignal.java
- core/src/main/java/org/jruby/util/NoFunctionalitySignalFacade.java
- core/src/main/java/org/jruby/util/SignalFacade.java
- core/src/main/java/org/jruby/util/SunSignalFacade.java
This avoids races due to the signal traps running on the JVM's
signal-handling thread while we run at_exit blocks on JRuby's
main thread.
Fixes #5437.
> Push signal traps and at_exit blocks to a common thread for exec.

- core/src/main/java/org/jruby/util/RegularFileResource.java
This is just a possible fix for the issue https://github.com/jruby/jruby/issues/5539.
> Ensure symlink path names passed to File.lstat are dereferenced when necessary

- core/src/main/java/org/jruby/IncludedModuleWrapper.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyModule.java
- spec/tags/ruby/core/kernel/autoload_tags.txt
- spec/tags/ruby/core/module/autoload_tags.txt
- test/jruby/autoloaded.rb
- test/jruby/test_autoload.rb
Reverts jruby/jruby#5489
This wasn't quite green, and failed a number of Kernel.autoload specs. Still needs work before merging.
> Revert "Autoload fixes"

- core/src/main/java/org/jruby/NativeException.java
- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyException.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/exceptions/RaiseException.java
- core/src/main/java/org/jruby/management/Runtime.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- core/src/main/java/org/jruby/runtime/JavaSites.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
- core/src/main/java/org/jruby/runtime/backtrace/BacktraceData.java
- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
* Request backtrace from exception object before raise, so that
pre-set backtrace or overridden #backtrace skip native trace
gathering.
* Eliminate some redundant or unused backtrace-gathering methods.
* Fix Kernel#warn uplevel logic to use partial traces (Java 9).
The fixes here allow two additional ways of blunting the cost of
raising an exception (by eliminating the native stack trace):
* Call Exception#set_backtrace before raising
* Use an Exception subtype that overrides Exception#backtrace
This improves the performance of these scenarios to be roughly
equivalent to the three-arg form of Kernel#raise.
Fixes #5605.
> Multiple adjustments to the Exception and raise logic.

- core/src/main/java/org/jruby/RubyGlobal.java
- core/src/main/java/org/jruby/util/cli/Options.java
noticed this while implementing the deprecation warning `Object#=~` for 2.6
the 3 state warning level was only using true/false states so it ended up printing warnings by default
JRuby should keep a `nil` (falsy) warning level by default, as Verbosity enum was intended to
no one complained about this on 9.1/9.2 so I am targeting 2.6 for now, its present on 9.2 as well
> [fix] properly calculate warning ($VERBOSE) default

- README.md
The build links on https://www.jruby.org/nightly redirect to https://support.cloudbees.com/hc/en-us/articles/360008971551-DEV-cloud-End-of-Life
I think it's better to remove the mention until we found an alternative solution.
> Remove nightly mention b/c DEV@cloud is EOL

- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/date/RubyDateTime.java
- test/jruby/test_date.rb
noticed a lot of (new) DateTime failures on 2.6 branch from CSV tests
turns out they were all related to sec arg rounding when a `Float` is given.
this patch will handle such cases ~ as MRI, its not matching C logic but is quite close.
> [fix] DateTime (civil) Float sec rounding

- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/date/RubyDateTime.java
- lib/ruby/stdlib/date.rb
- test/jruby/test_date.rb
`eql?` wasn't consistent with `==` (sub-millis rational needed normalization)
and also return from `===` wasn't matching MRI 2.5 ()
> [fix] make Date/DateTime equality consistent

- .travis.yml
With the loss of Cloudbees' devops tooling, we have no place to host nightly builds. Our simplest option is probably to just deploy snapshots on every successful build, so there's always a current JRuby snapshot available. This PR attempts to do that on Travis.
> Deploy snapshots after successful builds

- lib/pom.rb
- lib/pom.xml
CHANGELOG:
* update Bouncy-Castle to 1.61 (and handle supported BC compatibility)
* [fix] avoid NPE when CRL fails to parse (invalid str) (jruby/jruby#5619)
* hide (deprecated) Jopenssl constant 
* default OpenSSL.warn to warnings-enabled flag
* only un-restrict jce when its restricted
* OpenSSL::Cipher#update additional buffer argument (#170) (jruby/jruby#5242)
> update to jruby-openssl 0.10.2

- .travis.yml
- rakelib/commands.rake
- rakelib/rubyspec.rake
- spec/jruby.2.5.mspec
- spec/tags/ruby/core/encoding/default_external_tags.txt
- spec/tags/ruby/core/process/groups_tags.txt
- spec/tags/ruby/core/process/kill_tags.txt
- spec/tags/ruby/core/process/spawn_tags.txt
- spec/tags/ruby/core/process/status/exitstatus_tags.txt
- spec/tags/ruby/core/process/status/termsig_tags.txt
- spec/tags/ruby/language/predefined_tags.txt
- spec/tags/ruby/language/string_tags.txt
- spec/tags/ruby/library/net/http/http/get2_tags.txt
- spec/tags/ruby/library/net/http/http/get_tags.txt
- spec/tags/ruby/library/net/http/http/post2_tags.txt
- spec/tags/ruby/library/net/http/http/post_tags.txt
I'm moving any specs that require --debug to the "slow" suite and enabling that suite in CI. This should speed up the main "fast" suite and allow us to untag some specs that are broken by --debug.
> Isolate debug specs and run fast suite without --debug

- core/src/main/java/org/jruby/util/Pack.java
This mitigates a performance regression in GraalVM 0.13 where our
main unpack switch does not JIT for heavy use of unpack('m').
I had to do an additional method split in order to get things to
compile properly, so there's still a regression in GraalVM that
that needs to be addressed, but this at least gets a benchmark of
unpack('m') to run with similar performance to Hotspot.
> Outline case bodies from unpack logic.

- core/src/main/java/org/jruby/RubyFatal.java
This allows users to define their own Fatal class or module
without conflicting.
Fixes #5648.
> Remove the "Fatal" constant since it's hidden in MRI.

- .travis.yml
It was also running for PRs against the master and maintenance
branches.
> Only run deploy against actual pushes to our repo

- lib/ruby/stdlib/pty.rb
Fix as suggested in #5663. Provides same behavior as MRI now. 
Additionally, I ran this test: `jruby -r ./test/mri/lib/envutil.rb test/mri/test_pty.rb` and it passed. I wasn't sure if I needed to to anything else, or why https://github.com/jruby/jruby/blob/master/test/mri/excludes/TestPTY.rb suggests that it should fail.
This also doesn't address the opposite behavior of the nonblock flag as I noted in #5663 
Resolves #5663
> Use close_on_exec method instead of using fcntl calls for pty. Fixes #5663

- core/src/main/java/org/jruby/ext/bigdecimal/Multiplication.java
- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- test/jruby/test_big_decimal.rb
in certain cases its really slow e.g. a `x / 2` as discovered from https://github.com/jruby/jruby/issues/5650
```ruby
TIMES = (ENV['TIMES'] || 10_000_000).to_i
Benchmark.bmbm do |bm|
bm.report("/2 flt") {
rad_per_deg = Math::PI/180
loc1 = [46.3625, 15.114444]
loc2 = [46.055556, 14.508333]
val = ((loc2[1]-loc1[1]) * rad_per_deg)
TIMES.times { val / 2 }
}
bm.report("/2 dec") {
rad_per_deg = Math::PI/180
loc1 = [BigDecimal('46.3625'), BigDecimal('15.114444')]
loc2 = [BigDecimal('46.055556'), BigDecimal('14.508333')]
val = ((loc2[1]-loc1[1]) * rad_per_deg)
TIMES.times { val / 2 }
}
bm.report(" 1/1280") {
one = BigDecimal(1)
div = BigDecimal(1280)
TIMES.times { one / div }
}
end
```
here the `"/2 dec"` case is very slow - on JRuby **9.2.6** taking **400s**, while MRI takes **10s** : 
```
user …
```
> speedup BigDecimal division

- core/src/main/java/org/jruby/RubyEnumerator.java
- core/src/main/java/org/jruby/RubyGenerator.java
- core/src/main/java/org/jruby/ext/fiber/ThreadFiber.java
This patch sets the name of the threads used to drive fibers (or the similar Enumerator#next coroutines) in order to more easily audit and debug those threads. Relates to #5671 and fixes #5670.
> Provide better thread name for enumerator/fiber workers.

- core/src/main/java/org/jruby/ext/socket/RubyUDPSocket.java
- test/jruby/test_socket.rb
This is an attempt at fixing #5656.  I could not get the reporters server code to work on linux much less the other platforms referenced.  I believe it was something underneath this source line in original code:
```java
socket.multicastStateManager.getMulticastSocket().getChannel();
```
in Java source of getChannel() is literally 'return null'.  Based on changes over the years I suspect something changed in our implementation (like maybe we subclassed the channel?).  This version just uses the socket itself to receive and it blocks and also seems to work.  I also added the equivalent logic if somehow the socket is in a messed up state and tried to mark itself as non-blocking.
With that said I am not confident so I need some eyeballs...
> multicast receive broken everywhere

- README.md
You can also get jruby through Homebrew, https://formulae.brew.sh/formula/jruby
> Homebrew support

- core/src/main/java/org/jruby/Main.java
- core/src/main/java/org/jruby/RubyInstanceConfig.java
The -x option has been broken since 9e2d6dccb9e481fe25184202ee5a1762bb0fba28, as `parseShebangOptions` is no longer run, which is responsible for calling `setHasShebangLine`. As this is no longer done, `hasShebangLine` always returns false, even if there is a valid shebang.
The fix is to remove the check at this location and move it into the `findScript` function, which already searches for the ruby shebang.
Like mentioned in #4536, there seems to be a test for this, but it is not run during CI (at least I couldn't find it). Also parseShebangOptions seems to be dead code, which I can also remove if you want.
> Fix -x command line option to skip header

- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/ext/thread/ConditionVariable.java
- core/src/main/java/org/jruby/ext/thread/Mutex.java
- core/src/main/java/org/jruby/runtime/JavaSites.java
- spec/ruby/library/conditionvariable/wait_spec.rb
- spec/tags/ruby/core/mutex/lock_tags.txt
- spec/tags/ruby/core/mutex/synchronize_tags.txt
- test/mri.stdlib.index
- test/mri/excludes/TestConditionVariable.rb
> Return to interruptible lock acquisition in Mutex.

- spec/java_integration/packages/access_spec.rb
- test/DefaultPackageClass.java
reported as GH-5684 ... 
after the proper fix is in https://github.com/headius/backport9/pull/1 (backport9 gets updated)
> [test] public field accessiblity in default package

- bin/jruby.bash
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/util/ByteList.java
... also incorporates https://github.com/jruby/jruby/pull/5612
there's one assert left that is failing related to frame dup-ing (for procs)
> pass -ea to JVM and fix asserts for test targets

- spec/ruby/core/enumerator/lazy/select_spec.rb
@headius These are some simple tests for the lazy enumerator issue you pushed patches for recently.  Unfortunately I haven't been able to get the build environment set up correctly to run them myself and see why they're failing (I keep getting a (OpenSSL::X509::StoreError) setting default path failed: No password supplied for PKCS#12 KeyStore error when attempting `mvn -Pbootstrap`)
> Test that lazy enumerator doesn't pre-evaluate

- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/javasupport/ext/JavaLang.java
- core/src/main/java/org/jruby/javasupport/ext/JavaMath.java
- spec/java_integration/extensions/math_spec.rb
`to_d` is a convention used by Ruby's BigDecimal (from bigdecimal/util.rb)
also explicitly re-def inherited Java Number extensions
NOTE: a reminder that this won't have negative impact on loading, since Java extension are lazy
> [ji] support java.math.BigDecimal#to_d

- pom.rb
- pom.xml
- includes updated time-zone data (2018g)
- fixes DateTime.withTimeAtStartOfDay() when DST is at midnight (we've run into this!)
> update joda-time to latest 2.10.1

- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/util/io/OpenFile.java
- core/src/main/java/org/jruby/util/io/PopenExecutor.java
- core/src/main/java/org/jruby/util/io/PosixShim.java
In order to support concurrent reads and writes via the PosixShim,
we need to make errno be a thread-local. Some callers do their own
locking, releasing the lock before calling PosixShim, which causes
the errno updates and clears to step on other threads. It might be
possible to have those callers pass in their "unlock around" logic
as shown in #5706, but my first attempt did not work exactly right
and may introduces object overhead for stateful lambdas.
This implementation introduces thread-local read/write overhead to
all accessors of errno, but appears to be a clean way to keep this
field safe across concurrent IO operations.
Fixes #5706.
> Make the PosixShim errno field into a thread-local

- spec/jruby.mspec
- spec/tags/ruby/command_line/dash_encoding_tags.txt
- spec/tags/ruby/command_line/dash_external_encoding_tags.txt
- spec/tags/ruby/command_line/dash_internal_encoding_tags.txt
- spec/tags/ruby/command_line/dash_upper_i_tags.txt
- spec/tags/ruby/command_line/dash_upper_k_tags.txt
- spec/tags/ruby/command_line/dash_upper_s_tags.txt
- spec/tags/ruby/command_line/dash_upper_x_tags.txt
- spec/tags/ruby/command_line/dash_x_tags.txt
- spec/tags/ruby/command_line/feature_tags.txt
- spec/tags/ruby/command_line/frozen_strings_tags.txt
At some point we stopped including the command line specs in our CI runs. This PR restores them and tags off failures from recent spec updates.
Fixes #5705.
> Re-add command line specs to CI and tag new failures

- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/javasupport/ext/JavaTime.java
- spec/java_integration/types/coercion_spec.rb
should be good to go, a further extension would be to have a `to_date` for Java date types
> [ji] to_time conversion for Java DateTime types

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- spec/ruby/core/enumerable/shared/find.rb
MRI allows calling `find(nil)` and treats it as if no ifnone proc was
passed:
```
$ RBENV_VERSION=2.5.3 ruby -e 'puts [1,2,3].find(nil) { false }.inspect'
nil
$ RBENV_VERSION=jruby-9.2.7.0 ruby -e 'puts [1,2,3].find(nil) { false }.inspect'
NoMethodError: undefined method `call' for nil:NilClass
Did you mean?  caller
find at org/jruby/RubyEnumerable.java:656
<main> at -e:1
```
> Ignore nil for ifnone argument in Enumerable#find

- bin/jruby.bash
960efcb13aa8fe6d44098ebe83ceeb7f90160445 and 7c4bf9c5d47aaa3f17d49636ee2dcb0dcded81b7 changed the starter so that the `$CLASSPATH` is added to the module path when running on java9+.
Treating the CLASSPATH as modules will create automatic modules for all entries that are not actually modules. This can lead to several problems, e.g. the automatic module name is determined by the name of the jar or directory, which fails when one component is not a valid java identifier. Another issue is that several automatic modules might export the same package, which is not allowed and leads to an error.
While the first problems is relatively easy to fix, the second one requires large changes and might not even possible if you are using third-party libraries (e.g. we are using UNO, which [has problems …
> RFC: Do not add CLASSPATH to the module path

- core/src/main/java/org/jruby/java/invokers/StaticFieldGetter.java
- core/src/main/java/org/jruby/java/proxies/JavaProxy.java
- core/src/main/java/org/jruby/javasupport/binding/ClassInitializer.java
- core/src/main/java/org/jruby/javasupport/binding/FieldInstaller.java
- core/src/main/java/org/jruby/javasupport/binding/Initializer.java
- core/src/main/java/org/jruby/javasupport/binding/InterfaceInitializer.java
- core/src/main/java/org/jruby/javasupport/binding/StaticFieldGetterInstaller.java
This fixes #5730 and deprecates the behavior in question (accessing Java interface constant fields using Ruby accessor-style syntax).
We will remove this unintended behavior in 9.3.
> Fix and deprecate Java interface constant accessors

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/runtime/encoding/EncodingService.java
If the `file.encoding` property does not point at an encoding we recognize, such as "MS950" from #5707, we would hard error during JRuby initialization. This PR modifies that behavior to fall back on whatever we determine is the default external encoding.
This mitigates the error seen in #5707 but it may not match CRuby behavior exactly.
cc @enebo @lopex
> Use external when windows filesystem encoding is not found

- spec/jruby.mspec
* These features have been removed in https://github.com/ruby/spec/issues/667, so they don't do anything anymore.
> Remove enable_feature calls in jruby.mspec

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/parser/StaticScope.java
- core/src/main/java/org/jruby/runtime/scope/DynamicScopeGenerator.java
- core/src/main/java/org/jruby/util/ClassDefiningJRubyClassLoader.java
This PR pregenerates all DynamicScope subclasses we normally generate at runtime. The classes are included in the JRuby jar file so none of these classes are generated at runtime.
The logic here uses the max generated size as the max to pregenerate, resulting in no runtime generation happening. Currently, we generate up to 50-wide, so this PR currently generates 51 classes into JRuby.jar. Typical Ruby code will use only the smallest sizes, so this may be wasteful. The full set of 51 classes increases the size of my local jruby.jar by about 90k.
We may want to consider pregenerating fewer classes (if the size of the jar is important) as well as possibly generating fewer shapes overall (since there are diminishing returns to create e.g. a 50-wide scope class that's only used for one …
> Pre-generate DynamicScope shapes at build time

- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/ext/socket/RubyServerSocket.java
- core/src/main/java/org/jruby/ext/socket/RubySocket.java
- core/src/main/java/org/jruby/runtime/Helpers.java
This fixes issues from #5709 and #5754.
* Unify logic for turning Java exceptions into Errno based on their messages. This allows the proper errors to be raised for ETIMEDOUT and EHOSTUNREACH within socket logic.
* Check for closed channel when doing the final flush logic in IO. This allows channels closed elsewhere or sockets not completely established to be closed again without error.
* Remove custom Socket#close since it should now work with the modified IO#close finalization logic.
> Socket error fixes

- core/src/main/java/org/jruby/util/TypeConverter.java
- spec/ruby/core/kernel/fixtures/classes.rb
- spec/ruby/core/kernel/rand_spec.rb
- spec/ruby/core/random/fixtures/classes.rb
- spec/ruby/core/random/rand_spec.rb
JRuby is currently converting Time objects to floats when generating a
random value from a range:
```
$ RBENV_VERSION=jruby-9.2.7.0 ruby -e 'puts rand(Time.now..Time.now)'
1562034267.423605
```
MRI returns a Time object:
```
$ RBENV_VERSION=2.6.3 ruby -e 'puts rand(Time.now..Time.now)'
2019-07-01 19:27:25 -0700
```
I believe the `RubyNumeric` check I added is the same as what MRI uses
in `rb_check_to_float`: https://github.com/ruby/ruby/blob/0b858425e1e4f2de40dc0d8e5dd105a2fd93e478/object.c#L3769
> Support Time ranges in rand

- maven/jruby-jars/jruby-jars.gemspec
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement. This PR removes that property.
* [RubyForge was closed down in 2013][1].
* [rubygems/rubygems#2436 deprecated the `rubyforge_project` property][2].
[1]: https://twitter.com/evanphx/status/399552820380053505
[2]: rubygems/rubygems#2436
> jruby-jars.gemspec: Drop rubyforge_project

- core/src/main/java/org/jruby/RubyIO.java
Once https://github.com/jnr/jnr-enxio/pull/32 is merged, this change will enable support for IO::for_fd in windows. See other PR for test details. Tested on Win10 x64
> Add support for IO::for_fd on windows after jnr-enxio#32

- spec/tags/ruby/core/string/freeze_tags.txt
This was likely failing because we ran the full RubySpec suite
with --debug when run through rake. This turned on frozen string
debugging, which disabled the deduplication this spec tests.
Fixes #5070.
> Remove tag for "str".freeze idempotency test.

- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/util/JRubyFile.java
- core/src/main/java/org/jruby/util/RegularFileResource.java
- core/src/main/java/org/jruby/util/io/ChannelFD.java
- core/src/main/java/org/jruby/util/io/FilenoUtil.java
- core/src/main/java/org/jruby/util/io/OpenFile.java
These changes make JRuby be compatible with MRI's API's and behaviors on Windows serial ports.
Fileno is now real in most cases, but lazily generated in most cases to avoid sucking up 2x the number of file resources.
I put the WinC interface in FilenoUtils arbitrarily, I wasn't sure the best place to put it
> MRI compatibility with IO::sysopen for serial ports on windows

- core/src/main/java/org/jruby/specialized/RubyObjectSpecializer.java
- core/src/main/java/org/jruby/util/cli/Options.java
This partially addresses #4643.
One of the main features of the old "reify.classes" feature was that all Object subclasses would reify as their actual names. This is needed for JVM tooling to separate different types of Ruby object since normally they'll all appear to be RubyObject or one of the specialized subclasses like RubyObject1.
However the other features of reify.classes are difficult to reconcile with reified variables from reify.variables, due to the complexity of mapping a Ruby class hierarchy into a Java class hierarchy at the same time we are reifying variables into fields.
This patch goes partway to restore the actual names by forcing reify.variables to use the actual Ruby class name without attempting to match the class hierarchy or generate the other Java methods from …
> Allow generating reified Ruby classes with actual name.

- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyEnumerator.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyYielder.java
- core/src/main/java/org/jruby/runtime/CallBlock.java
- core/src/main/java/org/jruby/runtime/JavaInternalBlockBody.java
- test/jruby/test_enumerator.rb
we can than remove the hack from https://github.com/jruby/jruby/pull/2458
... and get some reported (Enumerator) behaviour to work properly, namely : 
- fixes #5044
- #4108 seems working, except `Enumerator.new {|y| y.yield([1])}.lazy.map {|e| e}.to_a`
> [fix] Enumerable#first block signature (matches MRI)

- .mvn/wrapper/maven-wrapper.properties
- azure-pipelines.yml
Attempting to get Azure Pipelines working again by forcing a slightly older Maven version.
It seems that https://issues.apache.org/jira/browse/MNG-6644 is causing the failures.
> Tweak Azure to use mvnw and Maven 3.6.0.

- core/src/main/java/org/jruby/javasupport/JavaUtil.java
- spec/java_integration/interfaces/implementation_spec.rb
By holding a reference to the proc, we anchor the proc's binding to the singleton class. When methods from the singleton class are cached elsewhere, such as for Java interface proxies (see GH-4968) we end up keeping the proc's binding alive longer than we'd like.
This patch detaches the proc object from the singleton, instead pointing it at the Proc class. The side effects from this include(at least) that any new singleton methods defined on that proc's singleton class will dispatch to hook methods (like singleton_method_defined) on Proc, rather than on the proc object. It's unknown whether this would affect any existing code.
> Dereference proc from interface impl singleton

- core/src/main/java/org/jruby/ext/ffi/AutoPointer.java
- core/src/main/java/org/jruby/ext/ffi/jffi/JITRuntime.java
- core/src/main/java/org/jruby/ext/ffi/jffi/NativeCallbackFactory.java
- core/src/main/java/org/jruby/runtime/callsite/BimorphicCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/BitAndCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/BitOrCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/CachingCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/CmpCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/DivCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/EqCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/GeCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/GtCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/LeCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/LtCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/MinusCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/ModCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/MulCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/PlusCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/RespondToCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/ShiftLeftCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/ShiftRightCallSite.java
- core/src/main/java/org/jruby/runtime/callsite/XorCallSite.java
restores interpreter 'fast' Fixnum/Float operations performance, which degraded after doing the `isBuiltin` checks (#4736)
there's a bit of refactoring needed for the CachingCallSite API used
we're adding a `CacheEntry setCache(CacheEntry entry, IRubyObject self)`
and checks such as `isBuiltin(RubyClass)` change to -> `isBuitlin(IRubyObject self)`
... this is the way JRuby intends to use these APIs anyway, so no harm done there
the gist of better performance is adding logic in custom sites when `setCache` happens,
do the builtin and target check there so that on the hot-path, taking the direct specific (Fixnum/Float) branch becomes 2 `instanceof` checks (edit: plus the obvious type "token" check)
> fix custom call-site performance regression

- bench/core/array/unique_bench.rb
- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyProcess.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java
- core/src/main/java/org/jruby/runtime/CallBlock.java
- core/src/main/java/org/jruby/runtime/JavaInternalBlockBody.java
- core/src/main/java/org/jruby/util/SunSignalFacade.java
- core/src/main/ruby/jruby/kernel/enumerable.rb
noticed a lot of unnecessary single element array wrapping at Enumerable's impls
... this could be aided with a simple override on the (native) `BlockCallback`
the most interesting piece is doing less work on `Array#uniq` (and also `Enumerable#uniq`)
also the `Enumerable` is still faster to have on the native end, numbers :
```
kares@clevo:~/workspace/oss/jruby$ ruby bench/core/array/unique_bench.rb
Rehearsal --------------------------------------------------------------------------------
Array#uniq (size: 8) [5000000x]                2.207314   0.000000   2.207314 (  2.207925)
Array#uniq (size: 32) [5000000x]               5.405314   0.000000   5.405314 (  5.406322)
Array#uniq(&block) (size: 8) [5000000x]        3.594613   0.000000   3.594613 (  3.595398)
Enumerable#uniq (size: 8) …
```
> aligned (and faster) uniq impls + less wrapping

- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/javasupport/JavaClass.java
This should fix the issue reported as a comment in https://github.com/ruboto/JRuby9K_POC/issues/7.
The issue here appears to be that non-existent inner classes are not handled properly; the resulting null or nil values fail to cast to expected types and the superclass const_missing fallback never triggers.
The change I have here uses a different path for acquiring a reference to the proxy class, which then allows the fallback to fire properly.
The original change was made by @kares in #3333 but it appears the test cases added did not test the case where there is no inner class for the constant.
> Fail gracefully when inner class const_missing finds nothing

- bin/jruby.bash
This is a work-in-progress to find additional settings and tweaks we can associate with the `--dev` flag to speed things up at boot for developer environments.
> Further improvements to dev mode

- bin/jruby.bash
The bash script sometimes returns an incorrect path for `JRUBY_HOME`. I came up with a bunch of cases where it would return the wrong directory, in no particular order:
1. a directory in PATH is a symlink
2. a directory in PATH is in a symlink
3. the executable is a symlink in PATH
4. the executable is in a directory that is a symlink
5. the executable is a symlink that points to an executable in a directory that is a symlink
6. the executable is being read from a pipe
Simply replacing `$0` with `$BASH_SOURCE` fixes case 3. Obviously this is bash-specific, so this can't be ported to the sh script.
Case 4 are solved by using readlink on the executable until it isn't a symlink. The script already did this, so I made some changes to solve other issues.
Cases 1, 2, and 5 are solved by running …
> Consistently resolve path of jruby.bash

- core/src/main/java/org/jruby/RubyEncoding.java
- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/ast/ListNode.java
- core/src/main/java/org/jruby/ext/ripper/HeredocTerm.java
- core/src/main/java/org/jruby/ext/ripper/StringTerm.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/Bootstrap.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter7.java
- core/src/main/java/org/jruby/lexer/yacc/HeredocTerm.java
- core/src/main/java/org/jruby/lexer/yacc/StringTerm.java
- core/src/main/java/org/jruby/util/ByteList.java
- core/src/main/java/org/jruby/util/TypeConverter.java
This is a set of memory/alloc-reducing experiments that can be merged or cherry-picked as appropriate.
> Tweaks to reduce memory use of short commands

- core/src/main/java/org/jruby/RubyInstanceConfig.java
- core/src/main/java/org/jruby/java/invokers/FieldMethodOne.java
- core/src/main/java/org/jruby/java/invokers/FieldMethodZero.java
- core/src/main/java/org/jruby/java/invokers/RubyToJavaInvoker.java
- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/javasupport/JavaMethod.java
- core/src/main/java/org/jruby/javasupport/JavaUtil.java
- core/src/main/java/org/jruby/javasupport/binding/ConstructorInvokerInstaller.java
- core/src/main/java/org/jruby/javasupport/binding/FieldInstaller.java
- core/src/main/java/org/jruby/javasupport/binding/Initializer.java
- core/src/main/java/org/jruby/javasupport/ext/JavaUtil.java
- core/src/main/java/org/jruby/management/BeanManagerImpl.java
- core/src/main/java/org/jruby/runtime/encoding/EncodingService.java
- core/src/main/java/org/jruby/util/cli/Options.java
- core/src/main/java/org/jruby/util/io/ChannelHelper.java
- core/src/main/java/org/jruby/util/io/FilenoUtil.java
The logic previously was depending on the ji.setAccessible
property, which by default would simply refuse to set accessible
*at all* when the Java version was >= "1.9" (also showing this
logic was introduced very early in the Java 9 development cycle.)
That default is removed here, along with a the CAN_SET_ACCESSIBLE
static field in RubyInstanceConfig deprecated and replaced with
the original meaning of this property, simply whether to attempt
setAccessible.
The direct calls to setAccessible have been replaced by the
trySetAccessible in backport9 library that checks if the target
member's module is open to JRuby, allowing users to opt-in to that
reflective access if their application needs it. Previously these
cases still skipped setAccessible just due to being on Java 9+.
Most of the …
> Move all JI setAccessible to trySetAccessible.

- core/src/main/java/org/jruby/java/proxies/ArrayJavaProxy.java
- core/src/main/java/org/jruby/java/util/ArrayUtils.java
- spec/java_integration/types/array_spec.rb
- test/jruby/test_higher_javasupport.rb
- `j_ary = [ 1 ].to_java; j_ary[2]` shall raise `IndexError` (instead of `ArgumentError`)
- handle edge cases e.g. `[ "a", "b", "c" ].to_java[-10..2]` similar to a Ruby `Array` (`nil`)
the first one might be considered a bug as well as a breaking change -> maybe target 9.3?
> [ji] align Java array (with post 1.8 conventions)

- core/src/main/java/org/jruby/RubyKernel.java
In order for users to be able to test if the thread's sleep loop
was interrupted, we need to ensure the interrupt bit is set after
an interrupted loop, even if the loop itself ignores the
interrupt.
See #4206.
> Propagate interrupt after interrupted sleep loop.

- core/src/main/java/org/jruby/RubyProcess.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- core/src/main/java/org/jruby/util/cli/Options.java
This addresses #1050 in the same way CRuby implements this. In
CRuby, the wait functions are called directly, and the
`pthread_kill` function is used to force the call to be
interrupted. It turns out the JVM also uses `pthread_kill` to
interrupt blocking native calls, so we use the same binding they
do.
Note that this will only be used on non-Windows, but the JDK's
binding of `NativeThread.signal` might already be stubbed out
there.
> Wrap Process.wait* calls with pthread_kill logic.

- core/src/main/java/org/jruby/ext/securerandom/RubySecureRandom.java
similar problem as https://github.com/jruby/jruby/issues/5773
in mri https://github.com/ruby/ruby/blob/master/random.c#L1568
```
require 'securerandom'
SecureRandom.rand
Traceback (most recent call last):
6: from /home/ahorek/.rvm/rubies/jruby-head/bin/irb:13:in `<main>'
5: from org/jruby/RubyKernel.java:1199:in `catch'
4: from org/jruby/RubyKernel.java:1199:in `catch'
3: from org/jruby/RubyKernel.java:1430:in `loop'
2: from org/jruby/RubyKernel.java:1067:in `eval'
1: from (irb):4:in `evaluate'
NoMethodError (private method `rand' called for SecureRandom:Module)
[1,2,3].shuffle(random: SecureRandom)
Traceback (most recent call last):
8: from /home/ahorek/.rvm/rubies/jruby-head/bin/irb:13:in `<main>'
7: from org/jruby/RubyKernel.java:1199:in `catch'
6: from …
```
> make SecureRandom.rand public

- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
- core/src/main/java/org/jruby/util/func/ObjectIntIntFunction.java
This is faster than using the Java 9+ stack walker API to generate
a full trace and resolves at least part of GH-5857.
> Use Java 8 stack walker when full trace is requested.

- core/src/main/java/org/jruby/RubyInstanceConfig.java
- core/src/main/java/org/jruby/compiler/BlockJITTask.java
- core/src/main/java/org/jruby/compiler/FullBuildTask.java
- core/src/main/java/org/jruby/compiler/JITCompiler.java
- core/src/main/java/org/jruby/compiler/MethodCompiledJITTask.java
- core/src/main/java/org/jruby/compiler/MethodJITTask.java
- core/src/main/java/org/jruby/internal/runtime/AbstractIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/management/Config.java
- core/src/main/java/org/jruby/management/ConfigMBean.java
- core/src/main/java/org/jruby/runtime/InterpretedIRBlockBody.java
- core/src/main/java/org/jruby/runtime/MixedModeIRBlockBody.java
- core/src/main/java/org/jruby/util/cli/Options.java
- core/src/main/resources/org/jruby/runtime/Constants.java
- core/src/test/java/org/jruby/embed/ScriptingContainerTest.java
... after some time esp. for big (Rails) apps that seemingly always execute some 'new-hot' methods
JIT parts also seemed ripe for a cleanup, so there's a few bits such as :
- not having multiple `callCount` in a hierarchy
- negated JIT condition - JITing when JIT meant to be disabled
- get JIT excludes to also exclude block compilations
- more useful ji logging - seeing exception.toString failures
aside from these, there's 2 simple but important changes : 
- `-Xjit.max=10000` default, to compilations and not leak meta-space
even for a large Rails app this should be conservative as it takes several hours to reach the limit
from a production app 10_000 JIT compiles means having around 550 of allocated meta-space
- `Xjit.maxsize` reduced from 2000 -> 1000 again based on real world production …
> respect jit.max to stop compilation

- core/src/main/ruby/jruby/path_helper.rb
references
https://travis-ci.org/puma/puma/jobs/587423508
https://github.com/puma/puma/commit/c68dfffc32c7e23ea6bcbdb1e2177bd782199cc6
```
FrozenError: can't modify frozen String
org/jruby/RubyString.java:2684:in `<<'
uri:classloader:/jruby/path_helper.rb:59:in `block in quote_sensitive_split'
org/jruby/RubyString.java:5645:in `each_char'
uri:classloader:/jruby/path_helper.rb:19:in `quote_sensitive_split'
uri:classloader:/jruby/path_helper.rb:94:in `smart_split_command'
org/jruby/RubyKernel.java:1780:in `_exec_internal'
uri:classloader:/jruby/kernel/kernel.rb:4:in `exec'
/home/travis/.rvm/gems/jruby-head/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:53:in `kernel_exec'
/home/travis/.rvm/gems/jruby-head/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:34:in `run' …
```
> frozen path helper

- core/src/main/java/org/jruby/RubyInstanceConfig.java
- core/src/main/java/org/jruby/compiler/BlockJITTask.java
- core/src/main/java/org/jruby/compiler/MethodCompiledJITTask.java
- core/src/main/java/org/jruby/compiler/MethodJITTask.java
since there's currently no way to exclude dynamic evals (e.g. from Rails)
allows us to handle excludes as long as FILE is set ... e.g. [excluding generated attribute methods](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/attribute_methods.rb#L48)
> [feat] jit.exclude based on path/to/impl_file.rb

- core/src/main/java/org/jruby/compiler/BlockJITTask.java
- core/src/main/java/org/jruby/compiler/Compilable.java
- core/src/main/java/org/jruby/compiler/JITCompiler.java
- core/src/main/java/org/jruby/internal/runtime/AbstractIRMethod.java
- core/src/main/java/org/jruby/runtime/InterpretedIRBlockBody.java
- core/src/main/java/org/jruby/runtime/MixedModeIRBlockBody.java
wasn't working since the (internal) closure id was returned
since block tasks will know the impl module - return that
and use the common logic for extracting owner name
> [fix] jit.excludes for block using class (and method) name

- core/src/main/java/org/jruby/compiler/BlockJITTask.java
- core/src/main/java/org/jruby/compiler/ClassLoaderMode.java
- core/src/main/java/org/jruby/compiler/JITCompiler.java
- core/src/main/java/org/jruby/compiler/MethodCompiledJITTask.java
- core/src/main/java/org/jruby/compiler/MethodJITTask.java
- core/src/main/java/org/jruby/util/cli/Options.java
- core/src/main/java/org/jruby/util/collections/WeakValuedMap.java
introduces a `-Xjit.loader.mode` which is either UNIQUE (default), SHARED or SHARED_SOURCE
most of it is making `WeakValueMap` implement `Map` as I originally did something else here ...
so I've kept that code and just did a fake `Map` for the single (shared) global class-loader.
that can be changed as needed to a cleaner (proper oop) way.
the SHARED_SOURCE was so far only tested with jruby's test suite, the JITed class-loader count went down to 10% ... and meta-space was much less fragmented - saving around 8% of allocated space.
was not sure whether we should attempt to somehow detect `eval`-ed pieces
and not share them with the same source file but rather always on their own?
given that SHARED_SOURCE isn't changed to be the new default, we can also decide later.
also if you have …
> attempt to share loader for JIT-ed classes

- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/parser/StaticScope.java
This cleans up the acquisition of a complete local variable list from StaticScope, and then uses that cleaned-up logic for `Kernel#local_variables` to eliminate access of the DynamicScope.
> Simplify and use static scope for local_variables.

- core/src/main/java/org/jruby/RubyException.java
- core/src/main/java/org/jruby/javasupport/ext/JavaLang.java
- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
- spec/java_integration/addons/throwable_spec.rb
Since Java throwables are treated similarly to regular Ruby exceptions,
I think it makes sense to implement `full_message` for easier logging
and debugging.
This moves the `RubyException` implementation to `TraceType` so that it
can be shared with `Throwable`. I had to change the `exception` argument
type in `printBacktraceMRI` in order to support the exception-like
object that `Throwable` provides.
Closes: https://github.com/jruby/jruby/issues/5906
> Implement Java::JavaLang::Throwable#full_message

- core/src/main/java/org/jruby/internal/runtime/AbstractIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRNoProtocolMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java
- core/src/main/java/org/jruby/ir/IRMethod.java
a load test profiled showed some lower (but likely often unnecessary) numbers around:
```
org.jruby.ir.IRMethod.lazilyAcquireInterpreterContext()	
org.jruby.internal.runtime.methods.MixedModeIRMethod.ensureInstrsReady()	
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(ThreadContext, IRubyObject, RubyModule, String, IRubyObject, IRubyObject, Block)	
org.jruby.RubyClass.finvoke(ThreadContext, IRubyObject, String, IRubyObject, IRubyObject, Block)	
org.jruby.RubyBasicObject.send(ThreadContext, IRubyObject, IRubyObject, IRubyObject, Block)	
org.jruby.RubyKernel.send(ThreadContext, IRubyObject, IRubyObject, IRubyObject, IRubyObject, Block)
org.jruby.RubyKernel$INVOKER$s$send.call(ThreadContext, IRubyObject, RubyModule, String, IRubyObject, IRubyObject, IRubyObject, Block) …
```
> less locking in interpreter mode (due IRMethod)

- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/RubyObject.java
- core/src/main/java/org/jruby/internal/runtime/AbstractIRMethod.java
- core/src/main/java/org/jruby/ir/IRMethod.java
This is likely at least a partial fix for #5910, where it appears
that multiple threads all trigger reificatin of a class's
variables at the same time, leading to some of those threads
choosing a different reified type and ultimately class casting
exceptions.
The change here synchronizes against the class's "real" class,
which should be the one on which we attach the allocated. This
should force multiple threads all allocating the first instance
at once to wait for each other, eventually falling back on the
new allocator that does not re-reify the type.
This will eventually be moot once individual object instances hold
a reference to their own layout managers.
> Synchronize variable reification against real class.

- core/src/main/java/org/jruby/RubyException.java
- spec/ruby/core/exception/inspect_spec.rb
> Use new RubyStringBuilder.str api to create inspected string for Exception

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/Pack.java
- core/src/main/ruby/jruby/kernel.rb
- core/src/main/ruby/jruby/kernel/string.rb
feature [String#unpack1](https://bugs.ruby-lang.org/issues/12752) should be an optimization, but on jruby it's significantly slower even more than #unpack.first
examples from stdlib
https://github.com/jruby/jruby/blob/4e8bb2666a7257f0f5986800f96bb88efdd6acbd/lib/ruby/stdlib/base64.rb#L59
https://github.com/jruby/jruby/blob/d03c357cef56ff2935fdb1c3d534d7286d5286cc/lib/ruby/stdlib/erb.rb#L995
```
jruby
unpack h*      2.961M (? 4.8%) i/s -     14.738M in   4.995894s
unpack1 h*    591.196k (? 8.0%) i/s -      2.946M in   5.019534s
unpack C*      2.628M (? 5.9%) i/s -     13.082M in   5.000418s
unpack1 C*    642.124k (? 3.2%) i/s -      3.227M in   5.032145s
unpack m      2.878M (? 5.8%) i/s -     14.328M in   5.002753s
unpack1 m    616.794k (? 2.4%) i/s -      3.095M in   5.020186s
unpack …
```
> faster unpack1

- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyProcess.java
- core/src/main/java/org/jruby/util/cli/Options.java
- core/src/main/java/org/jruby/util/io/PopenExecutor.java
Our native subprocess logic has some quirks, and for cases where
it is a problem like #5911 it would be good to be able to disable
native popen/spawn/backquote without disabling all of native
support. This PR adds the property `jruby.native.popen` defaulting
to true. Users can force the use of the built-in JDK process logic
by passing `-Xnative.popen=false` to JRuby or passing
to the JVM `-Djruby.native.popen=false`.
> Add native.popen option to disable native popen.

- core/src/main/java/org/jruby/runtime/invokedynamic/MathLinker.java
This primarily adds a hard RubyFixnum or RubyFloat type check on
self, to ensure we're not even attempting fast bindings for other
types. It also reduces overall binding overhead in that case by
moving direct indy logic out of the fail path and moves a couple
more adapted method handles to constants.
Fixes #5938.
> Restructure indy-based math binding.

- core/src/main/java/org/jruby/ir/transformations/inlining/InlineCloneInfo.java
synchronization using a boxed primitive isn't reliable, because the field's value could be changed while a thread is in a synchronized block.
> properly synchronize globalInlineCount

- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/ext/thread/Mutex.java
This PR contains fixes for some interruptibility issues introduced in JRuby 9.2.8:
* A thread woken up while attempting to acquire a contended lock would raise an error rather than continuing to try to acquire the lock.
* A thread sleeping via a `ConditionVariable` would be uninterruptible.
WIP until I confirm it's ready.
> Mutex fixes for interruptibility

- spec/ruby/library/conditionvariable/signal_spec.rb
This tests (J)Ruby's ability to safely switch back and forth between two threads that both have locks on a single mutex, as identified in #5863.
I'm happy to make changes to this spec if needed.  In particular, I wasn't sure what a suitable timeout should be (went with 5 seconds), and also whether to add this to the spec for `#signal` or `#wait`.  I went with `#signal` because it seems that the failure is in the ability to wake up after going to sleep.
> Test passing control between two threads in the ConditionVariable spec

- core/src/main/java/org/jruby/util/io/PopenExecutor.java
See #5865
The logic here was disabled because it makes changes to file descriptors in the parent process, which could cause a race if multiple threads try to `popen` using the same descriptors. However the race only affects subprocess launching and the mostly-inert `CLOEXEC` descriptor flag, so I think any possible problems can be mitigated easily.
Note we also are not consistent about setting `CLOEXEC` right now anyway, owing to the JVM's hiding of many descriptors. `CLOEXEC` cleanup and serializing these changes in `popen` can come later (if they're needed).
> Enable recursive fd redirection for popen logic.

- core/src/main/java/org/jruby/RubyDir.java
- core/src/main/java/org/jruby/javasupport/JavaUtil.java
- test/jruby/test_dir.rb
- test/mri/excludes/TestDir.rb
Fixes #4495 and partial fix for #3205
> encoding parameter for Dir.open, Dir.new #3205 #4495

- core/src/main/java/org/jruby/internal/runtime/ThreadService.java
For #5936 we saw some cases where the SoftReference created here
came back as null, even after the "adopt" logic had run. While I
have not isolated an exact cause, there are thread locals, soft
references, and GC interacting here. Since the original logic did
not guarantee non-null references throughout the code, I've
modified it to always check and only proceed once it truly has
non-null references and eventually context in hand.
> Improve how we acquire ThreadContext to eliminate null refs.

- lib/ruby/stdlib/resolv.rb
As described in logstash-plugins/logstash-filter-dns#52 
`resolv.rb` was updated from upstream Ruby stdlib starting at JRuby 9.2.0.0 which essentially re-introduced issue logstash-plugins/logstash-filter-dns#40 where all DNS request will eventually systematically time out.
This problem will only be triggered if there are multiple nameserver hosts specified OR if there is no nameserver host but there are more than one host in `/etc/resolv.conf` resulting in the usage of the `UnconnectedUDP` class in `resolv.rb`.
Essentially the problem is that the [`DNS.allocate_request_id(host, port)` call](https://github.com/jruby/jruby/blob/9.2.0.0/lib/ruby/stdlib/resolv.rb#L790) will cache the allocated id using the `host` and `port` parameters. 
But the cache cleanup will be done in the `close` method …
> use same parameter for DNS.allocate_request_id/free_request_id to fix leak

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/internal/runtime/ThreadService.java
This change reduces the overhead of calling Ruby.getCurrentContext
since we still call it in a number of places.
* ThreadService now extends ThreadLocal rather than aggregating a ThreadLocal in a field. This eliminates one hop.
* All hot-path methods in ThreadService are static.
* Restore @kares recursion logic since it does appear faster than an explicit null check loop.
On OpenJDK 8 C2 this reduces single-thread getCurrentContext time from around 4ns to around 3.2ns. Other VMs have similar gains.
Tested with a trivial benchmark:
```java
import org.jruby.Ruby;
public class ContextGetter {
public static void main(String[] args) {
Ruby runtime = Ruby.newInstance();
while (true) {
long nanos = System.nanoTime();
for (int i = 0; i < 100_000_000; i++) {
runtime.getCurrentContext();
} …
```
> Tweak getCurrentContext for SPEED

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyEnumerator.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyGlobal.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyMatchData.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubyStruct.java
- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/set/RubySet.java
- core/src/main/java/org/jruby/ext/set/RubySortedSet.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java
- core/src/main/java/org/jruby/specialized/RubyArrayOneObject.java
- core/src/main/java/org/jruby/specialized/RubyArrayTwoObject.java
This avoids bouncing through the metaClass to get the runtime,
which happens in these methods and in several downstream calls.
Several cases also needed the context, so this saves the extra
overhead of traversing the runtime, thread service, and thread
local to get the context.
This is a PR to get input. Some signatures change without a class-local replacement, so code compiled to those signatures on those classes would fail. I didn't want to leave deprecated no-arg versions all over the place.
There are also many other core IRubyObject methods that don't accept context.
I have not done any perf measurements but it's probably negligible. The main benefit is that the context will almost always be in cache for a given thread, since we pass it through almost all call paths.
> Propagate ThreadContext through to_a implementations

- core/src/main/java/org/jruby/util/ShellLauncher.java
Hi!
I have no idea what I'm doing (and don't have a local dev environment, so I'm making things up without even a typecheck to back me up :pensive:), so this is probably disastrously wrong in detail, but...
I think something along these lines fixes #3428, as well as a wider issue:
```
% env | grep EDITOR
EDITOR=vim
% ruby -e 'system({ "EDITOR" => "emacs" }, "env")' | grep EDITOR
EDITOR=emacs
% rbenv shell jruby-9.2.8.0
% ruby -e 'system({ "EDITOR" => "emacs" }, "env")' | grep EDITOR
EDITOR=vim
EDITOR=emacs
```
POSIXly speaking (without having checked the relevant docs), that seems Bad. Even without the not-removing-nils issue, it appears to be a bit hit-or-miss which entry a process will choose to honour... I'm struggling to show it in isolation, but I got here because I was seeing the …
> Properly override base env with supplied values for spawn

- bin/.jruby.module_opts
- core/src/main/java/org/jruby/util/Pack.java
Rails uses unpack1 'm0' to decode base64 cookies.  Recent work had improved the performance of unpack1 but I was somewhat disturbed that MRI did so much better once the decode string got larger.  This PR fast paths m0 and will also use a version which does not use ByteBuffer.
This benchmark looks at some larger strings (note: largest one is a bit bigger than the max size of a cookie but it is close enough to 4096 to get an idea of the cost at that size:
```
MRI 2.7
Warming up --------------------------------------
unpack1 m len: 288     2.089k i/100ms
unpack1 m len: 576     1.330k i/100ms
unpack1 m len: 1152   858.000  i/100ms
unpack1 m len: 2304   469.000  i/100ms
unpack1 m len: 4608   249.000  i/100ms
Calculating -------------------------------------
unpack1 m len: 288     22.723k (± …
```
> Faster unpackm0

- bench/core/string/bench_sub.rb
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/StringSupport.java
This PR addresses #5905. It's still pretty naive, and I'm really not a Java programmer, so there's probably a few dumb mistakes and style things aside from the big MatchData problem.
The big known problem remaining is how to populate the `$~` `MatchData`. In MRI the `MatchData` from a string-only `String#sub` or `#gsub` will return a `Regexp` from `MatchData#regexp`. I don't think we currently have a way of doing that, so that means changes to `MatchData`.
MRI is clearly doing something odd here, because if you call `#inspect` on the `MatchData` returned from a string pattern `#sub`, it's in a different form to what you get from invoking it with a Regexp pattern (this from MRI 2.6.3):
```
~ $ irb
irb(main):001:0> "a".sub("a", "b")
=> "b"
irb(main):002:0> $~
=> #<MatchData: a> …
```
> Use string index in String #sub/#gsub when String pattern passed without creating a Regexp

- core/src/main/java/org/jruby/RubyInteger.java
just do the same as mri https://github.com/ruby/ruby/blob/e7ea6e078fecb70fbc91b04878b69f696749afac/numeric.c#L3320
```
after
big      6.596M (? 7.8%) i/s -     32.708M in   4.995933s
before
big      4.264M (? 5.7%) i/s -     21.237M in   4.994988s
```
+indy
```
after
big      8.865M (? 2.6%) i/s -     44.215M in   4.991349s
before
big      4.704M (? 4.4%) i/s -     23.487M in   5.004868s
```
```
require 'benchmark/ips'
Benchmark.ips do |x|
x.report('fix') { 5.succ }
x.report('big') { 500000000000000000000000000000000000000000000000000000000000000000000000004.succ }
end
```
> expand #succ for bignums

- core/src/main/java/org/jruby/ext/date/RubyDate.java
refs https://github.com/jruby/jruby/issues/5965 the change was merged in MRI ruby/ruby@e7ea6e0
> optimize isGregorianLeap

- core/src/main/java/org/jruby/ir/targets/Bootstrap.java
- core/src/main/java/org/jruby/ir/targets/InvokeSite.java
- core/src/main/java/org/jruby/runtime/Helpers.java
This logic will cache the target class's method_missing impl when
a method call fails to find a natural method table entry. This
scenario was a source of failed call sites in Redmine's json
builder and in the Rails StringInquirer class used for Rails.env.
With this change in place Redmine json issue requests improved by
roughly 15%.
> Cache method_missing target

- core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java
- spec/java_integration/object/marshal_spec.rb
This includes two fixes introduced (at least in part) by #5832:
* Private classes were considered for method binding even though
we no longer set them accessible on Java 9+ when they have not
already been opened. This resulted in Java 9+ environments
producing method errors when they attempted to dispatch to those
methods on private classes.
* In order to fix the above for private classes with public
interfaces, this patch also fixes how we traverse a class's
implemented interfaces. Possibly from changes in #5832, we were
not walking an interface's superinterfaces, causing us to only
walk one level in such cases.
In my local tests, this caused failures in `spec:ji` for specs accessing the following classes; I do not believe that these methods should be callable, since they are on private …
> Bind only public interface methods for private classes

- lib/ruby/stdlib/rubygems/defaults/jruby.rb
- test/mri/lib/envutil.rb
Rubygems deprecated it in https://github.com/rubygems/rubygems/pull/2857.
> Remove usages of deprecated ConfigMap

- core/src/main/java/org/jruby/util/Pack.java
- spec/tags/ruby/library/base64/strict_decode64_tags.txt
it fails for shared strings if begin != 0
```
require 'base64'
url = "data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImFob3kuanMiXSwibmFtZXMiOlsiaGVsbG8iLCJ3b3JsZCJdLCJtYXBwaW5ncyI6IkFBQU0sU0FBU0EsUUFDUCxTQUFTQyxJQUNQLE9BQU8sRUFHVCxPQUFPQSxJQUFVQSIsInNvdXJjZXNDb250ZW50IjpbIiAgICAgIGZ1bmN0aW9uIGhlbGxvICgpIHtcbiAgICAgICAgZnVuY3Rpb24gd29ybGQgKCkge1xuICAgICAgICAgIHJldHVybiAyO1xuICAgICAgICB9O1xuXG4gICAgICAgIHJldHVybiB3b3JsZCgpICsgd29ybGQoKTtcbiAgICAgIH07XG4iXX0="
base = url.split(",").last
Base64.strict_decode64(base)
```
refs https://github.com/jruby/jruby/pull/5961
> fix strict_base64 for shared strings

- bin/jruby.bash
MacOS
```
brew install jruby
jruby -v
/usr/local/bin/jruby: line 88: cd: /usr/local/bin/jruby: Not a directory
Error: --module-path requires module path specification
```
> fix 'jruby: line 88: cd: ../libexec/bin: No such file …'

- core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java
- spec/java_integration/fixtures/IsEqualClass.java
- spec/java_integration/methods/equals_spec.rb
The `equal?` method should always be identity equality and not get overridden if a class defines an `isEqual` method as in Joda's AbstractPartial does.
Fixes #5990.
> Do not alias a Java IsEqual to equal?

- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/RubyProc.java
- core/src/main/java/org/jruby/RubyStruct.java
- core/src/main/java/org/jruby/compiler/BlockJITTask.java
- core/src/main/java/org/jruby/ir/instructions/CallBase.java
- core/src/main/java/org/jruby/ir/instructions/specialized/ZeroOperandArgNoBlockCallInstr.java
- core/src/main/java/org/jruby/ir/passes/AddCallProtocolInstructions.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/Bootstrap.java
- core/src/main/java/org/jruby/ir/targets/YieldSite.java
- core/src/main/java/org/jruby/runtime/Block.java
- core/src/main/java/org/jruby/runtime/BlockBody.java
- core/src/main/java/org/jruby/runtime/CompiledIRBlockBody.java
- core/src/main/java/org/jruby/runtime/IRBlockBody.java
- core/src/main/java/org/jruby/runtime/MethodBlockBody.java
- core/src/main/java/org/jruby/runtime/MixedModeIRBlockBody.java
- core/src/main/java/org/jruby/util/cli/Options.java
This PR contains several improvements to block dispatch to reduce overhead.
* Make Block.type final, to take advantage of final optimizations in some JVM JITs. If it needs to be modified, the Block should be cloned. Most blocks will never need this since they're always normal or always lambda.
* Move BlockBody.evalType to Block and make it a final field. This eliminates the ThreadLocal in IRBlockBody and avoids constantly updating it back to normal, which was done every call to any IR block in the system.
* Make escapeBlock final. This is only ever set at construction time and never modified again. Setting it here allows final optimizations to reduce loads when checking for escaped blocks.
* Reset and recalculate IRScope flags before running AddCallProtocol. This allows ACP to reduce how …
> Reduce block overhead

- core/src/main/java/org/jruby/RubyString.java
This PR implements String#split with a blcok.
See [Feature #4780](https://bugs.ruby-lang.org/issues/4780).
> Ruby 2.6 : Add String#split with a blcok

- bin/jruby.bash
Here are a bunch of changes cleaning up the Bash launcher. Most of it is assisted by [shellcheck](https://www.shellcheck.net).
Changes include syntax improvements, removing unused variables, and some minimal syntax changes to make it easier to port to POSIX shell in the future.
See commit messages for more details.
> Bash cleanup

- core/src/main/java/org/jruby/RubyRandom.java
This PR implements Random.bytes method.
See Feature [#4938](https://bugs.ruby-lang.org/issues/4938)
> Ruby 2.6 : Add Random.bytes

- bin/jruby.bash
Looks like I broke something in my bash cleanup. This variable can never start as an array since it's from the environment. Treating it as an array parses all the options as one, so none of the variables the case statement get set right.
It is expanded correctly later, so the flags are passed to java, but the default value of -Xss is appended and overrides the previous one (I assume).
Setting JAVA_OPTS to something not starting with -Xss, e.g. `-Xms256m -Xss4096k` and putting this:
```bash
printf JAVA_OPTS: ; printf ' "%s"' $JAVA_OPTS; echo
```
somewhere late in the script shows the incorrect behaviour.
> Remove array expansion of JAVA_OPTS environment variable

- core/src/main/java/org/jruby/ext/ffi/Type.java
MRI
```
FFI::Type::Builtin::FLOAT
=> #<FFI::Type::Builtin:FLOAT32 size=4 alignment=4>
FFI::Type::Builtin::FLOAT.to_s
=> "#<FFI::Type::Builtin:0x0000000003b0d918>"
```
jruby
```
FFI::Type::Builtin::FLOAT
#<FFI::Type::Builtin:0x60e67c06>
FFI::Type::Builtin::FLOAT.to_s
"#<FFI::Type::Builtin:FLOAT size=4 alignment=4>"
```
jruby + patch
```
FFI::Type::Builtin::FLOAT
"#<FFI::Type::Builtin:FLOAT size=4 alignment=4>"
FFI::Type::Builtin::FLOAT.to_s
#<FFI::Type::Builtin:0x60e67c06>
```
> [fix] inspect builtin

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyChain.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyEnumerator.java
This PR implements Enumerator::Chain class, Enumerable#chain and Enumerator#+.
See Feature [#15144](https://bugs.ruby-lang.org/issues/15144)
> Ruby 2.6 : Enumerator::Chain class, Enumerable#chain, Enumerator#+

- bench/core/kernel/bench_raise.rb
- core/src/main/java/org/jruby/exceptions/RaiseException.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
initially I thought `rescue nil` back-trace capturing is disabled on purpose
but seems it simply got lost at f64a3e0
follow-up on https://github.com/jruby/jruby/pull/6014
should introduce some perf.testing to avoid loosing performance
> [fix] restore rescue nil performance 

- lib/ruby/stdlib/fiddle/jruby.rb
fixes https://github.com/jruby/jruby/issues/5956 and https://github.com/jruby/jruby/issues/5955
but this test case doesn't work yet
https://github.com/jruby/jruby/blob/4e8bb2666a7257f0f5986800f96bb88efdd6acbd/test/mri/fiddle/test_func.rb#L73
I'm experimanting for now :)
> fiddle fixes

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/ir/instructions/CallBase.java
- test/mri/excludes/TestRefinement.rb
Kernel#send and BasicObject#__send__ should honor refinements from the surrounding scope.
Note this forces sends in the presence of refinements to require a scope, which currently means a dynamic scope.
Fixes #5945
> Refined send

- maven/jruby-complete/src/it/runnable/Mavenfile
- test/pom.rb
It fixes `mvn -Pbootstrap` on my environment using java 11. Before I would get the following error when running integration tests:
```
(...)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for JRuby 9.2.10.0-SNAPSHOT:
[INFO]
[INFO] JRuby .............................................. SUCCESS [  0.303 s]
[INFO] JRuby Core ......................................... SUCCESS [  9.286 s]
[INFO] JRuby Lib Setup .................................... SUCCESS [  3.578 s]
[INFO] JRuby Integration Tests ............................ FAILURE [  3.722 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: …
```
> Bump mavengem-wagon version everywhere

- lib/ruby/stdlib/rubygems/installer.rb
* It would try to use ruby.exe, which is currently not shipped as part of JRuby distributions.
* See https://github.com/jruby/jruby-launcher/issues/29#issuecomment-586701997
This of course should probably be fixed in RubyGems upstream.
I'll let you handle that.
> Fix windows_stub_script to use jruby.exe

- core/pom.rb
- core/pom.xml
This is in response to additional constants in jnr-constants 0.9.15. This fixes #6070.
jnr-constants 0.9.15
jnr-enxio 0.25
jnr-unixsocket 0.27
jnr-posix 3.0.54
> Update jnr dependencies

- core/src/main/ruby/jruby/kernel/enumerator.rb
This PR will include commits to reduce the chance of `Enumerator#next` fibers leaking.
The original issue is #6004.
So far most of the leaks appear to be caused by combining `Enumerator::Lazy` with `Enumerator#next`, since many lazy paths construct new Lazy instances in such a way that they are hard-referenced by the eventual fiber.
> Fix Enumerator fiber leaks

- BUILDING.md
I don't think triple backquotes are meant to be used inline, at least they broken syntax highlighting of my editor :)
> Change triple to single backquotes

- core/src/main/java/org/jruby/RubyDir.java
- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/util/StringSupport.java
- test/jruby.index
This should fix issues reported with RubyGems 3.0.6 and jarred resources.
Fixes #6060 
Fixes #6082 
Fixes #6083 
I have reverted the tests we disabled in 9.2.10.0 but a more direct test of this behavior (i.e. passing a `base:` URI to Dir.glob) would be useful to make sure we don't regress.
> Use expand_path logic for Dir.glob base path

- core/src/main/java/org/jruby/javasupport/JavaConstructor.java
If this call were made with the wrong number of arguments, it could easily walk off the type array due to the lack of arity checking in the convertArguments call.
Fixes #6079.
> Check arity earlier in JavaConstructor#new_instance

- lib/ruby/stdlib/cgi/util.rb
- spec/tags/ruby/library/cgi/escapeHTML_tags.txt
fixes https://github.com/jruby/jruby/issues/6093
> CGI.escapeHTML restore the original encoding

- core/src/main/java/org/jruby/util/JRubyClassLoader.java
- core/src/main/java/org/jruby/util/OneShotClassLoader.java
These classloaders apparently led to a deadlock inside Azul Zing
when using the ReadyNow feature that saves class and JIT data
betwen runs. This should be a benign change, since these loaders
typically only ever load one class, but we'll let it back for a
while.
> Mark custom classloaders as parallel capable

- core/src/main/java/org/jruby/RubyClass.java
This was removed in 2011 by aa4e8bb8dd after it broke some
libraries that mined information out of the backtrace,
specifically RSpec 2. Since then, RSpec and other libraries have
become more robust about how they present and manipulate
backtraces, so this commit puts those frames back.
This is a partial fix for #6055, but invokedynamic "new" logic
will still omit that frame when calling the core "new" method.
> Restore the backtrace element for the `new` call

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyArithmeticSequence.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/runtime/JavaSites.java
This PR implements Enumerator::ArithmeticSequence class , Numeric#step and Range#step.
See MRI's NEWS file https://github.com/ruby/ruby/blob/ruby_2_6/NEWS
> Ruby 2.6 : Enumerator::ArithmeticSequence class, Numeric#step, Range#step

- core/src/main/ruby/jruby/java/core_ext/module.rb
- core/src/main/ruby/jruby/java/core_ext/object.rb
This PR contains commits to clean up `java_import` and bring up to date with modern Ruby patterns.
Inspired by #6115.
> Cleanups and improvements for java_import

- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/util/time/TimeArgs.java
The initialization path for RubyTime had grown unwieldy, with many paths crossing through the same logic and obscuring each others behavior. This refactor does the following:
* Separates as much as possible the different call paths
* Reduce duplication in argument processing
* Simplify handling of subsecond times
* Remove most of this logic from RubyTime into a utility class
* Remove a couple long-deprecated construction methods
This passes CRuby and rubyspec Time tests and will be the baseline for adding support for the new duck-typed "Timezone" object in 2.6.
> RubyTime initialization refactor

- core/src/main/ruby/jruby/kernel/enumerator.rb
This PR targets to make the following TravisCI test passed.
```
TestLazyEnumerator#test_inspect [/Users/kiichi/git/jruby/test/mri/ruby/test_lazy_enumerator.rb:450]:
<"#<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: 1..10>:map>:collect>:flat_map>:collect_concat>:select>:find_all>:reject>:grep(1)>:zip(\"a\"..\"c\")>:take(10)>:take_while>:drop(3)>:drop_while>:cycle(3)>"> expected but was
<"#<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator::Lazy: …
```
> Ruby 2.6 : fix Enumerator::Lazy#find_all and #filter

- core/src/main/java/org/jruby/RubyEnumerable.java
This PR targets to make the following TravisCI test passed.
```
30) Failure:
TestEnumerable#test_to_h_block [/Users/kiichi/git/jruby/test/mri/ruby/test_enum.rb:186]:
<{"hello"=>"world",
"key"=>"value",
"other_key"=>"other_value",
"obtained"=>"via_to_ary"}> expected but was
<{"hello"=>"world",
:key=>:value,
"other_key"=>"other_value",
:obtained=>:via_to_ary}>.
```
> Ruby 2.6 : fix Enumerable#to_h with block.

- core/src/main/java/org/jruby/ext/timeout/Timeout.java
- core/src/test/java/org/jruby/embed/ScriptingContainerTest.java
- lib/ruby/stdlib/timeout.rb
Some JVM-based projects (e.g. [puppetlabs/puppetserver](https://github.com/puppetlabs/jruby-utils/blob/2f5897fa01123f5d930c9e07ae93e8bfacd17811/src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj#L194)) that embed JRuby using `ScriptingContainer` and use the `timeout` module suffer thread leaks when recycling `ScriptingContainer`s.  Such users appear to expect `ScriptingContainer#terminate` to clean up all allocated resources (within reason) including threads.
This PR is an attempt to do so by shutting down the `ScheduledThreadPoolExecutor` created during the initialization of the `Timeout` module on Ruby teardown.
> Address dangling threads in Timeout module

- core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java
- spec/compiler/general_spec.rb
The method name (as a symbol) was not being properly recombined
with the incoming arguments array, so any varargs calls would
error out while attempting to bind a method_missing target.
This change folds the combined array back into the arguments so
it can bind properly.
Fixes #6130
> Properly recombine varargs with method name for indy m_m

- pom.rb
- pom.xml
The 2.2.0 version gemspec provided by prints an annoying warning when read:
```
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/deivid/.rbenv/versions/jruby-9.2.11.0/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
```
> Bump `json` version provided by default

- BUILDING.md
This is another overzealous quoting I found in docs. Same as https://github.com/jruby/jruby/pull/6058.
> Fix another unintended triple backquote

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/ext/timeout/Timeout.java
- lib/ruby/stdlib/timeout.rb
This adds the ability to register an exit hook from Java using a simple function object. It also switches the Timeout library from using `at_exit` to using this API for executor shutdown.
See #6127 which, due to the lack of such an API, was forced to dig around in JRuby internals from Ruby code.
There may be other places where this could be used but I did not audit other `at_exit` consumers.
> Enhanced exit blocks

- core/src/main/java/org/jruby/RubyStruct.java
This PR targets to make the following TravisCI test passed.
```
13)
Struct#to_h with block raises ArgumentError if block returns longer or shorter array ERROR
ArgumentError: wrong array length at 0 (expected 2, was 3)
org/jruby/RubyStruct.java:651:in `to_h'
/home/travis/build/jruby/jruby/spec/ruby/core/struct/to_h_spec.rb:27:in `block in <main>'
/home/travis/build/jruby/jruby/spec/ruby/core/struct/to_h_spec.rb:26:in `block in <main>'
org/jruby/RubyBasicObject.java:2687:in `instance_exec'
org/jruby/RubyArray.java:4557:in `all?'
org/jruby/RubyArray.java:1817:in `each'
org/jruby/RubyArray.java:1817:in `each'
/home/travis/build/jruby/jruby/spec/ruby/core/struct/to_h_spec.rb:4:in `<main>'
org/jruby/RubyKernel.java:1051:in `load'
org/jruby/RubyBasicObject.java:2687:in `instance_exec' …
```
> Ruby 2.6 : fix Struct#to_h exception message

- lib/ruby/stdlib/rubygems/defaults/jruby.rb
This issue was initially reported here: https://github.com/jruby/jruby/issues/6030
It breaks `rspec-rails`' `jruby-head` build: https://travis-ci.org/github/rspec/rspec-rails/jobs/670723126
This was supposed to fix it: https://github.com/jruby/jruby/pull/5966/files
And this as well: https://github.com/jruby/jruby/commit/637b17ce3f9981f84840a54803cc83bcd0571a98#diff-2d9baebc59d1732672e3dba0ba309e84
Somehow, those changes did not reflect on `master`.
> Remove usages of deprecated ConfigMap (again)

- core/src/main/java/org/jruby/ext/socket/RubySocket.java
Direct blocking connects can't be interrupted through normal Ruby
thread events because a hard interrupt would destroy the related
channel. Like other IO, this change uses fully non-blocking
channels and selectors to handle blocking.
Fixes #6126
> Do all socket connects nonblocking for interrupts

- core/src/main/java/org/jruby/RubyTime.java
- spec/ruby/core/time/shared/to_i.rb
This fixes #6104. Needs specs though.
> Round Time#to_i down rather than truncating

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/internal/runtime/ThreadService.java
This change modifies our shutdown process to asynchronously interrupt and wait for all registered threads (excluding main) to allow them to complete execution.
Previously our behavior was to walk away from running threads. This behavior appears to have either changed in CRuby long ago, or we never implemented this behavior.
Note that this implementation does not currently differentiate between threads started from Ruby code and threads started by other code in the JVM that happened to get adopted by JRuby. We probably should not attempt to kill those adopted threads, and certainly don't want to try to join on them.
The following script illustrates some behavior of thread shutdown. This may be a good start at writing a spec.
```ruby
t = Thread.new {
p 1
begin
sleep
ensure
p 2
end
}
at_exit …
```
> Shut down threads on teardown

- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/internal/runtime/AdoptedNativeThread.java
- core/src/main/java/org/jruby/internal/runtime/RubyNativeThread.java
- core/src/main/java/org/jruby/internal/runtime/ThreadLike.java
- core/src/main/java/org/jruby/internal/runtime/ThreadService.java
The old logic maintained a weak reference to the native thread
associated with a Ruby thread, in order to avoid keeping its
resources alive longer than the thread's lifecycle. However in
the case shown in #6142, it seems likely that under heavy load the
native thread gets collected before it starts running. Because of
the logic we have to silently ignore collected references, the
NativeThread.start method simply returns if the thread has gone
away, giving us no indication that the thread never actually ran.
This patch splits our NativeThread into two types:
* RubyNativeThread, which holds a hard reference to the native
Thread and implements start to call Thread#start.
* AdoptedNativeThread, which holds a weak reference to the native
Thread and errors (BUG!) if we attempt to call call …
> Hold a hard reference to Ruby threads

- .github/workflows/ci.yml
Trying to get the remaining maven suites to pass in 11 so we can matrix these.
> Align 8 and 11 in github actions CI

- core/src/main/java/org/jruby/ast/RootNode.java
- core/src/main/java/org/jruby/ext/coverage/CoverageData.java
- core/src/main/java/org/jruby/ext/coverage/CoverageModule.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/IRClosure.java
- core/src/main/java/org/jruby/ir/IRFlags.java
- core/src/main/java/org/jruby/ir/IRManager.java
- core/src/main/java/org/jruby/ir/IRMethod.java
- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/ir/Operation.java
- core/src/main/java/org/jruby/ir/instructions/LineNumberInstr.java
- core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
- core/src/main/java/org/jruby/ir/persistence/IRReader.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java
- core/src/main/java/org/jruby/parser/ParserSupport.java
- core/src/main/java/org/jruby/runtime/profile/builtin/MethodData.java
- core/src/main/java/org/jruby/util/collections/IntList.java
This commit also makes some substantial changes to how coverage is
compiled in IR and JIT.
* Coverage is now independent of tracing and adds behavior to the
LineNumberInstr
* Coverage is always available
* Each covered LineNumber does its own update of coverage data
* Oneshot mode only updates once and then clears coverage flag
* JIT uses indy to bind the coverage updating logic, with oneshot
clearing it to a no-op after the first execution
> Implement oneshot_lines for coverage

- core/src/main/java/org/jruby/ext/stringio/StringIO.java
- test/mri/excludes/TestCSVEncodings.rb
Fix StringIO#write method logic.
Ported from MRI 2.6. https://github.com/ruby/ruby/blob/46a5d1b4a63f624f2c5c5b6f710cc1a176c88b02/ext/stringio/stringio.c#L1275-L1314
This change to make the following TravisCI test passed.
```
TestCSVEncodings
test_encoding_is_upgraded_during_writing_as_needed
test_encoding_is_upgraded_for_ascii_content_during_writing_as_needed
```
link  #6157
> Ruby 2.6 : fix StringIO#write method logic

- lib/ruby/stdlib/coverage.rb
Fixes #6181
Note that the output here differs from CRuby, perhaps for the same reasons we don't pass other coverage tests. Some lines are not seen as coverable when they should be.
@enebo Did you look into those coverage tests any more? Would this be better using Ripper?
Output on CRuby:
```
[] ~/projects/jruby $ rvm ruby-2.6.5 do ruby -rcoverage -e 'p Coverage.line_stub("pom.rb")'
[0, nil, nil, 0, nil, 0, 0, 0, 0, 0, nil, 0, nil, 0, nil, 0, 0, 0, 0, nil, nil, nil, 0, nil, 0, 0, nil, nil, 0, 0, 0, nil, 0, nil, 0, 0, nil, 0, nil, 0, 0, nil, nil, 0, nil, nil, nil, 0, 0, nil, nil, nil, nil, 0, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, 0, 0, nil, nil, 0, nil, nil, …
```
> Implement Coverage.line_stub

- core/src/main/ruby/jruby/java/core_ext/module.rb
- spec/java_integration/module/java_import_spec.rb
- spec/java_integration/object/java_import_spec.rb
- spec/java_integration/types/retrieval_spec.rb
given invalid import names `java_import` will raise `NameError`, 
removing `constant =~ /^[A-Z].*/` capitalization validation, leaving that part to `const_set`
the `[A-Z]` validation did not handle multi-byte capital (UTF-8) characters that well ...
in theory Java class names support the full Unicode set not just ascii characters.
> [ji] java_import now raise NameError on invalid names

- .github/workflows/ci.yml
This caused tests of actual JRuby behavior to fail, which annoyed me.
> Move dependency check to a separate job and only run once

- core/src/main/ruby/jruby/kernel/enumerator.rb
- spec/ruby/core/enumerator/next_spec.rb
- spec/tags/ruby/core/enumerator/lazy/chunk_while_tags.txt
- spec/tags/ruby/core/enumerator/lazy/slice_after_tags.txt
- spec/tags/ruby/core/enumerator/lazy/slice_before_tags.txt
- spec/tags/ruby/core/enumerator/lazy/slice_when_tags.txt
- spec/tags/ruby/core/enumerator/lazy/take_tags.txt
- spec/tags/ruby/core/enumerator/yielder/append_tags.txt
This fixes the remaining failure in CSV as discussed in #6157. Enumerators that fail prematurely due to an exception should be re-started on the next call to `next`.
> Restart dead enumerator

- core/src/main/java/org/jruby/ir/targets/Bootstrap.java
- spec/compiler/general_spec.rb
This was previously fixed only on master in #6132, but in order to support #6191 I am merging it to the jruby-9.2 branch. We won't release a 9.2.12, but users can build this branch to get the patched version.
> Merge variadic method_missing indy fix from master

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/RubyProcess.java
- core/src/main/java/org/jruby/ext/ffi/io/FileDescriptorIO.java
- core/src/main/java/org/jruby/javasupport/JavaUtil.java
- core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java
- core/src/main/java/org/jruby/util/ShellLauncher.java
- core/src/main/java/org/jruby/util/io/FilenoUtil.java
- core/src/main/java/org/jruby/util/io/SeekableByteChannelImpl.java
- core/src/main/java/org/jruby/util/unsafe/UnsafeHolder.java
This PR attempts to tweak all of our uses of `setAccessible` for accessing internal JDK classes to do the "right thing", be that using method handles, `addOpens`, or other tweaks to open up these classes if we legally can or fall back gracefully to degraded functionality *without warnings*.
The general strategy is described in the first commit to FilenoUtil, but I summarize it again here:
* Reflecting against these classes should always succeed if they are present, so this does not change.
* Instead of using the Field or Method directly, we unreflect it into a MethodHandle. This lets us know we have a fully-accessible way to deal with the reflected access, and since it raises errors instead of silently warns, we can fall back for inaccessible structures.
* When we are dealing with an …
> Use all the tricks to properly eliminate illegal access warnings

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/ext/timeout/Timeout.java
This PR fixes the following problems:
* Bad ordering of teardown that might interfere with user-defined exit hooks and finalizers.
* Timeout registering its shutdown hook as a normal `at_exit` hook, potentially breaking `at_exit` hooks that were registered earlier. (#6212)
> Reorder teardown and add a post-exit hook registry

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
- test/mri/excludes/TestTranscode.rb
This fixes failling TestTranscode#test_invalid_replace_string and #test_scrub_encode_with_coderange.
see https://github.com/ruby/ruby/blob/v2_6_6/string.c#L10152-L10172
https://github.com/ruby/ruby/blob/v2_6_6/transcode.c#L2703
> Ruby 2.6 : fix failling transcode tests.

- core/pom.rb
- core/pom.xml
This will fix #6202 by utilizing jnr/jnr-posix#148 and
jnr/jnr-ffi#204 to try loading POSIX functions from the default
image (current process) before attempting to acquire it out of the
actual C library.
> Update jnr-posix and jnr-ffi to get default image seach

- core/src/main/java/org/jruby/RubyFile.java
- spec/java_integration/paths/uri_classloader_spec.rb
- test/jruby/test_file.rb
- test/jruby/test_pathname.rb
- test/jruby/test_uri_classloader.rb
> Don't double-slash path elements when canonicalizing

- core/src/main/java/org/jruby/RubyDir.java
- core/src/main/java/org/jruby/RubyEncoding.java
- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/ir/targets/indy/IndyValueCompiler.java
- core/src/main/java/org/jruby/util/TypeConverter.java
This PR holds some experiments in making file path negotiation (expand_path, fnmatch) work properly with strings that are encoded as "binary" or "ASCII-8BIT".
In these cases it appears we should largely ignore the encoding of the characters and treat it as raw bytes, since it's not possible for us to guess the encoding. However some of the logic in these methods uses Java strings, and therefore needs to be decoded into UTF-16 characters. We will need to balance the binary cases with the properly-encoded cases as best we can, or otherwise rewrite this logic altogether to use only the raw byte form.
> Encoding experiments with file path negotiation

- core/src/main/java/org/jruby/util/StringSupport.java
- test/mri/excludes/TestUTF16.rb
This fixes failling [TestUTF16#test_succ ](https://github.com/jruby/jruby/blob/master/test/mri/ruby/enc/test_utf16.rb#L267-L273) .
> Fix failling TestUTF16#test_succ

- core/src/main/java/org/jruby/RubyFloat.java
no difference in performance, but it looks like a duplicity
> flo_floor remove dead code

- core/src/main/java/org/jruby/util/JRubyClassLoader.java
- core/src/main/java/org/jruby/util/cli/Options.java
This is another alternative fix for the issues reported in #6218
and diagnosed as a JDK bug in the following OpenJDK issue:
https://bugs.openjdk.java.net/browse/JDK-8246714
Rather than avoid the caching or leave all jar files open, this
patch takes a conservative approach. Temporary jar files that we
unpack must be deleted and should be closed even if globally
cached, since they will not conflict with other jar cache
consumers. Normal jars on the filesystem will remain unclosed, to
avoid impacting other consumers of the global jar cache.
This does mean that once a jar is opened by JRuby via our
classloader, it will not be closed until the process terminates.
Because this is a new behavior that may not be desirable in some
situations, this patch also adds a new property: …
> Only close temporary jars to avoid poisoning global jar file cache

- core/src/main/java/org/jruby/util/ShellLauncher.java
fixes a wrong reference introduced by https://github.com/jruby/jruby/commit/e8dbe9c269f7723badb89d137b2a1d52b3d3400b
> fix copy & paste error

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyException.java
- core/src/main/java/org/jruby/exceptions/Exception.java
- core/src/main/java/org/jruby/exceptions/RaiseException.java
- core/src/test/java/org/jruby/exceptions/TestRaiseException.java
- spec/java_integration/addons/throwable_spec.rb
* Make a best effort to sync up `cause` between Java and Ruby.
* Provide more convenience forms of RaiseException.from that accept a String path to the exception class and varargs constructor parameters.
Fixes #6203.
> Improved integration with Ruby and Java exceptions

- core/src/main/java/org/jruby/ir/persistence/IRReader.java
- core/src/main/java/org/jruby/ir/persistence/IRReaderDecoder.java
- core/src/main/java/org/jruby/ir/persistence/IRReaderStream.java
Instruction reading is done lazily to avoid the cost of
deserializing method bodies that will never be called. However the
buffer associated with the original file was being shared across
all of these lazy deserializations, causing concurrency issues.
This patch modifies the lazy deserialization lambda to operate
against a duplicate of the original reader, isolating its changes
in a separate buffer and avoiding the concurrency issues.
Fixes #6210
> Do lazy instruction deserialization against dup'ed reader

- core/src/main/java/org/jruby/ext/socket/SocketUtils.java
Our gethostname backends on the JDK's socket API, which always
returns a decoded character string. Rather than try to pretend
that this decoding has not happened and stuff the string back into
a "binary" ASCII-8BIT string, we instead always normalize the
encoding to UTF-8, the default encoding for Ruby strings now.
Fixes #6156
> Always encode gethostname result as UTF-8

- core/src/main/java/org/jruby/util/JarCache.java
- core/src/main/java/org/jruby/util/JarResource.java
This cache appears to have thread-safety issues. It is currently
used as a global (aka static) cache of all JarEntry from a given
jar file, to reduce the costs of searching and loading resources.
However it breaks when used across runtimes due to the
JRubyClassLoader shutdown sequence removing and thereby closing
jar files without consideration for whether they may be in use by
another runtime on the same JVM.
As far as I can tell, the jars being cached and explicitly
removed in this way should not conflict across runtimes, since
they are unpacked into unique temporary files, but the bug in
JarCache is there nonetheless.
There may be a way to ensure that a given index, and the JarFile
reference it contains, are not and will not be in use by any other
thread, allowing the file to be …
> Fix reference type and avoid closing jar directly

- core/src/main/java/org/jruby/runtime/InterpretedIRBlockBody.java
The logic here used to go to interpreterContext to check for the
call protocol logic. The hasExplicitCallProtocol method returns a
cached value acquired from the encapsulated scope, via its flags.
However the enum of flags in IRScope may be mutated concurrently,
leading to a situation where we have seen the scope flip to having
call protocols installed, but the InterpreterContext in hand is
still the one without protocol instructions. As a result, we may
start interpreting using an unoptimized IR along the "direct" path
which does not push any scope state. This lead to the AIOOB
reported later in #6282.
The NPE reported in #6282 has not reproduced for me on the
jruby-9.2 branch, and may have been fixed through other means, but
this modified logic should also help any such cases that …
> Always treat non-full IC as not having protocol

- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java
- spec/java_integration/fixtures/InnerClasses.java
- spec/java_integration/interfaces/java8_methods_spec.rb
- spec/java_integration/spec_helper.rb
- spec/java_integration/types/retrieval_spec.rb
This commit makes two changes to fix #6196:
* When both an inner class and a static final field have the same
name, only define the field. Typically this is used for a
singleton pattern where the field points at a singleton instance
of the inner class, as with Kotlin companion classes. Since we
can't define both, we prefer the field.
* Do not define the inner class constant as a side effect of
initializing that class's proxy, like we do for package
constants for normal classes. Defer that constant definition to
the initialization of the declaring class, which will make the
decision whether to define (or not) the constant at that point.
If both the field and the class are needed, it's still possible to
import the inner class under a specific name using `java_import`:
```ruby …
```
> Only define static field constant when inner class collides

- .github/workflows/ci.yml
- .travis.yml
- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java
- pom.rb
- pom.xml
- spec/java_integration/fixtures/JavaFields.java
- test/jruby/test_higher_javasupport.rb
This PR will fix issues preventing some of our test suites from passing on Java 11, in order to help move toward full compatibility in the presence of Java modules.
This PR is based on 9.3 but most fixes should be mergeable to 9.2, and we may want to consider some or all of them for 9.2.12.
> Fixes to improve Java 11 testing

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java
This cherry-picks the fix for #6287 for 9.2.12.
> Do not bind methods from classes that are not exported

- .travis.yml
- bin/.dev_mode.java_opts
- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
- core/src/main/java/org/jruby/ext/socket/RubyTCPServer.java
- core/src/main/java/org/jruby/ext/socket/RubyUDPSocket.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- rakelib/test.rake
This PR makes a few changes to our Travis CI runs:
* Modify the "int" builds to encourage a full build for code called twice, using threshold=1 and jit.background=false.
* Remove "fullint" builds from JRuby and MRI suites.
* Add indy flag to a few JDK11 builds.
* Duplicate some of the JDK11 builds for JDK14. These builds should be kept up with latest OpenJDK release (so move to 15 this fall).
> Reconfigure some CI builds and add JDK14

- spec/jruby.mspec
- spec/tags/ruby/security/cve_2011_4815_tags.txt
- spec/tags/ruby/security/cve_2017_17742_tags.txt
- spec/tags/ruby/security/cve_2018_16396_tags.txt
- spec/tags/ruby/security/cve_2018_8778_tags.txt
* Inherit from the default MSpec configuration
* Run security specs
[`security/` specs](https://github.com/ruby/spec/commits/master/security) exist since a while in ruby/spec but it seems JRuby didn't run them in CI yet.
> Run security specs

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyFloat.java
- core/src/main/java/org/jruby/runtime/Helpers.java
This PR makes changes to RubyFixnum, RubyBignum, and RubyFloat hashing to incorporate the per-runtime random seed, in an effort to mimic CRuby's fixes for CVE-2011-4815.
This CVE was part of a flurry of "hashDOS" fixes that happened in the early 2010s to address poor hash use by application frameworks like Rails. Because untrusted data from web requests was blindly used for internal hashing, these frameworks could be DOS'ed by predicting the hashes of strings and other data and tricking Ruby into putting all elements in the same linear-scanned hash box.
The change here roughly mimics the CRuby logic for combining a random seed with the 64-bit long representation of these core numeric types, which in turn propagates that randomness to the composite types like Complex and Rational.
We may …
> Mimic CRuby's numeric hashing

- core/src/main/java/org/jruby/util/Pack.java
This corrects the error raised for the case where the unpack spec
requests a size that's outside the string, which relates to
CVE-2018-8778.
The other two cases that raised the ArgumentError for "outside of
string" appear to be correct, since making them raise RangeError
causes spec failures.
This addresses a security spec failure as shown in #6304.
> Raise RangeError for out of bounds unpack_at

- lib/pom.rb
- lib/pom.xml
This updates our shipped webrick to 1.6.0.
See #6304 for two security spec failures that this addresses.
There seems to be no other released version of webrick that has all the relevant CVE fixes. The versions shipped with CRuby do not correspond to any released version of webrick.
> Update WEBrick to 1.6.0

- core/src/main/java/org/jruby/runtime/load/LibrarySearcher.java
This allows us to propagate IOException rather than wrongly
interpreting it as an error caused by the load of the file itself.
It still gets wrapped in a LoadError, but at least it does not
provide a misleading message.
Relates to #4194.
> Do the read of the full file contents separately

- core/src/main/java/org/jruby/ir/instructions/ClassSuperInstr.java
- core/src/main/java/org/jruby/ir/instructions/InstanceSuperInstr.java
- core/src/main/java/org/jruby/ir/instructions/UnresolvedSuperInstr.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/InvocationCompiler.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/ir/targets/indy/ClassSuperIterInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/indy/IndyInvocationCompiler.java
- core/src/main/java/org/jruby/ir/targets/indy/InstanceSuperIterInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/indy/SuperInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/indy/UnresolvedSuperIterInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/simple/NormalInvocationCompiler.java
- spec/ruby/language/break_spec.rb
Fix for #4695. See example case there (updated to work properly in comments).
Specs included. I put them in break specs because this is more testing behavior of break than of super.
> Mark literal blocks escaped when passed through a super call

- .travis.yml
- Gemfile
- azure-pipelines.yml
- test/pom.rb
Something changed on rubygems.org that's causing the mavengem plugin to produce "marshal data too short" errors. While we investigate, remove rspec from -Pbootstrap mavengems and instead use bundler to install it in CI.
See https://github.com/torquebox/jruby-maven-plugins/issues/107
> Use Gemfile to install rspec for now

- core/src/main/java/org/jruby/Ruby.java
On some platforms, the expected BindException messages may differ,
so we need to fall back to the regexp match to make sure we do not
raise a SystemCallError.
Fixes #6322
> Fall back on old regexp BindException mapping

- core/src/main/java/org/jruby/ext/ffi/jffi/AllocatedNativeMemoryIO.java
This appears to be long-broken logic for setting autorelease to false, since the only value that will change the unmanaged bit is passing autorelease = true. The change here allows toggling both ways.
This may not have been seen before because this version of MemoryIO is only used when the requested size is greater than 256 bytes, and typically structs are smaller than that. In #6284, as well as #6310 and sass/sassc-ruby#208, we have reports of a double free, and sassc itself uses autorelease on a potentially large value here:
https://github.com/sass/sassc-ruby/blob/4bd764f568ad312a78181d7a3187f3715388e33e/lib/sassc/native.rb#L54-L58
> Allow false autorelease to set unmanaged = true

- core/src/main/java/org/jruby/RubyIO.java
On target streams that may do partial reads, the logic here fails
to write all content read from the source stream. The return value
of Channel.write is never checked, but the total bytes written is
incremented, resulting in silently losing data.
The patch loops until all bytes have been written to the output
channel after each read.
CRuby does similar logic. We may need to add additional blocking
write or thread event checks here, in case the target stream
blocks during the write loop, but that will require the different
`transfer` paths to be expanded to support nonblocking IO
channels.
Fixes #6078
> [fix][backport] Ensure copy_stream write sends all bytes read

- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/runtime/DynamicScope.java
- rakelib/rubyspec.rake
In the logic to look for a valid return target, we find a lambda, via `IRRuntimeHelpers.initiateNonLocalReturn` calling `getContainingLambda`. However when we later try to detect if the return jump should propagate as a LocalJumpError (because its target scope is no longer active) we do not do this same search for a lambda (see `IRRuntimeHelpers.checkForLJE`). This inconsistency causes the errors from #6350, because we incorrectly detect the target as the lambda, but do the detection against its parent scope and raise an IRReturnJump with an improper target scope. This jump then bubbles all the way off the stack and never becomes a LocalJumpError.
In CRuby, when the lambda becomes inactive, the return target moves to the containing return target scope. This means a given return can …
> Consider both "argument scope" and lambda as return jump target

- test/mri/excludes/JSONGeneratorTest.rb
- test/mri/excludes/JSONParserTest.rb
- test/mri/excludes/TC_JSON.rb
- test/mri/excludes/TC_JSONEncoding.rb
- test/mri/excludes/TC_JSONGenerate.rb
- test/mri/excludes/TC_JSONUnicode.rb
These seem to have fixed in JRuby 9.2.8.0 .
> Tag off remaining json failures.

- core/src/main/java/org/jruby/util/StringSupport.java
- test/mri/excludes/TestM17N.rb
Ported from MRI 2.3.
See [https://github.com/ruby/ruby/commit/9d502cf9a44d3934742d076f184574ef5b89702a#diff-7a2f2c7dfe0bf61d38272aeaf68ac768]().
> Fix test_greek_capital_gap failure.

- core/src/main/java/org/jruby/RubyRegexp.java
- test/mri/excludes/TestUTF16.rb
This fixes failling [TestUTF16#test_regexp_union](https://github.com/jruby/jruby/blob/master/test/mri/ruby/enc/test_utf16.rb#L275-L277) .
> Fix failling TestUTF16#test_regexp_union

- test/mri/excludes/TestNetHTTP.rb
- test/mri/excludes/TestNetHTTPLocalBind.rb
- test/mri/excludes/TestNetHTTP_v1_2_chunked.rb
These seem to have fixed in jruby 9.3.0.0-SNAPSHOT.
> [test] Tag off remaining http failures.
