- .gitignore
- core/src/main/java/org/jruby/truffle/nodes/control/AndNode.java
Use full condition profiling including counters that inject probabilities for AndNode.
> Introduce condition profiling for AndNode.

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- spec/regression/GH-1695_bigdecimal_and_rational_multiplication_rounds_the_rational_number_spec.rb
This commit fixes #1695 on master. Change the rspec file name is related to #2174. 
@headius Please also refer to #2011.
> Fix GH-1695 on master

- core/src/main/java/org/jruby/RubyEnumerator.java
I think only Enumerator#feed is missing now, however I am raising PR for these two methods in case I don't finish the implementation of it by Monday. (preview release)
> Implemented Enumerator#peek_values and Enumerator#next_values

- core/src/main/java/org/jruby/runtime/Signature.java
Fixes #2518, now if have a required keyword argument we will add +1 to required arity.
> Fixed arity require in case of required keyword arguments

- lib/ruby/stdlib/win32/registry.rb
This solved https://github.com/jruby/jruby/issues/2500.
> Modified the make_wstr method so that it appends a null character.

- core/src/main/java/org/jruby/RubyFileStat.java
* Fix File::Stat#struct when uninitialized
* Make other methods fail unless initialized
> Fix uninitialized usage of File::Stat on jruby-1_7

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerator.java
Fixes #2553, now size works as intended.
> Fix the bug with size with each_slice without block

- core/src/main/java/org/jruby/ast/ArgsNode.java
- core/src/main/java/org/jruby/ast/MethodDefNode.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
Fixes #2480 and #2512 with RubyMethod by taking account of required kwargs.
> Fixed arity issue with RubyMethod

- core/src/main/java/org/jruby/ast/ArgsNode.java
- core/src/main/java/org/jruby/ast/MethodDefNode.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
Reverts jruby/jruby#2584.  This broke some rubyspec specs.
> Revert "Fixed arity issue with RubyMethod"

- core/src/main/java/org/jruby/ir/IRBuilder.java
Fixes the RubySpec failure with #2584
> Fixed the errors with RubySpec 

- truffle/src/main/java/org/jruby/truffle/nodes/RubyCallNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/CachedBooleanDispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/CachedBoxedDispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/CachedBoxedMethodMissingDispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/CachedBoxedSymbolDispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/CachedUnboxedDispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/DispatchHeadNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/DispatchNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/dispatch/UncachedDispatchNode.java
> [Truffle] Fix indentation

- test/mri/excludes/TestFileUtils.rb
There seems to be no issues with the `FileUtils` tests.
> Remove FileUtils's test exclusions

- spec/truffle/tags/core/bignum/to_s_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/BignumNodes.java
Tried to follow patterns in Fixnum. The core spec builds successfully.
> [Truffle] Implemented Bignum#to_s when given a base

- spec/truffle/tags/core/bignum/bit_length_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/BignumNodes.java
Using the BigInteger.bitLength appears to work for this.
> [Truffle] Implemented Bignum#bit_length

- truffle/src/main/java/org/jruby/truffle/translator/BodyTranslator.java
I think this fix could work for now ... fixes #2652
> [Truffle] Fixing a parse error in single character regex hex

- truffle/src/main/java/org/jruby/truffle/nodes/core/StringNodes.java
> [Truffle] Adding TruffleBoundary to fix Illegal recurion errors

- tool/truffle/run_each_core_dir.rb
- tool/truffle/run_each_spec.rb
@chrisseaton You asked me to add these before, just got to this now.
> [Truffle] Adding spec running scripts to tools.

- truffle/src/main/java/org/jruby/truffle/runtime/ModuleOperations.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/CoreLibrary.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/RubyBasicObject.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/RubyClass.java
@eregon I made the changes we discussed.  Any additional feedback would be great.
> [Truffle] Fixed class variable lookup from singleton classes by attaching their companion class to them.

- spec/truffle/tags/core/array/replace_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/coerce/ToAryNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/ArrayNodes.java
@nirvdrum @chrisseaton Is this correct place to use a CreateCast? If not, why not?
Also trying to implement ToAryNode here.
> [Truffle] Trying to add #to_ary to Array#replace

- spec/truffle/tags/core/array/delete_at_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/ArrayNodes.java
Please review because I am not too familiar with contains and branch profile.
Maybe the profiles are not needed here?
> [Truffle] Returning nil for out of range Array#delete_at

- core/src/main/java/org/jruby/util/Pack.java
- test/externals/ruby1.9/excludes/TestBase64.rb
- test/test_base64_strangeness.rb
apparently the respective tests were excluded.
@headius could have a look - there is a lot of "duplication" but did not know how to avoid it. if this patch is OK I will also merge it to master.
> implements strict base64 encoding

- truffle/src/main/java/org/jruby/truffle/nodes/methods/MarkerNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/methods/arguments/OptionalKeywordArgMissingNode.java
- truffle/src/main/java/org/jruby/truffle/nodes/methods/arguments/UnknownArgumentErrorNode.java
As requested by @chrisseaton. Ping @matthias-springer
> Add missing copyright headers [ci skip]

- spec/truffle/tags/core/array/zip_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/ArrayGuards.java
- truffle/src/main/java/org/jruby/truffle/nodes/core/ArrayNodes.java
- truffle/src/main/ruby/core/rubinius/common/array.rb
This is about 110% over several `jt bench compare topaz-neural-net` runs.
> [Truffle] Updating Array#zip to handle more specs in array.rb

- truffle/src/main/java/org/jruby/truffle/nodes/core/FixnumNodes.java
> [Truffle] Adding overflow specializations for Fixnum#abs.

- truffle/src/main/java/org/jruby/truffle/nodes/core/RegexpNodes.java
- truffle/src/main/ruby/core/rubinius/common/regexp.rb
Is there a case where this is true?
> [Truffle] Move Regexp#=== to regexp.rb.

- tool/jt.rb
This is just an idea to add a command to run mri tests.
The big args array was derived from https://travis-ci.org/jruby/jruby/jobs/57843253
> [Truffle] Add jt test mri command.

- truffle/src/main/java/org/jruby/truffle/runtime/DebugOperations.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/RubyBasicObject.java
@chrisseaton @nirvdrum What do you think?
Sounds very expensive?
The parent is needed otherwise replace cannot work correctly.
One alternative I see is to have a uber DebugNode stored in RubyContext with all subnodes we need. Of course that's profile pollution, but is it worse than duplicating logic and doing all these instanceof?
> [Truffle] On demand freeze node

- core/src/main/java/org/jruby/RubyInstanceConfig.java
- core/src/main/java/org/jruby/util/URLResource.java
This is to support Warbler's runnable feature
> Added uri:classloader handling to RubyInstanceConfig.getScriptSource. 

- lib/ruby/stdlib/io/linux_console.rb
Adding ppc64 as supported platform for tty.
> Enabling tty for powerpc64

- spec/truffle/tags/core/thread/new_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/ThreadNodes.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/RubyThread.java
> Revert "[Truffle] Allow to pass arguments to Thread.new"

- core/src/main/java/org/jruby/util/TypeConverter.java
> Issue #2924

- core/src/main/java/org/jruby/RubyComparable.java
> add recursion guard in Comparable.

- core/src/main/java/org/jruby/util/io/PopenExecutor.java
This addresses https://github.com/jruby/jruby/issues/3054.
> Add incrementor back PopenExecutor to prevent infinite loop.

- core/src/main/java/org/jruby/RubyDir.java
> Added uri to path when using file protocol to chdir

- lib/ruby/stdlib/date.rb
- spec/ruby/library/date/add_month_spec.rb
- spec/ruby/library/date/next_year_spec.rb
- spec/ruby/library/date/prev_year_spec.rb
From #2867, with commits rebased to avoid too much conflicts.
> Date next year difference

- core/src/main/java/org/jruby/RubyRange.java
- spec/ruby/core/range/max_spec.rb
> Fixing ClassCastException reported in issue #3118

- core/src/main/java/org/jruby/util/ConvertBytes.java
#1258 - java implementation + optimalizations
Performance chart
> bignum speedup

- core/src/main/java/org/jruby/ir/persistence/IRWriterAnalyzer.java
- core/src/main/java/org/jruby/ir/persistence/IRWriterStream.java
s/IRWriterAnalzer/IRWriterAnalyzer/
> minor typo

- core/src/main/java/org/jruby/ext/socket/SocketUtils.java
- spec/ruby/library/socket/shared/pack_sockaddr.rb
Ensure compatability with MRI Ruby
closes #3156
> treat port nil as 0 for pack_sockaddr_in

- spec/compiler/general_spec.rb
Just a few minor tweaks/improvements.
> Spec improvements

- spec/ruby/core/objectspace/each_object_spec.rb
- spec/ruby/core/objectspace/fixtures.rb
- spec/tags/ruby/core/objectspace/each_object_tags.txt
- truffle/src/main/java/org/jruby/truffle/nodes/core/ObjectSpaceNodes.java
- truffle/src/main/java/org/jruby/truffle/runtime/object/ObjectGraph.java
- truffle/src/main/java/org/jruby/truffle/runtime/subsystems/AtExitManager.java
- truffle/src/main/java/org/jruby/truffle/runtime/subsystems/ObjectSpaceManager.java
- truffle/src/main/ruby/core/thread.rb
> ObjectSpace specs

- core/src/main/java/org/jruby/Main.java
- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/util/cli/Options.java
- test/truffle/memory/minimum-heap.rb
- test/truffle/memory/total-allocation.rb
- test/truffle/startup/count-classes.rb
- test/truffle/startup/jruby-timed
- test/truffle/startup/process-times.rb
- test/truffle/subjects/client.rb
- test/truffle/subjects/server.rb
- truffle/src/main/java/org/jruby/truffle/runtime/core/CoreLibrary.java
@pitr-ch @eregon @nirvdrum please review
> [Truffle] Add tools for measuring startup time and memory consumption.

- truffle/src/main/java/org/jruby/truffle/nodes/core/TrufflePrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/nodes/rubinius/AtomicReferenceNodes.java
- truffle/src/main/java/org/jruby/truffle/om/dsl/api/Layout.java
- truffle/src/main/java/org/jruby/truffle/om/dsl/processor/layout/LayoutGenerator.java
- truffle/src/main/java/org/jruby/truffle/om/dsl/processor/layout/LayoutParser.java
- truffle/src/main/java/org/jruby/truffle/om/dsl/processor/layout/model/NameUtils.java
- truffle/src/main/java/org/jruby/truffle/om/dsl/processor/layout/model/PropertyBuilder.java
- truffle/src/main/java/org/jruby/truffle/om/dsl/processor/layout/model/PropertyModel.java
- truffle/src/main/java/org/jruby/truffle/runtime/core/CoreLibrary.java
- truffle/src/main/java/org/jruby/truffle/runtime/layouts/Layouts.java
- truffle/src/main/java/org/jruby/truffle/runtime/layouts/rubinius/AtomicReferenceLayout.java
- truffle/src/main/ruby/core.rb
- truffle/src/main/ruby/core/rubinius/bootstrap/atomic.rb
- truffle/src/main/ruby/core/shims.rb
Adding to support c-r synchronisation layer
> [Truffle] add Rubinius memory barrier and AtomicReference

- core/src/main/java/org/jruby/RubyEnumerable.java
Rubyspecs:
- https://github.com/jruby/jruby/blob/ruby-2.3/spec/ruby/core/enumerable/grep_v_spec.rb
> [Ruby-2.3] - Implements Enumerable#grep_v

- core/src/main/java/org/jruby/RubyNumeric.java
RubySpecs:
- https://github.com/jruby/jruby/blob/ruby-2.3/spec/ruby/core/numeric/negative_spec.rb
- https://github.com/jruby/jruby/blob/ruby-2.3/spec/ruby/core/numeric/positive_spec.rb
> [Ruby-2.3] - Implements Numeric#positive? and Numeric#negative?

- core/src/main/java/org/jruby/RubyThread.java
Rubyspecs:
https://github.com/ruby/rubyspec/pull/165
> [Ruby-2.3] - Implements Thread#name and Thread#name=

- core/src/main/java/org/jruby/ext/socket/RubyUNIXSocket.java
> Proper support for UNIXSocket.for_fd

- .travis.yml
- test/pom.rb
- tool/jt.rb
- tool/travis_runner.sh
Don't merge - just here for the CI
> [Truffle] Reduce Maven cruft

- test/truffle/integration/pack-real-usage/pack-real-usage.rb
- truffle/src/main/java/org/jruby/truffle/core/StringOperations.java
- truffle/src/main/java/org/jruby/truffle/core/array/ArrayNodes.java
- truffle/src/main/java/org/jruby/truffle/core/format/nodes/PackNode.java
- truffle/src/main/java/org/jruby/truffle/core/format/nodes/PackRootNode.java
- truffle/src/main/java/org/jruby/truffle/core/format/nodes/UnpackRootNode.java
- truffle/src/main/java/org/jruby/truffle/core/format/nodes/write/WriteUTF8CharacterNode.java
- truffle/src/main/java/org/jruby/truffle/core/format/runtime/PackFrameDescriptor.java
- truffle/src/main/java/org/jruby/truffle/core/format/runtime/PackResult.java
See comment in https://github.com/jruby/jruby/pull/3630/files#diff-2e927e2da41351366400bb91b3d92c2bR2492
> Truffle pack length and range

- .travis.yml
- lib/ruby/truffle/jruby+truffle/gem_ci/activesupport.rb
- lib/ruby/truffle/jruby+truffle/gem_ci/default.rb
- lib/ruby/truffle/jruby+truffle/gem_ci/travis.txt
- lib/ruby/truffle/jruby+truffle/gem_configurations/activesupport.yaml
- lib/ruby/truffle/jruby+truffle/lib/runner.rb
- tool/travis_runner.sh
There is a new `ci` command in j+tr tool.
> [Truffle] CI for gems

- core/src/main/java/org/jruby/RubyBignum.java
> Adds method #bitLength to Bignum

- core/src/main/java/org/jruby/internal/runtime/methods/InvokeDynamicMethodFactory.java
- core/src/main/java/org/jruby/ir/targets/Bootstrap.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
- core/src/main/java/org/jruby/runtime/invokedynamic/InvocationLinker.java
> Ensure native methods called by indy get frame if requested.

- core/src/main/java/org/jruby/util/io/EncodingUtils.java
In prep for a String-based transcode to address the test in #3877.
> Refactor transcodeLoop into ruby and non-ruby parts.

- core/src/main/java/org/jruby/RubyString.java
- test/mri/excludes/TestString.rb
essentially backporting MRI changes
> fix four additional MRI string tests

- spec/truffle/tags/core/array/hash_tags.txt
- truffle/src/main/java/org/jruby/truffle/core/array/ArrayNodes.java
- truffle/src/main/ruby/core/array.rb
Does this need `@TruffleBoundary`?
> [Truffle] Implement Array#hash using murmurhash

- spec/truffle/tags/core/exception/system_call_error_tags.txt
- truffle/src/main/java/org/jruby/truffle/Layouts.java
- truffle/src/main/java/org/jruby/truffle/core/CoreLibrary.java
- truffle/src/main/java/org/jruby/truffle/core/ProcessNodes.java
- truffle/src/main/java/org/jruby/truffle/core/exception/CoreExceptions.java
- truffle/src/main/java/org/jruby/truffle/core/exception/ExceptionNodes.java
- truffle/src/main/java/org/jruby/truffle/core/exception/ExceptionOperations.java
- truffle/src/main/java/org/jruby/truffle/core/exception/SystemCallErrorLayout.java
- truffle/src/main/java/org/jruby/truffle/core/exception/SystemCallErrorNodes.java
- truffle/src/main/java/org/jruby/truffle/core/rubinius/IOBufferPrimitiveNodes.java
- truffle/src/main/java/org/jruby/truffle/language/parser/jruby/BodyTranslator.java
- truffle/src/main/java/org/jruby/truffle/platform/posix/TrufflePosixHandler.java
- truffle/src/main/ruby/core/exception.rb
Please review the new layout usage here.
> [Truffle] Add SystemCallError Layout for errno field

- tool/truffle/callgraph2html.rb
This PR removes an unnecessary line of code and some trailing whitespace.
> Remove duplicated line.

- test/truffle/cexts/ruby-argon2/test.rb
- tool/jt.rb
Depends on https://github.com/jruby/jruby-truffle-gem-test-pack/pull/1
> [Truffle] Add CExt test for ruby-argon2

- COPYING
- Rakefile
- rakelib/helpers.rb
- rakelib/rubyspec.rake
- spec/READ_ME_FIRST.txt
Please tell if something should be fixed instead of deletion.
> Remove dead rake tasks

- appveyor.yml
This PR updates the maven download and caching options
see also: #4075
> fix up appveyor.yml

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
> backport BigDecimal .to_r for #3728

- core/src/main/java/org/jruby/RubyInstanceConfig.java
- core/src/test/java/org/jruby/test/TestRubyInstanceConfig.java
- core/src/test/resources/test_dir/test_script.rb
Backport #4100 from 9000
Tests and fixes #3901 for 1.7
> Backport "Change script file restriction" from 9000

- pom.rb
- pom.xml
This will prevent issues like #4135 from happening in the future.
> Unconditionally enable maven enforcer in release profile.

- spec/truffle/tags/core/module/deprecate_constant_tags.txt
- truffle/src/main/java/org/jruby/truffle/core/module/ModuleFields.java
- truffle/src/main/java/org/jruby/truffle/core/module/ModuleNodes.java
- truffle/src/main/java/org/jruby/truffle/language/RubyConstant.java
- truffle/src/main/java/org/jruby/truffle/language/WarnNode.java
- truffle/src/main/java/org/jruby/truffle/language/constants/LookupConstantNode.java
- truffle/src/main/java/org/jruby/truffle/language/constants/LookupConstantWithLexicalScopeNode.java
- truffle/src/main/java/org/jruby/truffle/language/objects/LookupForExistingModuleNode.java
I will add some questions in the diff.
> [Truffle] Module#deprecate_constant

- .travis.yml
- lib/ruby/truffle/truffle/bundler-workarounds.rb
- tool/jt.rb
- truffle/src/main/java/org/jruby/truffle/core/exception/CoreExceptions.java
- truffle/src/main/java/org/jruby/truffle/core/kernel/KernelNodes.java
So far this works for `bundle install` and `bundle exec rake` for the gem mentioned in the changes: `hike`.  I'm still working on getting this working with an example gem that has a native build.
Please let me know if you have any feedback.
> [Truffle] Add bundler workarounds files, jt test bundle command

- core/src/main/java/org/jruby/management/Runtime.java
I have been spending a lot of time reading the jruby source code and I have no idea of how I can contribute so I thought I would start with the most simple contribution I could. I have added doco for one method. Not sure if this is any value for jruby or even if you accept pull requests this small however why not give it a go.
If this is of value I can start adding more comments as I attempt to understand the code base. Also tell me if my understanding of this method is correct. I can adjust the comment if need me. Thanks.
> Updated doc for dumpThreads method in Runtime

- core/src/main/java/org/jruby/RubyBasicObject.java
- spec/ruby/core/kernel/clone_spec.rb
> Fix clone hierarchy

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyInstanceConfig.java
- core/src/main/java/org/jruby/compiler/JITCompiler.java
- core/src/main/java/org/jruby/util/SecurityHelper.java
- core/src/main/java/org/jruby/util/cli/Options.java
- lib/pom.rb
- lib/pom.xml
> upgrade jruby-openssl to 0.9.18

- core/src/main/java/org/jruby/RubyFloat.java
> Add optional precision for Float#floor

- spec/truffle/specs/truffle/ropes/complex_structure_spec.rb
- truffle/src/main/java/org/jruby/truffle/core/rope/RopeOperations.java
- truffle/src/main/java/org/jruby/truffle/core/rope/TruffleRopesNodes.java
> [Truffle] fix RopeOperations.flattenBytes

- spec/truffle/tags/language/predefined_tags.txt
- truffle/src/main/java/org/jruby/truffle/core/CoreLibrary.java
- truffle/src/main/java/org/jruby/truffle/parser/BodyTranslator.java
- truffle/src/main/ruby/core/process.rb
> [Truffle] Implement changing argv[0] on Linux

- spec/truffle/tags/language/constants_tags.txt
- tool/truffle/options.yml
- truffle/src/main/java/org/jruby/truffle/builtins/CoreMethodNodeManager.java
- truffle/src/main/java/org/jruby/truffle/core/kernel/KernelNodes.java
- truffle/src/main/java/org/jruby/truffle/core/module/ModuleNodes.java
- truffle/src/main/java/org/jruby/truffle/core/symbol/SymbolNodes.java
- truffle/src/main/java/org/jruby/truffle/language/LazyRubyRootNode.java
- truffle/src/main/java/org/jruby/truffle/language/constants/LookupConstantWithDynamicScopeNode.java
- truffle/src/main/java/org/jruby/truffle/language/constants/LookupConstantWithLexicalScopeNode.java
- truffle/src/main/java/org/jruby/truffle/language/constants/ReadConstantWithDynamicScopeNode.java
- truffle/src/main/java/org/jruby/truffle/language/loader/CodeLoader.java
- truffle/src/main/java/org/jruby/truffle/language/methods/DeclarationContext.java
- truffle/src/main/java/org/jruby/truffle/language/methods/InternalMethod.java
- truffle/src/main/java/org/jruby/truffle/language/methods/MethodDefinitionNode.java
- truffle/src/main/java/org/jruby/truffle/language/methods/ModuleBodyDefinitionNode.java
- truffle/src/main/java/org/jruby/truffle/language/methods/SharedMethodInfo.java
- truffle/src/main/java/org/jruby/truffle/language/objects/DynamicLexicalScopeNode.java
- truffle/src/main/java/org/jruby/truffle/language/objects/RunModuleDefinitionNode.java
- truffle/src/main/java/org/jruby/truffle/options/Options.java
- truffle/src/main/java/org/jruby/truffle/options/OptionsCatalog.java
- truffle/src/main/java/org/jruby/truffle/parser/BodyTranslator.java
- truffle/src/main/java/org/jruby/truffle/parser/ParseEnvironment.java
- truffle/src/main/java/org/jruby/truffle/parser/TranslatorDriver.java
- truffle/src/main/java/org/jruby/truffle/parser/TranslatorEnvironment.java
> [Truffle] Dynamic constant lookup

- core/src/main/java/org/jruby/RubyHash.java
It passes the TestHash#test_compact method of the MRI test.
> Implemented Hash#compact and Hash#compact!

- core/src/main/java/org/jruby/RubyHash.java
It passes the TestHash#test_transform_values and
TestHash#test_transform_values_bang methods of the MRI test.
> [ruby 2.4] Implemented Hash#transform_values(!)

- spec/truffle/tags/core/string/modulo_tags.txt
- truffle/src/main/java/org/jruby/truffle/core/format/printf/PrintfCompiler.java
- truffle/src/main/java/org/jruby/truffle/core/format/printf/PrintfSimpleParser.java
- truffle/src/main/java/org/jruby/truffle/core/kernel/KernelNodes.java
- truffle/src/main/java/org/jruby/truffle/language/globals/ReadGlobalVariableNode.java
- truffle/src/main/java/org/jruby/truffle/parser/BodyTranslator.java
> [Truffle] Sprintf check for too many args when $DEBUG is true

- core/src/main/java/org/jruby/util/Pack.java
- spec/jruby/base64_decode_spec.rb
This fixes #4028 for the master branch.
> fix Base64#decode64 behavior

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- spec/regression/JRUBY-4463_bigdecimal_marshal_roundtrip_spec.rb
> Fix #4463 Marshal load bigdecimal NaN fails

- core/pom.xml
> Update jnr-constants to 0.9.9 for 1.7.

- core/src/main/java/org/jruby/ext/tracepoint/TracePoint.java
- core/src/test/java/org/jruby/ext/tracepoint/TracePointTest.java
- core/src/test/resources/tracepoint_tests/event_test.rb
The current TracePoint implementation contains a small bug. The event will not dispatched correct. I fixed it and added a TestCase.
> Kullmann: Fix TracePoint nil event. Add test

- lib/ruby/stdlib/io/linux_console.rb
> Add native console support on AARCH64

- BUILDING.md
This PR changes the instructions in `BUILDING.md` to have Markdown that renders right on GitHub.
> BUILDING.md: Markdown formatting, copy-edits

- lib/pom.rb
- lib/pom.xml
this updates the bundler jruby-openssl gem
> upgrade jruby-openssl to 0.9.21

- core/src/main/java/org/jruby/RubyProcess.java
The file was previously messed up with mixed tabs and spaces, making it be quite hard to read on GitHub (which renders tabs as 8 spaces by default.) The rest of the file had spaces for indentation, so I assume this is the right fix.
> RubyProcess.java: fixed formatting

- COPYING
> Update rake's url

- core/src/main/java/org/jruby/ext/set/RubySet.java
- spec/ruby/core/set/case_equality_spec.rb
- spec/ruby/core/set/sortedset/case_equality_spec.rb
- test/mri/test_set.rb
tests cherry picked from https://github.com/ruby/ruby/commit/2aee703e7a29bcfc2095e40870f5a3c45cd96dd2.
Feature https://bugs.ruby-lang.org/issues/13801.
> Alias Set#=== to #include?

- core/src/main/java/org/jruby/RubyString.java
- test/mri/ruby/test_string.rb
For Ruby 2.5 support
https://bugs.ruby-lang.org/issues/13077
> String#-@ deduplicates unfrozen strings

- core/src/main/java/org/jruby/RubyString.java
- test/mri/ruby/test_string.rb
See https://bugs.ruby-lang.org/issues/13712
#4876
> Ruby 2.5: Support regex for String#start_with?

- core/src/main/java/org/jruby/RubyThread.java
https://bugs.ruby-lang.org/issues/13009
#4876 
Tests are already implemented in ``test/mri/ruby/test_thread.rb#test_thread_local_fetch"
> Implement fetch for Thread.current

- core/src/main/java/org/jruby/RubyComplex.java
test/mri/ruby/test_complex.rb#test_infinite_p and test/mri/ruby/test_complex.rb#test_infinite_p were failing. 
See in MRI
https://github.com/ruby/ruby/commit/65d7479920d1bc94a25dbd759bb573c7b88c9fe1
https://github.com/ruby/ruby/commit/241ba38d7007ca64a2e18b8422b18a9988eeab3e
> Fix Complex#finite? and Complex#infinite? failing tests

- core/src/main/java/org/jruby/RubyComplex.java
- core/src/main/java/org/jruby/RubyRational.java
Complex and Rational are always frozen now.
See https://github.com/ruby/ruby/commit/42c98194b37bf2c0b0f3f88f8530f46f55a6d55c in MRI.
> Freeze Complex and Rational

- core/src/main/java/org/jruby/ext/pathname/RubyPathname.java
- core/src/main/java/org/jruby/runtime/JavaSites.java
Hi folks,
I opened another PR to complete the work on https://github.com/jruby/jruby/pull/5095 since I can't push to that branch.
All Pathname tests should pass now.
/cc: https://github.com/jruby/jruby/issues/4876
Thanks,
> Add Pathname#glob

- core/src/main/java/org/jruby/RubyModule.java
> Clone frame and block before proceeding into class_exec logic.

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/ext/win32/resolv/Win32Resolv.java
- core/src/main/java/org/jruby/util/WindowsFFI.java
https://github.com/jruby/jruby/pull/5158
> WIP: resolv ffi prototype

- core/src/main/java/org/jruby/RubyDir.java
- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubyString.java
- spec/java_integration/addons/dir_spec.rb
- spec/java_integration/addons/file_spec.rb
- spec/java_integration/addons/io_spec.rb
> [ji] coercing Ruby File/Dir to Java File/Path

- core/src/main/java/org/jruby/RubyModule.java
- test/jruby/test_module.rb
resolves https://github.com/jruby/jruby/issues/5229
> dont mutate module names

- core/src/main/java/org/jruby/ext/zlib/JZlibInflate.java
> zlib inflate Fixes #5234

- BUILDING.md
Change the "make" to "Make" and added the links for the tools
> Changing building.md

- bin/jruby.bash
> fix duplicated file encoding

- core/src/main/java/org/jruby/RubyFile.java
This code was rewritten in #5075 to call `utimensat()` which takes nanosecond precision, but then falls back to calling `utimes()` which takes microsecond precision. Passing in microsecond values greater than 1,000,000 caused `utimes()` to fail with `Errno::EINVAL`. See #5261 for more details.
This fixes the issue by converting to microseconds before calling `utimes()`.
> Fix parameters to utimes() fallback call (fixes #5261)

- core/src/main/java/org/jruby/RubyEnumerable.java
- spec/tags/ruby/core/enumerable/all_tags.txt
- spec/tags/ruby/core/enumerable/any_tags.txt
- spec/tags/ruby/core/enumerable/none_tags.txt
- spec/tags/ruby/core/enumerable/one_tags.txt
Hi folks,
I noticed that some tests related to a feature that I introduced months ago were tagged as failing so I gave a shot to fix them.
Those tests should be passing now.
As usual, any feedback is more than welcome.
> Fix some failed tests for Enumerable#all?, #any?, #none? and #one?

- .mvn/extensions.xml
- core/pom.xml
- lib/pom.xml
- pom.rb
- pom.xml
+ use polyglot-maven 0.3.1
... jar_dependencies upgrade is due to JRuby (9.2) load_ext mechanism
https://github.com/jruby/jruby/issues/5233
> upgrade jar_dependencies to 0.4.0

- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/platform/Platform.java
https://github.com/jruby/jruby/issues/5331
> wsl workaround

- lib/pom.rb
- lib/pom.xml
@kares in case I do not get this merged today please feel free to merge - if CI says OK of course ;)
> upgrade mavengem extension

- core/src/main/java/org/jruby/RubyTime.java
- test/jruby/test_time.rb
... seems to resolve an old issue of JRuby's https://github.com/jruby/jruby/issues/1795
closes #1795
> [fix] do not parse zone for local + better dst calculation

- core/src/main/java/org/jruby/RubyRegexp.java
https://github.com/ruby/ruby/blob/ef69efef1da9a36d0953fdb0651faf881531781a/re.c#L1740
> missing return

- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/ffi/StructLayout.java
- core/src/main/java/org/jruby/util/RubyDateFormat.java
```
long ms = int * int + int;
```
the multiplication is evaluated using int arithmetic even if you expect long
> fix potential int overflow

- core/src/main/java/org/jruby/ext/date/RubyDate.java
> Use default sg ITALY with getChronology here.

- core/src/main/java/org/jruby/RubyArray.java
Resubmitting PR #5464 against the right branch ruby-2.6. /cc: @enebo
> Add Array#union

- lib/pom.rb
- lib/pom.xml
resolves SSL connection issue (on Java 11) among others
see GH-5374
> update jruby-openssl to 0.10.1

- core/src/main/java/org/jruby/runtime/opto/FailoverSwitchPointInvalidator.java
Instead of locking around updates to the switchpoint and failure
count, this patch replaces those fields with a stamped atomic
reference that can update both atomically.
Fixes #5525.
> Use atomics to reduce contention within failover invaldator.

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/IRClosure.java
- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/ir/instructions/RuntimeHelperCall.java
- core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java
- core/src/main/java/org/jruby/ir/persistence/IRReader.java
- core/src/main/java/org/jruby/ir/persistence/IRWriter.java
- core/src/main/java/org/jruby/ir/runtime/IRReturnJump.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/parser/StaticScope.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
- core/src/main/java/org/jruby/runtime/load/LoadService.java
- spec/ruby/language/return_spec.rb
My main commit explains most of the details of what changed.  See #5517 for more on what was broken.
> Fixes #5517 (returns in unexpected place)

- core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java
- core/src/main/ruby/jruby/kernel/rbconfig.rb
`DESTDIR` - which should be always empty on JRuby
could use some tests esp. for embedded cases and understanding why this came up at GH-5562
> adding RbConfig TOPDIR (and related)

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubySignal.java
- core/src/main/java/org/jruby/util/NoFunctionalitySignalFacade.java
- core/src/main/java/org/jruby/util/SignalFacade.java
- core/src/main/java/org/jruby/util/SunSignalFacade.java
Reverts jruby/jruby#5441
This was not ready to merge and I don't believe it had a green build (or at least my last comment says it still has failures). Reverting to do additional work before merging.
> Revert "Push signal traps and at_exit blocks to a common thread for exec."

- core/src/main/ruby/jruby/kernel/prelude.rb
resolves https://github.com/jruby/jruby/issues/5599
> pp should always be private (port from MRI 2.6)

- pom.rb
- pom.xml
This updates json so we can get the Fixnum/Bignum Ruby 2.5 fix for flori/json#361.
> Updage to json 2.2.0

- core/pom.rb
- core/pom.xml
> Update backport9 to 1.3

- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/IREvalScript.java
- core/src/main/java/org/jruby/ir/IRScope.java
- core/src/main/java/org/jruby/ir/IRScriptBody.java
- core/src/main/java/org/jruby/ir/IRVisitor.java
- core/src/main/java/org/jruby/ir/instructions/RunBeginBlockInstr.java
- core/src/main/java/org/jruby/ir/interpreter/Interpreter.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
May be a work in progress, but simple examples run fine right now.
Needs tests of root-level scripts with BEGIN.
Fixes #713.
> Run BEGIN blocks from JVM-compiled scripts.

- core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java
> RbConfigLibrary: Set COUTFLAG to "-o "

- core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java
> RbConfigLibrary: Set CCDLFLAGS to "-fPIC"

- core/src/main/java/org/jruby/util/io/EncodingUtils.java
A minor diff found while investigating #5681.
> Tweak the transcode loop to match MRI error behavior.

- core/src/main/java/org/jruby/ext/ffi/Platform.java
- core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java
- core/src/main/java/org/jruby/platform/Platform.java
Not sure if it's done correctly or I'm missing something, please let me know.
> Identify DragonFlyBSD as a platform

- core/src/main/java/org/jruby/RubyIO.java
- spec/tags/ruby/core/io/pread_tags.txt
- spec/tags/ruby/core/io/pwrite_tags.txt
- test/mri/ruby/test_io.rb
> Implement IO#pread and pwrite.

- pom.rb
- pom.xml
DateTimeZone data updated to version 2019b + few bug fixes
> update joda time to 2.10.3

- core/pom.rb
- core/pom.xml
- maven/jruby-complete/pom.rb
- pom.xml
> automatic-module-name

- core/src/main/java/org/jruby/Ruby.java
the synchronization of adding a new module (class) to the system,
has a considerable cost e.g. in threaded envs such as Rails
we simply avoid the sync cost by using a concurrent collection
resolves GH-5901
> [fix] avoid locking on class/module creation

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/specialized/RubyArrayOneObject.java
- core/src/main/java/org/jruby/specialized/RubyArraySpecialized.java
- core/src/main/java/org/jruby/specialized/RubyArrayTwoObject.java
fixes https://github.com/jruby/jruby/issues/5929
> dupImpl specializations

- core/src/main/java/org/jruby/javasupport/Java.java
- test/jruby/test_higher_javasupport.rb
> fix class nesting #5925

- core/pom.rb
- core/pom.xml
- pom.rb
- pom.xml
joda-time wasn't too out of date, but we had not updated timezones since 2013. 😳
> Update joda-time and joda-timezones to 2019c

- pom.xml
Fixes  #5991
Signed-off-by: Raymond Augé <rotty3000@apache.org>
> update maven-bundle-plugin and bndlib to latest

- pom.rb
- pom.xml
side note: it fixes the javase version but there are still a lot of warning so some refinements can be nice later
> ensure javase version in osgi meta is 8 and not 9

- core/src/main/java/org/jruby/RubyEncoding.java
> Add filesystem and internal encoding names

- core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
- test/mri/ruby/test_rational.rb
https://github.com/jruby/jruby/issues/6025
> [fix] SyntaxError rational overflow

- test/mri/ruby/test_rational.rb
https://github.com/ruby/spec/pull/750
> revert rational test

- core/src/main/java/org/jruby/ir/IRBuilder.java
- spec/ruby/language/predefined_spec.rb
fixes https://github.com/jruby/jruby/issues/6015
> [fix] restore $! on non-local return from rescue

- .gitignore
- core/pom.rb
- core/pom.xml
> make jruby-core-source jar has no absolute path from home dir

- core/src/main/java/org/jruby/java/proxies/JavaProxy.java
- core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java
This search logic was only being used when binding all the methods for a Java class in Ruby space, while the one-off accessors like `java_method` went through different logic. The latter logic has never been updated to work properly under the new module regime, which led to bugs like #5894 that would attempt to invoke private or otherwise inaccessible methods rather than continuing to search for a public version.
This patch opens up the accessible-only method search from MethodGatherer so it can be reused for the one-off forms.
Fixes #5894
> Generify and reuse accessible method search

- core/src/main/java/org/jruby/ext/ffi/Util.java
fewer lines of code + a little bit faster
> optimize roundUpToPowerOfTwo

- lib/pom.rb
- lib/pom.xml
release notes: https://github.com/jruby/jruby-openssl/releases/tag/v0.10.3
> update jruby-openssl to 0.10.4

- .travis.yml
- maven/jruby/src/it/GH-6081-dependency-convergence/pom.xml
Reported violation, when built against one commit before 9.2.10.0: https://travis-ci.org/pzygielo/jruby/builds/652664828#L1142
Job failed: https://travis-ci.org/pzygielo/jruby/builds/652664828#L1219
but overall build result was: success.
This PR is targeted at master, where convergence is observed now.
> Add IT for issue 6081

- core/src/main/java/org/jruby/RubyEnumerable.java
- test/jruby/test_enumerator.rb
> [fix] Enumerable#any? does not require an arg

- core/src/main/java/org/jruby/util/Sprintf.java
- core/src/main/java/org/jruby/util/StringSupport.java
- spec/ruby/core/kernel/shared/sprintf.rb
See #6137 for the original bug report. This PR includes the change proposed there along with some new doco for `nth` and a spec.
> Subtract begin offset for partial substring in sprintf 's'

- core/src/main/java/org/jruby/RubyBasicObject.java
- test/jruby/test_higher_javasupport.rb
~~needs a proper test~~, resolves https://github.com/jruby/jruby/issues/6160
> [fix][ji] handle concurrent proxy iface impl init

- core/src/main/java/org/jruby/util/IdUtil.java
> missing break

- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/util/Dir.java
- test/mri/excludes/TestFnmatch.rb
This PR will have a few commits to re-port the fnmatch logic from CRuby. Will fix #6193 and others.
> Update fnmatch implementation

- core/src/main/java/org/jruby/util/RubyDateFormatter.java
This fixes #6169 and I believe matches CRuby for the "special" formats handled here, but I am unsure if this is the right way to fix it. CRuby has something similar in its complicated strftime code, but they do not have a separate parser for date formats like we do.
@enebo I feel like this is something that should be done in the strftime parser; it should see that the next token is going to want space padding and insert the FORMAT_OUTPUT token with appropriate flags. What do you think?
> Default to space padding for "special" formats

- core/src/main/java/org/jruby/util/ResourceException.java
- core/src/main/java/org/jruby/util/URLResource.java
- core/src/test/java/org/jruby/util/URLResourceTest.java
> Raise proper error for missing URLResource target

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/exceptions/ReadPartialBufferOverflowException.java
- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
- core/src/main/java/org/jruby/ext/timeout/Timeout.java
- core/src/main/java/org/jruby/ir/instructions/UnresolvedSuperInstr.java
- core/src/main/java/org/jruby/util/IOChannel.java
- spec/ruby/library/timeout/timeout_spec.rb
These are small fixes to address failing tests in WEBrick, as reported in #6171.
> Fixes to get WEBrick tests greener

- core/src/main/java/org/jruby/embed/ScriptingContainer.java
- maven/jruby-jars/Mavenfile
> Fix jruby jars deploy

- core/src/main/java/org/jruby/compiler/util/HandleFactory.java
- core/src/main/java/org/jruby/internal/runtime/methods/DumpingInvocationMethodFactory.java
- core/src/main/java/org/jruby/java/codegen/RealClassGenerator.java
- core/src/main/java/org/jruby/runtime/scope/DynamicScopeGenerator.java
fixes a leak in ```DynamicScopeGenerator.java``` + refactor
> FileOutputStream's cleanup

- core/src/main/java/org/jruby/compiler/FullBuildTask.java
- core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java
- core/src/main/java/org/jruby/ir/passes/CompilerPass.java
- core/src/main/java/org/jruby/ir/persistence/IRDumper.java
- core/src/main/java/org/jruby/util/cli/Options.java
Possibly best reviewed by looking at the individual commits.
> Some fixes, tweaks, and new tools for working with IR

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyIO.java
It never did anything before, but passed tests because you can't tell if it actually does anything. Now it will do things, but you still can't tell if it does anything.
> Implement IO#advise

- lib/pom.rb
- lib/pom.xml
This pulls in SnakeYAML 1.26 and fixes #6320.
> Update Psych to 3.2.0

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/ir/targets/indy/YieldSite.java
- core/src/main/java/org/jruby/runtime/callsite/CachingCallSite.java
- core/src/main/java/org/jruby/specialized/RubyArrayOneObject.java
- core/src/main/java/org/jruby/specialized/RubyArrayTwoObject.java
- spec/regression/GH-3155_array_map_with_mutation_spec.rb
> Miscellaneous small optimizations

- core/src/main/java/org/jruby/ext/ffi/AbstractMemory.java
implements https://github.com/ffi/ffi/commit/895482b21167c4a5db36e12ac3cbdeafb2bd1144
> [ffi] read_string should not throw an error on length 0

- core/src/main/java/org/jruby/ext/ffi/StructLayout.java
implements https://github.com/ffi/ffi/commit/5ed3af193ecd8cfa2146f758a5a87271df0a019c
> [ffi] add bounds checks for writing to an inline char[]

- core/src/main/java/org/jruby/ext/ffi/MemoryUtil.java
implements https://github.com/ffi/ffi/issues/305
> [ffi] Do NULL pointer check only when array length > 0

- core/src/main/java/org/jruby/ext/socket/RubySocket.java
depends on https://github.com/jnr/jnr-constants/pull/71
> move socket message to constants

- core/src/main/java/org/jruby/ext/date/RubyDate.java
- test/jruby/test_date.rb
fixes https://github.com/jruby/jruby/issues/6386
> restore $! on date comparisons

- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
- test/jruby/test_socket.rb
fixes: https://github.com/jruby/jruby/issues/6399
> basic TCP_INFO support

- core/src/main/java/org/jruby/ext/ffi/Platform.java
https://github.com/ffi/ffi/issues/824
@eregon thanks for the suggestion!
> [ffi] fix libc name on Linux

- core/src/main/java/org/jruby/RubyFileStat.java
- test/jruby/test_dir.rb
fixes: https://github.com/jruby/jruby/issues/6397
> handle winstat errors

- lib/ruby/stdlib/jruby/compiler.rb
- test/jruby/compiler/test_jrubyc.rb
> Fixes #6404 jrubyc: mangled ("--target") path on Windows

- core/src/main/java/org/jruby/RubyFileStat.java
- test/jruby/test_file.rb
https://github.com/jruby/jruby/issues/6458
https://github.com/jnr/jnr-posix/commit/c5a412a8c80502f99f2baabf784ac4fa9a43aa36
> [windows] fix gid

- lib/pom.rb
- lib/pom.xml
> Update webrick to 1.6.1

- core/src/main/java/org/jruby/ast/visitor/AbstractNodeVisitor.java
- core/src/main/java/org/jruby/ast/visitor/NodeVisitor.java
- core/src/main/java/org/jruby/ast/visitor/OperatorCallNode.java
Extracted from #6422 at @enebo's request
> OperatorCallNode was missing from NodeVisitor, add it

- core/src/main/java/org/jruby/RubyDir.java
- core/src/main/java/org/jruby/RubyGlobal.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/TypeConverter.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
- spec/tags/ruby/core/env/assoc_tags.txt
- spec/tags/ruby/core/env/delete_tags.txt
- spec/tags/ruby/core/env/each_pair_tags.txt
- spec/tags/ruby/core/env/each_tags.txt
- spec/tags/ruby/core/env/element_reference_tags.txt
- spec/tags/ruby/core/env/element_set_tags.txt
- spec/tags/ruby/core/env/has_key_tags.txt
- spec/tags/ruby/core/env/has_value_tags.txt
- spec/tags/ruby/core/env/include_tags.txt
- spec/tags/ruby/core/env/index_tags.txt
- spec/tags/ruby/core/env/key_tags.txt
- spec/tags/ruby/core/env/member_tags.txt
- spec/tags/ruby/core/env/rassoc_tags.txt
- spec/tags/ruby/core/env/rehash_tags.txt
- spec/tags/ruby/core/env/replace_tags.txt
- spec/tags/ruby/core/env/shift_tags.txt
- spec/tags/ruby/core/env/store_tags.txt
- spec/tags/ruby/core/env/update_tags.txt
- spec/tags/ruby/core/env/value_tags.txt
Removing failures associated with ENV.  Largely these are all passing in non-String-compatible values.
> Some simple spec fixes in ENV

- core/src/main/java/org/jruby/ext/ffi/AbstractMemory.java
- core/src/main/java/org/jruby/ext/ffi/Util.java
- lib/pom.rb
- lib/pom.xml
- spec/ffi/async_callback_spec.rb
- spec/ffi/buffer_spec.rb
- spec/ffi/callback_spec.rb
- spec/ffi/dup_spec.rb
- spec/ffi/embed-test/embed-test.rb
- spec/ffi/enum_spec.rb
- spec/ffi/fixtures/StringTest.c
- spec/ffi/fixtures/compile.rb
- spec/ffi/fork_spec.rb
- spec/ffi/library_spec.rb
- spec/ffi/managed_struct_spec.rb
- spec/ffi/memorypointer_spec.rb
- spec/ffi/number_spec.rb
- spec/ffi/platform_spec.rb
- spec/ffi/pointer_spec.rb
- spec/ffi/rbx/memory_pointer_spec.rb
- spec/ffi/spec_helper.rb
- spec/ffi/string_spec.rb
- spec/ffi/struct_spec.rb
- spec/ffi/typedef_spec.rb
- spec/ffi/union_spec.rb
> [ffi] update to 1.14.2

- core/src/main/java/org/jruby/ext/socket/RubyUNIXSocket.java
We open the socket before we bind or connect, and must clean up
if there is a subsequent error.
Fixes #6529.
> Close socket when bind or connect fails

- pom.rb
- pom.xml
DateTimeZone data updated to version **2021a**
> [deps] update joda-time to latest

- core/src/main/java/org/jruby/java/invokers/RubyToJavaInvoker.java
Array.set is much slower than raw array access, and leads to a very
laggy ui in certain JRubyFX workloads that involve lots of vararg
calls to java apis. This patch optimizes that case, and leads to a
resulting, user-visible ~10x speedup
This change was pulled out of https://github.com/jruby/jruby/pull/6422 work
> Optimization for calling java vararg methods on hotspot. ~10x speedup

- core/src/main/java/org/jruby/util/io/PopenExecutor.java
In #5383 we added logic to create a new process group when doing
chdir in spawn, to avoid orphaning the eventual process spawned
by the intermediate sh. Unfortunately this has a side effect of
hanging on waitpid if the process spawns a long-running daemon.
This patch removes the process group and instead uses exec in the
generated sh script so that the sh process is replaced. The forked
daemon lives on, as it should, but only the main process is
waited on.
Fixes #6579
> Remove process group to avoid hanging daemons

- core/src/main/java/org/jruby/ext/socket/RubyIPSocket.java
See https://github.com/sorbet/sorbet/issues/1216
There will only be a handful of small fixes in here since the Java package module issues are rather tricky.
> Fixes to support Sorbet

- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
invastigate TypeError: size differ. expected as sizeof(int)=4 but 0 failure
> fix getsockopt failure

- lib/pom.rb
- lib/pom.xml
fixes https://github.com/jruby/jruby/issues/6662
> ostruct 0.3.3

- core/pom.rb
- core/pom.xml
- pom.rb
- pom.xml
Part of supporting the backported socket library in #6664.
> Latest JNR libraries for 9.2

- core/src/main/java/org/jruby/exceptions/RaiseException.java
- core/src/test/java/org/jruby/exceptions/TestRaiseException.java
in Ruby we now get proper cause exception being hooked up.
if this (Ruby land) cause is a Ruby `Exception` or a Java `Throwable` we should also expose it on `RaiseException#getCause` as the proper cause ... thus a `re.printStackTrace` will properly print it's Ruby/Java cause throwable.
also helps logging using Java tools such as log4j.
> [ji] set Ruby/Java cause on RaiseException

- core/pom.rb
- core/pom.xml
- pom.rb
- pom.xml
This merges in preliminary support for Apple Silicon (armple).
> JNR updates

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyObjectSpace.java
- core/src/main/java/org/jruby/util/Inspector.java
- spec/tags/ruby/core/objectspace/weakmap/each_key_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/each_pair_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/each_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/each_value_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/element_set_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/include_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/inspect_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/keys_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/length_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/member_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/size_tags.txt
- spec/tags/ruby/core/objectspace/weakmap/values_tags.txt
- test/mri.core.index
> Add all missing methods to WeakMap

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/anno/AnnotationBinder.java
- core/src/main/java/org/jruby/anno/IndyBinder.java
- maven/jruby-complete/pom.rb
- spec/java_integration/fixtures/EveryTypeAnnotations.java
- spec/java_integration/reify/annos_spec.rb
- spec/java_integration/types/classgen_spec.rb
- test/pom.rb
> Move to jakarta-annotation-api

- core/pom.rb
- core/pom.xml
- test/check_versions.sh
jnr-ffi to 2.2.4, jnr-constants to 0.10.2, jnr-posix to 3.1.6,
jnr-enxio to 0.32.5, and jnr-unixsocket to 0.38.7
> Update JNR deps

- core/src/main/java/org/jruby/ext/set/RubySet.java
- core/src/main/java/org/jruby/runtime/Signature.java
- spec/tags/ruby/library/set/initialize_tags.txt
Hi,
This PR resolve `Set#initialize` compatibility when initializing a `Set` with an Enumerable. In summary fixes https://github.com/jruby/jruby/issues/6616
> Resolve Set#initialize compatibility

- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
fixes: https://github.com/jruby/jruby/issues/6714
> getsockopt crash in --dev mode

- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- spec/tags/ruby/core/module/define_method_tags.txt
Untag some tests regarding method visibility. Also closes https://github.com/jruby/jruby/issues/596.
> Fix some specs regarding method visibility

- .travis.yml
1/ JRUBY_OPTS are being ignored, so half of the stages aren't tested as supposed
2/ add a --dev stage in order to catch https://github.com/jruby/jruby/issues/6714
> [travis] add --dev stage, fix JRUBY_OPTS

- core/src/main/java/org/jruby/RubyTime.java
fixes https://github.com/jruby/jruby/issues/6659
> File#mtime fix timezone

- core/src/main/java/org/jruby/ir/operands/Rational.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
https://github.com/jruby/jruby/issues/6764
> Use canonical form for "r" liternal

- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter6.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter7.java
- core/src/main/java/org/jruby/ir/targets/JVM.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/runtime/backtrace/BacktraceData.java
- core/src/main/java/org/jruby/runtime/backtrace/FrameType.java
- core/src/main/java/org/jruby/util/JavaNameMangler.java
This PR contains fixes for ArgumentError backtrace when crossing into jitted methods.
Fixes #6335.
May improve #5103.
> Handle varargs frame on arity error in jitted code

- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRNoProtocolMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRBodyMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java
- core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java
- core/src/main/java/org/jruby/ir/instructions/DefineClassInstr.java
- core/src/main/java/org/jruby/ir/instructions/DefineModuleInstr.java
- core/src/main/java/org/jruby/ir/interpreter/Interpreter.java
- core/src/main/java/org/jruby/ir/interpreter/InterpreterContext.java
- core/src/main/java/org/jruby/ir/targets/GlobalVariableCompiler.java
- core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java
- core/src/main/java/org/jruby/ir/targets/InvocationCompiler.java
- core/src/main/java/org/jruby/ir/targets/JVM.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/ir/targets/indy/IndyGlobalVariableCompiler.java
- core/src/main/java/org/jruby/ir/targets/indy/IndyInvocationCompiler.java
- core/src/main/java/org/jruby/ir/targets/simple/NormalGlobalVariableCompiler.java
- core/src/main/java/org/jruby/ir/targets/simple/NormalInvocationCompiler.java
- core/src/main/java/org/jruby/runtime/backtrace/BacktraceData.java
- core/src/main/java/org/jruby/runtime/backtrace/FrameType.java
- core/src/main/java/org/jruby/util/JavaNameMangler.java
Doing this as a PR because it was a pretty messy merge.
> Merge lastline and other bits from 9.2

- core/src/main/java/org/jruby/IncludedModule.java
- core/src/main/java/org/jruby/IncludedModuleWrapper.java
- core/src/main/java/org/jruby/PrependedModule.java
- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/ext/cgi/escape/CGIEscape.java
- core/src/main/java/org/jruby/internal/runtime/methods/DynamicMethod.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalStream.java
- spec/tags/ruby/library/cgi/unescapeHTML_tags.txt
builds on the top of https://github.com/jruby/jruby/pull/6777 that should fix the issue with prepends
see https://github.com/jruby/jruby/pull/5949
> use optimized CGIEscape

- lib/pom.rb
- lib/pom.xml
This updates did_you_mean to 1.3.0 to match Ruby 2.6.8.
> Update did_you_mean to 1.3.0 to match ruby 2.6.8

- lib/pom.rb
- lib/pom.xml
https://github.com/jruby/jruby/issues/6793
> update ffi to 1.15.4

- pom.rb
- pom.xml
to see if it helps with
```
[WARNING] Error injecting: org.apache.maven.plugin.surefire.SurefirePlugin
java.lang.NoClassDefFoundError: org/apache/maven/surefire/testset/TestSetFailedException
```
https://app.travis-ci.com/github/jruby/jruby/jobs/533782401
> update surefire plugin

- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
> reduce some repeated method calls

- core/src/main/java/org/jruby/RubyGC.java
- core/src/main/java/org/jruby/RubyObjectSpace.java
- spec/jruby.mspec
- spec/ruby/core/objectspace/garbage_collect_spec.rb
- spec/tags/ruby/core/gc/start_tags.txt
> Add optional argument to start and garbage_collect

- core/src/main/java/org/jruby/ext/socket/Addrinfo.java
- spec/tags/ruby/library/socket/addrinfo/inspect_tags.txt
before
```
'#<Addrinfo: 127.0.0.1:80>'
```
after
```
'#<Addrinfo: 127.0.0.1:80 TCP>'
```
> Addrinfo#inspect add protocols

- core/src/main/java/org/jruby/Main.java
- core/src/main/java/org/jruby/util/cli/OutputStrings.java
Show the help message via pager if running on a tty. [Feature #3000](https://github.com/ruby/ruby/pull/3000)
Also, highlights headings and options in the message.
demo: https://asciinema.org/a/PXZO3Kvy8F0kxSfL7A9RkWSQV
> [Feature] pager for --help - Ruby 3

- core/src/main/java/org/jruby/RubyModule.java
This adds support for public/private_class_method.
> Expand this array logic

- .github/workflows/ci.yml
- .github/workflows/manual-snapshot-publish.yml
- .github/workflows/snapshot-publish.yml
- tool/concurrent-ruby-github-actions.sh
- tool/sequel-github-actions.sh
Part of the work for #6936. Once we're happy I'll squash this all down into one commit for merging.
> Migrate Travis jobs to GHA

- core/pom.rb
- core/pom.xml
- pom.rb
- pom.xml
* https://github.com/jnr/jffi/milestone/29
* https://github.com/jnr/jnr-ffi/milestone/38
* https://github.com/jnr/jnr-posix/milestone/51
* https://github.com/jnr/jnr-enxio/milestone/34
* https://github.com/jnr/jnr-unixsocket/milestone/41
> Update JNR dependencies

- core/src/main/java/org/jruby/RubyArray.java
> Suport sliced with Enumerator::ArithmeticSequence on Array

- lib/pom.rb
- lib/pom.xml
- test/mri/ostruct/test_ostruct.rb
> Update ostruct to 0.5.1

- core/src/main/java/org/jruby/RubyHash.java
> Support for hash argument to `Hash#transform_keys!` and `Hash#transform_keys`

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/ext/ffi/jffi/VariadicInvoker.java
- pom.rb
- pom.xml
This PR will incorporate the recent work to get variadic functions working properly on Apple Silicon.
> Update JNR for Apple Silicon varargs support

- core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
- core/src/main/java/org/jruby/parser/ParserConfiguration.java
- core/src/main/java/org/jruby/parser/ProductionState.java
- core/src/main/java/org/jruby/parser/RubyParser.java
- core/src/main/java/org/jruby/parser/RubyParser.y
- core/src/main/java/org/jruby/parser/skeleton.parser
- test/mri/excludes/TestSyntax.rb
Use full int for lines and columns during parse time.
> Fix #9684. AIIOBE when files >16bit lines and using coverage

- core/src/main/java/org/jruby/ir/instructions/BuildDynRegExpInstr.java
The cache here serves as a cache for dynamic "once" regexps but
is also being used as the holder for non-"once" regexp. This leads
to a concurrency issue since a single field in this instruction is
used across threads and they may step on each other.
This patch avoids using the shared field for non-"once" dynamic
regexps. As a side effect, these instruction instances will not
be queriable for their last-built RubyRegexp, which also seems
appropriate if they are not a "once" dregexp.
Fixes #6992
> Do not cache non-"once" dregexp

- .github/workflows/ci.yml
- spec/ffi/fixtures/GNUmakefile
- spec/ffi/function_spec.rb
- spec/jruby.mspec
- spec/tags/ruby/library/socket/unixserver/accept_nonblock_tags.txt
- tool/maven-ci-script.sh
We now have a self-hosted runner thanks to MacStadium's OSS program. Try to get a job running.
> Fixes to run tests on Apple Silicon

- test/mri/excludes/TestPrime.rb
> Remove tag of test_prime.rb test case.

- core/src/main/java/org/jruby/RubyArithmeticSequence.java
This commit makes the following test pass.
* test_eql_p in test/mri/ruby/test_arithmetic_sequence.rb
> add ArithmeticSequence#eql?

- core/src/main/java/org/jruby/RubyArray.java
For #7015
The current "test/mri/ruby/test_array.rb"  does not have "intersect?" test,  I get it from mri and run it localy.
> Ruby 3.1: Add Array#intersect?

- core/src/main/java/org/jruby/RubyArray.java
See  #7037 . This reverts Array#minmax to use calling supser.
> Update Array#minmax with block

- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRange.java
"spec/ruby/core/range/step_spec.rb" will pass perfectly 
and "test_step_bug15537" of "test/mri/ruby/test_range.rb" will also pass.
> Fix Range#step

- bin/jruby.sh
Some tests were failing because of an oversight in the argument parsing, and a couple other things caught my eye.
> Launcher fixes

- core/src/main/java/org/jruby/RubyArray.java
This PR converts exception message using an ArithsemeticSequece arg.
e.g.
[1].slice((-101..-1)%2) shoud throw "((-101..-1).%(2)) out of range".
The original exception message is "-1..-1 out of range".
* test_slice_out_of_range in test/mri/ruby/test_array.rb
> Fix RangeError message generated by Array#slice

- core/src/main/java/org/jruby/RubyEnumerable.java
* test_tally in test/mri/ruby/test_enum.rb
> Fix Enumerable#tally for some edge cases

- core/src/main/java/org/jruby/RubyArithmeticSequence.java
* test_each_slice in test/mri/ruby/test_enumerator.rb
> Update ArithemeticSequence#each_slice to fix failing TestEnumerator#test_each_slice_size

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/RubyException.java
- core/src/main/java/org/jruby/RubyFloat.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyMarshal.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/RubyRegexp.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubyStruct.java
- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/RubySystemCallError.java
- core/src/main/java/org/jruby/ast/util/ArgsUtil.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalCommon.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalStream.java
- core/src/main/java/org/jruby/runtime/marshal/UnmarshalCache.java
- core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java
- core/src/main/java/org/jruby/util/RubyStringBuilder.java
- spec/tags/ruby/core/marshal/load_tags.txt
- spec/tags/ruby/core/marshal/restore_tags.txt
More or less ended up being a rewrite.  Not finished as I still need to handle Marshal#dump.
> Fix marshal

- core/src/main/java/org/jruby/RubyRange.java
1. This commit updates Range#to_a simplify to fix failing TestRange#test_last_with_redefine_each.
I wonder if the deleted code in the to_a function contributes to the optimization for some cases.
But TestRange#test_last_with_redefine_each does not work because of the redefine #each method is not evaluated.
I give priority to passing the Range tests.
2. This commit also updates Range#last. In mri 3.1.0, the range_last function in range.c does optimization.
When the begin and the end of a range are integer type and  #each method of a range is not redefined,
the range_last function returns correct values without making a unnecessary array instance.
> Update Range#to_a and #last

- bin/jruby.sh
Caught a typo using shellcheck, decided to add some directives to minimize shellcheck's output.
> Shellcheck fixes and directives

- core/src/main/java/org/jruby/RubyRange.java
* test_min in test/mri/ruby/test_range.rb
> Update Range#min to fix failing TestRange#test_min

- core/src/main/java/org/jruby/RubyRange.java
* test_first_last in test/mri/ruby/test_range.rb
> Update Range#first to fix failing TestRange#test_first_last

- bin/jruby.sh
Thanks to [esceval](https://github.com/mentalisttraceur/esceval) and the [interface](https://github.com/spack/spack/blob/develop/lib/spack/env/cc#L103:L174) from spack's shell scripts, I was able to simplify the implementation of arrays. This new implementation looks much cleaner and stores everything literally like a bash array would. And unlike spack's implementation, you can store a literal BEL character :)
> [launcher] Better arrays

- spec/tags/ruby/core/range/each_tags.txt
The current master works on. See #7118 .
> Remove tag of Range#each spec

- core/src/main/java/org/jruby/RubyRandom.java
- spec/tags/ruby/core/kernel/rand_tags.txt
spec/ruby/core/kernel/rand_spec.rb and test/mri/ruby/test_rand.rb all pass.
> Update Kernel#rand to return nill when range is backwards

- core/src/main/java/org/jruby/util/io/OpenFile.java
This may resolve issues like #6669 where an in-use stream is
closed in another thread. We have some races here (which may be
unavoidable) that can lead to the fd field getting nulled out on
the way to a read or write. Without null checks, we may raise NPE
instead of a more appropriate EBADF when the fd is dereferenced.
> More checking for null fd

- core/src/main/java/org/jruby/ext/socket/RubySocket.java
partly reverts https://github.com/jruby/jruby/pull/6945
see https://github.com/jruby/jruby/issues/7069
> revert ipv6 availability

- core/src/main/java/org/jruby/RubyException.java
> Disallow circular causes

- core/src/main/java/org/jruby/RubyFile.java
- test/jruby/test_file.rb
- test/jruby/test_marshal_gemspec.rb
- test/jruby/test_set.rb
Fixes and test changes to get our JRuby-specific test suites running green and matching Ruby 3.1 behaviors.
> Greening our suites

- core/src/main/java/org/jruby/RubyArray.java
The method for `Array#select!` didn't check after each successive block yield if the array was frozen cause a failed test
> Fix failed test in Array#select! test

- spec/tags/ruby/core/string/valid_encoding_tags.txt
> Remove tag of String#valid_encoding?

- core/src/main/java/org/jruby/RubyString.java
- spec/tags/ruby/core/string/split_tags.txt
This commit updates String#split to check value of $;.
> Update String#split with String when $; is not nil

- lib/pom.rb
- lib/pom.xml
* io-wait 0.2.3
* net-http 0.2.2
* strscan 3.0.2
* stringio 3.0.2
> Update to released gems

- core/src/main/java/org/jruby/ext/thread/Queue.java
- spec/tags/ruby/core/queue/initialize_tags.txt
> Ruby3.1: Add Queue.new with an Enumerable of initial values

- core/src/main/java/org/jruby/RubyComplex.java
- spec/tags/ruby/core/complex/hash_tags.txt
- spec/tags/ruby/core/complex/marshal_dump_tags.txt
1. This PR updates Complex#hash to avoid same hash values generated from different instances.
2. This PR updates Complexl#marshal_dump to private method.
> Update Complex#hash and  #marshal_dump

- README.md
I update README.md a little bit.
> Add actions link to status badge

- core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java
- test/jruby/test_higher_javasupport.rb
the code is ugly but would otherwise need more refactoring, reproducer at #7244
> [fix] [ji] needs extra method == checks in some cases

- core/src/main/java/org/jruby/util/JarCache.java
- core/src/main/java/org/jruby/util/cli/Options.java
Changed option name according to discussion under #7232
> Renamed option for JAR cache epiration

- lib/pom.rb
- lib/pom.xml
> Update to strscan 3.0.4

- core/src/main/java/org/jruby/runtime/Helpers.java
Fix #7120 
Full credit goes to @rsim for [coming up with the fix](https://github.com/jruby/jruby/issues/7120#issuecomment-1177313307).
> Fix BootstrapMethodError in runtime helpers

- lib/pom.rb
- lib/pom.xml
> update jar-dependencies 0.4.2 reference in lib/pom.rb

- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/util/TypeConverter.java
* test_Integer in test/mri/ruby/test_integer.rb
> Fix Kernel#Integer

- lib/pom.rb
- lib/pom.xml
Reverts jruby/jruby#7291
See comments there for why we had to back off and try this again.
> Revert "update jar-dependencies 0.4.2 reference in lib/pom.rb"

- core/src/main/java/org/jruby/RubyBignum.java
* test_pow in test/mri/ruby/test_integer.rb
> Fix Integer#pow for big integer edge cases

- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyRandomBase.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/RubySignalException.java
- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/socket/Option.java
- core/src/main/java/org/jruby/util/TypeConverter.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
* test_try_convert in test/mri/ruby/test_integer.rb
> Fix Integer.try_convert

- core/src/main/java/org/jruby/lexer/yacc/StringTerm.java
- spec/regression/GH-7306_redundant_regexp_escape_spec.rb
> Fix parsing Regexp for #7306

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyInteger.java
* test_aref in test/mri/ruby/test_integer.rb
> Fix Integer#[]

- core/src/main/java/org/jruby/IncludedModuleWrapper.java
- core/src/main/java/org/jruby/PrependedModule.java
- spec/ruby/core/module/const_defined_spec.rb
- spec/ruby/fixtures/constants.rb
Fixes https://github.com/jruby/jruby/issues/7256
Re-creating this original PR (https://github.com/jruby/jruby/pull/7299) with base set to jruby-9.3
> Fix for issue 7256 (jruby-9.3)

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
fixes https://github.com/jruby/jruby/issues/7324
spec https://github.com/ruby/spec/pull/938
> Fix negative scale BigDecimal#to_r

- core/src/main/java/org/jruby/RubyEnumerable.java
- spec/ruby/core/array/sum_spec.rb
- spec/ruby/core/enumerable/sum_spec.rb
- test/jruby/test_array.rb
> fix Enumberable sum when elements are array

- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubyKernel.java
- spec/tags/ruby/core/file/dirname_tags.txt
> Ruby3.1: Add File.dirname with an optional level argument

- core/src/main/java/org/jruby/ext/fiber/ThreadFiber.java
Virtual threads from Project Loom allow spinning up many more fibers than when using native threads. This is an early patch to add vthread support to JRuby's fibers when the vthread API is available (starting as a preview feature in JDK19). 
Enable the feature when running on JDK 19:
* Pass `--enable-preview` to the JVM
* Pass `-J--enable-preview` to JRuby
* Put `--enable-preview` in `JAVA_OPTS` env
Tested with 100k fibers spun up, and then later resumed, using the following script:
```ruby
5.times do
t = Time.now
ary = 100_000.times.map { Fiber.new { } }
ary.each(&:resume)
p Time.now - t
end
```
Without vthreads, this script runs for a few seconds and then blows up, either raising memory errors or crashing the JVM. With vthreads it can complete multiple iterations, warming up to around …
> Use vthreads when available

- core/src/main/java/org/jruby/RubyInstanceConfig.java
> Use thread-safe COW lists here

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/ext/set/RubySet.java
- core/src/main/java/org/jruby/ext/set/RubySortedSet.java
- spec/tags/ruby/core/kernel/clone_tags.txt
Rekajgger the freeze keyword handling.
> Fix kernel clone

- core/src/main/java/org/jruby/RubyClass.java
- rakelib/test.rake
- spec/java_integration/fixtures/isolated/classes/GH7327Base.java
- spec/java_integration/fixtures/isolated/interfaces/GH7327Interface.java
- spec/java_integration/reify/become_java_spec.rb
> defined reified classes with their parent class's classloader as parent

- core/src/main/java/org/jruby/AbstractRubyMethod.java
- core/src/main/java/org/jruby/RubyMethod.java
- core/src/main/java/org/jruby/RubyUnboundMethod.java
- spec/ruby/core/method/fixtures/classes.rb
- spec/ruby/core/method/super_method_spec.rb
- spec/ruby/core/unboundmethod/super_method_spec.rb
closes https://github.com/jruby/jruby/issues/7344
> Fix for method visibility changes super_method for module-inherited methods

- core/src/main/java/org/jruby/javasupport/JavaUtil.java
> non-void `setFoo` now generates ruby-style proxies #7340

- core/src/main/java/org/jruby/RubyHash.java
- spec/tags/ruby/core/hash/transform_keys_tags.txt
* spec/ruby/core/hash/transform_keys_spec.rb
> Fix Hash#transform_keys! for edge case

- core/src/main/java/org/jruby/javasupport/binding/MethodInstaller.java
- spec/java_integration/fixtures/MethodNames.java
- spec/java_integration/methods/naming_spec.rb
Add tests and fix setters not being generated for some java objects #7340
> non-void setFoo now generates ruby-style proxies for existing java classes #7340

- lib/pom.rb
- lib/pom.xml
- test/check_versions.sh
closing https://github.com/jruby/jruby/issues/7397
> [deps] update Bundler/Rubygems to latest patch

- core/src/main/java/org/jruby/RubyObjectSpace.java
Additional fixes for #7390 to fix #7323
> Don't iterate the metaclasses of java packages

- core/src/main/java/org/jruby/util/RegexpOptions.java
> Regexp new none option

- core/src/main/java/org/jruby/RubyArray.java
* test_join_recheck_elements_type  in test/mri/ruby/test_array.rb
> Fix Array#join for edge case

- core/src/main/java/org/jruby/DelegatedModule.java
- core/src/main/java/org/jruby/IncludedModule.java
- core/src/main/java/org/jruby/PrependedModule.java
- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/runtime/ClassIndex.java
- test/mri.core.index
Multiple fixes to get refinements updated to 3.1 capabilities and characteristics.
> Refinement changes through Ruby 3.1

- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/instructions/ZSuperInstr.java
when calling zsuper it was not setting callInfo but more than that in IRBuilder it was not even saving it properly to the instruction.
> zsuper was not passing kwarg flag values

- core/src/main/java/org/jruby/RubyProcess.java
- spec/tags/ruby/core/process/status/wait_tags.txt
> Implement Process::Status.wait

- core/src/main/java/org/jruby/util/StringSupport.java
This expands our port of encoding negotiation logic, with the goal of fixing the remaining encoding-related failure in #7080. Unfortunately it does not appear to fix that issue.
Pushing this as a PR until I can figure out what I'm missing.
> Expand ported logic for encoding negotiation

- core/src/main/java/org/jruby/RubyRational.java
- core/src/main/java/org/jruby/RubyString.java
- test/mri/excludes_wip/Rational_Test.rb
The following tests in test/mri/ruby/test_rational.rb will pass.
* test_Rational_without_exception
* test_conv
* test_ratsub
test_gcd_no_memory_leak still does not pass.
> Fix Rational for some edge cases

- core/src/main/java/org/jruby/ext/ripper/HeredocTerm.java
- core/src/main/java/org/jruby/ext/ripper/RipperParser.java
- core/src/main/java/org/jruby/ext/ripper/RipperParserBase.java
- core/src/main/java/org/jruby/ext/ripper/RubyLexer.java
- core/src/main/java/org/jruby/ext/ripper/StringTerm.java
- core/src/main/java/org/jruby/lexer/LexingCommon.java
- core/src/main/java/org/jruby/lexer/yacc/HeredocTerm.java
- core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
- core/src/main/java/org/jruby/parser/RubyParser.java
- core/src/main/java/org/jruby/parser/RubyParser.y
- core/src/main/java/org/jruby/parser/RubyParserBase.java
- spec/tags/ruby/library/ripper/lex_tags.txt
- test/mri/excludes/TestRipper/Lexer.rb
- test/mri/excludes/TestRipper/ParserEvents.rb
- test/mri/excludes/TestRipper/ScannerEvents.rb
- test/mri/excludes/TestRipper/Sexp.rb
working through problems found running tests in syntax_tree gem.
> Ripper fixes

- core/src/main/java/org/jruby/RubyComplex.java
- test/mri/excludes/Complex_Test.rb
- test/mri/excludes_wip/Complex_Test.rb
The following tests in test/mri/ruby/test_complex.rb will pass.
- test_marshal
- test_marshal_compatibility
- test_respond
- test_conv
The only one test in test_fixed_bug still does not pass.
```
assert_raise(ArgumentError){ Complex('--8i')}
```
> Fix Complex for some edge cases

- lib/ruby/stdlib/cgi.rb
- lib/ruby/stdlib/cgi/cookie.rb
- lib/ruby/stdlib/cgi/core.rb
- lib/ruby/stdlib/cgi/html.rb
- lib/ruby/stdlib/cgi/session.rb
- lib/ruby/stdlib/cgi/session/pstore.rb
- lib/ruby/stdlib/cgi/util.rb
- lib/ruby/stdlib/cgi/version.rb
- spec/ruby/library/cgi/cookie/name_spec.rb
- spec/ruby/library/cgi/cookie/parse_spec.rb
https://www.ruby-lang.org/en/news/2022/11/22/http-response-splitting-in-cgi-cve-2021-33621/
> Update CGI to 0.1.0.2 for CVE-2021-33621

- core/src/main/java/org/jruby/RubySymbol.java
> Symbol to_s returns frozen string

- core/src/main/java/org/jruby/RubyBignum.java
This also adds in handling for n = 0 always returning 0 regardless of the size of m (for n << m and n >> m).
Fixes #7554
> Raise NoMemoryError for lshift > int max

- .github/workflows/ci.yml
- lib/ruby/stdlib/pty.rb
- samples/ffi/pty.rb
Getting it green and running it faster.
> Improvements and greening of 9.3 CI

- core/src/main/java/org/jruby/runtime/ThreadContext.java
> Also include frame's block for instance_eval

- core/src/main/java/org/jruby/ext/socket/RubySocket.java
When a connect_nonblock ultimately fails with one of these exceptions, we should tidy up the internal IO bits so it does not appear to be a usable stream. This lack of cleanup caused any call to `close` after a failed connection to raise EBADF, because the socket appeared to be open but was not.
Fixes #7483
> Cleanup IO state for true connect failures

- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/RubyStruct.java
- spec/tags/ruby/core/struct/values_at_tags.txt
* spec/ruby/core/struct/values_at_spec.rb
> Fix Struct#values_at when passed an integer Range argument for edge cases

- core/src/main/java/org/jruby/RubyInteger.java
Ticket: https://bugs.ruby-lang.org/issues/18809
I also push a PR for ruby spec: https://github.com/ruby/spec/pull/1013
> Add Integer#ceildiv

- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/instructions/ArrayDerefInstr.java
- core/src/main/java/org/jruby/ir/instructions/AsStringInstr.java
- core/src/main/java/org/jruby/ir/persistence/IRReaderStream.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/ir/targets/indy/ArrayDerefInvokeSite.java
- core/src/main/java/org/jruby/ir/targets/indy/AsStringSite.java
- core/src/main/java/org/jruby/ir/targets/indy/InvokeSite.java
- core/src/main/java/org/jruby/ir/targets/simple/NormalInvocationCompiler.java
- spec/compiler/general_spec.rb
I'm using coverage data to improve the testing in the compiler `general_spec.rb`. These are the improvements.
> JIT coverage fixes

- core/src/main/java/org/jruby/util/Pack.java
- core/src/main/java/org/jruby/util/TypeConverter.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
- spec/tags/ruby/core/array/pack/a_tags.txt
- spec/tags/ruby/core/array/pack/at_tags.txt
- spec/tags/ruby/core/array/pack/b_tags.txt
- spec/tags/ruby/core/array/pack/c_tags.txt
- spec/tags/ruby/core/array/pack/d_tags.txt
- spec/tags/ruby/core/array/pack/e_tags.txt
- spec/tags/ruby/core/array/pack/f_tags.txt
- spec/tags/ruby/core/array/pack/g_tags.txt
- spec/tags/ruby/core/array/pack/h_tags.txt
- spec/tags/ruby/core/array/pack/i_tags.txt
- spec/tags/ruby/core/array/pack/j_tags.txt
- spec/tags/ruby/core/array/pack/l_tags.txt
- spec/tags/ruby/core/array/pack/m_tags.txt
- spec/tags/ruby/core/array/pack/n_tags.txt
- spec/tags/ruby/core/array/pack/p_tags.txt
- spec/tags/ruby/core/array/pack/q_tags.txt
- spec/tags/ruby/core/array/pack/s_tags.txt
- spec/tags/ruby/core/array/pack/u_tags.txt
- spec/tags/ruby/core/array/pack/v_tags.txt
- spec/tags/ruby/core/array/pack/w_tags.txt
- spec/tags/ruby/core/array/pack/x_tags.txt
- spec/tags/ruby/core/array/pack/z_tags.txt
A lot of failures for a single blob of code.
> Array#pack unknown directive warns

- core/src/main/java/org/jruby/RubyArray.java
- spec/tags/ruby/core/method/hash_tags.txt
- spec/tags/ruby/core/proc/new_tags.txt
Same impl which makes this method hash spec pass.
> Array#to_s/inspect should be same method

- core/src/main/java/org/jruby/RubyBinding.java
- spec/tags/ruby/core/binding/local_variable_set_tags.txt
Simple check to make sure we are really trying to set/get actual lvars.
> Binding local_variables makes sure they are lvars

- core/src/main/java/org/jruby/util/cli/ArgumentProcessor.java
- spec/tags/ruby/command_line/dash_encoding_tags.txt
> Add --encoding command line option.

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
- core/src/main/java/org/jruby/util/cli/ArgumentProcessor.java
- spec/tags/ruby/command_line/backtrace_limit_tags.txt
- spec/tags/ruby/command_line/dash_external_encoding_tags.txt
- spec/tags/ruby/command_line/dash_internal_encoding_tags.txt
- spec/tags/ruby/command_line/dash_l_tags.txt
- spec/tags/ruby/command_line/dash_n_tags.txt
- spec/tags/ruby/command_line/dash_upper_u_tags.txt
- spec/tags/ruby/command_line/dash_upper_w_tags.txt
- spec/tags/ruby/command_line/rubyopt_tags.txt
A few minor fixes and cleanup of spec tags.
> Spec sweep

- core/src/main/java/org/jruby/util/cli/ArgumentProcessor.java
- core/src/test/java/org/jruby/test/TestCommandlineParser.java
- test/jruby/test_command_line_switches.rb
- test/jruby/test_load.rb
All -I provided relative paths shold be made absolute
> All -I provided relative paths shold be made absolute

- spec/tags/ruby/core/binding/eval_tags.txt
> Passing specs

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/RubyMatchData.java
- core/src/main/java/org/jruby/RubyRegexp.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/ext/strscan/RubyStringScanner.java
- spec/tags/ruby/library/stringscanner/scan_tags.txt
- test/mri/strscan/test_ractor.rb
- test/mri/strscan/test_stringscanner.rb
* Update joni to 2.1.48 to get new accessors and Region factory
* Update strscan + tests from ruby/strscan@ce7e061994
* Switch to Region accessors and factory method throughout
> Update joni and strscan

- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
> Mimic CRuby's range error logic for chr

- .github/workflows/ci.yml
- .github/workflows/snapshot-publish.yml
See https://issues.apache.org/jira/browse/MNG-7693
This is temporary until GHA has updated to Maven 3.9.1 which fixes the above issue.
> Force older maven version

- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyEnumerator.java
- core/src/main/java/org/jruby/util/collections/DoubleObject.java
- core/src/main/java/org/jruby/util/collections/SingleBoolean.java
- core/src/main/java/org/jruby/util/collections/SingleDouble.java
- core/src/main/java/org/jruby/util/collections/SingleInt.java
- core/src/main/java/org/jruby/util/collections/SingleLong.java
- core/src/main/java/org/jruby/util/collections/SingleObject.java
- core/src/main/java/org/jruby/util/func/ObjectObjectIntFunction.java
Various cleanup of Enumerator logic.
> Enumerator cleanup

- spec/tags/ruby/library/etc/getgrgid_tags.txt
- spec/tags/ruby/library/etc/getgrnam_tags.txt
- spec/tags/ruby/library/etc/getlogin_tags.txt
- spec/tags/ruby/library/etc/getpwuid_tags.txt
- spec/tags/ruby/library/etc/group_tags.txt
- spec/tags/ruby/library/syslog/alert_tags.txt
- spec/tags/ruby/library/syslog/crit_tags.txt
- spec/tags/ruby/library/syslog/debug_tags.txt
- spec/tags/ruby/library/syslog/err_tags.txt
- spec/tags/ruby/library/syslog/info_tags.txt
- spec/tags/ruby/library/syslog/log_tags.txt
- spec/tags/ruby/library/syslog/notice_tags.txt
- spec/tags/ruby/library/syslog/opened_tags.txt
- spec/tags/ruby/library/syslog/options_tags.txt
- spec/tags/ruby/library/syslog/reopen_tags.txt
- spec/tags/ruby/library/syslog/warning_tags.txt
> Syslog tags

- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
for binary compatibility with Java 8
fixes https://github.com/jruby/jruby/issues/7736
> fix flipBuffer overloads

- core/src/main/java/org/jruby/ext/ripper/HeredocTerm.java
- core/src/main/java/org/jruby/ext/ripper/RipperParser.java
- core/src/main/java/org/jruby/ext/ripper/RipperParserBase.java
- core/src/main/java/org/jruby/lexer/LexingCommon.java
- core/src/main/java/org/jruby/parser/RubyParser.java
- core/src/main/java/org/jruby/parser/RubyParser.y
- core/src/main/java/org/jruby/parser/RubyParserBase.java
working through failures from syntax_tree gem.
> Ripper fixes found while running syntax_tree gems tests.

- core/src/main/java/org/jruby/util/TypeConverter.java
- spec/tags/ruby/core/array/try_convert_tags.txt
- spec/tags/ruby/core/hash/try_convert_tags.txt
- spec/tags/ruby/core/regexp/try_convert_tags.txt
- spec/tags/ruby/core/string/try_convert_tags.txt
> fix try_convert error message

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- test/mri/excludes/TestBigDecimal.rb
The following tests will pass in test/mri/bigdecimal/test_bigdecimal.rb .
* test_power_with_prec
> Add BigDecimal#power(n, prec)

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- test/mri/excludes/TestBigDecimal.rb
This PR adds BigDeciaml#quo(value, digits) and gets higher compatibility.
* test_div in test/mri/bigdecimal/test_bigdecimal.rb
* test_dev_precision in test/mri/bigdecimal/test_bigdecimal.rb
> Add BigDecimal#quo(value, digits)

- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- test/mri/excludes/TestBigDecimal.rb
* test_to_f in test/mri/bigdecimal/test_bigdecimal.rb
> Fix BigDeciaml#to_f

- core/src/main/java/org/jruby/RubyRational.java
- spec/tags/ruby/core/rational/truncate_tags.txt
* spec/ruby/core/rational/truncate_spec.rb
> Fix Rational#truncate with an invalid value

- core/pom.rb
- core/pom.xml
- pom.rb
- pom.xml
* jffi: 1.3.11
* jnr-ffi: 2.2.14
* jnr-posix: 3.1.17
* jnr-enxio: 0.32.15
* jnr-unixsocket: 0.38.20
> Update JNR versions

- core/pom.rb
- core/pom.xml
This updates joni to 2.21, pulling in the new Region API changes, configurable options, and a few minor fixes like #7830.
> Update joni to 2.2

- core/src/main/java/org/jruby/ext/fiber/ThreadFiber.java
- core/src/main/java/org/jruby/util/cli/Category.java
- core/src/main/java/org/jruby/util/cli/Options.java
* Use method handles to launch
* Guard behind an option so they can be disabled
> Improvements for vthread fibers

- .github/workflows/ci.yml
- spec/java_integration/extensions/collection_spec.rb
- spec/java_integration/extensions/list_spec.rb
- test/jruby/test_higher_javasupport.rb
- test/mri/excludes/TestIO_M17N.rb
This PR will provide updates to CI and patches for JRuby to run on Java 21. I don't expect there to be many changes needed.
> Support Java 21

- core/src/main/java/org/jruby/runtime/load/LibrarySearcher.java
- core/src/test/java/org/jruby/runtime/load/TestLoadService.java
> Guard for null in StringWrapper

- core/src/main/java/org/jruby/ext/socket/Addrinfo.java
- spec/tags/ruby/library/socket/addrinfo/ipv6_unique_local_tags.txt
fixes https://github.com/jruby/jruby/issues/7922
> add Addrinfo#ipv6_unique_local?

- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/instructions/CallBase.java
- core/src/main/java/org/jruby/ir/instructions/specialized/ZeroOperandArgNoBlockCallInstr.java
Also noticed IR persist would not restore this state :smile:
> Proc.new with no args no longer supported in 3.1

- core/src/main/java/org/jruby/runtime/scope/DynamicScopeGenerator.java
This is to help debug #7815 and hopefully provide more meaningful traces going forward.
The non-specialized methods have line numbers from 0 up. Generated nullable getters have lines 100 + (variable offset). Generated non-nullable getters (nil for null) have lines 200 + (variable offset). Generated setters have lines 300 + (variable offset).
> Improve line numbers for generated dynscopes

- core/pom.rb
- core/pom.xml
- pom.rb
- pom.xml
* jffi 1.3.12 brings windows-aarch64 support
* jnr-ffi 2.2.15 brings riscv64 support
* jnr-posix 3.1.18
* jnr-enxio 0.32.16
* jnr-unixsocket 0.38.21
> Update jnr stack

- lib/pom.rb
> Update ffi to 1.16.1

- core/src/main/java/org/jruby/util/Dir.java
- spec/ruby/core/file/shared/fnmatch.rb
closes https://github.com/jruby/jruby/issues/7942
> fnmatch not matching glob syntax

- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyRegexp.java
- core/src/main/java/org/jruby/RubyThread.java
Working on #7604 a bit again. The new csv hits strscan and regexp core heavier, so I'm looking for ways to reduce the overhead along those paths.
> Misc regex and strscan improvements

- core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java
fixes https://github.com/jruby/jruby/issues/7968
> add RbConfig::CONFIG["SOEXT"]

- lib/pom.rb
- lib/pom.xml
See https://github.com/ruby/strscan/pull/67
> Update strscan to 3.0.7

- lib/pom.rb
> Make sure gems path is regex-safe

- core/src/main/java/org/jruby/runtime/Helpers.java
- core/src/main/java/org/jruby/util/io/OpenFile.java
JRuby 9.3 version of https://github.com/jruby/jruby/pull/7967.
> Propagate read errors in IO backend

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyDir.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyGlobal.java
- core/src/main/java/org/jruby/util/Pack.java
- spec/tags/ruby/core/array/collect_tags.txt
- spec/tags/ruby/core/array/filter_tags.txt
- spec/tags/ruby/core/array/keep_if_tags.txt
- spec/tags/ruby/core/array/map_tags.txt
- spec/tags/ruby/core/array/pack/p_tags.txt
- spec/tags/ruby/core/array/reject_tags.txt
- spec/tags/ruby/core/array/select_tags.txt
- spec/tags/ruby/core/array/sort_by_tags.txt
- spec/tags/ruby/core/array/to_h_tags.txt
- spec/tags/ruby/core/env/delete_tags.txt
- spec/tags/ruby/core/env/has_key_tags.txt
- spec/tags/ruby/core/env/include_tags.txt
- spec/tags/ruby/core/env/key_tags.txt
- spec/tags/ruby/core/env/member_tags.txt
Taking some time to do a pass over specs and look for things we can fix now.
> Fix various specs

- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/util/time/TimeArgs.java
- spec/tags/ruby/core/time/at_tags.txt
- spec/tags/ruby/core/time/gm_tags.txt
- spec/tags/ruby/core/time/local_tags.txt
- spec/tags/ruby/core/time/localtime_tags.txt
- spec/tags/ruby/core/time/mktime_tags.txt
- spec/tags/ruby/core/time/new_tags.txt
- spec/tags/ruby/core/time/now_tags.txt
- spec/tags/ruby/core/time/utc_tags.txt
> Time spec fixes

- core/src/main/java/org/jruby/util/io/EncodingUtils.java
- spec/tags/ruby/core/file/constants/constants_tags.txt
- spec/tags/ruby/core/file/stat/blksize_tags.txt
- spec/tags/ruby/core/file/stat/blocks_tags.txt
- spec/tags/ruby/core/file/stat/dev_major_tags.txt
- spec/tags/ruby/core/file/stat/dev_minor_tags.txt
- spec/tags/ruby/core/file/stat/ftype_tags.txt
- spec/tags/ruby/core/file/stat/grpowned_tags.txt
- spec/tags/ruby/core/file/stat/ino_tags.txt
- spec/tags/ruby/core/file/stat/nlink_tags.txt
- spec/tags/ruby/core/file/stat/rdev_major_tags.txt
- spec/tags/ruby/core/file/stat/rdev_minor_tags.txt
- spec/tags/ruby/core/file/stat/world_readable_tags.txt
- spec/tags/ruby/core/file/stat/world_writable_tags.txt
- spec/tags/ruby/core/file/utime_tags.txt
- spec/tags/ruby/core/file/world_readable_tags.txt
- spec/tags/ruby/core/filetest/identical_tags.txt
- spec/tags/ruby/core/io/new_tags.txt
- spec/tags/ruby/core/symbol/end_with_tags.txt
Just some random tag removal and a few fixes
> Tag sweep2

- core/src/main/java/org/jruby/RubyObjectSpace.java
They will use value comparisons rather than identity comparisons to mimic CRuby's behavior for immediate values.
Fixes #7862
> Expand WeakMap to allow floats and fixnums

- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyInstanceConfig.java
- core/src/main/java/org/jruby/compiler/impl/SkinnyMethodAdapter.java
- core/src/main/java/org/jruby/ir/IRBuilder.java
- core/src/main/java/org/jruby/ir/IRManager.java
- core/src/main/java/org/jruby/ir/IRVisitor.java
- core/src/main/java/org/jruby/ir/instructions/BIntInstr.java
- core/src/main/java/org/jruby/ir/instructions/IntegerMathInstr.java
- core/src/main/java/org/jruby/ir/interpreter/FullInterpreterContext.java
- core/src/main/java/org/jruby/ir/operands/TemporaryIntVariable.java
- core/src/main/java/org/jruby/ir/operands/TemporaryVariableType.java
- core/src/main/java/org/jruby/ir/persistence/IRDumper.java
- core/src/main/java/org/jruby/ir/targets/JVM.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
This fixes problem in other PR and I just pushed to new one so I can throw in some other changes.
> Pattern jit

- core/src/main/java/org/jruby/RubyException.java
> Implement `Exception.to_tty?`

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/ext/nkf/RubyNKF.java
- core/src/main/java/org/jruby/ext/socket/Option.java
- core/src/main/java/org/jruby/util/Pack.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
A few cleanups I ran into while poking around RubyString.
> Various cleanups for String operations

- core/src/main/java/org/jruby/util/Pack.java
Noticed we had this logic to only skip nul's in some codes but it called a method which 100% skipped all nul's so no point in having that code in there unless we are skipping too much.  I see no tests or specs to say we are doing this wrong so let's just clean this up.
> ignore codes logic was not doing anything in unpack

- core/src/main/java/org/jruby/ext/socket/RubyUDPSocket.java
- spec/tags/ruby/library/socket/udpsocket/inspect_tags.txt
At worst this will be a little refactoring but it should at least print more info closer to what MRI has.  If this leads to it working better than that will be in there as well (which is what I hope happens).
Thus far: 
1. Mild refactoring.  
2.  Eliminated unneeded instanceof check for String when we already know it is a Fixnum.  This also eliminated an extra RubyInteger check.
> Try and make UDP look a little more like MRI (and hopefully make it more functional)

- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/java/dispatch/CallableSelector.java
- test/jruby/test_java_extension.rb
- test/org/jruby/test/TestHelper.java
> recognize RubySymbol as assignable to String

- core/src/main/java/org/jruby/ext/thread/Queue.java
- spec/ruby/core/queue/freeze_spec.rb
> Ruby 3.3 support: Queue#freeze now raises TypeError

- core/src/main/java/org/jruby/Ruby.java
> Inspect frozen object for error

- core/src/main/java/org/jruby/ext/strscan/RubyStringScanner.java
Patches:
* https://github.com/ruby/strscan/pull/67
* https://github.com/ruby/strscan/pull/79
* https://github.com/ruby/strscan/pull/81
* https://github.com/ruby/strscan/pull/84
> Update strscan to 3.0.9

- core/src/main/java/org/jruby/ext/strscan/RubyStringScanner.java
Reverts jruby/jruby#8075
Several tainting tests fail because we've removed tainting in the gem, and for some reason the new string copying logic leads to boundary errors. Reverting the update for now and will evaluate changes individually.
> Revert "Update strscan to 3.0.9"

- lib/pom.rb
- lib/pom.xml
See https://github.com/ruby/strscan/issues/86
> Update strscan to 3.1.0 for OOB fix

- core/src/main/java/org/jruby/ext/strscan/RubyStringScanner.java
Various fixes and improvements from the past few months.
* https://github.com/ruby/strscan/pull/72
* https://github.com/ruby/strscan/pull/74
* https://github.com/ruby/strscan/issues/75
* https://github.com/ruby/strscan/pull/76
* https://github.com/ruby/strscan/issues/78
* https://github.com/ruby/strscan/pull/80
* https://github.com/ruby/strscan/issues/83
* https://github.com/ruby/strscan/issues/86
* https://github.com/ruby/strscan/pull/87
> Update strscan from gem v3.1.0

- core/src/main/java/org/jruby/RubyIO.java
> Invert this logic to match O_NONBLOCK flag

- core/src/main/java/org/jruby/RubyModule.java
- spec/tags/ruby/core/module/undef_method_tags.txt
fix undef_method error message.  Minor limited impact fix.
> fix undef_method error message

- maven/jruby/src/templates/hellowarld/Gemfile.lock
> update this ancient lockfile

- maven/jruby/src/templates/hellowarld/Gemfile
- maven/jruby/src/templates/hellowarld/Gemfile.lock
Not sure why it took multiple PRs to get to this version of Puma but covfefe.
> one last update to puma version for sample Gemfile

- core/src/main/java/org/jruby/RubyFile.java
- spec/tags/ruby/core/file/lutime_tags.txt
lutimes was passing huge wrong values to function
> lutimes was passing huge wrong values to function

- core/src/main/java/org/jruby/RubyProc.java
- spec/tags/ruby/core/proc/clone_tags.txt
Proc#clone of frozen proc should stay frozen
> Proc#clone of frozen proc should stay frozen

- core/src/main/java/org/jruby/RubyMethod.java
- spec/tags/ruby/core/method/clone_tags.txt
Method.clone of frozen should stay frozen
> Method.clone of frozen should stay frozen

- core/src/main/java/org/jruby/RubyUnboundMethod.java
- spec/tags/ruby/core/unboundmethod/clone_tags.txt
UnboundMethod#clone of frozen UnboundMethod should stay frozen
> UnboundMethod#clone of frozen UnboundMethod should stay frozen

- core/src/main/java/org/jruby/RubyString.java
- spec/tags/ruby/core/string/to_c_tags.txt
Return proper encoding error string for String#to_c
> Return proper encoding error string for String#to_c

- core/src/main/java/org/jruby/RubyBasicObject.java
- spec/tags/ruby/core/kernel/remove_instance_variable_tags.txt
frozen error handling for remove_instance_variable
> frozen error handling for remove_instance_variable

- core/src/main/java/org/jruby/RubyKernel.java
- spec/tags/ruby/core/kernel/trace_var_tags.txt
Implement string/eval form of trace_var
> Implement string/eval form of trace_var

- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyKernel.java
- spec/tags/ruby/core/file/new_tags.txt
- spec/tags/ruby/core/file/open_tags.txt
- spec/tags/ruby/core/io/binwrite_tags.txt
- spec/tags/ruby/core/io/for_fd_tags.txt
- spec/tags/ruby/core/io/initialize_tags.txt
- spec/tags/ruby/core/io/new_tags.txt
- spec/tags/ruby/core/io/open_tags.txt
- spec/tags/ruby/core/io/read_tags.txt
- spec/tags/ruby/core/io/write_tags.txt
- spec/tags/ruby/core/kernel/open_tags.txt
Fix various kwarg-related specs in IO#open, File#open and Kernel#open.
> Fix various kwarg-related specs in IO#open, File#open and Kernel#open.

- pom.rb
- pom.xml
mostly just, TimeZone data **updated to version 2024agtz**
https://www.joda.org/joda-time/changes-report.html#a2.12.7
> [deps] update joda-time to 2.12.7

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyProc.java
dup and clone will now do things like copy instance vars.
> Proc#{dup,clone} should be like other objs

- core/src/main/java/org/jruby/ext/tracepoint/TracePoint.java
tracepoint only runs in thread it was enabled on
> tracepoint only runs in thread it was enabled on

- core/src/main/java/org/jruby/RubyMethod.java
- core/src/main/java/org/jruby/RubyUnboundMethod.java
{,Unbound}Method#{proc,dup} need to be more like other Ruby objects
> {,Unbound}Method#{proc,dup} need to be more like other Ruby objects

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
Some simple refactoring but removing some mysterious classcast guards
> Some simple refactoring but removing some mysterious classcast guards

- bench/bench_string_interpolation.rb
- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/Appendable.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyFloat.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- core/src/main/java/org/jruby/ir/targets/ValueCompiler.java
- core/src/main/java/org/jruby/ir/targets/indy/BuildDynamicStringSite.java
- core/src/main/java/org/jruby/ir/targets/indy/IndyValueCompiler.java
- core/src/main/java/org/jruby/ir/targets/indy/StringBootstrap.java
- core/src/main/java/org/jruby/ir/targets/simple/NormalValueCompiler.java
This PR will include various optimizations for dynamic string build and manipulation, including at least:
* Bytecode size reductions
* Specialized call site logic for string templating
* Optimized to_s invocation for non-string dynamic elements
> Optimizations for dynamic string building

- core/src/main/java/org/jruby/ir/interpreter/InterpreterContext.java
- core/src/main/java/org/jruby/ir/passes/AddMissingInitsPass.java
- core/src/main/java/org/jruby/ir/passes/OptimizeDynScopesPass.java
- core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
- spec/tags/ruby/language/END_tags.txt
END was not getting parents lvars.  
References where getting a valid staticscope but the dynamic scope would end up all being nil.
> END was not getting parents lvars

- core/src/main/java/org/jruby/ir/builder/IRBuilder.java
- core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java
- spec/tags/ruby/language/case_tags.txt
Give same error message for duplicated case arms
> Give same error message for duplicated case arms

- core/src/main/ruby/jruby/kernel/enumerator.rb
- spec/ruby/core/enumerator/next_values_spec.rb
- spec/ruby/core/enumerator/peek_values_spec.rb
- spec/tags/ruby/core/enumerator/next_values_tags.txt
- spec/tags/ruby/core/enumerator/peek_values_tags.txt
This PR fixes the issue described in https://github.com/jruby/jruby/issues/8199, adds 2 new test cases, and removes tags for 2 existing, disabled test cases
> Fix issue#8199

- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/util/ClassDefiningClassLoader.java
- core/src/main/java/org/jruby/util/ClassDefiningJRubyClassLoader.java
- core/src/main/java/org/jruby/util/NClassClassLoader.java
- core/src/main/java/org/jruby/util/OneShotClassLoader.java
- spec/java_integration/reify/become_java_spec.rb
a quick attempt to support partial removing of a reified class hierarchy... (https://github.com/jruby/jruby/issues/8141)
if this seems fishy I am okay to drop and leave this use-case as not supported
> [ji] support re-reifying class hierarchy

- core/src/main/java/org/jruby/RubyIO.java
IO#readlines accepts another arg
> IO#readlines accepts another arg

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/RubyRegexp.java
> Implement Regexp#linear_time?

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyRegexp.java
- core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java
Implement regexp timeout.
Regexp#timeout{,=}
Regexp.new(+ keyword timeout:)
> Implement regexp timeout

- bin/jruby.sh
> Resolve symlinks in user provided $JAVA_HOME

- core/src/main/java/org/jruby/util/ClasspathLauncher.java
> handle FileSystemNotFoundException when getting jruby jar

- core/src/main/java/org/jruby/api/Convert.java
- core/src/main/java/org/jruby/ext/coverage/CoverageData.java
- core/src/main/java/org/jruby/ext/coverage/CoverageModule.java
- core/src/main/java/org/jruby/ir/builder/IRBuilder.java
- core/src/main/java/org/jruby/parser/Parser.java
- core/src/main/java/org/jruby/parser/RubyParserBase.java
- spec/tags/ruby/library/coverage/result_tags.txt
Implement Coverage::supported?
> Implement Coverage::supported?

- core/src/main/java/org/jruby/ir/builder/IRBuilder.java
- core/src/main/java/org/jruby/parser/Parser.java
- core/src/main/java/org/jruby/parser/RubyParserBase.java
Print out paths for syntax errors
> Print out paths for syntax errors

- core/src/main/java/org/jruby/RubyArgsFile.java
- core/src/main/java/org/jruby/internal/runtime/GlobalVariable.java
- core/src/main/java/org/jruby/internal/runtime/ReadonlyAccessor.java
- core/src/main/java/org/jruby/runtime/IAccessor.java
- spec/tags/ruby/core/argf/codepoints_tags.txt
- spec/tags/ruby/core/argf/each_codepoint_tags.txt
- spec/tags/ruby/core/argf/filename_tags.txt
- spec/tags/ruby/core/argf/lines_tags.txt
- spec/tags/ruby/core/argf/path_tags.txt
Largely only $FILENAME properly changing value as it iterates through ARGF files but there was some other which say they pass now so I removed those tags.
> ARGF spec fixes.

- core/src/main/java/org/jruby/RubyStruct.java
- spec/tags/ruby/core/struct/keyword_init_tags.txt
- test/jruby/test_socket.rb
Fix all known failing struct specs in ruby/spec
> Struct specs

- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipWriter.java
CRuby does this lazily on first write, when it sets up the headers, but that laziness is handled inside jzlib for us. Just set it and if it is updated by user it will be updated in the writer.
Fixes https://github.com/jruby/jruby/issues/7879, which led to tests being skipped in
https://github.com/rack/rack/pull/2182.
> Set writer modification time to now by default

- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/javasupport/ext/Module.java
- test/jruby/test_higher_javasupport.rb
similar to how `java_import` works we should check whether the constant was already set and not set it again - this effectively avoids emitting a lot of *"already initialized constant"* in a multi threaded environment. 
on top of that using synchronization we avoid *"already initialized constant"* even in rare cases (which could have still happened with Java proxy class initialization in general).
reproducer for the warnings is easy to spot esp. with `include_package`:
`jruby -v -e "mod = Module.new { include_package 'java.lang.reflect' }; threads = (0..10).map { Thread.start { sleep(0.01); mod::Array } }.each { |t| t.join }"`
```
jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 11.0.14.1+1 on 11.0.14.1+1 +jit [x86_64-linux]
-e:1: warning: already initialized constant …
```
> [ji] avoid already initialized constant warnings

- test/mri/excludes/TestM17NComb.rb
> Remove exclude for passing test

- core/src/main/java/org/jruby/util/ShellLauncher.java
This is a modified version of a patch proposed in https://github.com/jruby/jruby/issues/7515#issuecomment-1368041882 that uses a third mechanism for getting the PID: the `pid` method added to ProcessImpl in 8 and made public in Process in 9.
For JRuby 10, which will target Java 17 or 21, we can just call `pid` directly.
Fixes #7515
> Enhance reflective pid-getting for Windows Java 8+

- .github/workflows/ci.yml
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyThread.java
* Add JDK 23 to all multi-version jobs
* Remove build caching that now just adds time to all jobs
> Various CI updates

- core/src/main/java/org/jruby/ir/builder/IRBuilder.java
> Trivial refactoring for match

- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/date/RubyDateTime.java
- core/src/main/java/org/jruby/javasupport/ext/JavaTime.java
- core/src/main/java/org/jruby/util/RubyDateFormatter.java
more api conversion around Time+
> more api conversion around Time+

- .github/workflows/ci.yml
- core/src/main/java/org/jruby/util/cli/Options.java
There will be some impact to startup and warmup time initially but this is the future of JRuby.
See https://github.com/jruby/jruby/pull/8266.
> Enable invokedynamic by default

- core/src/main/java/org/jruby/RubyDir.java
- core/src/main/java/org/jruby/RubyFile.java
- core/src/main/java/org/jruby/RubyFileStat.java
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/RubyThread.java
- core/src/main/java/org/jruby/api/Check.java
- core/src/main/java/org/jruby/ext/socket/Addrinfo.java
- core/src/main/java/org/jruby/ext/socket/RubyUNIXServer.java
- core/src/main/java/org/jruby/ext/socket/RubyUNIXSocket.java
- core/src/main/java/org/jruby/runtime/load/LoadService.java
- core/src/main/java/org/jruby/util/StringSupport.java
- core/src/main/java/org/jruby/util/io/PopenExecutor.java
While doing this I realized we in almost all cases run this method twice.  I pruned back to only call this once and this eliminated almost all the calls.
> Add new Check#checkEmbeddedNulls to replace StringSupport method

- lib/pom.rb
- lib/pom.xml
- maven/jruby-jars/Mavenfile
> Update to jar-dependencies 0.5.0

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFloat.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
Make Numeric#coerce use TC with deprecated fallback
> Make Numeric#coerce use TC with deprecated fallback

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyFloat.java
- core/src/main/java/org/jruby/RubyGlobal.java
- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRandom.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/RubyRational.java
- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/timeout/Timeout.java
- core/src/main/java/org/jruby/util/Numeric.java
> is_zero+zero_p TCification

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyFloat.java
- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRational.java
- core/src/main/java/org/jruby/ext/date/DateUtils.java
> TCification of isPositive

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyFloat.java
- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/RubyRational.java
- core/src/main/java/org/jruby/util/Sprintf.java
- core/src/main/java/org/jruby/util/time/TimeArgs.java
> TCification of isNegative

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyBinding.java
- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/RubyFileStat.java
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyMatchData.java
- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRandom.java
- core/src/main/java/org/jruby/RubyRegexp.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubyStruct.java
- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/digest/RubyDigest.java
- core/src/main/java/org/jruby/ext/pathname/RubyPathname.java
- core/src/main/java/org/jruby/ext/zlib/JZlibDeflate.java
- core/src/main/java/org/jruby/java/proxies/JavaProxy.java
> Make initialize_copy use TC

- rakelib/commands.rake
- rakelib/rubyspec.rake
See how dot format is for specs for CI
> See how dot format is for specs

- lib/pom.rb
- lib/pom.xml
- maven/jruby-complete/src/it/extended/Mavenfile
- maven/jruby-complete/src/it/runnable/Mavenfile
- maven/jruby-complete/src/templates/osgi_many_bundles_with_embedded_gems/gems-bundle/pom.rb
- maven/jruby-complete/src/templates/osgi_many_bundles_with_embedded_gems/pom.rb
- maven/jruby-jars/Mavenfile
- maven/jruby/src/it/j2ee_jetty/pom.rb
- maven/jruby/src/it/j2ee_jetty_rack/Mavenfile
- maven/jruby/src/it/j2ee_tomcat/pom.rb
- maven/jruby/src/it/j2ee_tomcat_rack/Mavenfile
- maven/jruby/src/it/j2ee_wildfly/pom.rb
- maven/jruby/src/it/jetty/Mavenfile
- maven/jruby/src/it/many_jars_with_embedded_gems/app/pom.rb
- maven/jruby/src/it/many_jars_with_embedded_gems/pom.rb
- maven/jruby/src/it/many_jars_with_embedded_gems_ng/pom.rb
- maven/jruby/src/it/tomcat/pom.rb
- maven/jruby/src/templates/hellowarld/Mavenfile
- maven/jruby/src/templates/j2ee_wlp/pom.rb
- maven/jruby/src/templates/osgi_all_inclusive/pom.rb
- pom.rb
- pom.xml
Various small fixes, but notably File.exists? replaced so it works with JRuby 10.
> Update to jruby-maven-plugins 3.0.4

- lib/pom.rb
- lib/pom.xml
- maven/jruby-complete/src/it/extended/Mavenfile
- maven/jruby-complete/src/it/runnable/Mavenfile
- maven/jruby-complete/src/templates/osgi_many_bundles_with_embedded_gems/gems-bundle/pom.rb
- maven/jruby-complete/src/templates/osgi_many_bundles_with_embedded_gems/pom.rb
- maven/jruby-jars/Mavenfile
- maven/jruby/src/it/j2ee_jetty/pom.rb
- maven/jruby/src/it/j2ee_jetty_rack/Mavenfile
- maven/jruby/src/it/j2ee_tomcat/pom.rb
- maven/jruby/src/it/j2ee_tomcat_rack/Mavenfile
- maven/jruby/src/it/j2ee_wildfly/pom.rb
- maven/jruby/src/it/jetty/Mavenfile
- maven/jruby/src/it/many_jars_with_embedded_gems/app/pom.rb
- maven/jruby/src/it/many_jars_with_embedded_gems/pom.rb
- maven/jruby/src/it/many_jars_with_embedded_gems_ng/pom.rb
- maven/jruby/src/it/tomcat/pom.rb
- maven/jruby/src/templates/hellowarld/Mavenfile
- maven/jruby/src/templates/j2ee_wlp/pom.rb
- maven/jruby/src/templates/osgi_all_inclusive/pom.rb
- pom.rb
- pom.xml
Pulls in maven-tools 1.2.2 fix for File.exists?
> Update jruby-maven-plugins to 3.0.5

- core/src/main/java/org/jruby/ir/builder/IRBuilder.java
Somehow this never got wired up even though the other bits are there.
> Add trace instr for rescue when trace enabled

- core/src/main/java/org/jruby/NativeException.java
- core/src/main/java/org/jruby/RubyComplex.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/ext/ripper/RubyLexer.java
- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
- core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- core/src/main/java/org/jruby/runtime/backtrace/RubyStackTraceElement.java
- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
Hopefully this is the last of them. Lots of new failures are due simply to mismatching error messages.
> Switch more error backquotes to single

- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyMatchData.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/javasupport/ext/JavaUtilRegex.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
- core/src/main/java/org/jruby/util/Sprintf.java
Make all jruby methods use context in Array
> Make all jruby methods use context in Array

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyComplex.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyFloat.java
- core/src/main/java/org/jruby/RubyInteger.java
- core/src/main/java/org/jruby/RubyKernel.java
- core/src/main/java/org/jruby/RubyMatchData.java
- core/src/main/java/org/jruby/RubyNumeric.java
- core/src/main/java/org/jruby/RubyRational.java
- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
context for all numeric types jruby methods
> context for all numeric types jruby methods

- core/src/main/java/org/jruby/RubyStruct.java
- core/src/main/java/org/jruby/RubyTime.java
context for all Struct methods
> context for all Struct methods

- core/src/main/java/org/jruby/MetaClass.java
- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyArray.java
- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/RubyEnumerable.java
- core/src/main/java/org/jruby/RubyEnumerator.java
- core/src/main/java/org/jruby/RubyException.java
- core/src/main/java/org/jruby/RubyHash.java
- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/RubyNameError.java
- core/src/main/java/org/jruby/RubyNoMethodError.java
- core/src/main/java/org/jruby/RubyObject.java
- core/src/main/java/org/jruby/RubyProcess.java
- core/src/main/java/org/jruby/RubyRange.java
- core/src/main/java/org/jruby/RubyRegexp.java
- core/src/main/java/org/jruby/RubySystemCallError.java
- core/src/main/java/org/jruby/RubyTime.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ext/jruby/JRubyObjectInputStream.java
- core/src/main/java/org/jruby/ext/socket/RubySocket.java
- core/src/main/java/org/jruby/ext/zlib/JZlibDeflate.java
- core/src/main/java/org/jruby/ext/zlib/JZlibInflate.java
- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java
- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipWriter.java
- core/src/main/java/org/jruby/ext/zlib/RubyGzipFile.java
- core/src/main/java/org/jruby/javasupport/Java.java
- core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java
- core/src/main/java/org/jruby/util/io/PopenExecutor.java
- core/src/test/java/org/jruby/test/TestRubyClass.java
allocate() needs ThreadContext
> allocate() needs ThreadContext

- core/src/main/java/org/jruby/util/Pack.java
Fix specs involving comments in unpack format strings
> Fix specs involving comments in unpack format strings

- core/src/main/java/org/jruby/ObjectFlags.java
- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/RubySymbol.java
Fix failing specs for chilled symbols
> Fix failing specs for chilled symbols

- core/src/main/java/org/jruby/RubyComplex.java
- core/src/main/java/org/jruby/RubyGlobal.java
- core/src/main/java/org/jruby/RubyMatchData.java
- core/src/main/java/org/jruby/RubyRational.java
- core/src/main/java/org/jruby/RubyRegexp.java
- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/ext/date/RubyDate.java
- core/src/main/java/org/jruby/ir/instructions/BuildBackrefInstr.java
- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- core/src/main/java/org/jruby/runtime/Helpers.java
- core/src/main/java/org/jruby/runtime/ThreadContext.java
- core/src/main/java/org/jruby/util/RegexpOptions.java
- core/src/test/java/org/jruby/TestRegexpCache.java
More context being pushed through regexp code
> tcification of regex

- core/src/main/java/org/jruby/RubyBasicObject.java
- core/src/main/java/org/jruby/RubyClass.java
- core/src/main/java/org/jruby/RubyComparable.java
- core/src/main/java/org/jruby/ext/digest/RubyDigest.java
- core/src/main/java/org/jruby/ext/set/RubySet.java
- core/src/main/java/org/jruby/ext/set/RubySortedSet.java
- core/src/main/java/org/jruby/ext/socket/Addrinfo.java
- core/src/main/java/org/jruby/ext/socket/Option.java
- core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
- core/src/main/java/org/jruby/ext/socket/RubyIPSocket.java
- core/src/main/java/org/jruby/ext/socket/RubySocket.java
- core/src/main/java/org/jruby/ext/socket/RubyTCPServer.java
- core/src/main/java/org/jruby/ext/socket/RubyUDPSocket.java
- core/src/main/java/org/jruby/ext/socket/RubyUNIXSocket.java
- core/src/main/java/org/jruby/ext/socket/SocketUtils.java
- core/src/main/java/org/jruby/ext/zlib/JZlibDeflate.java
- core/src/main/java/org/jruby/ext/zlib/JZlibInflate.java
- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java
- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipWriter.java
- core/src/main/java/org/jruby/ext/zlib/RubyGzipFile.java
- core/src/main/java/org/jruby/ext/zlib/RubyZlib.java
- core/src/main/java/org/jruby/ext/zlib/ZStream.java
- core/src/main/java/org/jruby/util/io/Sockaddr.java
Remove more use of getRuntime()
> Remove more use of getRuntime()

- core/src/main/java/org/jruby/RubyFixnum.java
The call to Math.multiplyExact works very well when the result does not overflow, skipping range checks and using the host CPU's support for overflow checks. However when we are dancing on the range boundary and multiplyExact fails repeatedly, the cost of raising all those exceptions massively outweighs the gains.
This is the primary cause of performance issues reported in jruby/jruby#8516.
This patch reverts to a version of the old range-checking logic. Performance on the bug report's benchmark is an order of magnitude faster for the two cases that seemed to overflow a lot, and the other cases do not seem to degrade.
Fixes jruby/jruby#8516
> Revert multiply to use non-intrinsic exactness checks

- lib/ruby/stdlib/jruby/thread_dump.rb
> Update thread dump hook for modern JRuby

- core/src/main/ruby/jruby/kernel/process.rb
- spec/tags/ruby/core/process/argv0_tags.txt
Only 11 years late.
Fixes #8568.
> Add Process.argv0

- core/pom.rb
- core/pom.xml
Issues fixed:
* https://github.com/jruby/jcodings/pull/61
* https://github.com/jruby/jcodings/pull/62
* https://github.com/jruby/jcodings/issues/60
> Update to jcodings 1.0.59

- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
Added **nil support which is same as **{} semantically.
> Implement **nil

- core/src/main/java/org/jruby/ext/thread/Mutex.java
CRuby semantics for an interrupt during lock appear to ensure that the lock is released before propagating any interrupt exception. This poll was added without such behavior, leading to locks being left locked even though a thread interrupt happened. This in turn breaks some semantics of Mutex#synchronize, since the lock call does not happen within the try/finally that would release it, so any exception raised will exit synchronize with the lock still locked.
The fix here wraps the additional poll with try/catch to ensure poll-triggered exceptions release the lock before propagating.
Fixes #8585
> Unlock if poll triggers an exception

- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/api/Warn.java
- core/src/main/java/org/jruby/common/RubyWarnings.java
Add warning for ::Ruby = as reserved constant
> Add warning for ::Ruby = as reserved constant

- core/src/main/java/org/jruby/RubyMatchData.java
Implement MatchData#byte{beg,end}
> Implement MatchData#byte{beg,end}

- lib/pom.rb
- lib/pom.xml
Fixes jruby/jruby#8606 via jruby/jar-dependencies#93
> Use jar-dependencies 0.5.4

- core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java
- spec/ruby/library/zlib/gzipreader/each_char_spec.rb
> add zlib each_char

- core/src/main/java/org/jruby/RubySymbol.java
These are optimizations and cleanup found while working to improve the performance of the `json` library.
See ruby/json#725
> Improvements to support json library

- lib/pom.rb
- lib/ruby/stdlib/resolv.rb
- test/mri/resolv/test_dns.rb
- test/mri/resolv/test_resource.rb
- test/mri/resolv/test_svcb_https.rb
This is a version of ruby/resolv lightly modified to fix the Windows platform check. We can merge this or wait for a release, but this will help confirm that the new version runs ok.
> Test new version of resolv

- core/src/main/java/org/jruby/RubyBignum.java
- core/src/main/java/org/jruby/RubyFixnum.java
- core/src/main/java/org/jruby/RubyInteger.java
- spec/tags/ruby/core/integer/ceil_tags.txt
- spec/tags/ruby/core/integer/fdiv_tags.txt
- spec/tags/ruby/core/integer/floor_tags.txt
- spec/tags/ruby/core/integer/left_shift_tags.txt
- spec/tags/ruby/core/integer/right_shift_tags.txt
Various fixes to get Integer specs green on JRuby 10.
> Integer spec fixes for JRuby 10

- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/exceptions/FiberKill.java
- core/src/main/java/org/jruby/ext/fiber/ThreadFiber.java
This isn't going to get green without some rework of how we manage Fiber lifecycles, but I've got it pretty close.
> Fiber specs for JRuby 10

- core/src/main/java/org/jruby/RubyString.java
- core/src/main/java/org/jruby/util/StringSupport.java
> Fix `tr!` and `reverse!` on ByteList view with non-zero begin index

- core/src/main/java/org/jruby/ext/ffi/StructLayout.java
Previous changes from raw array and I put in wrong field name
> Previous changes from raw array and I put in wrong field name

- core/src/main/java/org/jruby/util/Dir.java
- test/jruby/test_dir.rb
> fix glob dir on windows

- .github/workflows/ci.yml
- bin/jruby.sh
Aditional patches for `set -u` and POSIX shell compatibility.
> Additional fixes for jruby.sh

- core/pom.rb
- core/pom.xml
- core/src/main/java/org/jruby/RubyConverter.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
- spec/tags/ruby/library/rbconfig/unicode_emoji_version_tags.txt
- spec/tags/ruby/library/rbconfig/unicode_version_tags.txt
https://github.com/jruby/jruby/issues/8661
> Unicode 15.0

- core/src/main/java/org/jruby/Ruby.java
- core/src/main/java/org/jruby/RubyString.java
* Type the cache as containing FString.
* Make FStringEqual wrapper closeable for try-with-resources.
* Clean up FString construction.
* Allow incoming FString to become the cached FString if it wins.
* Allow going straight to cache with ByteList rather than via intermediate RubyString.
* Cache an fstring for each symbol.
> FString logic cleanup

- core/src/main/java/org/jruby/runtime/load/LoadService.java
Propagate Java throwables during load
We have long re-raised Java exceptions during load as LoadError,but this indicates that the problem was with booting up Ruby code or libraries rather than a more fatal Java error.
Also, because we raise LoadError, RubyGems will think that it might be able to help by re-activating the gem in question and re-requiring, which can lead to confusing double loads and duplicate constant definitions.
We considered wrapping with a different exception, like RuntimeError, but that doesn't fix the problem of hiding the
original Java throwable in a non-obvious way. Users can specify the -d flag to print out throwable stack traces during load, but most don't know to do it and it is often inconvenient.
This patch makes the following changes for Java throwables …
> Propagate Java throwables during load without wrapping

- core/pom.rb
- core/pom.xml
- test/mri.core.index
- test/mri/excludes/TestCaseMapping.rb
fixes https://github.com/jruby/jcodings/pull/64
depends on https://github.com/jruby/jcodings/pull/67
> fix a regression in KDDI transcoding

- core/src/main/java/org/jruby/embed/jsr223/JRubyEngine.java
> Implement AutoCloseable on JRubyEngine

- spec/tags/ruby/language/predefined_tags.txt
we started throwing the right error (possibly from API conversion work)
> spec fixed at some point in past

- core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
- test/mri/excludes/TestKeywordArgumentsSymProcRefinements.rb
Fix more corner cases of kwargs from MRI test suite
> Fix more corner cases of kwargs from MRI test suite

- core/src/main/java/org/jruby/RubyIO.java
Fix missing 2 arg for IO#readline
> Fix missing 2 arg for IO#readline

- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/util/StringSupport.java
Fixes for the stack of "potential NPE" reports that have come in recently.
> Fix recent potential NPE reports

- core/src/main/java/org/jruby/ir/targets/indy/BuildDynamicStringSite.java
- core/src/main/java/org/jruby/ir/targets/indy/IndyValueCompiler.java
- spec/compiler/general_spec.rb
There was one reported bug (#8847), one unreported bug (frozen and chilled were flipped), and a lot of error-prone code. This PR fixes all of it.
> Improvements for dynamic string invokedynamic site

- pom.rb
- pom.xml
Maven Central now has a new process for publishing artifacts. This PR contains the necessary changes.
> Migrate to the new Maven Central publishing system

- core/src/main/java/org/jruby/RubyModule.java
- core/src/main/java/org/jruby/ast/executable/RuntimeCache.java
- core/src/main/java/org/jruby/ir/targets/simple/ConstantLookupSite.java
- core/src/main/java/org/jruby/javasupport/JavaPackage.java
- core/src/main/java/org/jruby/runtime/JavaSites.java
- core/src/main/java/org/jruby/util/IdUtil.java
Various fixes to try to get Zeitwerk green on JRuby 10.
See #6781.
> Fixes to improve Zeitwerk support

- core/src/main/java/org/jruby/RubyIO.java
- core/src/main/java/org/jruby/ir/interpreter/Profiler.java
- core/src/main/java/org/jruby/ir/passes/BasicCompilerPassListener.java
- core/src/main/java/org/jruby/util/ShellLauncher.java
- core/src/main/java/org/jruby/util/io/EncodingUtils.java
The handful of NPE issues found by the SAST tool in #8840 are worth a look, so I'm fixing them here.
> Improvements based on SAST null reference reports

- lib/pom.rb
- lib/pom.xml
> Update strscan to fix number scanning at nonzero offset

- core/src/main/java/org/jruby/RubySymbol.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalCommon.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalDumper.java
- core/src/main/java/org/jruby/runtime/marshal/MarshalLoader.java
- core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java
- spec/ruby/core/marshal/dump_spec.rb
- spec/ruby/core/marshal/shared/load.rb
Loading was implemented but dumping wasn't.
> Implement ruby2_keywords_hash dumping

- core/src/main/java/org/jruby/RubySymbol.java
A few small tweaks to the symbol table.
> Symbol table tweaks

- core/src/main/java/org/jruby/RubyBinding.java
- spec/ruby/core/marshal/dump_spec.rb
> Make Binding unmarshalable

- core/src/main/java/org/jruby/embed/internal/ConcurrentLocalContextProvider.java
- core/src/main/java/org/jruby/embed/internal/ThreadLocalContext.java
- core/src/main/java/org/jruby/embed/internal/ThreadSafeLocalContextProvider.java
- core/src/test/java/org/jruby/embed/internal/ThreadLocalContextTest.java
Re-push of https://github.com/jruby/jruby/pull/8483
> Fix memory leak in Concurrent/ThreadSafeLocalContextProvider

- .github/workflows/ci.yml
Broke some things merging this over from 9.4.
> Fixes for multiplaform rake targets on CI

- USERS.md
Also tidied the formatting and templates to make it easier for others to add new ones and easier to scan through and see the different products/companies.
> Add users entry for GoCD
