jruby/jruby

core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyEnumerable.java, core/src/main/java/org/jruby/RubyEnumerator.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/runtime/JavaSites.java
There are several changes here to avoid uncached method lookups along hot paths:
* All uses of RubyBasicObject.isBuiltin except for two have been replaced with CachingCallSite.isBuiltin. The two that remain are for the IO stream wrappers and are not valuable to cache. This came up in a profile of RubyKon where Array#any?'s uncached isBuitin must be on a hot path.
* All uncached method calls in RubyEnumerable are replaced by CallSite.call, including the various callEach forms. These sites are localized as much as possible to avoid conflicts, but will still churn quite a bit in a typical application that has many Enumerable implementers. Long-term we should move Enumerable to a Ruby implementation that can be split and specialized.
In addition, in RubyEnumerable all lambdafiable block …
=> Avoid uncached isBuiltin and uncached calls in Enumerable

core/src/main/java/org/jruby/ir/targets/simple/NormalInvokeSite.java, core/src/main/java/org/jruby/runtime/invokedynamic/MathLinker.java
Numeric operators with a literal long-ranged integer or double-ranged float on the RHS attempt to dispatch directly without an object, to avoid type-checking an incoming boxed Fixnum or Float object. However when the primitive type does not match the type of the LHS, we fell back to slow-path uncached invocation at indy call sites.
This patch instead falls back on "normal" invocation, currying the boxed number as the sole argument to a second call site's invoker. This allows these primitive numeric ops to fall back to fully optimizable object-based dispatch.
=> Fallback primitive numeric ops to object dispatch

core/src/main/java/org/jruby/RubySymbol.java
In #5837, only `getSymbol(ByteList bytes, boolean hard)` method was modified, and its similar method, `getSymbol(ByteList bytes, ObjBooleanConsumer<RubySymbol> handler, boolean hard)` was not modified.
I think the method has a potential bug, so I fixed it.
=> Fix inconsistency in #5837

core/src/main/java/org/jruby/RubyString.java, test/mri/excludes/TestM17N.rb
This fixes failing [TestM17N#test_setbyte_range](https://github.com/jruby/jruby/blob/master/test/mri/ruby/test_m17n.rb#L1534-L1542) .
And sample.rb produces the same output.
```
s = "\xE3\x81\x82\xE3\x81\x84".dup.force_encoding("UTF-8")
s.setbyte(0, 0x4f7574206f6620636861722072616e6765)
p s
```
```
% ruby -v sample.rb
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
"e\x81\x82い"
```
```
% ruby -v sample.rb
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-09-03 ffffffffff OpenJDK 64-Bit Server VM 11.0.2+9 on 11.0.2+9 +jit [darwin-x86_64]
"e\x81\x82い"
```
=> Fix failing TestM17N#test_setbyte_range

lib/ruby/stdlib/jruby/compiler/java_class.rb, spec/jrubyc/java/annotation_spec.rb
```rb
require 'java'
java_import 'javax.ws.rs.Path'
java_import 'javax.ws.rs.GET'
java_import 'javax.ws.rs.Produces'
java_package 'com.headius.demo.jersey'
class HelloWorld
java_signature "@GET public java.lang.String cliched_message2()"
def cliched_message2
"Hello World"
end
end
```
```txt
...
@GET public java.lang.String cliched_message2() {
...
```
```txt
...
@GETpublic java.lang.String cliched_message2() {
...
```
Note no space
This PR fixes the space and formats all annotations alike
=> jrubyc: make valid java code when using annotations in java_signature

core/src/main/java/org/jruby/RubyArray.java, test/jruby/test_array.rb
In #6371 we saw that adding elements to the array while doing a `delete_if` iteration would end up skipping later elements. This was due to us memoizing the initial length of the array; elements added during iteration did not increase this length, so we would stop iterating prematurely.
The fix here matches CRuby, acquiring the array's new length for each iteration.
A test is provided in the JRuby suite but not in ruby/spec, due to the unspecified nature of this behavior.
=> Handle modification during delete_if iteration

core/src/main/java/org/jruby/Main.java
This is a cherry-pick of the crucial commit from #6213 that
should also fix #6379, where users reported that at_exit and
other "clean shutdown" hooks were improperly running during a
"hard shutdown" using `exit!`.
See c941c41 for the original commit and https://github.com/jruby/jruby/issues/6379#issuecomment-694328219 for a discussion of this fix.
=> Remove teardown hook to allow hard shutdown

core/src/main/java/org/jruby/util/JRubyClassLoader.java, core/src/main/java/org/jruby/util/cli/Options.java
This allows customizing the temp jar unpacking independently of the java.io.tmpdir location.
See #6314 and probably others related to temp locations with varying permissions.
=> Add an option for specifying the nested jar temp location

core/src/main/java/org/jruby/ext/jruby/JRubyUtilLibrary.java, spec/java_integration/utilities/jruby_util_spec.rb
I'm not sure why we've never done this before, but since there's
really no way to synchronize against an object's Java monitor from
Ruby this API seems like a gap in JRuby. Here I've added the
following JRuby utility functions:
* JRuby.synchronized(arg) {} which works like Java's synchronized
statement
* JRuby.wait(arg [, millis [, nanos]]) like Object.wait
* JRuby.notify(arg) and notifyAll(arg) like Object.notify[All]
This question came up in the JRuby chat, and it seems like a
useful and appropriate addition to the JRuby module.
=> Expose Java's built-in monitor synchronization as a JRuby API

core/src/main/java/org/jruby/runtime/callsite/ProfilingCachingCallSite.java
volatile isn't thread-safe, use AtomicInteger instead
=> synchronize totalMonomorphicCalls

lib/ruby/stdlib/rubygems/defaults/jruby.rb
have cleaned up unused parts in RG's *defaults/jruby.rb*, this is the only questionable piece.
WindowsPOSIX impl already `return 0` from `Process.uid` the patch should not be needed, 
the only place RGs uses `Process.uid` is for the cache check: https://github.com/rubygems/rubygems/blob/v3.0.6/lib/rubygems/source.rb#L120 which should not matter.
was thinking maybe this is there simply as a desired side-effect? https://github.com/jruby/jruby/commit/8a898fb50edc3af78c5832c484b3af5774384040
=> remove redundant Process.uid patch on windows

core/src/main/java/org/jruby/RubyThread.java, spec/regression/GH-6405_race_in_interruptible_lock_acquisition.rb
There's a race doing the lock add after the executeTask, since a thread event could interrupt the flow and bypass that logic. A finally would not be appropriate, since an interrupted attempt to acquire the lock would then stil add it. Instead we just move the lock add immediately after lockInterruptibly. If we reach this point, the lock is locked by the current thread, and must be added.
I am looking over the rest of the lock management code in Thread to see if there's other places that could be a risk, but this appears to fix the issue reported in #6405 and probably fixes the issue in #6326.
=> Make sure locks are added immediately after acquisition

core/src/main/java/org/jruby/RubyBignum.java, core/src/main/java/org/jruby/RubyNumeric.java, core/src/main/java/org/jruby/ext/ffi/Util.java
This adds ulong versions of the numeric-to-long conversion methods
that allow ulong-ranged values to be coerced to a Java long.
Callers must take care to use the resulting long correctly, since
Java will always see it as signed.
Added primarily to support ulong use cases in FFI, and fixes #6376
and a test commented out due to jnr/jffi#87.
The tests in question can be enabled via the following patch:
```diff
diff --git a/spec/ffi/struct_spec.rb b/spec/ffi/struct_spec.rb
index 70e60c15a9..b5e262a04a 100644
--- a/spec/ffi/struct_spec.rb
+++ b/spec/ffi/struct_spec.rb
@@ -365,17 +365,17 @@ module StructSpecsStructTests
int_field_test(:int, [ 0, 0x7fffffff, -0x80000000, -1 ])
int_field_test(:uint, [ 0, 0x7fffffff, 0x80000000, 0xffffffff ])
int_field_test(:long_long, [ 0, 0x7fffffffffffffff, …
```
=> Allow ulong range values to coerce to long bits

core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java, core/src/main/java/org/jruby/javasupport/binding/MethodInstaller.java
The existing logic will never bind any methods declared on a non-
public superclass, but this is incorrect behavior if the subclass
is public. A public subclass will expose public methods from any
superclass, regardless of the superclass's visibility, so we need
to also bind those methods.
There are two changes here:
* Allow methods to be gathered from non-public superclasses if the
target class is public.
* Allow those methods to be bound even if there's no definition on
the target class (no so-called "local method")
This fixes #6197
=> Allow public methods from non-public superclasses to bind

core/pom.rb, core/pom.xml
This long-standing bug allows a null key to get into the list of
keys when using the `poll` selector. One of the elements in the
internal array of keys is expected to be null to reserve a spot
for an additional poll file descriptor, but null elements should
never be returned in the keys list.
=> Update enxio to omit poll fd from key list

core/src/main/java/org/jruby/ext/date/RubyDate.java, test/jruby/test_date.rb
This is a regression since `Date`/`DateTime` where moved to native in 9.2.
In JRuby 9.1 we used to store the offset as it's returned by `Date#offset` (usually a `Rational`), 
however on the native side we now store `* DAYS_IN_SECONDS` an an integer.
The change here restores 9.1 behaviour.
resolves GH-6385
=> [fix] Date/DateTime loosing offset on marshal

core/src/main/java/org/jruby/ext/date/RubyDate.java, test/jruby/test_time.rb
=> Fixes #6428: Date._strptime raises Java exception on invalid argument

core/src/main/java/org/jruby/platform/Platform.java, core/src/test/java/org/jruby/platform/PlatformTest.java
Accidentally I found a bug in `Platform.initPlatform()`.  On Windows it returns `UnixPlatform` even though it has following logic:
```
private static Platform initPlatform(){
try {
if (IS_WINDOWS)
return new NTPlatform();
```
It turns out that ordering of static variables is matters.
When debugging it turns out that `Platform.OS` is null and IS_WINDOWS is not correctly computed.
Simplest solution is to just move `INSTANCE` below `OS` and `IS_WINDOWS`.
Tested on Oracle JDK 8 and Open JDK 11.
=> Fix platform type inititilization

core/src/main/java/org/jruby/ext/date/RubyDate.java, test/jruby/test_time.rb
back-port of https://github.com/jruby/jruby/pull/6429
=> [fix] Date._strptime raises Java exception on invalid argument

lib/pom.rb, lib/pom.xml
expected to avoid left-over reflection warnings on Java 9+
https://github.com/jruby/jruby-openssl/releases/tag/v0.10.5
=> update jruby-openssl to 0.10.5

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/BSwitchInstr.java, spec/ruby/language/case_spec.rb
Optimized Fixnum switch is only possible when we have a `case`
value and the `when` values are all int-ranged literal numbers.
The NPE in #6440 was due to us also trying to optimize homogeneous
int case/when even if the case value was null (omitted in source).
This patch limits the optimized switch generation to situations
where we have a non-null `case` value.
Fixes #6440.
=> Do not optimize case with null value to switch

core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/runtime/Helpers.java, core/src/main/java/org/jruby/runtime/MethodBlockBody.java, spec/tags/ruby/core/enumerable/collect_tags.txt, spec/tags/ruby/core/enumerable/map_tags.txt, spec/tags/ruby/core/hash/each_pair_tags.txt, spec/tags/ruby/core/hash/each_tags.txt
This fixes issue #5896 by always splatting out the arguments if possible.
I was surprised that `Helpers.restructureBlockArgs()` is only used here. Not sure why this is a special case.
Overall I'm not 100% sure about this fix. But since I couldn't get the tests to all run locally I'm opening up this PR in hopes that CI can reveal issues or someone here can tell me what I'm missing.
=> Fix yielding to methods that take two params from Hash#each

lib/pom.rb, lib/pom.xml
Upgrade webrick to 1.6.1 which fixes CVE-2020-25613
=> Update webrick to 1.6.1

core/src/main/java/org/jruby/RubyProcess.java
In #6466 we see that the thread from a Process::detach is raising
an error when the waitpid fails with an error. This does not
appear to match the logic in MRI and also breaks if there is a
"raise" hook installed in the system.
This change should better match MRI logic for the detach thread
and avoid the hook issue reported in #6466. It does not address a
separate bug in the trace hook logic when no Ruby frames are
available.
=> Simplify detached process thread logic

README.md
It was always OR but the language in the README did not make that clear.
Addresses questions raised in #6470.
=> Clarify license terms to be OR not AND

core/pom.rb, core/pom.xml, core/src/main/java/org/jruby/RubyFileStat.java, core/src/main/java/org/jruby/ext/socket/MulticastStateManager.java, core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java, core/src/main/java/org/jruby/ext/socket/RubySocket.java, pom.rb, pom.xml, test/jruby/test_file.rb
This picks up changes to the automatic module name from
jnr/jffi#67 but also updates JNR projects across the board to grab
all recent bug fixes.
=> Update JNR projects to latest

core/src/main/java/org/jruby/java/invokers/InstanceMethodInvoker.java, core/src/main/java/org/jruby/java/invokers/RubyToJavaInvoker.java, core/src/main/java/org/jruby/javasupport/binding/Initializer.java, core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java, spec/java_integration/interfaces/java8_methods_spec.rb
JRuby simply ignored any instance methods on interfaces, however this is incorrect due default methods.
resolves https://github.com/jruby/jruby/issues/6479
=> [ji] bind interface default methods

core/src/main/java/org/jruby/RubyProcess.java, spec/ruby/core/process/constants_spec.rb, spec/ruby/core/process/getrlimit_spec.rb, spec/ruby/core/process/setrlimit_spec.rb
See #6491 and https://github.com/rubygems/rubygems/issues/4129 for discussions of this issue.
We *could* also do this disabling when running on a platform that does not support our FFI, but that would increase the compatibility gap on such platforms.
=> Disable rlimit features on Windows

core/src/main/java/org/jruby/RubyProcess.java
As described in #6477 it appears that a successful waitpid under
some circumstances is leaving errno set, either to 11 (EAGAIN) or
in some situation 2 (ENOENT). The reasons for this unsanitary
errno handling are not clear, but the logic in JRuby should at
least be checking for a -1 retval before assuming there was an
error. This commit makes that modification which should avoid the
error reported in #6477.
This constitutes a "fix" of sorts, but we still don't know why the
cicumstances in #6477 lead to this errno result.
Fixes #6477.
=> Check the retval of waitpid before errno

core/src/main/java/org/jruby/RubyTime.java
This contains one or more fixes for timezone handling in 2.6 compatibility.
See #6488, which these fixes are intended to resolve.
=> Timezone fixes for 2.6 logic

core/src/main/java/org/jruby/RubyArray.java
Fixing shuffle at first for #6499 but sample appears to have the same problem.
=> Fix Array shuffle and sample arity checking

core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/java/proxies/ArrayJavaProxy.java, core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java, core/src/main/java/org/jruby/javasupport/Java.java, core/src/main/java/org/jruby/javasupport/JavaUtil.java, core/src/main/java/org/jruby/javasupport/ext/JavaLang.java, core/src/main/java/org/jruby/javasupport/ext/JavaNio.java, core/src/main/java/org/jruby/javasupport/ext/JavaTime.java, core/src/main/java/org/jruby/javasupport/ext/JavaUtil.java, core/src/main/java/org/jruby/javasupport/ext/JavaUtilRegex.java, core/src/main/java/org/jruby/util/Inspector.java, core/src/main/java/org/jruby/util/RubyStringBuilder.java, spec/java_integration/addons/throwable_spec.rb, spec/java_integration/types/array_spec.rb, spec/java_integration/types/inspect_spec.rb, spec/java_integration/types/map_spec.rb
This is, I believe, my 3rd attempt on Java types having usable `inspect` (last one [2 years ago](https://github.com/jruby/jruby/pull/5219) actually got reverted).
It's frustrating working with Java integration out-of-the-box (unless you alias all `alias inspect to_s`).
For example a rspec failure on a Java type will not get you anything useful: `#<Java::JavaTime::Instant:0xeded048>`
Even with a simple `inspect` -> `toString` alias (a previous attempt) I still find myself figuring out types manually.
e.g. `"[]"` is it an empty Ruby Array instance or a Java collection instance?
The proposal here would be to define simple inspect (Java#toString) on intermediate Java types: primitives, strings, enums (and maybe BigInteger/BigDecimal). This is already a compromise as sometimes it's useful to …
=> [ji] "usable" inspect for core Java types

Gemfile
This avoids the issue reported in #6452 by moving past the broken rspec-expectations version (see rspec/rspec-expectations#1241).
=> Upgrade RSpec to 3.10

core/src/main/java/org/jruby/RubyArray.java
before
```
[1,2,3] # new array
[_,1,2,3,_,_] # extend the array, move ptr by 1
[5,1,2,3,_,_] # unshift
[5,5,1,2,3,_] # unshift 2 = sliding array, but we have to copy all elements
```
after
```
[1,2,3] # new array
[_,_,_,1,2,3] # extend the array, move elements to the right
[_,_,5,1,2,3] # unshift
[_,5,5,1,2,3] # unshift 2, if there's a free capacity, just shift pointers and skip reallocations
```
results
```
before
unshift    172.393  (? 0.6%) i/s -    867.000  in   5.029295s
after
unshift      3.896k (? 2.5%) i/s -     19.760k in   5.075590s (22.8x faster)
ruby 2.7.2
unshift      2.332k (± 4.8%) i/s -     11.809k in   5.078204s
```
script
```
array = []
10_000.times do |i|
array.unshift(i)
end
```
=> optimize Array#unshift

core/src/main/java/org/jruby/ext/pathname/RubyPathname.java
Opening a PR to verify if the tests pass via CI, because I haven't been quickly able to run the tests locally.
I also wonder if I need to "sync" the Ruby specs (see #6519 and https://github.com/ruby/spec/pull/822), or add something in the test suite for this.
=> Make Pathname#inspect behave like other Ruby implementations (fixes #6519)

lib/ruby/stdlib/monitor.rb
The logic in MonitorMixin#mon_synchronize is broken as described
in ruby/monitor#2 due to the improper use of handle_interrupt.
This patch fixes the issue by ensuring the entire body of the
method is protected from interrupts except for the yield to the
incoming block. This avoids the ensure being interrupted, leaving
the monitor locked.
Fixes #6526
=> Fix interrupt handling in synchronize

core/src/main/java/org/jruby/ext/stringio/StringIO.java
See https://github.com/jruby/jruby/pull/6183
Fixes #6528.
=> Backport StringIO encoding fix

core/src/main/java/org/jruby/runtime/Helpers.java, core/src/main/java/org/jruby/util/ShellLauncher.java
The primary fix here is to do the same argument processing and executable searching for `popen` that we do for `system` by aligning the relevant logic. The other fix is to handle another special case JDK error when launching a process using a path that does not exist.
This will fix #6516 once finished.
=> Improvements for popen process launch in Windows

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyThread.java, core/src/main/java/org/jruby/ext/monitor/Monitor.java, core/src/main/java/org/jruby/ext/monitor/MonitorLibrary.java, core/src/main/java/org/jruby/ext/thread/ConditionVariable.java, core/src/main/java/org/jruby/ext/thread/Mutex.java, core/src/main/java/org/jruby/ext/thread/Queue.java, core/src/main/java/org/jruby/ext/thread/SizedQueue.java, core/src/main/java/org/jruby/runtime/JavaSites.java, lib/ruby/stdlib/monitor.rb
See https://github.com/ruby/ruby/pull/2576 which did the same for CRuby 2.7.
This eliminates the need for the monitor.rb fixes in #6527 and ruby/monitor#2, plus synchronize will perform significantly better than the nested block implementation.
This may be safe to include in 9.3 even though the compatibility level is 2.6.
=> Move Monitor to native

core/src/main/java/org/jruby/ext/fiber/FiberQueue.java, core/src/main/java/org/jruby/ext/fiber/ThreadFiber.java
The logic here is designed to simulate a single execution stack by
forwarding any interrupt exceptions during a blocking fiber
operation to the target fiber, since it is "current" and should be
the one to handle any thread-level event. Originally the logic
forwarded any exception received while waiting for a fiber
response to the fiber and looped back to wait for a result. This
had the side effect of locking both the caller and the target
fibers into an endless exception-forwarding loop if the interrupt
were timed such that both were in their fiber queue push/pop
logic. Because both sides thought the other was the active side,
the exception would be forwarded forever.
The new logic will only attempt to forward an interrupt exception
once, with one additional wait for a valid response or a …
=> Rework raise interrupt handling at fiber edges

core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java, test/jruby/test_socket.rb
this PR improves Redis support for their TCP keep-alive implementation https://github.com/jruby/jruby/issues/6541
also fixes a bug, getsockopt returns zero if the passed constant isn't supported. It should always be a SocketOption or an exception.
=> [socket] improve keep alive support

core/src/main/java/org/jruby/RubyFixnum.java, core/src/main/java/org/jruby/RubyFloat.java, core/src/main/java/org/jruby/RubyObjectSpace.java, core/src/main/java/org/jruby/runtime/ObjectSpace.java, core/src/main/java/org/jruby/util/Numeric.java
This commit improves the emulation of CRuby's fixnum and flonum tagged pointers.
Float emulation of flonum:
* Floats within flonum range will produce a flonum `object_id` that is reversible by ObjectSpace._id2ref.
* Float objects with equivalent values within flonum range are considered identical via `equal?`.
* RubyFloat.eql overrides the default RubyBasicObject.eql dynamic dispatch, as in RubyFixnum.
Fixnum emulation of fixnum:
* Fixnum objects with equivalent values within fixnum range *only* are considered identical via `equal?`. Previously all equivalent Fixnum objects were considered `equal?`.
Impact to existing behavior:
* Floats within range will now behave like flonums on CRuby rather than as independent objects.
* Fixnums outside of fixnum range will behave like independent …
=> Improve tagged pointer emulation

core/src/main/java/org/jruby/RubyProcess.java, core/src/main/java/org/jruby/RubyThread.java
The rb_waitpid function in CRuby does not actually trigger an
exception raise when the waitpid errors, leaving that to callers
to decide. Because ours did so, any errors during the
Process.detach call to waitpid would trigger the raise event hook
and unfix #6466.
This change moves the errno check outside of our rb_waitpid
equivalent, making it safe to use in the Process.detach thread.
Fixes #6466 again.
=> Handle errors in Process.detach properly

core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/util/io/ChannelFD.java, core/src/main/java/org/jruby/util/io/FilenoUtil.java
The `fstat` system call raises EPERM when run against an inotify file descriptor under Windows Subsystem for Linux, as reported in #6129.
Rails uses inotify support via rb-inotify, which recently started using `IO.new` to wrap the inotify file descriptor. Our logic for `IO.new` tries to use `fstat` in two places, which causes rb-inotify to fail.
There are updates to WSL that purport to improve inotify support, but I have been unable to find a rig that works properly.
This PR makes the following changes in an attempt to deal with the issue:
* When checking for fd liveness in FilenoUtil, we prefer `fcntl` except on Windows (which only has `fstat`). This means we use `fcntl` under WSL, avoiding the EPERM.
* Ignore any exception raised when using `fstat` to determine the file type, which we …
=> Work around EPERM fstat error for inotify under WSL

core/src/test/java/org/jruby/test/TestProcessSpawn.java
test-case similar to the behavior on #6477 except it would constantly raise `ENOENT` (before the #6489 fix)
*NOTE: seen this at Logstash's https://github.com/elastic/logstash/pull/12519, interestingly a test run would only fail when using the gradle test worker but not from a cli `jruby -S rspec` (which I haven't figured out why)*
=> [test] spawn+detach raising (previous) posix error

core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/util/IOChannel.java
* Avoid copying the source bytes if the source ByteBuffer has an accessible array.
* Update the source ByteBuffer position with the number of bytes the write call reports as written.
* Only loop on writes when the target is a real IO.
The last item fixes #6555.
=> IO.copy_stream fixes

core/src/main/java/org/jruby/RubyModule.java
This PR will track work to make our two types of "transparent" delegating method wrappers compatible with refinements.
As described in #6547, the wrapper methods that the Synchronized module uses interfere with refinement logic due to the latter's dependence on its own wrapper. When the two are active at the same time, the method lookup process may fail to locate methods that are clearly there, due to not knowing how to access the original unwrapped method properly.
The first fix here is a one-off that pre-unwraps all DelegatingDynamicMethod wrappers before proceeding to the rest of the refined logic, but the issue is systemic; the synchronized wrappers cannot be perfectly transparent, and so they interfere with method table logic that depends on seeing the original method. An alternative …
=> Make sync and profiling method wrapper logic work with refinements

core/src/main/java/org/jruby/ir/passes/AddCallProtocolInstructions.java, core/src/main/java/org/jruby/runtime/BlockBody.java, spec/ruby/core/proc/shared/call.rb
Our call logic was only using first incoming args[0] is arity was 1
and there is no kwrest(**a).  This should be arity of 1 and the lack of
presence of any kwargs at all.
Intuitively, we know if we have kwargs at the callsite and the block
accepts kwargs...we should pass them forward.
We also know that procs will pass any extra args to the proc whether
the proc is defined to accept them or not.  As opposed to lambdas which
would error because you are passing the wrong number.
So I feel pretty good about this fix but I am very leery on landing this
the day before a release.  Blocks are tricky internally in Ruby.
=> Fixes #6540. difference with block keyword arguments.

lib/ruby/stdlib/rubygems/defaults/jruby.rb
The setup command is used when upgrading RubyGems, and pristine
is a clean reinstall. Neither honor the settings for "install" or
"update" so we need to force them too.
See rubygems/rubygems#4404
=> Expand env-shebang to setup and pristine

core/src/main/java/org/jruby/util/IOOutputStream.java
The OutputStream returned by RubyIO.getOutputStream encodes all
strings as ASCII-8BIT which makes it incompatible with any IO that
has an incompatible external encoding. That is a separate bug, but
it affects uses of IOOutputStream that should be ok.
IOOutputStream aggregates an encoding to use, so it should be able
to pass properly-encoded strings through to the IO. This change
avoids using the stream from getOutputStream and instead calls
RubyIO.write directly.
This fixes the ASCII-8BIT failure noted in ruby/psych#481.
=> Call write directly rather than through stream

core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/RubyInteger.java, core/src/main/java/org/jruby/RubyThread.java, core/src/main/java/org/jruby/util/ByteList.java, core/src/main/java/org/jruby/util/IOInputStream.java, core/src/main/java/org/jruby/util/IOOutputStream.java, core/src/main/java/org/jruby/util/io/EncodingUtils.java, core/src/main/java/org/jruby/util/io/OpenFile.java
This PR tracks work to address #6589 by adding allocation-free RubyIO read and write paths.
=> Provide direct byte[] read and write for RubyIO

core/src/main/java/org/jruby/RubyRational.java, core/src/main/java/org/jruby/RubyString.java, core/src/test/java/org/jruby/test/TestRubyString.java
currently, there's no easy way to do a `RubyString#split` from a Java extension (due split writing a back-ref for the frame).
the idea here is to provide a "strongly" typed API that Java consumers could leverage wout shooting themselves in the :foot:
=> [feat] support RubyString#split for Java (exts)

core/src/main/java/org/jruby/embed/jsr223/JRubyEngine.java, core/src/test/java/org/jruby/embed/jsr223/JRubyEngineTest.java
Basically just adding the topmost Ruby frame's file and line to the message, to match e.g. Jython.
Existing tests do not seem to supply a filename for the top script, so I can only confirm the nameless version of this message is working:
```
[INFO] Running org.jruby.embed.jsr223.JRubyEngineTest
javax.script.ScriptException: Error during evaluation of Ruby at <script> at 2: (RuntimeError) hello from ruby
```
Fixes #6560
=> Improve JSR-223 exception messages

core/src/main/java/org/jruby/ext/socket/Addrinfo.java, core/src/main/java/org/jruby/ext/socket/SocketUtils.java
Numeric hosts can be converted to a byte sequence for address
lookup.
Fixes #3883
=> Accept numeric host

core/pom.rb, core/pom.xml, pom.rb, pom.xml
This bumps ASM to 9.1 as well since that was the main reason for
updating jnr-ffi.
Driven by updating ASM for #4835.
=> Update jnr-ffi and dependents

bin/jruby.bash
Detecting module support based on the existence of the jmods
directory was fragile for at least two reasons:
* The jmods directory is only present in some builds of the JDK
(not JRE) that can be used to jlink new runtime environments.
* Some distributions of the JDK may omit or relocate this
directory, such as Nix's version (#6608).
Instead we detect modules using two other mechanisms that should
reliably work on all modularized Java runtimes:
* Check for JAVA_HOME/lib/modules, generated by the jlink process.
* Check for a JAVA_HOME/release file with a MODULES entry.
See https://stackoverflow.com/questions/66601929 for a summary of
detection mechanism.
Fixes #6608.
jruby-launcher will need a matching update.
=> Detect modules more robustly

lib/pom.rb, lib/pom.xml
=> Only include gems in bundled or default

core/src/main/java/org/jruby/ext/zlib/JZlibInflate.java, spec/tags/ruby/library/zlib/deflate/deflate_tags.txt
Fixes #6606
Need to investigate the surrounding logic, since it no longer matches CRuby and this patch is a bit of a best guess at what is intended. The basic issue was that we were appending extra bytes on the input to the decompressed output. CRuby, on the other hand, just ensures the input buffer contains only those extra bytes, allowing you to pass the same input to inflate repeatedly to get multiple compressed chunks out of it.
We do not support this behavior, and the related test does not pass (this PR neither fixes nor breaks any CRuby zlib tests, as far as I could see).
=> Return only inflated content from Zlib.inflate

core/src/main/java/org/jruby/ast/HashNode.java, core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/RuntimeHelperCall.java, core/src/main/java/org/jruby/ir/operands/Hash.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, spec/tags/ruby/language/method_tags.txt
This fixes the problem reported in #6564.
It introduces a problem by not passing:
```ruby
def bar(a)
puts "BAR #{a}"
end
a = {}
bar(**a)
```
In Ruby 2.6 this will receive the empty hash as parameter 'a' in 'bar'.  In Ruby 3.0 this will be an arity mismatch.  I opted to break 2.6 compatibility because bar(**{}, **{}) will arity error (which is inconsistent) and 3.0 corrects this inconsistency.  I am comfortable with encouraging people to not expect this behaviour.  Anyone doing this will need to update their library/application anyways.
The mechanics of the fix is to look at any **a passed at the callsite and if it is empty we will not pass it along.  If it is not empty we do.  This is option number 2 in #6564.  Not ideal in that we add some more interpreted logic for callsites with **a …
=> Fixes #6564. Passing **kw to def with no args should work

core/src/main/java/org/jruby/runtime/callsite/CachingCallSite.java
During the various deprecations and undeprecations of this method,
it was inadvertently broken due to switching to a cacheAndGet path
that does not set the builtinCache field. Since call sites used
for isBuiltin are usually *only* used for isBuiltin, I modified
this to just use the standard cache field.
Relates to #6628
=> Unbreak CachingCallSite.isBuiltin

core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/RubyObject.java, core/src/main/java/org/jruby/RubyStruct.java
These are small improvements for the `dig` method:
* Arity-split up to three. These will be very common arities. We could split further in the future but with greatly diminishing returns.
* Make known types (Array, Hash, Struct) use an iterative algorithm to dig out successive values. This avoids recursion for known types.
This work was originally intended to fix #6628 but the performance issue there was primarily due to poor performance in MethodHandle.asCollector: #6630.
Benchmark numbers using just this branch improve for 1-3 arguments but then the indy numbers drastically fall off due to #6630 (see benchmark there).
No indy, before:
```
dig-01     38.572M (± 4.8%) i/s -    195.184M in   5.072156s
dig-02     40.883M (± 9.2%) i/s -    202.908M in   5.019322s
dig-03     29.216M (± 6.0%) …
```
=> Dig improvements

core/src/main/java/org/jruby/javasupport/ext/Kernel.java
Improves performance of these accesses by 10x:
Before:
```
$ rvm jruby-9.2.16.0 do jruby -e "loop { t = Time.now; i = 0; while i < 10_000_000; i+=1; java; java; java; java; java; end; puts Time.now - t }"
4.378078
4.057417
```
After:
```
$ jruby -e "loop { t = Time.now; i = 0; while i < 10_000_000; i+=1; java; java; java; java; java; end; puts Time.now - t }"
0.49563
0.451077
0.558907
```
=> Cache package after acquisition

.travis.yml, core/pom.rb, core/pom.xml, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java, core/src/main/java/org/jruby/ir/targets/indy/DRegexpObjectSite.java, core/src/main/java/org/jruby/ir/targets/indy/InvokeSite.java, core/src/main/java/org/jruby/runtime/Helpers.java, spec/compiler/general_spec.rb
It turns out that MethodHandle.asCollector is very slow for
subclasses of Object[] due to double-allocation and double-copying
done by the OpenJDK logic. To avoid this overhead, we use 10-wide
overloads of our own collector utility functions and pass to
Binder.collect, which now supports the
MethodHandles.collectArguments decorator.
Fixes #6628
=> Provide a collector for indy varargs boxing

core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java, core/src/main/java/org/jruby/runtime/Helpers.java, spec/compiler/general_spec.rb
When we generate the invoker class for arity-split methods, we
only generate overrides of (DynamicMethod subtype) JavaMethod.call
signatures that align with the split signatures, including whether
or not they receive a block. This allows the base JavaMethod to
maintain a minimal set of base implementations, with unimplemented
arities and block paths falling back on default implementations.
Unfortunately due to our indy dispatch logic only being smart
enough to directly bind the lowest specific arity, this can break
inlining for all other arities if the block/no-block signatures
do not match, falling back on the base implementations in
JavaMethod.
This patch improves the "generic" DynamicMethod.call binding to
avoid passing a block when the target methods is backed by a
direct native …
=> Improve inlining of varargs path for split methods

bin/jruby.bash
See https://github.com/jruby/jruby/pull/6615#pullrequestreview-623982563
The quoting around `$JAVA_HOME` was inadvertently removed while fixing module detection in #6615. The review linked above points out that this causes problems when the JDK is installed in a path with spaces. This is not common on unixy environments, and the bash script is not used on Windows where it is more common, but the regression is real.
This PR restores the quoting around `$JAVA_HOME` to fix the issue.
=> Restore quotes around module detection JAVA_HOME

bin/jruby.bash, test/jruby/test_command_line_switches.rb
This PR fixes #6637 by fully resolving any symlinks between the `java` command (found from `$JAVACMD` or `java` in PATH) before using that command's path to determine `$JAVA_HOME`.
The issue affects systems without `$JAVA_HOME` set, but that have a `java` command in PATH that resolves to a `$JAVA_HOME/bin/java` through a series of symlinks (e.g. CentOS).
This PR also exports `JRUBY_HOME`, `JAVACMD`, and `JAVA_HOME` so they will be seen by the JRuby process and subprocesses, avoiding recalculating this home or accidentally using a different JDK for additional JRuby launches.
I have added a test case for the symlink situation.
=> Resolve symlinked java command to find home

core/src/main/java/org/jruby/RubyRegexp.java, core/src/main/java/org/jruby/RubyString.java, spec/ruby/core/string/split_spec.rb
String#split appears to do nothing with the context backref slot
except using it to receive the MatchData from a regexp match and
eventually clearing it to nil. This patch sets up a thread-local
IRubyObject[] holder to use for that out value and avoids using
the context backref at all except for clearing it at the end.
This fixes #6160 by avoiding all reads of the context backref. It
may still cause problems for other backref-reading functions that
run concurrently and see the clearing to nil unexpectedly.
=> Reduce backref usage in split

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/IRVisitor.java, core/src/main/java/org/jruby/ir/Operation.java, core/src/main/java/org/jruby/ir/instructions/LoadBlockImplicitClosureInstr.java, core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java, core/src/main/java/org/jruby/ir/interpreter/StartupInterpreterEngine.java, core/src/main/java/org/jruby/ir/persistence/IRReaderStream.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/runtime/Helpers.java
* Avoid retrieving the implicit block from the frame if it is not
needed for a yield.
* When the implicit block is needed, load it directly from the
block binding rather than from the frame stack, avoiding pushing
the frame.
This speeds up leaf blocks that do not otherwise need a pushed
frame by many times... up to 30x for a simple block with no yield.
=> Reduce frame overhead for leaf blocks

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyArgsFile.java, core/src/main/java/org/jruby/RubyGlobal.java, core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyRegexp.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/ext/pathname/RubyPathname.java, core/src/main/java/org/jruby/ext/stringio/StringIO.java, core/src/main/java/org/jruby/runtime/Helpers.java, core/src/main/java/org/jruby/runtime/MethodIndex.java, core/src/main/java/org/jruby/runtime/ThreadContext.java
This PR seeks to improve the concurrency characteristics of methods that read or write the "frame global" backref variable `$~`.
As seen in #6640 the concurrency issues surrounding backref (#4868) can in some cases lead to internal race conditions we must avoid. In that issue, the frame backref was used during the execution of the main `split` loop, leading to two threads stepping on each other.
The work here will move all internal usage of backref (as an "out of band" data-passing mechanism) to a context-local (essentially thread-local) field, only propagating the resulting match to the frame backref at the end of the method as appropriate. This will essentially eliminate data races surrounding `$~` within our own code. The remaining race will be in user code that opts into consuming …
=> Improve concurrency of $~ adjacent methods

core/src/main/java/org/jruby/RubyException.java, core/src/test/java/org/jruby/test/TestRubyException.java
**HINT: this targets JRuby 9.3 - do not merge till master moves 9.2 into a branch**
will now return a more 'familiar' Java type (Throwable instance)
... like the rest of RubyXXX hierarchy
(e.g. RubyString returning java.lang.String by default)
=> [ji] change RubyException#toJava to convert by default

core/src/main/java/org/jruby/RubyKernel.java
The env hash is now peeled off during processing of the argument
array in ShellLauncher, so this is no longer needed and was not
correct in the first place (should have used a dup of ENV at
best.)
Fixes #6554
=> Do not merge extra env with current env

core/src/main/java/org/jruby/util/ByteList.java
I have a JRuby application that writes data into a `StringIO`. After a certain amount of data, the application throws a long winded exception with stack trace leading to `ByteList::ensure` with exception `Java::JavaLang::NegativeArraySizeException`.
It appears that the code attempts to extend the byte arrray beyond `Integer.MAX_VALUE` length which results in attempting to create a `byte[]` of negative length.
Relevant portion of stacktrace:
```
Java::JavaLang::NegativeArraySizeException:
--
org.jruby.util.ByteList.ensure(ByteList.java:344)
org.jruby.util.io.EncodingUtils.strBufCat(EncodingUtils.java:1712)
org.jruby.util.io.EncodingUtils.strBufCat(EncodingUtils.java:1697)
org.jruby.util.io.EncodingUtils.encCrStrBufCat(EncodingUtils.java:1820) …
```
=> Handle possible ArithmeticException when extending byte store for String

core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/runtime/Helpers.java, core/src/main/java/org/jruby/util/ByteList.java
This is a follow-up to #6670 that audits other locations we allocate arrays.
=> Array max size auditing and fixes

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/ext/socket/Addrinfo.java, core/src/main/java/org/jruby/ext/socket/Ifaddr.java, core/src/main/java/org/jruby/ext/socket/MulticastStateManager.java, core/src/main/java/org/jruby/ext/socket/Option.java, core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java, core/src/main/java/org/jruby/ext/socket/RubyIPSocket.java, core/src/main/java/org/jruby/ext/socket/RubyServerSocket.java, core/src/main/java/org/jruby/ext/socket/RubySocket.java, core/src/main/java/org/jruby/ext/socket/RubyTCPServer.java, core/src/main/java/org/jruby/ext/socket/RubyTCPSocket.java, core/src/main/java/org/jruby/ext/socket/RubyUDPSocket.java, core/src/main/java/org/jruby/ext/socket/RubyUNIXServer.java, core/src/main/java/org/jruby/ext/socket/RubyUNIXSocket.java, core/src/main/java/org/jruby/ext/socket/SocketLibrary.java, core/src/main/java/org/jruby/ext/socket/SocketType.java, core/src/main/java/org/jruby/ext/socket/SocketUtils.java, core/src/main/java/org/jruby/runtime/Helpers.java, test/jruby/test_socket.rb
This is a wholesale duplication of the 9.3 (master at time of
writing) socket implementation into 9.2 to pick up all recent
improvements in the socket library.
This should address #6541 and other socket issues fixed on master.
=> Copy 9.3 socket implementation to 9.2

core/src/main/java/org/jruby/AbstractRubyMethod.java, core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyInteger.java, core/src/main/java/org/jruby/anno/AnnotationBinder.java, core/src/main/java/org/jruby/anno/AnnotationHelper.java, core/src/main/java/org/jruby/anno/JRubyClass.java, core/src/main/java/org/jruby/anno/JRubyMethod.java, core/src/main/java/org/jruby/anno/TypePopulator.java
This PR will fix #5200 by also adding subclasses' bound methods to the mapping table, in one way or another. The initial logic adds a JRubyMethod.implementers list of subclasses to include in the mapping table, but it is fairly naive and does not check if the method is actually overridden. The fix provided would be sufficient, but requires at least one annotation in a given native class to specify a list of implementers to include.
If other experiments don't pan out, we can go with this, but I will try to refine this to only include the actually-overridden methods, and ideally to not require an explicit list of classes.
=> Include overriding classes in backtrace mapping

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/javasupport/Java.java, core/src/main/java/org/jruby/javasupport/JavaPackage.java, core/src/main/java/org/jruby/javasupport/JavaUtilities.java, core/src/main/java/org/jruby/javasupport/ext/Module.java, core/src/main/ruby/jruby/java/core_ext.rb, core/src/main/ruby/jruby/java/core_ext/module.rb, core/src/main/ruby/jruby/java/java_ext.rb, spec/java_integration/packages/include_spec.rb, test/jruby/test_higher_javasupport.rb
also `java_import` was moved to not have these in 2 places (could ditch the whole JI *module.rb* ext file)
the motivation for the move is to have predictable include_package behavior e.g. on Java linking errors.
previously w `include_package`, all `NameError` where rescued and loop continued attempting to load a class with the next package -> effectively creating a weird set of errors where the real cause is unknown e.g. https://github.com/cheald/manticore/issues/87
the changes here make sure only `ClassNotFoundException` is a valid error to continue the loop, alll other `NameError` instances (e.g. caused by `LinkageError`) will be raised promptly.
=> [refactor] move include_package into Java

core/src/main/java/org/jruby/RubyKernel.java, lib/ruby/stdlib/jruby/open3_windows.rb
This duplicates some logic in ShellLauncher but that other logic
splits the command line and tries to pass it as multiple args.
This way works ok and may be more reliable for Open3 cases, plus
it skips all the heinous logic in ShellLauncher.
Fixes #6678
=> Also use shell for commands with a space

.travis.yml
Bundler is included as a default gem in 9.3+ so it is already
available.
=> Do not install bundler during travis builds

core/pom.rb, core/pom.xml
https://github.com/jruby/jruby/issues/6514#issuecomment-752748414:
> We only use the API at build time for our annotation processor
Unfortunately, current `compile` scope used propagates to client project (it isn't _compile-time-only_) and is placed on project's classpath. I can't switch annotation api in the project, but I'd like to consider JRuby upgrade.
I've built and used jruby-core 9.3.0.0-SNAPSHOT to verify that this change would work as I expect it. (I used published snapshot in first place and learnt that it conflicts with the project.)
=> Do not pollute CP with annotation-api

core/src/main/java/org/jruby/util/Dir.java, spec/tags/ruby/core/dir/glob_tags.txt, test/mri/excludes/TestDir.rb
Hi,
This PR updates the `addToResultIfExists` Java method in order to handle the correct file name in the file system. It should close this issue: https://github.com/jruby/jruby/issues/2150.
**note:** This is my attempt to achieve my first contribution to JRuby, so any feedback here would be great.
Thanks
=> Fix Dir.glob with cases

.travis.yml, core/src/main/java/org/jruby/ir/IRClosure.java, core/src/main/java/org/jruby/ir/IREvalScript.java, core/src/main/java/org/jruby/ir/IRScope.java, tool/concurrent-ruby-travis.sh
This has two pieces:
1. Evals only live as a scope as long as they execute.  They should not
be asking the lexical scope they are called in for an id.  This is likely
a portion (or all) of the original reporters problem.
2. Closures in evals should be given out scope ids relative to the eval.
These were going to the eval and then the evals getScopeID would ask its
lexical parent for an ID (which is the scope outside the eval).
=> Fixes #6692.  AIOOBE on evals overflowing closure ids.

core/src/main/java/org/jruby/RubyInteger.java, core/src/main/java/org/jruby/RubyString.java
This logic would always create a new byte[], ByteList, and
RubyString when pulling single-byte characters from a multi-byte
string. This change allows it to use cached ByteList (and byte[])
for those cases if the encoding is UTF-8.
=> Use cached UTF8 single-char bytelists here

core/src/main/java/org/jruby/ext/jruby/JRubyUtilLibrary.java, core/src/main/java/org/jruby/ext/socket/RubyServerSocket.java, core/src/main/java/org/jruby/ext/socket/RubySocket.java, core/src/main/java/org/jruby/java/proxies/JavaProxy.java
While investigating an issue, https://github.com/socketry/falcon/issues/64, elsewhere, I found that in warnings emitted by JRuby, the direct link to a specific **wiki page link** had become **out of date**, and didn't point to the exact page anymore. It **just pointed to the start page**.
With this change, it does again point to the exact pages.
<details>
Here are other files that need a change, please make that change, if you find that before I do. Have a nice day!
</details>
=> Update wiki URLs to point directly to pages in warning messages

core/src/main/java/org/jruby/ir/IRScope.java, core/src/main/java/org/jruby/ir/operands/LocalVariable.java, core/src/main/java/org/jruby/ir/persistence/IRWriterAnalyzer.java, core/src/main/java/org/jruby/ir/persistence/IRWriterEncoder.java, core/src/main/java/org/jruby/ir/persistence/IRWriterStream.java, spec/jrubyc/java/files/for.rb, spec/jrubyc/java/loading_spec.rb, spec/jrubyc/java/method_spec.rb
When using a "for" loop it will not compile of NPE.
Solution is to subtract the depths introduced by for loop scopes so when we decode the local variables our existing logic will then reintroduce the depth offsets of for those same 'for' loops.
=> Fixes #6184. NullPointerException/"class is not compiled Ruby" for loop

bin/jruby.bash
When no JAVA_HOME env is set on MacOS, we do not properly detect
the actual JDK install location. The default `java` command is an
executable in /usr/bin/java that launches the default installed
JDK (usually the highest version). Since it is not a simlink the
logic we use on Linux to dig out the real JAVA_HOME does not work.
This patch uses the `java_home` command when no JAVA_HOME is set.
This command is only available on MacOS as far as I know, though
similar commands exist on other platforms.
Fixes #6726.
The same change needs to go into jruby-launcher.
=> Use java_home command on MacOS

.travis.yml
JDK 16 now has --illegal-access=deny by default. We should already
be good citizens and not dig around in unopened packages, but this
will help confirm and preserve that behavior.
Relates to #6721
=> Test on JDK 16

core/src/main/java/org/jruby/util/JarCache.java, core/src/main/java/org/jruby/util/JarResource.java
This PR backports #6268 to 9.2 to fix the evacuation of the cache (due to weakly referenced-keys that immediately get dereferenced).
This backport will make it easier to incorporate other improvements from @DirkMahler for #6730.
=> Backport JarCache soft reference fix

core/pom.rb, core/pom.xml, core/src/main/java/org/jruby/util/JarCache.java, core/src/test/java/org/jruby/util/JarCacheTest.java, pom.rb, pom.xml
* PR for #6730 , targeting `jruby-9.2`
* Last moficiation timestamp for JAR files is cached for at most 500ms now
* Added a simple unit test for verification that updated JAR is picked up (using Awaitility as a test dependency, hope you don't mind that I introduced it)
=> 6730 jar cache slowing down startup time 9.2

core/src/main/java/org/jruby/ir/IRBuilder.java
I may still change this PR a little but this is close(or done).
I don't like the ListNode logic.  !DNode && !Array seems like this could at a minimum use NodeType OR have a nicer helper method on AST
Also I need to audit uses of needSplat along with considering if we actually need buildWithOrder over build anyplace now.
=> Fixes #6173. Evaluation of when more lazily evaluates multiple conditions on one line. 

core/src/main/java/org/jruby/util/ShellLauncher.java, lib/pom.rb, test/jruby/test_exec.rb
This PR contains various small fixes for the native `exec` support on Windows, mostly relating to finding the full paths to cmd.exe and the .exe/.com/.bat/.cmd executables that go with a given command.
See #6745.
=> Fixes for Windows native exec

core/src/main/java/org/jruby/javasupport/ext/JavaLang.java, core/src/main/java/org/jruby/javasupport/ext/JavaTime.java, core/src/main/java/org/jruby/javasupport/ext/JavaUtil.java, spec/java_integration/types/inspect_spec.rb
following up on https://github.com/jruby/jruby/pull/6493 with more `inspect` on Java types, namely:
- `java.lang.Thread`
- `java.util.TimeZone`
- `java.time.ZoneId`
=> [ji] inspect for Thread/TimeZone/ZoneInfo

core/src/main/java/org/jruby/runtime/MixedModeIRBlockBody.java, spec/jruby.mspec, spec/tags/ruby/core/binding/eval_tags.txt, spec/tags/ruby/core/proc/new_tags.txt, spec/tags/ruby/core/string/slice_tags.txt, spec/tags/ruby/language/regexp_tags.txt
See #6753 for the PR that initiated this work, by @ahorek. That PR has been superseded by this one, which includes the added jit job and will eventually contain all fixes to get that job green.
=> Fix failures in ruby/spec running with immediate jit mode

core/src/main/ruby/jruby/kernel/file.rb, core/src/main/ruby/jruby/kernel/jruby/fcntl_ffi.rb
Activating FFI this early prevents it being upgraded by RubyGems
or Bundler. This also happens so early that there's no way to
eagerly activate the gem to pick up a newer version. As a result,
bundles or gems that depend on newer FFI will error or warn about
the mismatch.
This change modifies the FFI-based File methods on Windows
(File.symlink) and Solaris (File#flock) to lazily require a
separate file that loads FFI and redefines those methods.
Fixes #6751
=> Lazily define FFI-using File methods

core/pom.xml, core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/specialized/RubyArrayOneObject.java, core/src/main/java/org/jruby/specialized/RubyArrayTwoObject.java, core/src/main/java/org/jruby/util/io/EncodingUtils.java
The main problem with the original code was that we would:
```java
str.setEncoding(s.getEncoding());
```
Where s is an inspected element of the array.  MRI will call
rb_enc_associate which may setEncoding but might not.  In fact,
rb_enc_associate has a lot of logic which I don't really understand.
What I mean by that is that we call str.cat19 which will also do the
appropriate encoding negotiation of building up the result inspect
string.  Why add this extra method into the mix?
I opted to just let cat19 do its thing and spec:ruby:fast passed.
A second change I made was to make the inspect string use default_external
unless it is an encoding which does not support ascii (which is needed since
inspect is adding ascii like '[').  In the non-ascii case we just default to
US-ASCII. …
=> Fixes #6748. Inconsistent encoding when calling #to_s on arrays.

core/src/main/java/org/jruby/javasupport/Java.java, core/src/main/java/org/jruby/javasupport/JavaPackage.java, core/src/main/java/org/jruby/javasupport/JavaSupport.java, core/src/main/java/org/jruby/javasupport/JavaSupportImpl.java, test/jruby/test_higher_javasupport.rb
The fix here is to not register JavaPackage as a constant of Java.
This prevents srb from finding it via constants.  So the problem class
is never seen.
Note: I think in the scenario of walking ObjectSpace we can still run
across this but that may be another issue to deal with when we experience it.
The explanation of what is wrong is that JavaPackage is in fact a Class but
due to how we want it to behave we set its metaclass to Module.  When srb
retrieves an UnboundMethod off of Class that method cannot be bound to this
type because it says "nope I am a module" (even though it is actually a class).
=> Fixes #6242. Sorbet srb init crashes

core/src/main/java/org/jruby/util/IOChannel.java, core/src/test/java/org/jruby/util/TestIOChannel.java
The "optimizations" in #6557 were overzealous:
* The incoming ByteBuffer and its contents should not be
referenced past the end of the call, as was done here by
returning a String that directly wraps the buffer's underlying
array.
* The copy of bytes out of the native buffer is essentially the
same as calling #duplicate, so this is just unnecessary double-
copying.
Fixes #6767.
=> Undo shared-buffer optimizations from #6557

core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRBodyMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java, core/src/main/java/org/jruby/ir/instructions/DefineClassInstr.java, core/src/main/java/org/jruby/ir/instructions/DefineModuleInstr.java, core/src/main/java/org/jruby/ir/interpreter/Interpreter.java, core/src/main/java/org/jruby/ir/interpreter/InterpreterContext.java
This code previously used the current line from context, which
would be the line of the caller invocation.
Fixes #6768
=> Use line number of scope for initial backtrace

bin/jruby.bash
```
basename -- "$sym"
```
it fails on launch because "--" isn't a valid java command (it works on linux)
```
basename "$sym"
```
returns "java" on both platforms
=> [launcher] basename for solaris

bin/jruby.bash
This avoids any and all pitfalls with using external implementations, e.g. #6711.
=> Create and use pure-bash dirname and basename

core/src/main/java/org/jruby/RubyThread.java
introduced by https://github.com/jruby/jruby/commit/84ece2bba5ee9824fefb9f805df6314298154764
blockingThreadPoll was a public API and nio4r / puma use the method at https://github.com/socketry/nio4r/blob/master/ext/nio4r/org/nio4r/Selector.java#L237
=> restore api compatibility with nio4r

lib/pom.rb, lib/pom.xml, test/check_versions.sh
This updates 9.3 to jruby-openssl 0.10.7.
@kares Any reason we shouldn't do this?
=> Update to jruby-openssl 0.10.7

core/src/main/java/org/jruby/ir/IRManager.java, core/src/main/java/org/jruby/ir/instructions/BFalseInstr.java, core/src/main/java/org/jruby/ir/instructions/BNEInstr.java, core/src/main/java/org/jruby/ir/instructions/BNilInstr.java, core/src/main/java/org/jruby/ir/instructions/BTrueInstr.java, core/src/main/java/org/jruby/ir/instructions/BUndefInstr.java, core/src/main/java/org/jruby/ir/instructions/BranchInstr.java, core/src/main/java/org/jruby/ir/operands/Nil.java, core/src/main/java/org/jruby/ir/passes/LocalOptimizationPass.java, core/src/main/java/org/jruby/ir/representations/CFG.java, core/src/main/java/org/jruby/ir/transformations/inlining/CFGInliner.java
LocalOptimizationPass will propagate values.  For example:
```ruby
_tmp = true
unless _tmp
puts "Never"
end
```
In this case by the end of this pass we will see a BB end with a
b_false(true, some_label).  This clearly cannot happen.  If we eliminate
this instr then we should also be able to lop off the bb(s) representing
whatever is within the unless conditional.  In this snippet the entire
snippet should be dead code except _tmp = true.
To fix this I added simplifyBranch to BranchInstr.  This gives us the
ability to swap out a branch with a noop or a jump (in case where something
is unconditionally true).
After we replace the instr with a new one we need to reexamine the basicblock
it is in and correct any edge placement.
=> More agressively kill dead code

core/src/main/java/org/jruby/ir/IRBuilder.java
IRBuilder.createBranch is missing a case if we know we have a literal
and we compare it against nil we definitely know it is not a valid
branch.
=> b_nil should noop if compared against truthy immediate (IRBuilder)

core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/java/invokers/RubyToJavaInvoker.java, core/src/main/java/org/jruby/javasupport/JavaMethod.java, core/src/main/java/org/jruby/javasupport/proxy/JavaProxyClass.java, spec/java_integration/fixtures/concrete_subclass_overrides.rb, spec/java_integration/methods/super_on_concrete_subclass_spec.rb
The issue here was that we super calls would sometimes fall back on reflective invocation when more than one subclass was involved. This had the effect of restarting the invocation chain back at the bottom of the hierarchy (from the self object's class) due to the nature of reflective invocation (it always calls the lowest override).
The fix here pulls the super invocation logic back from within the Java integration guts and into the Ruby-level super logic, so we can look up an appropriate super shim method to invoke at the proper level.
This fix will need to be refined in the future, using some of the following ideas:
* Rewrite such supers to be a different instruction. We should be able to detect this in the same way we detect super in the initialize methods of Ruby/Java subclasses. …
=> Fix super chaining on Ruby subclasses of Java classes

core/src/main/java/org/jruby/lexer/yacc/HeredocTerm.java, core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java, core/src/main/java/org/jruby/lexer/yacc/StringTerm.java, shaded/src/main/java/Nothing.java
We have the test of time just created a new string using the lexers
encoding.  This worked until I fixed the last known issues in the
parser reporting errors with mixed strings (like binary data + UTF-8
escapes).  This is not a valid string and the parser should error out.
Unfortunately, by setting the lex encoding right away we are not in a
position of knowing whether the string should just have that encoding
or whether we are in a new string where we have not yet figured out
what encoding it should be.
Case in point.  #6832.  It is evaling as a Window-31J string BUT the
literal string is only utf-8 escapes.  It should resolve as being
UTF-8 yet it errors because it sees the escapes and then errors out
thinking it is already a windows-31J string.
The solution is to emulate how MRI does …
=>  Fix string literals in other encodings which should be utf-8 encoding

spec/tags/ruby/library/openstruct/to_h_tags.txt, test/mri/excludes/TC_OpenStruct.rb, test/mri/ostruct/test_ostruct.rb
See https://github.com/ruby/ostruct/issues/30 for the ostruct issue that caused us to revert to an earlier gem. This PR reverts the test and tags the specs that do not pass on the older version of ostruct.
See also #6831.
=> Revert ostruct tests/specs due to reverted gem

core/src/main/java/org/jruby/java/invokers/RubyToJavaInvoker.java, spec/java_integration/fixtures/ClassWithPrimitiveVarargs.java, spec/java_integration/methods/dispatch_spec.rb
An optimization to use direct array sets for object components
accidentally caused us to do the same logic for primitive
components. This fixes that regression and adds specs for calling
primitive varargs methods.
Fixes #6830
=> Fix calling primitive varargs and add tests

core/src/main/java/org/jruby/util/RegularFileResource.java, core/src/main/java/org/jruby/util/ResourceException.java, core/src/main/java/org/jruby/util/io/PosixShim.java
This triggered a failure in the io/wait tests when it expected a
nonblocking write-only open call against an unread fifo to raise
ENXIO. We instead raised one of our internal anonymous errors,
preventing the logic in this test from retrying:
https://github.com/ruby/io-wait/blob/0c73ebcf5d75b0568405f5863eefaffba0ec7a0e/test/io/wait/test_io_wait_uncommon.rb#L23
The changes here promote all unraised errno exceptions to use
ErrnoException, which propagates the errno object as well as the
name and path. This allows upstream error handling to raise the
proper Ruby error.
=> Fix handling of ENXIO error during resource open

core/src/main/java/org/jruby/RubyKeyError.java, test/mri.core.index
After JRuby 9.3, attempting to raise a KeyError with no arguments would
fail with an ArgumentError. This commit fixes this behavior to match
MRI, and updates the `key` and `receiver` methods to raise if they are
unset.
Prior to this, the relevant MRI tests for this functionality were not
running in CI, and when ran manually 3 tests were failing. Add the
`test_key_error.rb` file to the `mri.code` suite. After this change, all
tests from `test_key_error.rb` pass.
Fixes #6860.
Relevant MRI code: https://github.com/ruby/ruby/blob/09863a4cd8eb40b34b310083d8cdda899ab5bcc1/error.c#L2096-L2121
=> Fix KeyError behavior with no arguments

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyModule.java
respond_to? calls searchMethod and that code path ends up passing
the static scope as null.  RubyModule.searchWithCache notices we
are dealing with a refined method yet it has no static scope so it
just passes by the refinement logic.
The fix is to get current static scope based on the notion current
is the lexical location anything would be searching at the moment.
Getting current context as the fix is a little undesirable but pushing
context through all these paths would be a big change.
=> Fix #6859.  respond_to? regression with refinements.

core/src/main/java/org/jruby/ext/socket/Addrinfo.java
as requested in https://github.com/jruby/jruby/pull/6829
before
```
[#<Addrinfo: 216.58.201.78:80 TCP>]
```
after
```
[#<Addrinfo: 216.58.201.78:80 TCP (google.com)>]
```
some parts are still missing or they may behave differently, for instance:
```
ruby -rsocket -e "p Addrinfo.getaddrinfo('localhost', 80, :INET, :STREAM, Socket::IPPROTO_TCP, Socket::AI_CANONNAME)"
[#<Addrinfo: 127.0.0.1:80 TCP DESKTOP-U60MURJ (localhost)>]
```
=> addrinfo - inspect hostname

core/src/main/java/org/jruby/ir/passes/AddCallProtocolInstructions.java
Entertainingly the comment on the fixed line specifies what the line
should have said.  The new signature logic must explicitly check for
no kwargs.
=> Fixes #6870. Missing keywords after a second proc call (full/JIT).

core/src/main/java/org/jruby/runtime/ThreadContext.java, core/src/main/java/org/jruby/runtime/backtrace/BacktraceData.java, core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
Two fixes here:
* Fix the "raw" backtrace mode. Both "raw" and "full" were printing out all frames, but "raw" was improperly processing jitted frames into their Ruby method names like "full". I believe this was due to my unifying these two paths; "raw" passed in an empty set of interpreter frames, which prevented interpreter frames from being processed, but it still processed jitted method names. A new flag was added to indicate "raw" behavior, now skipping the jit frame rewriting.
* Fix the varargs method wrappers from JIT being included in exception traces. In #6771 I fixed the backtrace generation to include the JIT varargs wrapper, which previously had been ignored. However I messed up the guard that prevents those frames from being processed if the wrapped method also appears in the …
=> Fix raw and varargs backtrace elements

core/src/main/java/org/jruby/RubyRange.java
Makes  things like `(..0).step(1)` (beginless) returns an instance of `Enumerator::ArithmeticSequence`.
=> Handle beginless ArithmeticSequence

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/IRVisitor.java, core/src/main/java/org/jruby/ir/operands/Range.java, core/src/main/java/org/jruby/ir/persistence/IRReaderStream.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/ValueCompiler.java, core/src/main/java/org/jruby/ir/targets/indy/IndyValueCompiler.java, core/src/main/java/org/jruby/ir/targets/indy/RangeObjectSite.java, core/src/main/java/org/jruby/ir/targets/simple/NormalValueCompiler.java, spec/compiler/general_spec.rb
This adds logic in IR and JIT to cache the resulting Range object when a literal range is composed of other immediate literal values, like longs.
The first pass here is a simple introduction of logic to cache the resulting object, while still emitting code to create the input values. A more compact representation would not need to revisit the input value logic (even to check a cache) and would instead embed the values directly into the range, so it can be constructed and cached outside of IR/JIT output.
=> Cache literal ranges constructed from immediate values

core/src/main/java/org/jruby/ext/socket/Addrinfo.java, core/src/main/java/org/jruby/ext/socket/SocketUtils.java
Previously if the hostname was given it was looked-up rather than
being used with the requested address. The new logic will use the
hostname if alone or hostname plus address otherwise.
Also included in this patch, the array accesses now use `entry`
which will return a nil for missing items. Previous use of `eltOk`
would raise a ConcurrencyError if the array was not long enough.
=> Honor the requested address even given hostname

spec/java_integration/ant/ant_spec.rb, spec/java_integration/ant_spec_helper.rb, spec/java_integration/utilities/jar_glob_spec.rb
A spec in ji/ant/ant_spec.rb was changing ENV['PATH'] under certain
circumstances, which resulted in the shells spawned by backtick being
unable to find common programs like `zip` or `which`. Fix that, and restore
`jar_glob_spec.rb`'s use of `zip -d`.
=> Fix spec:ji on GHA

core/src/main/java/org/jruby/ext/socket/RubySocket.java, core/src/main/java/org/jruby/util/io/Sockaddr.java, spec/tags/ruby/library/socket/basicsocket/local_address_tags.txt, spec/tags/ruby/library/socket/basicsocket/recv_nonblock_tags.txt, spec/tags/ruby/library/socket/basicsocket/recvmsg_nonblock_tags.txt, spec/tags/ruby/library/socket/basicsocket/remote_address_tags.txt, spec/tags/ruby/library/socket/socket/listen_tags.txt
We have a few failures with IPv6 that have escaped notice due to not running in Travis CI. When they failed locally we probably ignored those failures assuming we did not have IPv6 set up properly.
This PR will include some fixes and some tags for IPv6-related failures we now see when running CI on GitHub Actions.
* Set IPv6-related constants to nil when unavailable: CRuby has complicated logic for defining socket-related constants and query methods, but I believe this is a rough match for how they filter out IPv6-related constants when IPv6 is not available. This is checked by e.g. MRI tests and rubyspec to skip or alter IPv6-related tests.
* Preserve multibyte strings in UNIX address: The path was being round-tripped through Java incorrectly, mangling multibyte characters.
* Update …
=> Socket fixes for GHA CI

core/src/main/java/org/jruby/util/cli/Options.java, lib/ruby/stdlib/date.rb, lib/ruby/stdlib/date/format.rb, test/jruby.index, test/jruby/test_date_parse_limit.rb, test/mri/excludes/JSONAdditionTest.rb
Excessively long input to the various Date parsing methods can cause the calling thread to run for a long time, perhaps tying it up indefinitely. This PR incorporates to changes similar to those in ruby/date@3959acc.
* Add a limit option to the affected Date parse methods (see commit above for the list).
* Make all regexp matches interruptible by default. This can be disabled using the JRuby property `regexp.interruptible=false` in .jruby_opts, with `-Xregexp.interruptible=false` on the command line, or by setting the JVM property `jruby.regexp.interruptible=false`
* Add the same test as CRuby under our JRuby test suite, since no spec was added by ruby-core and we are not merging updated tests for this release.
This patch differs from #6951 in that it enables interruptible Regexp matches …
=> Limit Date.parse input length and make interruptible

core/src/main/java/org/jruby/ir/IRMethod.java
Related to https://github.com/jruby/jruby/issues/6935, this makes the split-super errors in concrete reified classes refer to the restriction on the wiki
=> Make split-super errors slightly more user friendly

core/src/main/java/org/jruby/ext/set/RubySet.java
We can't blindly get the current object's class's superclass
because the object's class may be multiple descendants below the
Set class, causing super calls to super back into a lower point
in the hierarchy. This is the cause of #6958.
The fix here is to request a frame be pushed for Set#init_dup and
init_clone so that we can redispatch from the proper point in the
hierarchy. This also properly uses SuperCallSite, passing in the
class from which to super. The original code was flawed in two
ways:
* It always acquired the superclass via object.class.superclass,
which does not work for a two-deep descendant of Set.
* It passed the superclass in for the frame class, which allowed
the flawed logic to work for one level deep. It is broken for
two levels deep or no levels deep because it passes …
=> Push a frame for init_dup/clone for super

core/src/main/java/org/jruby/ir/operands/Symbol.java
Hello team,
I've been doing some reverse engineering work on a JRuby application and while dumping the IR using some code I wrote that uses [`IRDumper`](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ir/persistence/IRDumper.java) I hit a few `NullPointerException`s.
I see `getString` is already fixed in 9.3.x but the rest was missing.
I wasn't sure what was the best way to contribute this PR. Should I open `master` first and then backport to `jruby-9.3` and `jruby-9.2`?
=> Avoid NullPointerException in Symbol operand

core/pom.rb, core/pom.xml, core/src/main/java/org/jruby/ext/ffi/jffi/VariadicInvoker.java, core/src/main/java/org/jruby/ir/operands/Symbol.java, pom.rb, pom.xml
Pulls in recent work on variadic function calls to improve support for Apple Silicon plus an unmerged Symbol operand fix from 9.2.
* #6978
* https://github.com/jnr/jffi/pull/121
* https://github.com/jnr/jnr-ffi/pull/292
* https://github.com/jnr/jnr-posix/pull/174
=> Merge 9.2 for JNR update and Symbol fix

core/src/main/java/org/jruby/ir/IRBuilder.java
ZArray is a special case that stands for an empty array, but it doesn't inherit from the Array node
this fixes equality for
```ruby
case []
when []
puts 'correct ([])'
else
puts 'did not match'
end
```
see https://github.com/jruby/jruby/issues/6981
=> case when with an empty array

core/src/main/java/org/jruby/ir/IRScope.java
This makes two changes.  The first is to not record evals
as lexical children.  In IR we actually only use lexical
children for IR persistence (and AOT compilation).  We would
never persist a live eval instance.
This leads to the second change.  anyUsesEval was using lexicalChildren
to detect for evals when trying to perform AOT compilation (which we
do not allow).  This is better served by getClosures as we really
only care about "soft" scopes containing an eval (e.g. we don't
care if a method contains and eval if we are trying to AOT a module
scope (hard scope change) but we do care about a closure in a method
containing an eval (soft scope change)).
=> Fixes #6993.  Evals cause memory leak.

core/src/main/java/org/jruby/ir/instructions/BuildDynRegExpInstr.java
The cache here serves as a cache for dynamic "once" regexps but
is also being used as the holder for non-"once" regexp. This leads
to a concurrency issue since a single field in this instruction is
used across threads and they may step on each other.
This patch avoids using the shared field for non-"once" dynamic
regexps. As a side effect, these instruction instances will not
be queriable for their last-built RubyRegexp, which also seems
appropriate if they are not a "once" dregexp.
Fixes #6992
=> Do not cache non-"once" dregexp

bin/jruby.bash
This fixes the issue described in #6789 where a nonexistent `release` file gets grepped even though we do an existence check. The problem here is that in bash, unlike in C or Java, the `||` and `&&` operators have the same precedence, which means they will be evaluated from left to right. In the environment described by @lfiht in  #6789, where only the `modules` file exists, this leads to an error as the `grep` command tries to read the non-existent `release` file.
=> Module check mishandles bash operator precedence

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, spec/java_integration/fixtures/ClassWithSimpleMethod.java, spec/java_integration/fixtures/SubclassOfClassWithSimpleMethod.java, spec/java_integration/methods/dispatch_spec.rb
The logic here was falling into the reified Ruby < Java subclass logic when trying to super out of a reopened normal Java class. When in such a situation, we should detect that we are not in a Ruby subclass of a Java class and not try to use that logic, which depends on additional structures not present on normal proxied Java classes
Fixes #6968.
=> Java class reopened to add a super call should dispatch normally

bin/jruby.bash
This avoids spawning another subshell for the grouped `release` file checks.
Thanks @mrnoname1000 for the improved conditional.
=> Avoid subshell for module check

core/src/main/java/org/jruby/ir/IRBuilder.java
Allows coercing non-array to array of exception types.
=> Compile splatted rescue as splat

core/src/main/java/org/jruby/RubyArithmeticSequence.java, core/src/main/java/org/jruby/RubyRange.java
* spec/ruby/core/enumerator/arithmetic_sequence/inspect_spec.rb
* test_num_step_inspect and test_range_step_inspect in test/mri/ruby/test_arithmetic_sequence.rb
=> fix ArithmeticSequence#inspect

core/src/main/java/org/jruby/RubyArithmeticSequence.java
This commit makes the following test pass.
* test_first in test/mri/ruby/test_arithmetic_sequence.rb
=> fix ArithmeticSequence#first when begin param is nil.

lib/ruby/stdlib/date.rb
`jruby -v`: jruby 9.4.0.0-SNAPSHOT (3.1.0) 2022-01-15 a0b853cb09 OpenJDK 64-Bit Server VM 11.0.13+8-Ubuntu-0ubuntu1.21.10 on 11.0.13+8-Ubuntu-0ubuntu1.21.10 +jit [linux-x86_64]
Running `require 'date'` with jruby head results in a warning:
```
jruby -e 'require "date"'
```
> /tmp/jruby/stdlib/rubygems/core_ext/kernel_require.rb:85: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
The warning is caused by the space before the parenthesis in the definition of `self.valid_time_frags?`. This pull request removes the space.
=> Fix a warning when loading date.rb

core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/RubyString.java
* Check for tainting in Hash string key negotiation.
* Check for tainting during deduplication and skip interning if
tainted.
Fixes #7018
=> Avoid interning tainted strings

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/runtime/ivars/VariableTableManager.java
This PR combines the following commits, cherry-picked to the 9.2 branch:
* e963a579939720095cd2bdcf2d81d0ddad8a5979: added bareness-checking to `String#-@`.
* eb11c5de9d9f9e220c6166b440c484639384e291: bareness check reuse in string deuplication internals.
* 7c4edfb8ae7434d08598ee0c8aed9741a2fc76d1: only consider instance vars to make a string non-bare, and not internal vars.
* 59f08d59a52f99fd3f385b248d6ca319a941b458: from #7020 sans hash key duplication changes, check for taintedness in bareness checks.
=> Backport string deduplication fixes from 9.3

core/src/main/java/org/jruby/RubyArithmeticSequence.java, test/mri/excludes/TestArithmeticSequence.rb
add several methods inherited from Enumerator to ArithmeticSequence.
e.g. #each_cons, #each_slice, #each_with_object, #with_index, #next, #next_values, #peek, #peek_values and #rewind
Excluding test_stop_result test, all of the following tests pass.
* test/mri/ruby/test_arithmetic_sequence.rb
I guess there is a better implementation more than this commit. Although I give priority to passing the ArithmeticSequence tests.
=> add several methods inherited from Enumerator to ArithmeticSequence.

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyEnumerator.java, core/src/main/java/org/jruby/RubyProducer.java
* test_produce in test/mri/ruby/test_enumerator.rb
* spec/ruby/core/enumerator/produce_spec.rb
For #6464
=> Ruby 2.7 : Add Enumerator.produce

core/src/main/java/org/jruby/internal/runtime/RubyRunnable.java, core/src/main/java/org/jruby/ir/operands/IRException.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/runtime/Helpers.java
This PR will fix #7009 by converting the IRBreakJump into a LocalJumpError before it bubbles completely out of the thread.
Initial attempt at this allows the jump to bubble all the way to the top of RubyRunnable before getting converted, which does not exactly match CRuby behavior. In CRuby, the jump is an LJE immediately because they search the current thread for the target scope and raise LJE immediately if it is not present. We do not want to add such a search to our break instruction.
=> Handle unrooted break jumps in Thread

core/src/main/java/org/jruby/RubyEnumerator.java, core/src/main/ruby/jruby/kernel/enumerator.rb
To create an Enumerator instance with size, this implementation
uses __from method insted of Enumerator.new .
And this commit makes the following tests pass.
* spec/ruby/core/enumerator/lazy/eager_spec.rb
For #6464
=> Ruby 2.7: Add Enumerator::Lazy#eager

core/src/main/java/org/jruby/RubyChain.java
* spec/ruby/core/enumerator/chain/initialize_spec.rb
=> Fix uninitialized Enumerator::Chain#inspect

core/src/main/java/org/jruby/RubyArray.java
* test_minmax in test/mri/ruby/test_array.rb
* spec/ruby/core/array/minmax_spec.rb
=> Fix Array#minmax with block

core/src/main/java/org/jruby/RubyArray.java
If ArithmeticSequince range outsides of array, Array#slice becomes to throw RangeError.
* spec/ruby/core/array/minmax_spec.rb
* spec/ruby/core/array/element_reference_spec.rb
#6878
=> Fix Array#slice with Enumerator::ArithmeticSequence

core/src/main/java/org/jruby/RubyArray.java
This case should warn a message that is '$, is set to non-nil value'.
* spec/ruby/core/array/join_spec.rb
#6464
=> Fix Array#join with nil

core/src/main/java/org/jruby/RubyEnumerable.java
Enumerable#grep(_v) with block handles non-string elements correctly.
* spec/ruby/core/enumerable/grep_spec
* spec/ruby/core/enumerable/grep_v_spec.rb
#6878
=> Fix Enumerable#grep and Enumerable#grep_v with Regexp

core/src/main/java/org/jruby/RubyTime.java
* spec/ruby/core/time/ceil_spec.rb
* spec/ruby/core/time/floor_spec.rb
* test_ceil and test_floor in test/mri/ruby/test_time.rb
#6464
=> Ruby 2.7: Add Time#ceil and Time#floor

core/src/main/java/org/jruby/RubyEnumerable.java
Add Enumerable#compact
* test_compact in test/mri/ruby/test_enum.rb
For #7015
=> Ruby 3.1: Add Enumerable#compact

core/src/main/java/org/jruby/RubyArray.java
For #7015 
e.g. ` [1, 2, 3].each_slice(2){} =>  [1, 2, 3]`
=> Ruby 3.1: Update Array#each_slice to return a receiver

core/src/main/java/org/jruby/ext/strscan/RubyStringScanner.java
This passes all tests and specs and cleans up the code a bit to better match our modern patterns.
This is in prep for https://github.com/ruby/strscan/pull/25 which will absorb this implementation as part of the gem.
=> StringScanner fixes and cleanup

core/src/main/java/org/jruby/runtime/load/LoadService.java
Leaving this lock in place indicates to later feature tests that
the file was never loaded, incorrectly causing autoload constant
lookups to fail to load the file a second time. Instead, we
always remove any lock set up for the require so the feature does
not look like it is still in the process of loading.
See #7070
This is a WIP and we will see how it handles tests. I believe I originally added the `destroyLock` logic to form fit behavior to some spec, but I cannot remember which spec behavior led me to doing this. It seems wrong now to leave the lock in place under any circumstances, since it will interfere with future attempts to load that file (the case in #7070).
=> Remove the require lock on LoadError

core/src/main/ruby/jruby/kernel/enumerator.rb
For #7015
* test_compact in test/mri/ruby/test_enumerator.rb
=> Ruby 3.1: Add Enumerator::Lazy#compact

core/src/main/java/org/jruby/RubyChain.java
* test_chain_with_index in test/mri/ruby/test_enumerator.rb
=> Add Enumerator::Chain#with_index to fix failing TestEnumerator#test_chain_with_index

core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/RubyTime.java
This commit removes Time#succ . And this commit updates the discreteObject
function in RubyRange to fix failing spec/ruby/core/range/each_spec.rb .
The discreteObject function does not need to check the type of arg because of Time#succ is deleted.
See https://bugs.ruby-lang.org/issues/17039
=> Ruby3.0: Remove Time#succ

core/src/main/java/org/jruby/RubyTime.java
MRI 3.1.0 supports this format.
* test_evaluation_order in test/mri/ruby/test_time.rb
=> Ruby 3.1: Update Time#getlocal to support +HHMM and +HHMMSS format

core/src/main/java/org/jruby/RubyTime.java
* test_marshal_broken_month in test/mri/ruby/test_time.rb
=> Update Marshal#load for Time Class to fix failing edge case

core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java, core/src/main/java/org/jruby/util/cli/OutputStrings.java, spec/tags/ruby/library/socket/unixserver/accept_nonblock_tags.txt
In https://github.com/sass/sassc-ruby/issues/231 it was reported that JRuby builds an improper `ARCH_FLAG` on MacOS/M1, using `aarch64` when it should use `arm64`. This PR fixes that.
This may be an appropriate change for other `aarch64` platforms depending on what the compiler wants, but I do not currently have a working Linux/aarch64 system on which to test it.
I also noticed that the `-v` output on JRuby reverses the arch and OS compared to CRuby, so this PR fixes that as well.
Two spec tags are updated to the new `arm64` arch name on `darwin`.
=> Architecture tweaks for JRuby on M1

core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java
jruby 9.4.0.0-SNAPSHOT (3.1.0) 2022-03-10 0b09e5447d OpenJDK 64-Bit Server VM 25.292-b10 on 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 +jit [linux-aarch64]
```
Fetching sassc-2.4.0.gem
Building native extensions. This could take a while...
ERROR:  Error installing sassc:
ERROR: Failed to build gem native extension.
current directory: /home/jruby/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
/home/jruby/bin/jruby -I /home/jruby/lib/ruby/stdlib -r ./siteconf20220310-9324-qbakp6.rb extconf.rb
creating Makefile
current directory: /home/jruby/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
make DESTDIR\= clean
current directory: /home/jruby/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
make DESTDIR\=
compiling ./libsass/src/ast.cpp
c++: error: unrecognized command line option '-m64'
make: *** [Makefile:196: …
```
=> [aarch64] fix unrecognized command -m64 for native extensions

core/src/main/java/org/jruby/RubyKernel.java, spec/ruby/core/kernel/define_singleton_method_spec.rb
This PR makes public visibility the only visiblity for `define_singleton_method` methods, and adds a spec testing a simple case of this.
This is a bit of an open question, since in CRuby `define_singleton_method` ends up producing public methods nearly all of the time due to a quirk in how the frame's visibility is accessed.
There's at least one edge case where `define_singleton_method` **does** obey the frame visibility, but it requires calling `define_singleton_method` from within a scope rooted on the destination singleton class. I would argue this is a peculiar-enough edge case that it should be made to explicitly use public visibility in all cases.
See https://github.com/ruby/ostruct/issues/40 for a related issue, where we warn about aliasing `define_singleton_method` due to its …
=> Explicitly use public visibility for define_singleton_method

lib/pom.rb, lib/pom.xml
0.12 improves compatibility it also dropped the previous openssl/*.rb file duplication
- https://github.com/jruby/jruby-openssl/releases/tag/v0.12.1
- https://github.com/jruby/jruby-openssl/releases/tag/v0.12.2
=> [deps] bump jruby-openssl to latest (0.12.2)

core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/javasupport/util/JavaClassConfiguration.java, core/src/main/java/org/jruby/runtime/ivars/FieldVariableAccessor.java, core/src/main/java/org/jruby/runtime/ivars/RawFieldVariableAccessor.java, core/src/main/java/org/jruby/runtime/ivars/VariableTableManager.java, core/src/main/java/org/jruby/specialized/RubyObjectSpecializer.java, lib/ruby/stdlib/jruby/core_ext/class.rb, spec/java_integration/reify/become_java_spec.rb
This is principally for making Java integration produce more idomatic Ruby. This allows users to configure a class to store specific ivars in a field of a reified class. This is principally for JRubyFX at this point in time, as that framwork sets java fields on a provided class. 
Still a WIP. Notable things that need to be done:
Quick working demo:
```rb
require 'java'
require 'jruby/core_ext'
class BackedClass
java_field "java.lang.String testfield" # define the field to be reified
headius_definitely_approved_this_ivar_configuration_method_name :@testfield # now mark it used for ivar storage
def testread
puts "Ruby R #{@testfield.inspect}"
end
def testwrite(v)
puts "Ruby W #{v}"
@testfield = v
end
def testjavaread
puts "Java R #{self.class.java_class.get_field("testfield").get(self).inspe …
```
=> Allow reified classes to store instance variables in raw fields

core/src/main/ruby/jruby/java/core_ext/object.rb
* import in any context: warn of deprecation, recommend
java_import instead.
* java_import from a non-module object: removed deprecated
definition since it was being overwritten by toplevel
definition and lazy import is a good use case to support.
* java_import from toplevel: works without warning.
Fixes https://github.com/jruby/jruby/issues/6976
```
$ jruby -e 'java_import java.lang.System; p System'
Java::JavaLang::System
$ jruby -e 'import java.lang.System; p System'
-e:1: warning: import is deprecated; use java_import
Java::JavaLang::System
$ jruby -e 'class X; def foo; java_import java.lang.System; p System; end; end; X.new.foo'
Java::JavaLang::System
```
=> Better warnings for deprecated java_import forms

core/src/main/ruby/jruby/java/core_ext/object.rb
This method has been deprecated for many years and it's time to
remove it.
Relates to #6976
=> Remove long-deprecated import method for JI

core/src/main/java/org/jruby/RubyRange.java
This code has for years mistakenly dispatched to the full cover?
logic, which considers intersecting ranges as being covered. The
logic in CRuby, however, only uses a small part of the cover logic
that does not accept ranges. The naming of the methods (in CRuby
it's r_cover_p, and in JRuby that got mapped to the full cover_p
method instead of the equivalent rangeInclude method) probably
was confusing, or early in JRuby development CRuby's r_cover_p and
our cover_p were equivalent and that changed over time in CRuby.
This also eliminates a dynamic dispatch to `cover?` that does not
exist in CRuby.
Fixes #7137
=> Use non-range cover logic for eqq and include

core/src/main/java/org/jruby/ObjectFlags.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
Went with marking incoming key word rest arguments getting marked with
a flag indicating that it is a kwrest.  The flag is removed once we
enter check_arity helper.  A kwrest is transient and isolated from the
call site to the method which recieves it.  So there is no opportunity
for more than one thread to see this or other shenanigans like that.
This also is the general direction of Ruby 3 where we (and MRI) mark
kwargs hashes with a flag.  We seem to fail there as well so we might
actually need this new flag there (since kw and kwrest will have different
behavior when passed to a method like the one attached to #7102).
=> Fixes #7102. ArgumentError re-splatting empty keyword arguments

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/ext/socket/RubyTCPSocket.java, rakelib/rubyspec.rake, spec/ruby/library/socket/fixtures/classes.rb, spec/ruby/library/socket/udpsocket/send_spec.rb, spec/tags/ruby/core/argf/gets_tags.txt, spec/tags/ruby/core/argf/read_tags.txt, spec/tags/ruby/library/socket/tcpsocket/initialize_tags.txt, spec/tags/ruby/library/socket/tcpsocket/open_tags.txt
The fixes here, mostly in TCPSocket and related specs, allow the "work in progress" set of specs to run to completion, so contributors can see what remains there to be implemented.
Note that running individual sections of specs may still hang; notably, the root Fiber transfer spec hangs when running just the library specs, but does not hang in the full run (and even passes). There are interactions between the specs at play here. This PR only gets the complete suite running.
See also the fixes here to improve shutdown of TCPSocket and UDPSocket tests by closing the server before joining it (ruby/spec#925).
=> Fixes to allow WIP suite to run to completion

core/src/main/java/org/jruby/Ruby.java, spec/tags/ruby/core/hash/deconstruct_keys_tags.txt, spec/tags/ruby/core/struct/deconstruct_keys_tags.txt
- spec/ruby/core/struct/deconstruct_keys_spec.rb
- spec/ruby/core/hash/deconstruct_keys_spec.rb
=> Fix Struct#deconstruct_keysand Hash#deconstruct_keys error mesage when using no argument.

core/src/main/java/org/jruby/RubyBasicObject.java, test/mri/excludes/TC_OpenStruct.rb, test/mri/ostruct/test_ostruct.rb
This updates ostruct tests and fixes one of the resulting failures.
The two existing excludes were resolved:
* test_method_missing depends on the native method_missing not appearing in NoMethodError backtrace. Fixed by `omit = true` in the JRuby method_missing binding, which is a new change.
* test_to_h_with_block was likely fixed by updating ostruct.
Two new failures are due to ruby/ostruct#41 and will be fixed by ruby/ostruct#45: test_each_pair, test_initialize
=> Update and fix failures in ostruct tests

test/jruby/test_higher_javasupport.rb
fixes a failure according to https://github.com/jruby/jruby/pull/7158
```
Failure: test_raised_errors_on_array_proxy(TestHigherJavasupport):
`length': wrong number of arguments (given 1, expected 0).
<false> is not true.
/home/runner/work/jruby/jruby/test/jruby/test_higher_javasupport.rb:1874:in `test_raised_errors_on_array_proxy'
1871:       fail 'expected to raise'
1872:     rescue ArgumentError => e
1873:       msg = e.message
=> 1874:       assert msg.start_with?("wrong number of arguments calling `length` (given 1, expected 0)"), msg
1875:     end
1876: 
1877:     begin # array proxy class
```
=> update error message

test/mri/excludes/TestDateParse.rb
they're passing after https://github.com/jruby/jruby/pull/7148
=> remove date parse excludes

core/src/main/java/org/jruby/RubyString.java, spec/tags/ruby/core/string/split_tags.txt
This commit uses the isSpace function of ASCIIEncoding same as MRI uses rb_ispace function.
And this commit fixes String#split for edge case.
=> Fix String#split with String doesn't split on non-ascii whitespace

core/src/main/java/org/jruby/RubyArray.java
The method for `Array#reject!` didn't check after each successive block yield if the array was frozen cause a failed test
=> Fixed test fail regarding `Array#reject!`

core/src/main/java/org/jruby/RubyArray.java, test/mri/ruby/test_array.rb
Fixed issue with `Array#rindex`  test failing. Using `unpack` to deal with concurrency error and `Object#define_singleton_method` to replace `class_eval` which seemed to not be working
=> Fix failing test Array#rindex

core/src/main/java/org/jruby/util/StringSupport.java, spec/tags/ruby/core/string/length_tags.txt, spec/tags/ruby/core/string/size_tags.txt
This commit updates the strLengthWithCodeRangeNonAsciiCompatible function to fix String#length for edge case.
=> Fix String#length for an imcomplete surrogate in UTF-16

core/src/main/java/org/jruby/RubyObject.java, core/src/main/java/org/jruby/runtime/JavaSites.java
This change fixes a test in `test_array.rb`. The test in question is `test_count`.
The problem was that despite the `==` being overridden for the method was never called in preference to a fast equality i.e. checking the primitive values.
In the method there is a fast equals for both `RubyFixnum` and `RubyFloat` are tested so I provided a clause for both of them.
=> Added checks to equalInternal to check for override of == method

core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/util/Pack.java, spec/tags/ruby/core/string/unpack1_tags.txt
This commit adds String#unpack1 with offset but String#unpack with offset is already implmented.
See #7015
=> Ruby3.1: Add String#unpack1 with offset

core/src/main/java/org/jruby/RubyRandom.java, core/src/main/java/org/jruby/RubyRandomBase.java, spec/tags/ruby/library/securerandom/random_number_tags.txt
When argument is non-numeric, SecureRandom#random_number should throw ArgumentError.
=> Update SecureRandom#random_number when argument is non-numeric

core/src/main/java/org/jruby/RubyRandomBase.java, core/src/main/java/org/jruby/util/Random.java, spec/tags/ruby/core/random/random_number_tags.txt, spec/tags/ruby/library/securerandom/random_number_tags.txt
When random variable is null, this logic calls objRandomBytes function against the self obj to generate a random double value from 8 bytes same as mri 3.1.x.
And this  cleans up tags because securerandom and rand all spec pass.
=> Update SecureRandom#random_number with a float range limit

core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyRange.java
`RubyArray` tried turning a long into a int, causing a `RangeError` to be raised but and `IndexError` is expected by CRuby.
`RubyRange` incorrectly gave a negative value *plus* the length to the exception raise, it didn't revert the number to its original form in the message.
=> Fixed a failing test in regarding `Array#[]=` or `RubyArray.aset`

lib/ruby/stdlib/rubygems/defaults/jruby.rb
As of a later Linux 2.6 release (2.6.27.something) the kernel now
recognizes when another script is used as the shebang command and
properly runs that script rather than the binary that script needs
to launch (e.g. putting a bash script in the shebang line will run
the script, rather than bash). Because of that improvement, we no
longer need to use "env shebangs" on Linux, since the bin/jruby
shell script will launch correctly.
This change was released in late 2008, so any 2.6 kernels past
that date work properly. Linux 2.4 was EOL in 2011, so all up-to-
date Linux installs after that date should be on a 2.6 or higher
Kernel, very likely after the fix was landed. And 2.6 itself was
EOL in 2016, so all up-to-date Linux installs after that date will
certainly have the fix. We believe it is …
=> Remove env shebang on Linux

core/src/main/java/org/jruby/RubyRational.java, spec/tags/ruby/core/rational/comparison_tags.txt, spec/tags/ruby/core/rational/divide_tags.txt, spec/tags/ruby/core/rational/exponent_tags.txt, spec/tags/ruby/core/rational/marshal_dump_tags.txt, spec/tags/ruby/core/rational/minus_tags.txt, spec/tags/ruby/core/rational/multiply_tags.txt, spec/tags/ruby/core/rational/plus_tags.txt, spec/tags/ruby/core/rational/round_tags.txt
1. This PR deletes unnecessary condition expression to fix Rational#round .
2. This PR updates Rational#marshal_dump to private method.
3. This PR also cleans up tags of Rational's rspecs.
=> Fix Rational#round and Update Rational#marshal_dump

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyKernel.java, spec/tags/ruby/core/basicobject/__send___tags.txt, spec/tags/ruby/core/kernel/public_send_tags.txt, spec/tags/ruby/core/kernel/send_tags.txt
This commit uses the checkID method instead of the objectToSymbolString method.
=> Update Kernel#send, #public_send and BasicObject#send to raise correct error message

core/src/main/java/org/jruby/RubyMath.java, spec/tags/ruby/core/math/log2_tags.txt
When the argument is Bignum, this logic parses the argument to generate 2 params(double value and shift bits) and avoids overflow.
* spec/ruby/core/math/log2_spec.rb
=> Update Math#log when the argument is Bignum

core/src/main/java/org/jruby/RubyStruct.java, core/src/main/java/org/jruby/runtime/JavaSites.java, core/src/main/java/org/jruby/util/RecursiveComparator.java, spec/tags/ruby/core/struct/eql_tags.txt, spec/tags/ruby/core/struct/equal_value_tags.txt
* spec/ruby/core/struct/eql_spec.rb
* spec/ruby/core/struct/equal_value_spec.rb
=> Update Struct#eql? and #== to handle recursive structures correctly

core/src/main/java/org/jruby/RubyStruct.java, spec/tags/ruby/core/struct/new_tags.txt
* spec/ruby/core/struct/new_spec.rb
=> Update Struct.new to raise ArgumentError when there is a duplcate member

core/src/main/java/org/jruby/RubyComplex.java, spec/tags/ruby/core/kernel/Complex_tags.txt
For instance, Complet(123, exception: false) should be Complex(123).
When exception option is not boolean, ArgumentError should be raised same as mri 3.1.2.
This commit also decreases wip tag in rspecs.
=> Update Kernel.#Complex to treat exception option correctly

core/src/main/java/org/jruby/RubyIO.java, spec/tags/ruby/core/io/for_fd_tags.txt, spec/tags/ruby/core/io/new_tags.txt, spec/tags/ruby/core/io/open_tags.txt
For instance, IO.for_fd(IO.sysopen("tmp.rb"), "w", nil) shoud raise "`for_fd': wrong number of arguments (given 3, expected 1..2) (ArgumentError)".
This commit also decreases wip tag in rspecs.
=> Update IO.new, IO.open and IO.for_fd to raise ArgumentError for some edge cases

spec/tags/ruby/core/numeric/clone_tags.txt, spec/tags/ruby/core/numeric/step_tags.txt
I think this Numeric#clone failure fixed by eb078adb48fac335d53a4781f43b52f1fc2f2868 commit.
And I confirm all Numeric's rspecs work.
=> Remove wip tag of Numeric#clone

core/src/main/java/org/jruby/RubyMath.java, spec/regression/GH-7234_math_ldexp_spec.rb
When the exponent is greater than 1023, This commit avoids overflow by converting Math.pow(2.0, exponent) into Math.pow(2.0, exponent-1023) * Math.pow(2.0, 1023).
Because Math.pow(2.0, 1024) is evaluated to INFINITY(overflow).
#7234
=> Fix Math.ldexp for #7234

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/ir/operands/FrozenString.java
Using ConcurrentWeakHashMap class, I think frozen and dedup'd strings outside of the scope will be released.
This commit also overrides isChached of FrozenString class to avoid specific mri test failure.
See #7229
=> Update the implementation class of dedupMap to prevent the memory growth for #7229

core/src/main/java/org/jruby/java/codegen/RealClassGenerator.java, core/src/main/java/org/jruby/java/proxies/ConcreteJavaProxy.java, spec/regression/GH-7219_map_java_proxy_spec.rb
This commit uses checking class's type in several parts to avoid ClassCastException.
#7219
=> Avoid ClassCastException when super class is a Java Map for #7219

core/src/main/java/org/jruby/java/proxies/ArrayJavaProxy.java, spec/java_integration/types/array_spec.rb
ended up being broken with the JI `inspect` support added in 9.3
this only concerns empty `char[]` : 
```
>> ''.to_java.toCharArray
Traceback (most recent call last):
16: from org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
15: from org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
14: from org.jruby.RubyProc$INVOKER$i$call.call(RubyProc$INVOKER$i$call.gen)
13: from org.jruby.RubyProc.call(RubyProc.java:272)
12: from org.jruby.runtime.Block.call(Block.java:147)
11: from org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:66)
10: from org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
9: from org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
8: from …
```
=> [fix] [ji] empty char array inspect

core/src/main/java/org/jruby/RubyDir.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java, spec/java_integration/types/map_spec.rb
the gist of the changes is to fix the `java.util.Map#key?` case with nil values
`jruby -v -e "map = java.util.HashMap.new; map[:key] = nil; p map.size; p map.key? :key"`
```
jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf OpenJDK 64-Bit Server VM 11.0.14.1+1 on 11.0.14.1+1 +jit [x86_64-linux]
1
false
```
also on the Java consumer side having a "clean" way of checking a `IRubyObject` is present in the Hash seemed lacking ...
=> [ji] proper key? checking semantics for Map

core/src/main/java/org/jruby/embed/internal/EmbedEvalUnitImpl.java, core/src/main/java/org/jruby/embed/jsr223/JRubyEngine.java, core/src/test/java/org/jruby/embed/jsr223/JRubyEngineTest.java
This fixes #7187 by clearing the current in-flight exception once it is raised out of Ruby into Java. This prevents endless stacking of `cause` exceptions, but breaks the ability to query `$!` from the consumer side of the embedding APIs.
Note that only one of the two fixes is necessary to resolve #7187. One affects both ScriptingContainer and javax.script, and the other affects only the latter.
=> Do not stack causes for exceptions raised out of embedding APIs

core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java
Java calls may lazily convert incoming blocks to match an
interface type, which cannot be detected by this naive signature
check. We skip JI calls here to allow them to do the extra type
conversion.
Fixes #7246
=> Only drop block for non-JI native calls

core/src/main/java/org/jruby/RubyBignum.java, core/src/main/java/org/jruby/runtime/JavaSites.java, spec/tags/ruby/core/integer/chr_tags.txt, spec/tags/ruby/core/integer/lte_tags.txt, spec/tags/ruby/core/integer/zero_tags.txt
This commit also updates #<, #<=, #> and #>= by porting from mri.
* spec/ruby/core/integer/lte_spec.rb
=> Fix Bignum#<= for edge case

core/src/main/java/org/jruby/RubyNumeric.java, core/src/main/java/org/jruby/runtime/JavaSites.java
This commit fixes 'TypeError: TestTimeout::Seconds can't be coerced into Float' error in test/jruby/test_timeout.rb .
See https://github.com/jruby/jruby/runs/7591269856?check_suite_focus=true#step:7:243 .
=> Update doCoerce function

core/src/main/java/org/jruby/parser/RubyParser.java, core/src/main/java/org/jruby/parser/RubyParser.y
The fix was an error in our parser.  When we get exception variables in
a rescue statement we will make effectively '_e = $!' and then append
whatever is actually in the body of the exception body.  In MRI's case
it ends up being 'nil'.  In our case it was 'null'.  Our impl thinks it
is smart and realizes nothing is happening and what should you append
if it is null anyways and just left the body as only '_e = $!'.  We
needed '_e = $!; nil'.
Trivial fix is to make sure any null return from compstmt in this grammar
production will always just be nil.  Impact from this change should only
effect the case when a rescue body is empty and in the precence of an
exception variable.  What we did was wrong.  I see no risk.
=> Fixes #7218. Empty rescue block returns exception object instead of nil.

lib/ruby/stdlib/rubygems/defaults/jruby.rb, pom.rb, pom.xml
fixes #7262, but requires https://github.com/mkristian/jar-dependencies to have a new release first.
=> update jar-dependencies gem hooks

lib/ruby/stdlib/win32/registry.rb
The two delete functions were modified to be wide in CRuby in
response to https://bugs.ruby-lang.org/issues/10820 seven years
ago. The query function was mentioned here but not updated to be
wide. I am unsure how CRuby is locating the appropriate `A` or `W`
function given the bare name, but since we have largely forked
this file and always want to use the wide version, this change
seems appropriate.
Fixes #7106
=> Use the wide versions of these functions always

core/src/main/java/org/jruby/RubyTime.java
Fixes a few tests that were failing in master.
`Time#to_a` returns its timezone as the short name only. `Time#to_s` seems to have a different interpretation of this using something of the form `GMT-06:00` but the spec expected `CST`
To fix this I just changed how `Time#to_a` receives it's timezone.
=> Fixed tests in RubyTime failing with to_a

core/src/main/java/org/jruby/RubyTime.java
Fixes #7265 
`RubyTime.atMulti` would be passed `arg3` as `nil` if it wasn't given by the user. It complained that the unit couldn't be found.
So I added a check to see if it is `nil`, if it is then it is set to a symbol `:microsecond`. This appears to be the default value in CRuby.
Also updated the formatting as it wasn't the same as Ruby 3.
My Ruby Version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
Example Code:
```ruby
Time.at(12345, 500, in: '-04:00')
```
Ruby:
```
1969-12-31 23:25:45.0005 -0400
```
JRuby after PR:
```
1969-12-31 23:25:45.0005 -0400
```
=> Fixed issue with ArgumentError and time formatting

core/src/main/java/org/jruby/RubyInteger.java, core/src/main/java/org/jruby/RubyNumeric.java, core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/RubyString.java
There are several forms of loops here but none had any explicit
thread polling, which led to #7279 and timeout events not firing
during trivial Range#each loops. This commit adds polling to all
loops reachable from Range#each, which fixees #7279 and other
untested cases.
This does, however, come with a performance hit; the related thread
state must be checked after each loop. These could be improved in
the future by using a safe point mechanism like SwitchPoint, or by
porting these functions to Ruby which gets backedge thread polling
via the IR.
Fixes #7279
=> Add thread polling on backedges of Range#each loop

lib/ruby/stdlib/rubygems/defaults/jruby.rb, pom.rb, pom.xml
Reverts jruby/jruby#7264
This seems to break something:
https://github.com/jruby/jruby/runs/7656938830?check_suite_focus=true
Apply this revert before 9.3.7.0 if we don't have a better fix by then.
=> Revert "update jar-dependencies gem hooks"

core/src/main/java/org/jruby/javasupport/Java.java
This warning duplicates existing functionality intended to warn
when overwriting a constant, perhaps due to the more "magic"
nature of include_package and its open-ended behavior of assigning
constants to Java classes on demand. This feature is expected to
be used in places where you explicitly want the Java classes to be
preferred over classes further up in the hierarchy, so I believe
it makes sense to only warn if overwriting a constant that exists
on the target module directly.
Fixes #7185
=> Eliminate JI-specific const replacement warning

core/src/main/java/org/jruby/RubyBasicObject.java
In #7267 we had a report of endless exception cause processing
that turned out to be triggered by a bad finalizer (that allowed
an exception to bubble out) stacking up causes from previous calls
of that finalizer.
The fix here mimics what CRuby does: where they reset the errinfo
to what it was prior to the finalizer running (because CRuby's GC
often/usually runs on the current user thread), we simply clear it
after each finalizer has run (because the JDK runs finalizers on
a separate thread, as will our future non-JVM-finalizer version of
this logic).
No spec is provided yet due to the difficulty of testing
GC-triggered events across VMs. See https://github.com/ruby/spec/issues/935
for more details.
Fixes #7267
=> Clear errinfo after each finalizer runs

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/ir/Compiler.java, core/src/main/java/org/jruby/ir/persistence/IRReader.java, core/src/main/java/org/jruby/ir/persistence/IRReaderDecoder.java, core/src/main/java/org/jruby/ir/persistence/IRReaderStream.java, core/src/main/java/org/jruby/ir/persistence/IRWriter.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, spec/compiler/general_spec.rb
The filename from which a script is loaded can change after that
script has been AOT compiled to either serialized IR or JVM
bytecode formats. Previous commits broke this dynamic filename
handling by hardcoding the filename into the serialized IR and JVM
bytecode, causing #7211.
This commit reinstates the dynamic filename by passing it through
from load logic to the root scope creation, and removing the
hardcoded filenames produced by both AOT forms.
Note that one path has always been broken and remains broken: the
JVM `main` entry point provided to run a script directly as a Java
class. There is no way to reliably determine the real path of the
main class, so it continues to hardcode the original filename
(which is similar to javac embedding the original filename of a
compiled Java …
=> Always pass filename into AOT root scope creation

core/src/main/java/org/jruby/RubyInteger.java
This patch relates to https://bugs.ruby-lang.org/issues/18377
The results of TestInteger#test_times_bignum_redefine_plus_lt are below.
- jruby-head
```
1) Failure:
TestInteger#test_times_bignum_redefine_plus_lt [/Users/kiichi/IdeaProjects/jruby/test/mri/ruby/test_integer.rb:323]:
[ruby-core:106361].
<false> expected but was
<true>.
```
- jruby-head + this PR
```
1) Failure:
TestInteger#test_times_bignum_redefine_plus_lt [/Users/kiichi/IdeaProjects/jruby/test/mri/ruby/test_integer.rb:303]:
assert_separately failed with error message
pid 21910 exit 0
| -:21: warning: method redefined; discarding old +
| -:23: warning: method redefined; discarding old <
```
It still fails because of some warning messages, but I believe this patch works.
=> Fix Integer#times for big integer

core/src/main/java/org/jruby/RubyKernel.java
* test_Integer_with_invalid_exception in test/mri/ruby/test_integer.rb
=> Fix Kernel.Integer to treat exception option correctly

core/src/main/java/org/jruby/RubyMath.java, spec/tags/ruby/core/math/ldexp_tags.txt
This PR fixes for some edge cases.
* test_log, test_log10, test_override_bignum_to_f and test_cbrt in test/mri/ruby/test_math.rb
=> Fix Math.log, Math.log10 and Math.cbrt 

core/src/main/java/org/jruby/RubyTime.java
* test_at_with_uni in test/mri/ruby/test_time.rb
* spec/ruby/core/time/at_spec.rb
I think `bin/jruby --dev -S rake spec:ruby:fast` and `bin/jruby --dev -S rake spec:ruby:fast:jit` become green.
=> Fix Time.at with unit

core/src/main/java/org/jruby/java/proxies/ConcreteJavaProxy.java
Cherry-pick 6bf31f7c6462c798ebecaad7e5f96623951ae7a3 to prevent regression #7219 .
When this PR and #7312 are merged, `bin/jruby --dev -S rake spec:regression` becomes green.
=> Prevent regression #7219 on master

core/src/main/java/org/jruby/util/io/ModeFlags.java
The NOSHARE_DELETE ExtendedOption is not always available on all
systems, since it is part of a com.sun package that's not a public
API on recent JDKs. This commit guards its use, falling back on
the default NIO behavior of SHARE_DELETE when we can't access the
sole option that would turn it off.
Fixes #7268
=> Only use NOSHARE_DELETE if accessible

core/src/main/java/org/jruby/RubyProcess.java, spec/tags/ruby/core/process/euid_tags.txt
* spec/ruby/core/process/euid_spec.rb
* spec/ruby/core/process/egid_spec.rb
=> Fix Process#euid and #egid when an argument is username/groupname

core/src/main/java/org/jruby/RubyDir.java, core/src/main/java/org/jruby/util/StringSupport.java, spec/tags/ruby/core/dir/element_reference_tags.txt, spec/tags/ruby/core/dir/glob_tags.txt
This PR make the following test will all pass.
* spec/ruby/security/cve_2018_8779_spec.rb
* spec/ruby/security/cve_2018_8780_spec.rb
Results without this PR.
```
ruby spec/mspec/bin/mspec ci spec/ruby/security/cve_2018_8779_spec.rb
$ /Users/kiichi/IdeaProjects/jruby/bin/jruby -Xbacktrace.style=mri /Users/kiichi/IdeaProjects/jruby/spec/mspec/bin/mspec-ci spec/ruby/security/cve_2018_8779_spec.rb
uri:classloader:/jruby/kernel/kernel.rb:4: warning: unsupported exec option: close_others
jruby 9.4.0.0-SNAPSHOT (3.1.0) 2022-08-20 ddd1ed1ec1 OpenJDK 64-Bit Server VM 11.0.15+0 on 11.0.15+0 +jit [arm64-darwin]
1)
CVE-2018-8779 is resisted by UNIXServer.open by raising an exception when there is a NUL byte ERROR
Expected ArgumentError ((?-mix:(path name|string) contains null byte))
but got: …
```
=> Fix UNIXServer.open, UNIXSocket.open and some Dir class methods when argument contains NUL byte

core/src/main/java/org/jruby/RubyModule.java, spec/ruby/core/module/fixtures/classes.rb, spec/ruby/core/module/included_modules_spec.rb
I discovered this issue while investigating https://github.com/jruby/jruby/issues/7256
The included_modules method would sometimes include a wrapped module. With this change, the prepended module now shows up in this list, and not the anonymous/wrapped module (which looks to be just a JRuby implementation detail). included_modules now matches what CRuby returns for this case
=> Fix included_modules method to not return wrapped modules

core/src/main/java/org/jruby/Main.java, core/src/main/java/org/jruby/RubyException.java, test/jruby/test_exception.rb
Fix for https://github.com/jruby/jruby/issues/7316
Revert d2d594f8b76cb52758cc6dd498eb9ed0b61032bf and use similar approach from CRuby: https://github.com/ruby/ruby/commit/18492887224cd1aa1aa862ed0fa5237df31ead81
=> Fix issue #7316 runtime error when nested raise

core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/ext/zlib/JZlibDeflate.java, core/src/main/java/org/jruby/ext/zlib/JZlibInflate.java, core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java, core/src/main/java/org/jruby/ext/zlib/ZStream.java
a slight incompatibility I've found while testing the hexapdf gem
spec https://github.com/ruby/spec/pull/941
=> fix zlib encoding

core/src/main/java/org/jruby/RubyFileStat.java, spec/tags/ruby/core/file/stat/inspect_tags.txt
This commit fixes Files::Stat#inspect by using atime#inspect, mtime#inspect and ctime#inspect.
* spec/ruby/core/file/stat/inspect_spec.rb
=> Fix File::Stat#inspect

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/AttrAssignInstr.java, core/src/main/java/org/jruby/ir/instructions/CallBase.java, core/src/main/java/org/jruby/ir/instructions/CallInstr.java, core/src/main/java/org/jruby/ir/instructions/ClassSuperInstr.java, core/src/main/java/org/jruby/ir/instructions/EQQInstr.java, core/src/main/java/org/jruby/ir/instructions/InstanceSuperInstr.java, core/src/main/java/org/jruby/ir/instructions/MatchInstr.java, core/src/main/java/org/jruby/ir/instructions/NoResultCallInstr.java, core/src/main/java/org/jruby/ir/instructions/UnresolvedSuperInstr.java, core/src/main/java/org/jruby/ir/instructions/ZSuperInstr.java, core/src/main/java/org/jruby/ir/instructions/specialized/OneArgOperandAttrAssignInstr.java, core/src/main/java/org/jruby/ir/instructions/specialized/OneFixnumArgNoBlockCallInstr.java, core/src/main/java/org/jruby/ir/instructions/specialized/OneFloatArgNoBlockCallInstr.java, core/src/main/java/org/jruby/ir/instructions/specialized/OneOperandArgBlockCallInstr.java, core/src/main/java/org/jruby/ir/instructions/specialized/OneOperandArgNoBlockCallInstr.java, core/src/main/java/org/jruby/ir/instructions/specialized/OneOperandArgNoBlockNoResultCallInstr.java, core/src/main/java/org/jruby/ir/instructions/specialized/TwoOperandArgNoBlockCallInstr.java, core/src/main/java/org/jruby/ir/instructions/specialized/ZeroOperandArgNoBlockCallInstr.java, core/src/main/java/org/jruby/ir/interpreter/Profiler.java, core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/transformations/inlining/CFGInliner.java
Null object pattern is better here than constantly null-checking.
See f6ca739fbd4fc3fa101adb34ee319be6a78b232d for an example of confusion around whether this should be null or NullBlock.
=> Never store a null for closure operand

lib/pom.rb, lib/pom.xml
This pulls in a couple years of fixes including ruby/csv#120 which fixes #7346 (dangling fiber threads after CSV.parse_line).
=> Update CSV to 3.2.5

core/src/main/java/org/jruby/internal/runtime/ThreadService.java
If the main thread performing the teardown appears earlier in this map, we may skip the teardown of remaining threads. Instead, we avoid the kill+join dance for the current thread to ensure all other threads get a chance to terminate.
=> Avoid accidentally killing the teardown thread

core/src/main/java/org/jruby/ast/BignumNode.java, core/src/main/java/org/jruby/ast/ComplexNode.java, core/src/main/java/org/jruby/ast/FixnumNode.java, core/src/main/java/org/jruby/ast/NumericNode.java, core/src/main/java/org/jruby/ast/RationalNode.java, core/src/main/java/org/jruby/parser/ParserSupport.java, core/src/main/java/org/jruby/parser/RubyParser.java, core/src/main/java/org/jruby/parser/RubyParser.y
The wrong interface was being checked which made too many things get hit with this warning.  Fixing to use proper one and also auditing and correcting some missing types from the proper type should make this all correct.
Two bonus fixes:
1. Make warn text match 2.6.x from MRI
2. Do not print the same warning twice for the same piece of code.
=> Fix 7317 it warns me about "warning: found = in conditional, should be =="

core/src/main/java/org/jruby/util/RubyDateFormatter.java, spec/tags/ruby/library/date/strftime_tags.txt, spec/tags/ruby/library/datetime/strftime_tags.txt
When %v is given, the month should be uppercase.
See https://bugs.ruby-lang.org/issues/13810
=> Fix Date#strftime and DateTime#strftime with %v

core/src/main/java/org/jruby/RubyTime.java
This version of the fix  for #7265 makes arg3 = :microseconds as a default value similar to Ruby (Time#at is now impld in Ruby and is this way).
=> Fixes Time.at argument handling (#7265)

lib/pom.rb, lib/ruby/stdlib/resolv.rb, test/mri/resolv/test_addr.rb
This will fix the IPv6 parsing when the address has local zone id e.g. `fe80::861e:a3ff:fea5:dd27%en0` where `%en0` is a zone id
Extra links: 
* MRI issue - [resolv: add some more characters in IPv6 link local zone id](https://bugs.ruby-lang.org/issues/17524)
Example: 
```ruby
resolv = Resolv.new([
Resolv::Hosts.new
])
resolv.getaddress('google.com')
```
leads to
```
Traceback (most recent call last):
16: from org/jruby/RubyArray.java:1865:in `each'
15: from /Users/vidok/.rbenv/versions/jruby-9.3.3.0/lib/ruby/stdlib/resolv.rb:122:in `block in each_address'
14: from /Users/vidok/.rbenv/versions/jruby-9.3.3.0/lib/ruby/stdlib/resolv.rb:410:in `each_address'
13: from /Users/vidok/.rbenv/versions/jruby-9.3.3.0/lib/ruby/stdlib/resolv.rb:513:in `each_resource'
12: from …
```
=> Update Resolv to the latest MRI version

core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyThread.java, core/src/main/java/org/jruby/ext/fiber/FiberQueue.java, core/src/main/java/org/jruby/ext/fiber/ThreadFiber.java, spec/tags/ruby/core/fiber/raise_tags.txt, spec/tags/ruby/core/fiber/yield_tags.txt
This implements Fiber#raise by introducing a new transfer mechanism, FiberRequest, which can be used to do the raise safely on the Fiber side rather than trying to force it through thread mechanism. No specs regressed and nearly all Fiber#raise specs now pass, but I have not investigated the performance impact of this additional carrier object yet.
=> Implement most of Fiber#raise

core/src/main/ruby/jruby/kernel.rb, core/src/main/ruby/jruby/kernel/thread.rb, spec/tags/ruby/core/thread/ignore_deadlock_tags.txt
We do not have deadlock detection at lock edges, so there's no way to implement this. This patch adds it as a simple attr_accessor that does nothing else.
=> Implement Thread.ignore_deadlock as no-op

core/src/main/java/org/jruby/RubyHash.java
This was never intended to dodge arity-checking and the original behavior was introduced with optimizations in Ruby 2.1. The new logic is to always yield a single two-element array when the target block is a lambda.
See https://bugs.ruby-lang.org/issues/12706
=> Always yield two-elt ary from Hash#each to lambda

core/src/main/java/org/jruby/Ruby.java
Fixes #7370.  We print out twice because main script will try and precompile and we will raise a syntaxerror (RaiseError) but our code will blanket catch Exception/Throwable and end up trying to run the same code through the interpreter.
=> Fixes #7370: yield in class body produces two SyntaxError outputs

core/src/main/java/org/jruby/RubyThread.java, spec/tags/ruby/core/thread/inspect_tags.txt, spec/tags/ruby/core/thread/to_s_tags.txt
The following tests will pass except encoding test.
* spec/ruby/core/thread/inspect_spec.rb
* spec/ruby/core/thread/to_s_spec.rb
=> Fix Thread#inspect and #to_s behaviors to match mri

core/src/main/java/org/jruby/RubyThread.java, test/jruby/test_thread.rb
Some of this was already fixed by @k77ch7 in #7376 but those changes were made to match our own `test_inspect_and_to_s`, which had several lines modified to pass on JRuby and not run on CRuby. I have unmasked those lines, modified them to pass on CRuby, and adjusted JRuby behavior accordingly.
=> Various fixes for Thread#to_s

core/src/main/java/org/jruby/RubyHash.java, spec/tags/ruby/core/hash/hash_tags.txt
If using xor of key's hash and value's hash, a hash value always become to be 0. Therefore, to avoid generating 0 value, this commit uses hash of 16 bytes array which contains key's hash and values's hash.
* spec/ruby/core/hash/hash_spec.rb
=> Fix Hash#hash to return a correct value when key and value are same

core/src/main/java/org/jruby/RubyRange.java, spec/tags/ruby/core/range/dup_tags.txt, spec/tags/ruby/core/range/last_tags.txt, spec/tags/ruby/core/range/minmax_tags.txt
- Fix Range#dup to create an unfrozen range
- Fix Range#last (See https://bugs.ruby-lang.org/issues/18994)
=> Fix Range#dup and Range#last

core/src/main/java/org/jruby/RubyObjectSpace.java, core/src/main/java/org/jruby/javasupport/JavaPackage.java, core/src/main/java/org/jruby/runtime/ObjectSpace.java
IRB and Pry find modules via ObjectSpace, and arguably packages aren't  modules.
This change removes java packages from iteration. 
Fixes #7323 
While this change and the IRB change have overlap, I think both should be implemented for completeness
=> Fix #7323 by excluding java packages from ObjectSpace Module iteration

lib/ruby/stdlib/pty.rb
Also now looks less error-y
Before:
```
jruby-9.3.4.0 :016 > PTY.open
=> [#<IO:fd 18>, #<File:nil>] 
```
After/MRI:
```
2.6.2 :035 > PTY.open
=> [#<IO:masterpty:/dev/pts/42>, #<File:/dev/pts/42>] 
9.4.0.0 :002> PTY.open
=> [#<IO:masterpty:/dev/pts/49>, #<File:/dev/pts/49>]
```
=> Match MRI inspect values for PTY.open

lib/pom.rb, lib/pom.xml
A fix for https://github.com/jruby/jruby/issues/7335
https://github.com/jruby/jruby-openssl/releases/tag/v0.14.0
=> Updating jruby-openssl to 0.14.0

lib/pom.rb, lib/pom.xml
Updates SnakeYAML to 1.33 to address CVE-2022-38752 per #7386
=> Update to Psych 4.0.6

core/src/main/java/org/jruby/RubyHash.java, spec/tags/ruby/core/hash/each_pair_tags.txt, spec/tags/ruby/core/hash/each_tags.txt, spec/tags/ruby/core/hash/rehash_tags.txt, spec/tags/ruby/core/hash/ruby2_keywords_hash_tags.txt
This commit adds additional logic to remove duplicate key.  
* spec/ruby/core/hash/rehash_spec.rb
Before applies this patch, the rehash spec sometimes fails.
```
it "removes duplicate keys for large hashes" do
a = [1,2]
b = [1]
h = {}
h[a] = true
h[b] = true
100.times { |n| h[n] = true }
b << 2
h.size.should == 102
h.keys.should.include? a
h.keys.should.include? b
h.rehash
h.size.should == 101
h.keys.should.include? a
h.keys.should_not.include? [1]
end
```
=> Fix Hash#rehash when a hash is large and contains duplicate keys

core/src/main/java/org/jruby/RubyDir.java, core/src/main/java/org/jruby/RubyGlobal.java, core/src/main/java/org/jruby/util/io/EncodingUtils.java, spec/tags/ruby/core/dir/read_tags.txt, spec/tags/ruby/core/encoding/default_external_tags.txt, spec/tags/ruby/core/encoding/list_tags.txt
This commit also fixes 'Encoding.default_external=' behavior.
The following test will pass when this two updates are complete.
* spec/ruby/core/dir/read_spec.rb
=> Fix Dir#read when external encoding changed

core/src/main/java/org/jruby/RubyTime.java
* Don't normalize to UTC before setting time zone in the single- arg Time.at with a zone kwarg. timeZoneLocal does that before setting the passed-in zone, and if no zone is provided we should leave it local.
* When normalizing to UTC in zoneLocalTime, allow DateTime to also adjust the time, so we get the real equivalent time in UTC. This pairs with the above fix to only apply the zone offset once, and only apply it in the timeZoneLocal call tree.
Fixes #7406
=> Better match CRuby zone negotiation

test/mri.stdlib.index
'uninitialized constant IO::Buffer (NameError)' occurs because of IO::Buffer is not implmented.
=> Update mri.stdlib.index to execute 'rake test:mri:stdlib'.

core/src/main/java/org/jruby/RubyFile.java
This patch prevents TypeError.
```
TypeError: no implicit conversion of Hash into String
org/jruby/RubyFile.java:868:in `expand_path'
```
JRuby head
```
ruby test/mri/runner.rb  --excludes=test/mri/excludes -q -- csv test_tempfile.rb ruby/test_file.rb
results
930 tests, 9007 assertions, 0 failures, 151 errors, 0 skips
```
JRuby head + patched
```
jruby test/mri/runner.rb  --excludes=test/mri/excludes -q -- csv test_tempfile.rb ruby/test_file.rb
results
930 tests, 9091 assertions, 1 failures, 1 errors, 0 skips
```
=> Fix File#expantd_path to prevent many errors when stdlib tests run

rakelib/test.rake
When test:mri:core:int or test:mri:core:jit run, many NoMethodError occurs.
```
NoMethodError: undefined method `formatter' for DidYouMean:Module
```
This commit removes --disable-gem option from test.rake file because test/mir/ruby/test_pattern_match.rb requires DidYouMean module.
=> Update test.rake option

core/src/main/java/org/jruby/RubyEnumerator.java, core/src/main/java/org/jruby/java/proxies/ArrayJavaProxy.java, core/src/main/java/org/jruby/javasupport/ext/JavaLang.java, core/src/main/java/org/jruby/javasupport/ext/JavaUtil.java, spec/compiler/general_spec.rb, spec/tags/ruby/core/enumerator/new_tags.txt
Enumerator.new without a block should raise ArgumentError. 
* spec/ruby/core/enumerator/new_spec.rb
* test_initialize in test/mri/ruby/test_enumerator.rb
This PR also update `spec/compiler/general_spec.rb` to adapt Enuemurator.new behavior.
And this PR uses enumeratorize or enumeratorizeWithSize instead of `runtime.getEnumerator().callMethod("new", ...)` in som Java classes to prevent spec:compiler and spec:ji failures(https://github.com/jruby/jruby/actions/runs/3290468184).
=> Fix Enumerator.new without a block

core/src/main/ruby/jruby/kernel/enumerator.rb, spec/tags/ruby/core/enumerator/lazy/filter_map_tags.txt
This commit implements filter_map method in ruby code. 
* test_filter_map in test/mri/ruby/test_lazy_enumerator.rb
* spec/ruby/core/enumerator/lazy/filter_map_spec.rb
=> Fix Enumerator::Lazy#filter_map

core/src/main/java/org/jruby/RubyRational.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/util/Numeric.java, test/mri/excludes_wip/Rational_Test.rb
This PR fixes String#to_r for edges case
e.g. '5__5/33'.to_r => 5/1, '5/3.3_'.to_r => 50/33
This PR also fixes Marshal#load for Rational Class
* test_parse in test/mri/ruby/test_rational.rb
* test_marshal in test/mri/ruby/test_rational.rb
=> Fix String#to_r and Marshal#load for Rational Class

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/DebugOutputInstr.java, core/src/main/java/org/jruby/ir/instructions/IntegerMathInstr.java, core/src/main/java/org/jruby/ir/instructions/NopInstr.java
This addresses all known pattern matching errors except enhanced error throw messages with single line matches.  The 10 failures of that still appropriately fail in === cases but does not print out the same amount of info ('{}' vs '{}: : Array === {} does not return true' .  I do not consider that important for 9.4.0.0 but I may still fix it by release time since it is 10E in MRI test suite.
This branch also changed labels in IR to be more friendly for debugging.  We are not sharing labels in IR so this should not really affect size.  It does help determine what a label is meant for.
This branch also added a new debug instr for printing out any operands live value to stdout.  This instr is never meant to be committed but is very useful: ```debug("Call receiver: %s", receiver")```.  Also …
=> Last functional pattern match errors fixed.

core/src/main/java/org/jruby/ext/ripper/RipperParser.java, core/src/main/java/org/jruby/parser/RubyParser.y
Fix #7274.  tUPLUS is an IRubyObject and not a ByteList.
=> Fix #7427. ripper blow up.

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyInstanceConfig.java, core/src/main/java/org/jruby/common/RubyWarnings.java, core/src/main/java/org/jruby/runtime/load/LoadService.java, core/src/main/java/org/jruby/util/cli/ArgumentProcessor.java
* Move active set of categories into Ruby state.
* Handle -W with :deprecated, :no-deprecated, :experimental, and :no-experimental.
A behavioral difference remains, in that if -W is not followed by a digit or a colon, the next character is interpreted as the next single-character command-line flag.
=> Add support for -W:category flag

core/src/main/java/org/jruby/RubyInteger.java, test/mri/excludes_wip/Rational_Test.rb
When operands are Integer type, operands should be divided by gcd.
After applying this patch, the following test will pass.
* test_supp in test/mri/ruby/test_rational.rb
=> Update Integer#fdiv to match mri behavior

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/internal/runtime/methods/AliasMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/DynamicMethod.java
MRI has more logic than this so I think something is missing but we are also already missing logic associated with potentially redefined refinements.  This will definitely get rid of some warnings but perhaps too many.
=> Remove some alias warnings

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/runtime/load/LoadService.java, test/mri/excludes_wip/TestRequire.rb
Plumbing the wrapper all the way through the interfaces involved is more of a change than we are comfortable with at this stage, so use a thread-local to set up the fea cases that currently honor the wrapper.
Ruby feature https://bugs.ruby-lang.org/issues/6210
Part of Ruby 3.1 features (#7015).
Fixes #7439
=> Use thread-local for load wrapper

core/src/main/java/org/jruby/ext/ffi/jffi/DynamicLibrary.java, core/src/main/java/org/jruby/util/JRubyClassLoader.java, core/src/main/java/org/jruby/util/JRubyFile.java
After inspecting other options in the java ecosystem, like maven-lib-loader and others, I realized that all of them are for JNI and thus not applicable to JRuby. Further, doing this in JNR/JFFI would require duplicating code both there and in JRuby, so this seems to be the best spot for now.
so/dylib/dll files are now loadable from embedded resources by being extracted to the jruby temp dir before being sent to JFFI
=> Bundled and jarified native library loading for ffi

core/pom.rb, core/pom.xml, pom.rb, pom.xml
This brings in updates to jffi and jnr-ffi for LoongArch64 support plus miscellaneous fixes.
=> Update JNR dependencies for loongarch64 support

lib/ruby/stdlib/pty.rb
Something in the subspawn pty replacement causes stderr to be closed during testing. See https://github.com/jruby/jruby/actions/runs/3485667896/jobs/5831405466
This is a temporary fix until we can determine why subspawn's pty logic does this.
=> Use old pty.rb on Windows

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
checkHashType is called immediately above it.  It cannot be undefined.
=> Undefined impossible here.

maven/jruby-jars/jruby-jars.gemspec
JRuby was updated from EPL-1.0 to EPL-2.0 in https://github.com/jruby/jruby/commit/6fe0e5a1a93b006ee41764e2b7c1d7fc72514a90, but this metadata was missed.
If I've misunderstood, and the licensing of jruby-jars differs from jruby itself, I'm sorry. The [jruby-jars README](https://github.com/jruby/jruby/commit/6fe0e5a1a93b006ee41764e2b7c1d7fc72514a90#diff-7dce96ed26a75ec1de92a0f8111704c57e1ca510fc6ee8451428286b7a673186L835) was updated at the same time to use EPL-2.0
=> Update EPL version in jruby-jars Gemspec

.github/workflows/ci.yml
Several long-running jobs were not starting until late in each CI run, and several known-flaky or exotic suites were higher up. This patch moves the core Ruby compatibility tests higher up in the ordering, with third-party gems, exotic platforms, and expected failures toward the bottom.
=> Reorder CI jobs

.github/workflows/ci.yml
These suites have been failing for some time and we will not be able to diagnose the problem before 9.4. This PR ignores their failures for now. See #7470 and #7471.
=> Ignore failures in OpenJ9 and M1 CI jobs

core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java
=> Remove Hash index method, and fix ruby2_keywords_hash module method

.github/workflows/ci.yml, .github/workflows/snapshot-publish.yml
The version 3.x appears to be due to the following:
- https://github.com/actions/checkout/pull/689
There have been no breaking changes, and we seem to have no problem keeping up with the latest version.
=> Update actions/checkout version to v3

core/src/main/java/org/jruby/ir/IRScope.java
in irb we get a scenarion where we delete parent scope of a closure because at the time we delete it we do not know a closure will exist. The fix is a trivial bullet-proof test line.  Our actual code calling prepareForCompilation already is aware that null fic is a failure case.
=> one-time-execute can sometimes contain a closure.  guard it.

core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
This seems to fix an issue locally running railsbench under indy mode
that is superficially similar to #7434.
The issue occurs in our own Kernel#initialize_dup when running with JIT
and indy enabled. The originator is a Hash#merge that does a dup of an
empty hash, ultimately attempting to convert our UndefinedValue into a
hash object for the dup/replace logic. It seems like there's a rogue
keyword flag in the CallInfo at this point, such that it assumes the
incoming hash is supposed to be used as kwargs. Since it is empty, it
returns undefined which replaces the single hash argument passed in.
That value then goes on to be to_hash'ed and blows up.
It is unclear why this requires indy mode. There may be something
broken with CallInfo clearing alonst some indy path, or the non-indy
call …
=> Specific arity kwargs undefined

core/src/main/java/org/jruby/ir/IRBuilder.java
Fixes #7500.  The check in splats assumes any instanceof ListNode is arguments to be merged with the splat but all dynamic nodes like interpolated strings happen to be ListNodes as well (damn you OO).
=> DNodes are ListNodes and get compiled wrong in presence of a splat.

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/RuntimeHelperCall.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
The warns in place should happen for hash merging ** vs kwrest values combined with other kwrest or the kwreqs.
This fixes #7499
=> Excessive kwargs duplicate key warns

core/src/main/java/org/jruby/ast/ForwardingBlockArgNode.java, core/src/main/java/org/jruby/ext/ripper/RipperParser.java, core/src/main/java/org/jruby/parser/RubyParser.java, core/src/main/java/org/jruby/parser/RubyParser.y, core/src/main/java/org/jruby/parser/RubyParserBase.java, core/src/main/java/org/jruby/util/CommonByteLists.java
The primary fix here is to make a new subtype to tell whether we are using FWD_BLOCK or not (ForwaringBlockArgNode).  Secondary clarifier is to make ANON_BLOCK to complement FWD_BLOCK (both are '&').
The irony of the check is this is for a warning of something like: def foo(*r, ...); end
Notice '&' is not even in this signature.  They use existence of '&' as a proxy for '...'.
Fixes #7506
=> Fix syntax error in all cases where & is a param.

core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java, core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipWriter.java
Fixes #7476.  For any new to support subclasses we will have to annotate them until we make the newer keyword argument system.
=> Fixes #7476. Zlib::GzipWriter cannot be properly sub-classed

core/src/main/java/org/jruby/ext/zlib/RubyGzipFile.java
Ancient FIXME described this bug :)
Use kindOfModule to fix it vs Java identity check.
Fixes #7479
=> Fixes #7479. Cannot sub-class Zlib::GzipWriter and call .wrap

core/src/main/java/org/jruby/ext/ffi/Platform.java, core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java, install/jruby.install4j, spec/ffi/fixtures/compile.rb
The new version of jnr will support LoongArch64, wait for jnr to be released and then verify if this patch is appropriate for LoongArch
=> Support for LoongArch64

core/src/main/java/org/jruby/RubyFile.java, core/src/main/java/org/jruby/RubyGlobal.java, core/src/main/java/org/jruby/runtime/encoding/EncodingService.java, core/src/main/java/org/jruby/util/OSEnvironment.java
fixes a couple of broken encodings related to ENV variables like Dir.home and FileUtils.
CRuby 3.1 has switched from filesystem encodings to UTF-8, so let's try that... see https://github.com/ruby/ruby/pull/3818
=> ENV encoding fixes (windows)

core/src/main/java/org/jruby/ext/ffi/jffi/Factory.java
the current implementation isn't thread-safe, so the current errno context could be lost
errno is already implemented via LastError, so let's just alias it https://github.com/jnr/jffi/blob/master/jni/jffi/LastError.c#L72
fixes https://github.com/jruby/jruby/issues/7521
=> alias winapi_error to lasterror

core/src/main/java/org/jruby/RubyEnumerator.java
This is really weird that it is ASCII-8BIT by default but if you inspect something which inside of the enumerator is UTF-8 then the result string should also be UTF-8.
This fixes #7529
=> Enumerator#inspect: Use String concatenation not just bytelist appends

core/src/main/java/org/jruby/RubyEnumerator.java, core/src/main/java/org/jruby/RubyKernel.java, spec/regression/GH-7529_enumerator_inspect_has_ascii_encoding_spec.rb
I wanted to contribute a regression test for issue #7529, as a follow-up to its fix by @enebo in #7531, but I noticed that there was *already* a corresponding test case in the MRI test suite.
Before the fix, with master 278aaac1cf29da19e245a3903aedbac6d6e34334:
```
$ jruby test/mri/runner.rb  test/mri/ruby/test_enumerator.rb
...
[48/63] TestEnumerator#test_inspect_encoding = 0.02 s
7) Failure:
TestEnumerator#test_inspect_encoding [/home/cboos/workspace/jruby/test/mri/ruby/test_enumerator.rb:440]:
<#<Encoding:UTF-8>> expected but was
<#<Encoding:ASCII-8BIT>>.
Finished tests in 2.532488s, 24.8767 tests/s, 171.7678 assertions/s.
63 tests, 435 assertions, 6 failures, 1 errors, 0 skips
```
However, after the fix, with 1d9723771bb93d53acc4c6480e0097d65ba5154b, that test still failed!
With JRuby …
=> Enumerator inspect tests

core/src/main/java/org/jruby/RubyModule.java
So the basic problem is that (only in the interpreter) we would emit the name of the method/define_method in backtraces instead of the name where the block was originally conceived (lexical location).
This issue has been strange for 3 reasons:
1. JIT/FORCE works.  It generates backtraces differently.
2. mocha tests run in 9.3 in spite of this issue (something else happens)
3. As far as I can tell we have always been incompatible (9.2 at least)
=> Fixes #7492.  define_method should use definition scope.

core/src/main/java/org/jruby/RubyIO.java
IO::new is defined as a native method and was not marked as accepting keywords.
This fixes #7539
=> passthrough anno added

core/src/main/java/org/jruby/RubyThread.java, spec/java_integration/extensions/thread_spec.rb
stumbled upon `thread.to_java('org.jruby.RubyThread').native_thread` at least in 2 separate code-bases
believe 9.4 is a good opportunity to formalize `RubyThread#to_java` support to return a Java thread by default
=> [ji] support converting RubyThread to a java.lang.Thread

core/src/main/java/org/jruby/RubyEnumerable.java, test/mri/excludes/TestEnumerable.rb
* test_zip in test/mri/ruby/test_enum.rb
=> Fix Enumerable#zip when an argument does not have each method

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/RubyUnboundMethod.java, test/mri/excludes/TestSuper.rb
When the incoming UnboundMethod is from a Module not already
included in the target receiver's class hierarchy, the newly bound
Method should treat that method as living in a virtual module
included below the receiver's class. This allows the rebound
method to use `super` to call a method of the same name in the
receiver's hierarchy.
For the original change in CRuby (2.2) see:
https://github.com/ruby/ruby/commit/46f578d806df70c4cae43b614e56558977a4cc44
For the additional change to avoid the extra include class when
the owner module is already in the target hierarchy, see:
https://github.com/ruby/ruby/commit/160b67df68655322d09f566914c89e2d3e7cfc05
Fixes #7548.
=> UnboundMethod#bind should introduce include class

core/src/main/java/org/jruby/ir/IRBuilder.java, spec/ruby/language/fixtures/super.rb, spec/ruby/language/super_spec.rb
Fixes #7537.
zsuper within closure was not detecting keywords from the surrounding method.  This was pretty simple.  We were asking current scope (closure) if it received keywords.  We should be asking method scope for this.
=> Fixes #7537.  Kwargs arg regression.

core/src/main/java/org/jruby/ext/etc/RubyEtc.java
This is actually two fixes:
1. errno() is not set to 0 by sysconf???  So while running spec:ruby:fast it would get set to something and a couple of sysconfs would return -1 but expect errno == 0.  Kaboom.
2. we did not obey semantics that ret == -1 and errno == 0 should return nil.
(backported from 9.4)
=> Etc#sysconf errors when it shouldn't

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/internal/runtime/methods/AliasMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/DynamicMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/SynchronizedDynamicMethod.java
alias and synchronized methods are only wrappers so they should mark their source methods as being ruby2_keywords.  This also put setRuby2Keywords onto DynamicMethod to make it more clear this is a Ruby thing and not an IR-specific thing (IRMethodArgs as a cast is confusing).
=> Delegating methods must be able to set ruby2_keywords on delegate.

core/src/main/java/org/jruby/RubyBignum.java, spec/tags/ruby/core/float/gt_tags.txt, spec/tags/ruby/core/float/gte_tags.txt, spec/tags/ruby/core/float/lt_tags.txt, spec/tags/ruby/core/float/lte_tags.txt
This fixes float_cmp function to return correct value when float argument is infinity.
* spec/ruby/core/float/gt_spec.rb
* spec/ruby/core/float/gte_spec.rb
* spec/ruby/core/float/lt_spec.rb
* spec/ruby/core/float/lte_spec.rb
=> Fix comparator of Bignum and Infinity 

core/src/main/java/org/jruby/RubyNumeric.java, test/mri/excludes_wip/TestNumeric.rb
* test_remainder_infinity in test/mri/ruby/test_numeric.rb
=> Fix Numeric#remainder when divisor is infinity 

core/src/main/java/org/jruby/RubyFloat.java, core/src/main/java/org/jruby/RubyRational.java, test/mri/excludes_wip/TestNumeric.rb
This change is porting from mri(numeric.c and rational.c).
* test_floor_ceil_ndigits in test/mri/ruby/test_numeric.rb
* test_float_round_ndigits in test/mri/ruby/test_numeric.rb
=> Fix Float#floor and Float#round for some edge cases

test/mri/ruby/test_enum.rb
Its absence causes an intermittent failure, likely caused by load ordering randomness.
```
TestEnumerable#test_sum:
NameError: uninitialized constant TestEnumerable::SimpleDelegator
org/jruby/RubyModule.java:3947:in `const_missing'
/tmp/autopkgtest-lxc.wadx2atf/downtmp/autopkgtest_tmp/test/mri/ruby/test_enum.rb:1051:in `test_sum'
```
=> Fix missing require in mri-core tests

core/src/main/java/org/jruby/ir/IRBuilder.java
This was very narrow in scope.  If you only passed in a single argument we "unwrap" it from the original ```[arg]``` and just pass arg.  This in turn *spreads* whatever is there (if an array).
In this case arg is the keywords arg.  So the fix was to not unwrap in this case.
=> Fixes #7572.  Blocks with only keywords losing keyword status.

core/src/main/java/org/jruby/ir/IRBuilder.java
Almost zero-sum but it allows define_method with kwargs definition to potentially be converted from a proc to a full method and it also checks for whether the fcall is 'using'.  I don't think either of these current will play with kwargs but they may in the future and it is a little extra work to have some cleaner code.
=> Simplify logic in IRBuilder for keyword arguments.

core/src/main/java/org/jruby/platform/Platform.java, core/src/main/java/org/jruby/util/Pack.java
These pack directives are intended to produce an encoded signed or unsigned int of the width of a native pointer. Regardless of whether JRuby treats all platforms as 64-bit (due to JVM's 64-bit nature) we should probably encode these values according to the host platform's bit depth.
Fixes #7542
I do not have a 32-bit platform on which to test this, but hacking JRuby and mspec to pretend the system is 32-bit yields passing specs for the 32-bit logic:
```diff
diff --git a/core/src/main/java/org/jruby/platform/Platform.java b/core/src/main/java/org/jruby/platform/Platform.java
index 1b292498ce..2be4f03bf1 100644
--- a/core/src/main/java/org/jruby/platform/Platform.java
+++ b/core/src/main/java/org/jruby/platform/Platform.java
@@ -126,7 +126,7 @@ public abstract class Platform {
public …
```
=> Use platform bit width for J/j pack directive

core/src/main/java/org/jruby/RubyFloat.java, spec/tags/ruby/core/float/round_tags.txt
This change is porting from mri(numeric.c on master). Mri 3.1 and 3.2 have not been backported yet.
* spec/ruby/core/float/round_spec.rb
See https://bugs.ruby-lang.org/issues/19318 .
=> Fix Float#round with half even option

core/src/main/java/org/jruby/RubyDir.java
Fixes #7583.  We have some fairly convoluted options processing for Dir.glob and Dir.[] which is shared.  We were assuming #glob flags processing was active when we were processing #[] and trying to convert the options kwargs into an int value (boom).
Renamed some stuff for clarity and fixed underlying problem.  A rainy day job here would be to rewrite this method or possibly just make it two methods.  I do not recommend this until our next kwargs design change.  We may have a better interface for specifying kwargs which would make a significant part of this method not exist.
=> Code was trying to make an int out of the kwargs hash.

core/src/main/java/org/jruby/ir/IRBuilder.java
The block passed to `refine` should itself see refined methods. The call was made here, but made after the block was already constructed. Moving the call up allows the block to pick up the refined bit.
This regressed at some point during 9.4 development.
=> Set refinement bit before building closure

core/pom.rb, core/pom.xml, pom.rb, pom.xml
backport https://github.com/jruby/jruby/pull/7453
fixes the Puma issue on aarch64 platform, see https://github.com/jruby/jruby/issues/6821 and https://github.com/jnr/jnr-ffi/pull/299
=> backport Update JNR dependencies

core/src/main/java/org/jruby/RubyRandomBase.java, core/src/main/java/org/jruby/util/Random.java
Without initializing the seed array, this will return zero for all PRNG calls.
Fixes #7586
=> If no seed given, use current millis

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/util/CommonByteLists.java
The tzinfo gem at some point started using `send(:using ...)` to get around a JRuby arity bug. Unfortunately this breaks our detection of refinements, which depends on seeing a direct call to `using` or `refine` and so the refinements were never honored.
This commit also treats `send` with a literal `:using` or `:refine` symbol as a call to the related method.
At some point we may simply have to accept that all scopes could be refined, but this is an ok fix for a very specific and unusual situation.
See https://github.com/tzinfo/tzinfo/issues/145 for the issue reported to tzinfo about all our untaint warnings, which should have been masked by refinement.
=> Treat send of using or refine as refinement

core/src/main/java/org/jruby/lexer/LexingCommon.java
Fixes #7602.  The method checking the next char was actually checking the next char after the next char.  So ranges with an end of one char would see the newline/eof.
=> Fix errant ... warning

bin/jruby.sh
I'm using MSYS2 environment.
jruby.exe is launched not from current directory but globally in system. Even if you run it from current directory, there will be no effect because jruby.exe does nothing but returns code 0.
In PR #37 was added launch jruby.exe of MSYS, but this is the first version of MSYS not MSYS2.
=> Fixed launch jruby in MSYS2 environment

core/src/main/java/org/jruby/java/proxies/JavaProxy.java, spec/java_integration/methods/java_alias_spec.rb
previously doing a MyInterface.java_alias just errored:
`ClassCastException: class org.jruby.RubyModule cannot be cast to class org.jruby.RubyClass`
---
*extracted from https://github.com/jruby/jruby/pull/7503 after I bumped into this twice in 9.3.9.0*
=> [fix] java_alias-ing for interface methods

core/src/main/java/org/jruby/Ruby.java
previously there was no way of "just enabling warnings", warnings were enabled with `setVerbose(IRubyObject verbose)`
to be able to consume warnings but not change `$VERBOSE` I've added a `setWarningsEnabled`.
also for Java consumers it's easier to deal with Java values thus `setVerbose(Boolean verbose)` overload is added ...
=> [feat] allow enabling warnings wout changing $VERBOSE

core/src/main/java/org/jruby/RubyGlobal.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/common/RubyWarnings.java
the `runtime.getWarnings().warnDeprecated(name)` call was sometimes used as if it was passed a `"message"`
... which leads to deprecated warnings such as `jruby -v -e 'puts lambda(&proc {})'` : 
```
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 11.0.14.1+1 on 11.0.14.1+1 +jit [x86_64-linux]
-e:1: warning: lambda without a literal block is deprecated; use the proc without lambda instead is deprecated
#<Proc:0x68d6f48e -e:1>
```
(not the `" is deprecated"` at the end - added by the `warnDeprecated(String)` invocation)
reviewed all places using `warnDeprecated(String)` and started using an `warnDeprecated(ID, String)` overload which passes the message - this means some places also have a better ID tag (although it isn't used that much).
=> [refactor] warnings which assumed a message is being passed

core/src/main/java/org/jruby/RubyRandomBase.java
CRuby first attempts to call `bytes` on the given random object in order to allow random number implementations to override only that one method in order to change the random number source. We were skipping this logic and going straight back to our internal PRNG logic.
This had two effects:
* SecureRandom and similar classes would not always be the source for random numbers they appear to generate, since this callback to `bytes` was not happening for long-ranged random numbers.
* The test_ulong_limited_no_rand test from CRuby's test_rand.rb failed 50% of the time because we continued to generate actual random numbers (1..2) rather than using the non-random overridden `bytes` method.
=> Implement ulong random logic with random bytes

core/src/main/java/org/jruby/ir/instructions/RuntimeHelperCall.java, core/src/main/java/org/jruby/javasupport/JavaEmbedUtils.java, core/src/test/java/org/jruby/javasupport/JavaEmbedUtilsTest.java
~~the main thing is to fix an issue with `java_alias` that did not work with interfaces (included test errors with a `ClassCastException` using JRuby 9.3.9.0).~~
ended up in a code base that uses `JavaEmbedUtils`'s `invokeMethod` and `rubyToJava`, and require and extra cast which seemed like a missed opportunity :wink:
=> [refactor] make Java embed utils generic

lib/pom.rb, lib/pom.xml, test/mri/psych/helper.rb, test/mri/psych/test_array.rb, test/mri/psych/test_coder.rb, test/mri/psych/test_date_time.rb, test/mri/psych/test_encoding.rb, test/mri/psych/test_hash.rb, test/mri/psych/test_merge_keys.rb, test/mri/psych/test_numeric.rb, test/mri/psych/test_object.rb, test/mri/psych/test_parser.rb, test/mri/psych/test_psych.rb, test/mri/psych/test_safe_load.rb, test/mri/psych/test_scalar_scanner.rb, test/mri/psych/test_yaml.rb
Fixes #7570
Fixes #6365
See #7600 for the same PR against 9.3, which needs work because the tests do not pass with newer Psych's safe_load logic.
=> Use Psych 5.1

Gemfile
Relates to #7630, which may be a new incompatibility in rspec.
=> Update to rspec 3.12

core/src/main/java/org/jruby/internal/runtime/ThreadService.java
Previously, if we encounter an adopted thread when terminating the ThreadService we return early and fail to finish killing threads we spawned.
This changes the `return` to `continue` which I believe was always the intent.
=> Do not return early from ThreadService#terminate

core/src/main/java/org/jruby/ir/targets/indy/InvokeSite.java, spec/compiler/general_spec.rb
Original logic used hardcoded argument offsets, which was broken by my work in #7589 that removed the "caller" argument from self- calls that don't need to check visibility.
The new logic uses SmartBinder and Signature to manipulate incoming arguments by name rather than by index.
Fixes #7642
=> Use SmartBinder to set up struct calls

core/src/main/java/org/jruby/RubyArray.java, test/jruby/test_array.rb
If start >= array.size and length = 0, array#fill should extends self with nil.
Fixes #7648
=> Fix Array#fill for edge case

core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java, test/mri/excludes/TestBigDecimalUtil.rb
This change uses BigDecimal(string) instead of BigDecimal(double) to generate correct BigDecimal value and to avoid precision error.
Fixes #7650
=> Fix Float#to_d of bigdecimal/util

.github/workflows/ci.yml
This should eliminate warnings due to the GHA caching mechanism "save-state" getting aged out and replaced with newer "saveState".
=> Use new cache action

core/src/main/java/org/jruby/ir/interpreter/ExitableInterpreterContext.java
This was based on the potentially splitting constructor not passing on callInfo state.  This state is used to determine info about whether the last argument is a keyword or not.
=> Fixes #7637. Arity error with kwargs when subclassing a java class

core/src/main/java/org/jruby/Ruby.java, spec/tags/ruby/language/END_tags.txt
At some point we started making new block instances so they will never appear to be the same.  Change to blockbody and assume no one will be using the same body in multiple ways then register those are separate END blocks :)
=> END blocks had regressed and was calling same block >1

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/runtime/callsite/RespondToCallSite.java, spec/tags/ruby/core/kernel/respond_to_tags.txt
Call same method as MRI.  Old one was working but was giving a less specific error string.
=> Kernel#respond_to? return wrong error string but right error.

core/src/main/java/org/jruby/RubyProc.java, core/src/main/java/org/jruby/RubySymbol.java, spec/tags/ruby/core/proc/inspect_tags.txt, spec/tags/ruby/core/proc/to_s_tags.txt
Logic was there but weird relying on a side-effect which was never made.  This logic is less clever but also less likely to cause weird behavior (who knows what will happen if you reuse file in blockbody for other stuff?).
=> Proc#inspect with &:foo should print that out in str

core/src/main/java/org/jruby/ir/IRBuilder.java, spec/ruby/language/hash_spec.rb
Issue is in ordinary hash building this sort of duplication should be warned but in explicit kwargs they should not be.  When we built hashes we did not differentiate between the two types.
This is still missing testing.
=> Fix #7672. warning about duplicated keys

core/src/main/java/org/jruby/RubyInstanceConfig.java, spec/tags/ruby/command_line/feature_tags.txt
RUBYOPT was still processed whether it was disabled or not.
=> disabling RUBYOPT processing was not hooked up.

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, spec/tags/ruby/command_line/frozen_strings_tags.txt
AST/IR stores lines as zero-offset.  We report as one-offset.
=> Frozen string debugging off by one.

core/src/main/java/org/jruby/Ruby.java, spec/tags/ruby/command_line/dash_p_tags.txt
The -p command line should use print and not puts.
=> The -p command line should use print and not puts.

core/src/main/java/org/jruby/util/KCode.java, core/src/main/java/org/jruby/util/cli/ArgumentProcessor.java, spec/tags/ruby/command_line/dash_upper_k_tags.txt
Fixed windowsJ encoding and do not set on invalid K values
=> Fixed windowsJ encoding and do not set on invalid K values

core/src/main/java/org/jruby/ir/IRBuilder.java
The Parser for JRuby 9.4 is very different from 9.3.  Somehow we are emitting an implicit nil node for empty returns AND that somehow is the node marked as newline (which then is used to emit a line number instr).  implicit nils have a line number of -1.
=> Fix #7670. Coverage data goes off the rails.

core/src/main/java/org/jruby/common/RubyWarnings.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
Callback receives the warning's stack trace element and must return a formatted message. This allows reusing the same single trace element rather than generating it twice to build the message elsewhere.
=> Add a warn form that takes a callback

core/src/main/java/org/jruby/util/cli/Options.java
When outputting exception traces and IR printing to the console, use color by default if the console is attached to a TTY. We detect this by checking whether System.console() produces a non-null result.
=> Enable color if console is a tty

core/src/main/java/org/jruby/util/io/OpenFile.java
read all and read line were calculating CR but not setting it on the resulting string.  This prevents resulting string from having single byte optimizable code paths work.  I only did one benchmark using aref and it appears to be a little faster consistently but not a lot.  I imagine using really long lines and a complicated backtracking regexp will make this pop.
=> Make coderange set on strings created from some IO ops

core/src/main/java/org/jruby/RubyEnumerator.java
The JIT may call along these paths and they do not properly reject arities higher than 1.
Fixes #7708
=> Eliminate 2- and 3-arity paths for Enumerator#initialize

core/src/main/java/org/jruby/RubySymbol.java, spec/ruby/core/symbol/inspect_spec.rb
We only checked if first char was lower case if not a special character and if so we would always quote the symbol in Symbol#inspect! (e.g. :BAD.inspect -> ":\"BAD\"").
=> We were quoting symbols in inspect we shouldnt have

core/src/main/java/org/jruby/ast/InNode.java, core/src/main/java/org/jruby/ir/IRBuilder.java
Ruby 3.1 added more descriptive error strings.  This requires fishing some variables around.  Thus far only error for array pattern is supported.  More will be added in the future.
=> Add infra to support Ruby 3.1 pattern error messages.

core/src/main/java/org/jruby/RubyModule.java
Autoload constants should show their assigned location as the point at which autoload was called. This was broken in the JIT because it depended on artificial Backtrace frames that JIT- compiled code does not populate.
This patch switches the logic to use a real generated backtrace frame, making it accurate in all cases.
This has the side effect of using our fully-canonicalized path from the backtrace as the file location of the constant, which may not match CRuby's uncanonicalized paths. This breaks the same CRuby test that was getting incorrect line numbers before:
1) Failure:
TestAutoload#test_source_location [/Users/headius/work/jruby/test/mri/ruby/test_autoload.rb:440]: <"/var/folders/h_/tmq357111c18sxbwlyq34mh80000gn/T/autoload20230302-39483-kwznu0/test-Bug16764.rb"> expected but …
=> Use real stack trace for autoload const location

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/exceptions/RaiseException.java, core/src/main/java/org/jruby/ext/tracepoint/TracePoint.java, core/src/main/java/org/jruby/internal/runtime/RubyRunnable.java, core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/TraceInstr.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/indy/CallTraceSite.java, core/src/main/java/org/jruby/runtime/Block.java, core/src/main/java/org/jruby/runtime/RubyEvent.java, core/src/main/java/org/jruby/runtime/ThreadContext.java, core/src/main/java/org/jruby/runtime/TraceEventManager.java, core/src/test/java/org/jruby/runtime/EventHookTest.java
This PR is an attempt to make more of the trace events (for TracePoint and set_trace_func) always-on, without introducing significant overhead if they are not active (i.e. no enabled tracepoint or trace func).
=> Always on traces

spec/tags/ruby/library/etc/getgrgid_tags.txt, spec/tags/ruby/library/etc/getgrnam_tags.txt, spec/tags/ruby/library/etc/getlogin_tags.txt, spec/tags/ruby/library/etc/getpwuid_tags.txt, spec/tags/ruby/library/etc/group_tags.txt
These all work now and one for windows was removed at some point (still a spec for non-windows though).
=> passing specs

.github/workflows/ci.yml, core/src/main/java/org/jruby/internal/runtime/methods/HandleMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/InvokeDynamicMethodFactory.java, core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java, core/src/main/java/org/jruby/ir/targets/indy/InvokeSite.java
This PR will try moving a few CI test suites around, adding invokedynamic to some of them to increase coverage without adding more time.
=> Add more testing for invokedynamic modes

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyException.java, core/src/main/java/org/jruby/RubyProcess.java, core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/RubySystemCallError.java, core/src/main/java/org/jruby/runtime/builtin/IRubyObject.java, core/src/main/java/org/jruby/runtime/marshal/MarshalStream.java, spec/ruby/core/marshal/dump_spec.rb
This fixes #7734 by not confusing the finalizer with marshalable state.
=> Don't try to marshal non-serializable variables

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyEnumerable.java, core/src/main/java/org/jruby/RubyGlobal.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/common/IRubyWarnings.java, core/src/main/java/org/jruby/common/RubyWarnings.java, core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java, core/src/main/java/org/jruby/parser/RubyParserBase.java, core/src/main/java/org/jruby/parser/ScopedParserState.java, core/src/main/java/org/jruby/util/StringSupport.java, test/jruby/test_kernel.rb
`runtime.setWarningsEnabled()` in it's current form is actually useless given typical Ruby apps usage of `Kernel.silence_warnings` and `$VERBOSE = ...`. so I tried to re-invent the idea to actually make it useful: 
setting `runtime.setWarningsEnabled(false)` would act as a kill switch (typically in a production env) to avoid nasty surprises esp. with embedded JRuby scenarios - regardless of gems fiddling with `$VERBOSE` warnings end up disabled.
second I reviewed warning calls to use `warning` method, have an ID and report proper line number (some were of due the +1/-1 going on) by moving the line adjustment logic to the "source". also,  `RubyWarnings` got refactored so that the warning/warn calls delegate to pretty much one method as I was thinking of adding a `getWarningFilter` on the …
=> [feat] make Ruby#setWarningsEnabled actually useful

core/src/main/java/org/jruby/ext/ripper/RubyLexer.java, core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
base error is longer $_ddddddd variables was not doing set_yylval_name(). I aligned both lexers to have same code.
Fixes #7743.
=> Fix #7743. NPE during parsing the rspec documentation

core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java, spec/tags/ruby/library/bigdecimal/sub_tags.txt
* spec/ruby/library/bigdecimal/sub_spec.rb
=> Fix BigDecimal#sub with Object and significant digits

core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java, spec/tags/ruby/library/bigdecimal/constants_tags.txt
* spec/ruby/library/bigdecimal/constants_spec.rb
=> Fix rounding mode constants of BigDecimal to use the same mri's values

core/src/main/ruby/jruby/bigdecimal.rb, test/mri/excludes/TestBigDecimal.rb
* test_BigMath_exp_under_gc_stress in test/mri/bigdecimal/test_bigdecimal.rb
* test_BigMath_log_under_gc_stress in test/mri/bigdecimal/test_bigdecimal.rb
=> Fix BigMath#exp and #log error message for edge cases

core/src/main/java/org/jruby/util/RegexpSupport.java, spec/ruby/core/regexp/shared/new.rb
Test case is: ```Regexp.new(%q{\§})``` (spec will be coming as separate commit).  Problem was we were missing mbc logic in backslash processing.  It would advance one too many times and then only see half of the mbc.
I should have put this against 9.3.x as well but I will cherry-pick it back.
=> Fixes #7769. regexp with / before mbc should work.

core/src/main/java/org/jruby/ext/ripper/RipperParser.java, core/src/main/java/org/jruby/parser/RubyParser.java, core/src/main/java/org/jruby/parser/RubyParser.y
Fixes #7774.  We were calling var_field for opt params and opt block params when we shouldn't have been.  Simple fix.
=> Fixes #7774. ripper presents an extra on_var_field for opt params

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
Related to https://github.com/ruby/ruby/pull/7758
Stops `defined?(super)` on `BasicObject` from causing a NullPointerException and instead makes it return `nil` like expected
```rb
class BasicObject
def nullPtr
defined?(super)
end
end
nullPtr
```
=> Fix defined?(super) on BasicObject from causing NullPointerException

pom.rb, pom.xml
there were some failures due missing checksum from plugin:
```
Warning:  Could not validate integrity of download from
https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-logger-api/3.0.0-M5/surefire-logger-api-3.0.0-M5.pom
org.eclipse.aether.transfer.ChecksumFailureException: Checksum
validation failed, no checksums available
```
=> [build] update maven surefire plugin

core/src/main/java/org/jruby/util/cli/OutputStrings.java
This option was removed a long time ago.  Fixes #7790 .
=> Remove obsolete command line option `-T[level]`

lib/pom.rb, lib/pom.xml
time: https://www.ruby-lang.org/en/news/2023/03/30/redos-in-time-cve-2023-28756/
uri: https://www.ruby-lang.org/en/news/2023/03/28/redos-in-uri-cve-2023-28755/
=> Update time and uri for recent ReDoS issues

lib/pom.rb
M1 binaries weren't actually arm. Fixes #7793
=> Update Subspawn to fix #7793

lib/pom.rb, lib/pom.xml
This brings us current on the time gem by using the recently- created stub gem for the date library.
=> Update time to 0.2.2 and use date stub gem 3.3.3

core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java
This PR is for optimizations for calling Java methods from Ruby.
=> Java call optimizations

core/pom.rb, core/pom.xml
We still use an internal class, StackWalker8, which I exposed in backport9 1.13. This allows javadoc under Java 11 to generate successfully.
There's still more work to fully modularize.
Fixes the last part of #6607.
=> Update to backport9 1.13 for module javadoc fix

core/pom.rb, core/pom.xml, pom.rb, pom.xml
believe we should also release and update `tzdata.version` from **2019c** to **2023cgtz** (used in joda-time 2.12.2).
I wonder if the `org.jruby:joda-timezones` matters thought given the current **2019c** version was not aligned with `joda-time` 2.10.10 which is meant to be using (packages inside the joda-time.jar) **2021a**
=> [deps] update joda-time to latest 2.12.5

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/anno/AnnotationBinder.java, core/src/main/java/org/jruby/anno/InvokerGenerator.java
This PR contains 2 commits which should make the generated .class files more deterministic.
Essentially the problem is `Class#getDeclaredMethods` returns an undefined order, so even when a simple patch is applied to a stable version one ends up with a ton of .class files (mostly the "INVOKER" ones) *modified* in the resulting artifact (jruby-base.jar).
---
sample diff after re-compiling and decompiling `org/jruby/RubyArray\$INVOKER\$i\$all_p.class` using `javap` (nothing was changed against stable 9.3.10.0 the difference is likely just a different Java or OS version):
```diff
16,17c16,17
<   public org.jruby.runtime.builtin.IRubyObject call(org.jruby.runtime.ThreadContext, org.jruby.runtime.builtin.IRubyObject, org.jruby.RubyModule, java.lang.String, org.jruby.runtime.builtin.IRubyObject, …
```
=> [build] make generated .class files deterministic

core/pom.rb, core/pom.xml, core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipReader.java, core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipWriter.java
This fixes the bogus mtime on gzip readers by switching to the JRuby version of jzlib and populating mtime after the header has parsed.
This fixes jruby/jruby#7746 and rack/rack#2027.
=> Update jzlib and fix mtime

core/src/main/java/org/jruby/ir/Operation.java
Problem was receive_keywords has a side-effect of resetting callInfo but dead code elimination thought it could be removed. Once removed it allowed CALL_KEYWORDS_EMPTY to persist from parent method to next call.
=> Fixes #7804.  Incorrect ArgumentError: wrong number of arguments

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/util/io/SelectorPool.java, lib/pom.xml
This moves the creation of a new selector outside of the sync section, to avoid blocking threads that are just trying to put a selector back when we are waiting to open a new one.
This whole class could use some improvement using nonblocking collections, but this should help reduce contention for now.
Edit: This has expanded to remove additional areas of contention.
See jruby/jruby#7805.
=> Reduce contention in heavy IO operations

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/runtime/ThreadContext.java
No frame has been pushed yet for the script to run in, so we have no frame self to acquire. Use top self and let the script push a frame as needed.
Fixes #7820.
This may need to be backported to 9.3.
=> Use top self for evalScriptlet, since no frame yet

core/pom.xml, default.build.properties, lib/pom.rb, lib/pom.xml
Updating all default and bundled gems to meet or exceed CRuby 3.1.4 and bumping the reported compat version.
=> Update stdlib gems and compat to 3.1.4

lib/pom.rb, lib/pom.xml
IRB 1.7.0 brought in a bunch of new tests, some of which seem to cause our MRI stdlib suite to terminate early. Rather than wrestle with this right before release, we are going back to 1.4.2 for now and will do a proper upgrade for 9.4.4.
=> Return to IRB 1.4.2 for now

core/src/main/java/org/jruby/ir/IRBuilder.java, spec/ruby/language/case_spec.rb
The when logic was seeing a BlockNode but thinking it was a ListNode of when conditions.  Minimizing fix because I will cherry-pick this back to 9.3 and onto YARP branch which has a large number of IR builder changes stacked up.
=> Fixes #7848.  Wrong interpretation of multi-expr when clause

core/src/main/java/org/jruby/RubyIO.java
native open was not aware there was kwargs to pass on.  Our current kwargs impl leaves something to be desired here.  Next impl will remove the need to marking native methods as keywords.
=> Fixes #7847. File subclass passes args from open to new wrong

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/RubyNumeric.java
RubyHash had no signature for options but it was bound and it is not a bound method in MRI so I removed the annotation and added a java override for options variant of clone.
RubyNumeric had its own impl but RubyBasicObject implements that logic already for multiple immutable types so I just changed it to call that impl with a comment why the binding is there.
=> Fix #7839. `clone': wrong number of arguments

core/src/main/java/org/jruby/ast/CallNode.java, core/src/main/java/org/jruby/ast/CanRaise.java, core/src/main/java/org/jruby/ast/FCallNode.java, core/src/main/java/org/jruby/ast/VCallNode.java, core/src/main/java/org/jruby/ir/IRBuilder.java
This does not fix where the constant is highlighted for hash (see: https://bugs.ruby-lang.org/issues/16819 for more info) but it does fix the odd string of 0s in the reported case.
An older fix was marking all calls as newline nodes.  newline nodes up to this point was the only reason emit a line instruction.  I reverted this fix and instead marked call* nodes as CanRaise.  Then in IRBuilder I have a secondary field to track whether we have encountered something which can raise but is not a newline.  If so it will emit a linenum instr but will not mark it as needing line coverage.
=> Fixes #7859. Coverage returns incorrect info for hash literal constants

bin/jruby.sh
Forgot to PR some improvements to the launcher! Should be pretty self-explanatory and I made some notes going back over them:
Finally got rid of the realpath function from Stackoverflow and replaced it with some more self-explanatory functions. Should be faster now too since it runs as few external commands as possible. Hopefully it doesn't break things, if you want to test the readlink logic you can comment out lines 290-292 or remove realpath from your PATH.
Also I added a couple lines for compatibility with ksh93! I think every Bourne shell that's installable on modern operating systems can launch jruby now.
=> Launcher tweaks

core/src/main/java/org/jruby/RubyKernel.java
Ruby Issue: https://bugs.ruby-lang.org/issues/16131
JRuby Issue: https://github.com/jruby/jruby/issues/7517
=> Ruby 3.2 - Remove deprecated methods: trust/taint and friends

core/src/main/java/org/jruby/RubyException.java
RubyException ends up getting called and it is used by RaiseException (which is a RuntimeException in Java).  It seems like Ruby itself much less Java should have cause of an exception be itself.  This should also prevent the Java exception from having the same condition?
This should fix #7861 but we shall see if anything complains or not in the expanded CI run.
=> Make sure Ruby exception does not provide itself as cause.

lib/pom.rb, lib/pom.xml, test/check_versions.sh
See https://github.com/jruby/jruby-openssl/releases/tag/v0.14.2
Not sure from @kares if this is "ready", but there is some CVE noise (that doesn't affect JRuby) mentioned at https://github.com/jruby/jruby-openssl/pull/278 within the bundled bouncy castle version which would be nice to get rid of on the next JRuby `9.4.x` release.
=> [deps] update jruby-openssl to 0.14.2

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/CompiledIRNoProtocolMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java, core/src/main/java/org/jruby/ir/IRMethod.java, core/src/main/java/org/jruby/ir/interpreter/ExitableInterpreterContext.java, core/src/main/java/org/jruby/ir/interpreter/InterpreterContext.java, core/src/main/java/org/jruby/java/proxies/ConcreteJavaProxy.java
Since JRuby 9.3 Ruby sub-classes of Java classes are backed with a generated Java class,
the interpreter context for the constructor was always rebuild from scratch on every IR method call -> effectively looping through method's instructions.
---
**NOTE**: while this improves numbers by 5x it's still 4x slower than JRuby 9.2 (should probably implement a way of JIT-ing and avoid method lookup), the script from: https://github.com/jruby/jruby/issues/7763 ends up with the following numbers:
>```
> $ jruby slow_java_super.rb 
> jruby 9.2.20.0 (2.5.8) 2021-11-02 1a3255440b OpenJDK 64-Bit Server VM 11.0.14.1+1 on 11.0.14.1+1 +jit [linux-x86_64]
> 
> 1 RubyList.new(...) elapsed real-time: 3.4137503600068158
> 2 RubyList.new elapsed real-time: 2.6153695250031888
> ```
> ```
> $ jruby …
```
=> [fix] avoid walking constructor instructions on every call

.github/workflows/ci.yml, spec/jruby.mspec
Cleaning up issues on master:
* New rubyspecs check StringIO::VERSION which our stringio does not define. See ruby/stringio#57.
* sequel introduced a feature that depends on newer PG, so recommendation is for us to test against latest PG.
=> Greening master

lib/pom.rb, lib/pom.xml, spec/jruby.mspec, spec/tags/ruby/library/stringio/each_line_tags.txt, spec/tags/ruby/library/stringio/each_tags.txt
This fixes the missing `StringIO::VERSION` and tags two new failures due to updated behavior (to be fixed by https://github.com/ruby/stringio/pull/61).
=> Update StringIO and reenable specs

.github/workflows/ci.yml
This moves the logic of building JRuby and caching the build artifacts out to a reusable action.
The action lives at https://github.com/jruby/jruby-ci-build and performs the following actions in sequence:
* Checks out JRuby on the current branch
* Sets up Zulu Java 8
* Attempts to download a cached build of JRuby
* If the cache was unavailable, build and upload JRuby
All of the major jobs use this action to prep the JRuby build they test against. While the first several jobs (up to whatever concurrency we get) will all end up building JRuby themselves, once a cache has been uploaded no future jobs will need to build and bootstrap JRuby.
The primary goal here is to reduce duplication in the main build, but this also enhances the build by moving the bootstrap cache step into each job, so …
=> Reuse prebuild workflow

core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java, test/mri/excludes/TestBigDecimal.rb
* test_power_of_three in test/mri/bigdecimal/test_bigdecimal.rb
=> Fix BigDecimal#eql? when an argument is Rational

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/parser/Parser.java, core/src/main/java/org/jruby/parser/ParserConfiguration.java, core/src/main/java/org/jruby/parser/RubyParser.java, core/src/main/java/org/jruby/parser/RubyParser.y, core/src/main/java/org/jruby/parser/RubyParserBase.java
Top-level scopes for ordinary parses will no right-size dynscope vs always using manyvarsdynamicscope.  This work also made me realize first time simple non-binding evals can do this as well (first time binding also but it is more complicated).
=> Fix dynscopes

core/src/main/java/org/jruby/ast/HashNode.java, core/src/main/java/org/jruby/parser/RubyParserBase.java
This PR is a follow-up on https://github.com/jruby/jruby/pull/7623, namely the detected collection usage issue: https://github.com/jruby/jruby/commit/0224d5d2991abf6fd2492ae9e1bbf52a30bb181c
While fixing the collection removal (type) issue I discovered that the actual AST node removal on duplicate hash keys is problematic (there's a need to evaluate the RHS even despite it's end result being thrown away), so the actual removal is still NOT happening.
**The PR still fixes the duplicate line reporting - will now point to the correct (duplicate) location as does MRI! **
=> [fix] duplicate hash key literal removal

lib/ruby/stdlib/rbconfig/sizeof.rb, test/mri/excludes/TestBigDecimal.rb
This PR adds these values to run BigDecimal test.
The following tests will pass
* test_BigDecimal_with_integer in test/mri/bigdecimal/test_bigdecimal.rb
* test_llong_min_gh_200 in test/mri/bigdecimal/test_bigdecimal.rb
=> Add INT64_MAX, INT64_MIN, UINT64_MAX, LLONG_MAX, LLONG_MIN and ULLONG_MAX to RbConfig::LIMITS

core/pom.rb, core/pom.xml, core/src/main/java/org/jruby/ext/strscan/RubyStringScanner.java
* joni updated to 2.2.1 with the new Region factory and shapes.
* strscan updated to a modified version of the gem 3.0.6 that can compile against joni 2.2 (which hides Region fields).
Note that these changes mean any users depending on access to joni Region fields, or its constructor, will see some breakage, but these changes have been in the wild in 9.4.x for sevreal months without issues.
Relates to #7884
=> Update joni and strscan for recent fixes

core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java, spec/tags/ruby/library/bigdecimal/div_tags.txt
* spec/ruby/library/bigdecimal/div_spec.rb
=> Fix BigDecimal#div when an argument is object

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/GetFieldInstr.java, core/src/main/java/org/jruby/ir/instructions/RuntimeHelperCall.java, core/src/main/java/org/jruby/ir/interpreter/ExitableInterpreterEngine.java, core/src/main/java/org/jruby/ir/interpreter/StartupInterpreterEngine.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/InstanceVariableCompiler.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/indy/IndyInstanceVariableCompiler.java, core/src/main/java/org/jruby/ir/targets/simple/NormalInstanceVariableCompiler.java, core/src/main/java/org/jruby/runtime/Helpers.java, core/src/main/java/org/jruby/runtime/invokedynamic/VariableSite.java, core/src/main/java/org/jruby/runtime/ivars/FieldVariableAccessor.java, core/src/main/java/org/jruby/runtime/ivars/VariableAccessor.java
Optimize both @A ||= 1 and defined?(@A).
Changes:
1. @A ||= 1 will not use defined? at all but use get_field.  get_field
uses a cached VariableAccessor so repeated calls will get the value
much faster.
Secondly by not using defined? it is able to go from 2 branches to
1 branch.  This reduces resulting codesize a lot.
2. defined?(@A) is now written in terms of get_field.  get_field itself
added an option rawValue which will return %undefined instead of nil
when @A is not present.  This allows us to rewrite defined?(@) in terms
of an if/else branch (in IR) instead of the baked in ruby runtime helper
instr.
The general notion behind both is to use instrs which has a variable
accessor cache.
An interesting wrinkle is that indy on failed defined? is only a tiny
bit faster than it was.  I think …
=> Optimize @a ||= x and defined?(@a)

core/src/main/java/org/jruby/RubyHash.java
A change introduced in 60ae8bae9091ffdfe90ca9cb61ed0047d50653cd caused the once-transient buffer to be shared during recursive hash calculation, corrupting the results. This led to #7866.
The PR here fixes that by avoiding the shared buffer until all recursive hash calls have completed.
An additional small fix avoids allocating the long[] carrier object for hashes of size zero. Caching this in a thread-local would probably be worthwhile as well, but I was unsure how to do it safely.
=> Protect cached threadlocal in recursive hash

core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/BuildCompoundStringInstr.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
This avoids adding anything to the ivar table and short-circuits the frozen check. We may want to consider doing this for non-debug frozen literal strings as well.
=> Move frozen string debug fields into subclass

.github/workflows/ci.yml, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java, spec/java_integration/fixtures/CoreTypeMethods.java, spec/java_integration/methods/dispatch_spec.rb, spec/java_integration/reify/become_java_spec.rb
Several fixes here:
* Arguments passed to either instance or static method must match arity of target Java method. Not sure how the -1 got in here but it may have been thinking in terms of a MethodType, which will have the self object as the first argument for instance methods.
* This got past testing because of insufficient jitted code being tested with indy, so I enabled forced JIT and indy for more test suites and discovered additional issues.
* Cleaned up caching of the Ruby to Java indy handle so that it would not be reused for incompatible shapes of call sites.
* Removed caching of call site-specific adaptations on the handle. They must be reapplied for each form of call site that happens across the cached handle.
* Commented out a test that I don't believe should ever have passed, …
=> Multiple fixes for forced JIT and indy-based Java dispatch

core/src/main/java/org/jruby/util/OneShotClassLoader.java
This was lost while fixing class-resolution issues during JRuby 9.3 development. Without this, security checks that walk up the stack may hit jitted code that has an improper protection domain, different from JRuby or the system classloader, causing the check to fail.
See e352ba8265dd773fd341e8d6bbd0583540b119bd
Fixes #7216
=> Restore default protection domain for OneShotCL

core/src/main/java/org/jruby/Ruby.java
- Hopefully fixes #7916 
I'm not quite sure the appropriate sizing of the Maps here, but tried to follow existing conventions elsewhere and be conscious of the additional overhead of `ConcurrentHashMap`s for the nested Maps. But this may also be premature optimization in some areas, so will take maintainer guidance.
- Kept the second level maps initial size small by default (maybe too small?)
- Used 0.9 load factors similar to those in `RubyModule`
- We shouldn't need high concurrency here, so set to 2. Even 1 might be fine?
I also can't find an appropriate place to write particular tests here, so any pointers useful.
Needs to be ported forward to 9.4/master if suitable.
=> Make bound method management threadsafe

core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyString.java
Crux of problem was strscan#concat was calling JRuby String append function in Java and that was a pre-m17n version of append which was not encoding aware OR coderange aware.  As a result, the string thought it was 7bit ASCII (narrator: it was not) and this made joni go off the rails.
The fix I used was to move append19 impl into append and deprecate append19.  This version does all the right things.  In looking at callers of append there were not many consumers.  ARGF#read was also broken in the same way since we would be appending what- ever file in its encoding onto the existing string.
=> Fixes #7649. Infinite loop in StringScanner regex

core/src/main/java/org/jruby/RubyString.java, spec/ruby/core/string/uplus_spec.rb
It wasn't reporting itself as frozen, leading to #7924.
Fixes #7924 and includes a spec.
=> More frozen string tweaks

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
Problem was that we were seeing an empty kwarg marked from ruby2_keyword_hash and omitting it because it was a kwarg.  The logic doing this was for a failing test in MRI test suite that was passing that empty kwarg using a splat.  The fix was to only pass this along if it is a non-splat caller.
=> Fixes #7918.  Error with single splat method with keyword arguments

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyThread.java, core/src/main/java/org/jruby/runtime/load/LoadService.java, spec/tags/ruby/core/thread/backtrace/location/absolute_path_tags.txt
This fix allows __dir__ and Thread::Backtrace::Location and require_relative to use the proper path for a main script specified without a full path.
Fixes #7394
=> Store absolute path of main at load time

core/src/main/java/org/jruby/util/ConvertBytes.java, spec/ruby/core/string/to_i_spec.rb
Logic here is intended to bail out when the leading digit is `0` and there are two or more consecutive underscores, but it appears it was ported incorrectly (`us += 0` 🤨) resulting in it bailing out after ANY second underscore.
Fixes #7749.
=> Fix String#to_i with leading zero and underscores

.github/workflows/ci.yml, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/javasupport/JavaPackage.java, core/src/main/java/org/jruby/javasupport/JavaUtil.java, core/src/main/java/org/jruby/javasupport/proxy/JavaProxyClass.java, test/jruby/test_tempfile_cleanup.rb, test/pom.rb
The PR adds CI testing with Java 21 (release), also added some variations on the Java flavor used (with temurin).
The embedded (jruby-complete) test targets now also work on Java > 8 and are actively tested against later versions.
A few minor (Java) deprecations are addressed, most of the remaining ones are around SecurityManager and the related access exception being used... which are likely going to be tricky to get rid of.
=> More testing with Java 21

lib/pom.rb
Follow-up to #7941, looks like there's a minor regression in 1.16.1 (https://github.com/ffi/ffi/issues/1050)
=> Update ffi to 1.16.2

core/src/main/java/org/jruby/ir/IRScope.java, core/src/main/java/org/jruby/ir/operands/LocalVariable.java, test/jruby/compiler/test_jrubyc.rb
AOT code encodes IR into the .class file and it was not correctly adjusting local variable operands to account for `for` loops.  The code before the fix would count all possible `for` loops and not just the `for` loops between the current accessing scope and the destination scope.
Added a single test which has a complicated set of variable accesses which should exercise the depth adjustment which was fixed in this commit.
=> Fix #7815. NullPointerException for compiled code with for loop

core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java
This field access appears to trigger a bug in Java 8 and 11 (at least) leading to linkage errors and classes leaking across classloaders when a method handle is resolved at static initialization time.
See https://github.com/jruby/jruby/issues/7911
The change here provides a local MethodHandles.Lookup object rather than using a publicLookup() to acquire the field handle. This may work around whatever the JDK bug was.
Fixes #7911
=> Use a lookup() for field access in static constant

core/src/main/java/org/jruby/util/Dir.java
backport https://github.com/jruby/jruby/issues/7942 to 9.3.x
=> backport: fnmatch not matching glob syntax

core/src/main/java/org/jruby/Main.java, core/src/main/java/org/jruby/util/cli/OutputStrings.java
Fixes #7864.
Output before (`jruby --help | less`):
```
ESC[1mESC[1mUsage:ESC[0m jruby [switches] [--] [programfile] [arguments]ESC[0m
ESC[1m-0[octal]ESC[0m                                           specify record separator (\0, if no argument) 
ESC[1m-aESC[0m                                                  autosplit mode with -n or -p (splits $_ into $F) 
ESC[1m-cESC[0m                                                  check syntax only 
ESC[1m-CdirectoryESC[0m                                         cd to directory, before executing your script 
...
```
After:
```
Usage: jruby [switches] [--] [programfile] [arguments]
-0[octal]                                           specify record separator (\0, if no argument) 
-a                                                  autosplit mode with …
```
=> Avoid ANSI formatting when not on a TTY

core/src/main/java/org/jruby/util/StringSupport.java
This matches the CRuby code at this point, but it's not clear to me how or why it was set up to use the upper case table many years ago.
Fixes #7946
=> Convert to lower, not upper, for casecmp

.github/workflows/ci.yml
Was disabled due to an unusual failure (see jruby/jruby#7470) but appears to pass with more recent J9 JDKs
=> Re-enable J9 test in CI

lib/pom.rb, lib/pom.xml
Another follow-up to #7945 - being conservative in case these bugfixes affect JRuby since there has been a feature bump. (https://github.com/ffi/ffi/blob/master/CHANGELOG.md#1163--2023-10-04 and https://github.com/ffi/ffi/issues/1056)
=> Update ffi to 1.16.3

core/src/main/java/org/jruby/RubyThread.java, core/src/main/java/org/jruby/runtime/Helpers.java, core/src/main/java/org/jruby/util/io/OpenFile.java
The JRuby IO subsystem simulates a POSIX environment by capturing Java exceptions and translating them to their equivalent errno values. When a read produces an error, we return -1 and set the local shim's errno. This can then be used by POSIX-like consumers of the API to process the error without exception-handling.
However in the case of IO read operations, we were not appropriately checking the errno result for a failed (i.e. -1) read. Instead we assumed it was always an EAGAIN-like result and proceeded to select for read on the socket. Under normal circumstances, like the socket being fully closed on both ends, that select would raise an error anyway so no errors were lost.
In the example from #7961 (and likely the case in #6346), only one side of the socket was closed using …
=> Propagate read errors in IO backend

core/pom.rb, core/pom.xml
On Debian, possibly because of some OpenJDK hardening, TestProcessSpawn consistently fails:
```
[INFO] Running org.jruby.test.TestProcessSpawn
2023-10-24T00:19:47.130Z [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.889 s <<< FAILURE! - in org.jruby.test.TestProcessSpawn
[ERROR] testSpawnAndDetach(org.jruby.test.TestProcessSpawn)  Time elapsed: 1.867 s  <<< ERROR!
org.jruby.exceptions.SystemCallError: (ENOENT) No such file or directory - echo
```
Adding --add-opens to the java options envvar fixes the problem.
=> Fix ENOENT with TestProcessSpawn on Debian

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/ProcessModuleBodyInstr.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
I think since Ruby 3 esoteric forms where an SClass can get a block body to yield is no longer possible.  This I think has always been try for Class and Module bodies (syntactically) so I am removing emitting Load{Frame,Implicit}ClosureInstr for those scope types.
=> Less Load{Frame,Implicit}ClosureInstr

core/src/main/java/org/jruby/RubyArray.java
The logic here had diverged somewhat from CRuby's logic, and did not reacquire the array's begin or length as in CRuby. This led to bad length calculation when there were additional mutations during the select!/reject! loop.
Fixes #7976
=> Fix length handling in select!/reject! ensure

core/src/main/java/org/jruby/RubyTime.java
The intent here was to pass in what might be kwargs if the keyword flag was set, indicating that kwargs were being passed in. This assumption seems ok so I'm not sure why it doesn't hold. In any case, the cast here is unnecessary and the IRubyObject form will return null for non-RubyHashes.
The code that triggered this does deal directly with kwargs, but as a kwrest, forwarding it through a block:
https://github.com/rails/rails/blob/v7.1.1/activesupport/lib/active_support/testing/time_helpers.rb#L176-L183
This could indicate JRuby failing to pass along a keyword flag when forwarding kwrest.
The additional changes here are:
* Fall back on non-kwargs behavior if last arg turns out not to be a hash.
* Remove a redundant reset of the `callInfo` that governs keyword- passing.
Fixes #7982
=> Remove unnecessary cast of kwargs

core/src/main/java/org/jruby/util/io/FilenoUtil.java
My goal with this warning was to avoid bug reports about native
process functionality not working well when running without the
module flags we need to dig up native file descriptors from Java
channels. Since I added this, however, many things have changed:
* Native process IO does not go through Java channels anymore; it
instead uses real native IO all the way through.
* File IO now also usually goes through JNR using a native file
descriptor.
* The fileno extraction is now primarily used to provide a fileno
for RubyIO objects, but most Ruby code will not need the real
fileno.
* Module flags are frequently difficult to inject into a jar-based
usage of JRuby, so these flags may not be helpful anyway.
I believe a warning about degraded functionality is important, but
it should be at …
=> Hide FilenoUtil warning behind native.verbose property

core/src/main/java/org/jruby/java/proxies/ConcreteJavaProxy.java, core/src/test/java/org/jruby/javasupport/TestJava.java
introduced in 9.4.4.0 while doing a variant of: https://github.com/jruby/jruby/commit/bd9d40c02a1a693b46aa14e5feac7d64b5442246#diff-d269af154b613900dfe27e6c544a8c6748bf52af91e74395df49c70764db1478R1841
managed to miss copy-ing the loop last step (and I was pretty confident that is a tested code path)
=> [fix] infinite loop calling Java super from Ruby

core/src/main/java/org/jruby/java/proxies/ConcreteJavaProxy.java, core/src/test/java/org/jruby/javasupport/TestJava.java
back-port of https://github.com/jruby/jruby/pull/7990 for the 9.3 branch
=> [fix] infinite loop calling Java super from Ruby (#7990)

core/src/main/java/org/jruby/runtime/ivars/VariableTableManager.java, spec/tags/ruby/core/kernel/instance_variables_tags.txt
I could not find anywhere this is specified, except for:
* A very recent test in CRuby's test/ruby/test_shape.rb that confirms a degraded "complex" shape using CRuby's "st table" hashtable will continue to be returned in insertion order. This implies that insertion order is expected.
* A rubyspec added in 2021 in instance_variable_spec.rb that confirms instance variables are returned in insertion order. No links to issues or discussions is provided.
Since this is a simple enough change, we'll go ahead with it, but I don't know that it has ever been formally specified (and indeed I looked through other tests of other types of variables and see that there are commits to .sort them before inspection in tests.)
Fixes #7988
=> Preserve insertion order for ivars

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyIOError.java, core/src/main/java/org/jruby/exceptions/RaiseException.java, core/src/main/java/org/jruby/util/SunSignalFacade.java, core/src/main/java/org/jruby/util/io/OpenFile.java, rakelib/rubyspec.rake, test/jruby/test_io.rb, test/jruby/test_tempfile_cleanup.rb, test/tool/lib/webrick/server.rb
This will contain small fixes to get our CI more reliable, by fixing the causes of intermittent failures.
* `IO#read raises IOError when stream is closed by another thread` intermittent due to different ways of handling a nulled-out "fd". All cases where "fd" is null when it was previously confirmed to be non-null should indicate parallel close occurred. (Better state management here would be helpful, to ensure we **know** it only could have been closed in parallel.
=> Fix intermittent fails in CI

core/src/main/java/org/jruby/internal/runtime/GlobalVariable.java, core/src/main/java/org/jruby/internal/runtime/GlobalVariables.java, core/src/main/java/org/jruby/ir/targets/indy/CheckpointSite.java, core/src/main/java/org/jruby/ir/targets/indy/ConstantLookupSite.java, core/src/main/java/org/jruby/runtime/invokedynamic/GlobalSite.java, core/src/main/java/org/jruby/runtime/invokedynamic/MathLinker.java, core/src/main/java/org/jruby/util/cli/Options.java
A few places where we access and cache global variables were found to have races while investigating some `Process.kill` specs hanging only in JIT mode. I found the following issues:
* GlobalVariables.getVariable can race with a parallel global variable set, ending up with two different GlobalVariable accessor objects getting created. Caching the wrong one will result in a stale value cached permanently.
* The indy logic for caching global variable values had a race in acquiring the value and the SwitchPoint that guards it. Because they were acquired in the wrong order (value first) there's a chance that an old value might be guarded by a newer SwitchPoint and never get invalidated.
With these fixes made the `Process#kill` specs in question always run to completion, and I have re-enabled …
=> Fix issues in global variable thread-safety

core/src/main/java/org/jruby/AbstractRubyMethod.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyMethod.java, core/src/main/java/org/jruby/runtime/ThreadContext.java, core/src/main/java/org/jruby/runtime/backtrace/BacktraceData.java, core/src/main/java/org/jruby/runtime/backtrace/TraceType.java, core/src/main/ruby/jruby/kernel/kernel.rb
This allows tools to omit any of our internal Ruby-based kernel sources when processing backtraces and source_locations. The filtering here is only done in source_location and backtrace generation currently, with some extra logic during backtrace mining to skip internal frames for e.g. Kernel#warn.
I only did this filtering at the highest levels, when the filename is actually about to be used and returned to a Ruby consumer, to avoid any internal usage of these filenames breaking due to the new prefix.
Fixes #6430
=> Prepend internal marker to internal sources

core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyDir.java, core/src/main/java/org/jruby/java/invokers/ConstructorInvoker.java, core/src/main/java/org/jruby/java/invokers/RubyToJavaInvoker.java, core/src/main/java/org/jruby/java/proxies/JavaProxy.java, spec/java_integration/fixtures/AnArrayList.java, spec/java_integration/methods/java_alias_spec.rb
the use-case, as demonstrated in the spec, is to be able to bypass constructor lookup with:
`java_alias :_java_ctor_alias, :'<init>'` the reasoning is similar to using [`java_alias` with overloads](https://github.com/jruby/jruby/wiki/ImprovingJavaIntegrationPerformance)
---
also, there's a bunch of refactoring/cleanup commits:  
- avoid constructor lookup when using `setClassAllocator(Class)`
- set-up Java causes for (Java) allocator failing exceptions
=> [ji] support java_alias with constructor

core/src/main/java/org/jruby/RubyBasicObject.java
The fix added is very simple.  If we have an empty hash marked as a ruby2 keyword we just remove it.  This is basically how all ruby to ruby interactions work.
=> Fixes #8010. Kernel#send + empty kwargs hash error

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/IRScope.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/runtime/Helpers.java, core/src/main/java/org/jruby/runtime/Signature.java, core/src/main/java/org/jruby/util/TypeConverter.java, spec/java_integration/methods/java_alias_spec.rb, spec/tags/ruby/language/block_tags.txt, spec/tags/ruby/language/yield_tags.txt
The issue is if we try to call to_ary during block dispatch and respond_to? does not exist on the object it should return the original object.  We were failing because we rightly called method_missing but because m_m did not handle to_ary we just raised NoMethodError and not the original object.
This also fixes improper spreading of a single value array into a proc which only has optargs.
Some very minor error handling for uncommon syntax.
=> Fixes language specs involving blocks/yield

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/CheckArityInstr.java
There is some improvement with JIT and indy but my larger goal is to speed up startup time and removing recv_keywords and short-circuiting to a simple check_arity instr has a big effect on tiny no-arg methods/blocks.
BEFORE:
```text
jruby --dev ../snippets/bench1.rb
Warming up --------------------------------------
foo2   425.349k i/100ms
foo   439.825k i/100ms
Calculating -------------------------------------
foo2      4.697M (± 1.1%) i/s -     94.002M in  20.015869s
foo      4.887M (± 0.9%) i/s -     98.081M in  20.071418s
Comparison:
foo:  4887008.2 i/s
foo2:  4697008.2 i/s - 1.04x  slower
```
AFTER:
```text
jruby --dev ../snippets/bench1.rb
Warming up --------------------------------------
foo2   427.370k i/100ms
foo   599.189k i/100ms
Calculating ------------------------------------- …
```
=> Reduce overhead of kwargs for no-arg methods and blocks

core/src/main/java/org/jruby/ir/IRBuilder.java
Remove implicit prologue state to methods/blocks if that state is unused
This is for work to speed up the startup of JRuby by reducing instrs visited in the startup interpreter.  The implicit state
at the front of methods/blocks generally gets remove as dead instrs since their variables are not used.  The startup
interpreter does not run the compiler passes which do this due to the significant time they take to analyze the code.
This PR is doing cheap existence checks which will remove a lot of these instrs during build time.
=> Remove implicit prologue state to methods/blocks if that state is unused

core/src/main/java/org/jruby/RubyFixnum.java, core/src/main/java/org/jruby/RubyInstanceConfig.java, core/src/main/java/org/jruby/compiler/impl/SkinnyMethodAdapter.java, core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/IRManager.java, core/src/main/java/org/jruby/ir/IRVisitor.java, core/src/main/java/org/jruby/ir/instructions/BIntInstr.java, core/src/main/java/org/jruby/ir/instructions/IntegerMathInstr.java, core/src/main/java/org/jruby/ir/interpreter/FullInterpreterContext.java, core/src/main/java/org/jruby/ir/operands/TemporaryIntVariable.java, core/src/main/java/org/jruby/ir/operands/TemporaryVariableType.java, core/src/main/java/org/jruby/ir/persistence/IRDumper.java, core/src/main/java/org/jruby/ir/targets/JVM.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
Mostly just missing a few operations in the JIT, but I will throw some optimization work in here too.
=> Full JIT support for pattern matching

core/src/main/java/org/jruby/Main.java, core/src/main/java/org/jruby/runtime/backtrace/TraceType.java, spec/java_integration/addons/throwable_spec.rb
In my very limited test, this should matches MRI 3.2's formatting at byte level as long as the backtrace is exactly the same. E.g. rescue then re-raise a different error creates an additional line in backtrace for MRI, but not in jruby - the output will be slightly different in such case.
Why match MRI 3.2 not 3.1? The only difference between 3.1 and 3.2 is how `order:` works. In 3.2, `order` default to `:top`, which is the same as the current jruby behavior. Therefore, matching 3.2 is actually a smaller change than matching 3.1.
=> Match `Exception#full_message` with MRI 3.2

core/src/main/java/org/jruby/internal/runtime/methods/InvocationMethodFactory.java, core/src/main/java/org/jruby/util/ClassDefiningJRubyClassLoader.java
The exception thrown here when we cannot find a class can be very expensive at boot time. For most third-party extensions, this exception will be raised twice for every bound method, due to double-checking the classloader under lock a second time. By first looking for a .class resource, we can avoid the expensive exception if it is unlikely to succeed.
=> Try to find class resource to avoid exception

core/src/main/java/org/jruby/util/Pack.java
JIT and new Prism parser were right-sizing Strings whereas the current parser will create larger than actual string length mostly. This lead to a problem where checkLimit in original unpack code would examine capacity and pass the test even though capacity is not valid data.
The solution is to raise the proper error and use actual encoding limit.  the original checkLimit error message is for STRTOUL in MRI in processing the number after the '@' and that was not what we were doing.  I am unable to get that RangeError to occur in MRI so I am not sure when it is possible?
=> Fix String#unpack from using capacity() and causing wrong error

core/src/main/java/org/jruby/PrependedModule.java, spec/ruby/core/module/prepend_spec.rb
issue #7845 "Including a module again after prepending another module to it isn't idempotent"
=> override getDelegate in PrependedModule to return origin

core/src/main/java/org/jruby/RubyMatchData.java
issue #8029 
I am unsure if my usage of keywords/checkArity/optional/checkArgumentCount is correct. I couldn't find another example exactly like this in the codebase. It seems I can still call `named_captures(:bogus)` without any complaints so perhaps someone can point me in the right direction.
=> Ruby 3.3 support: add symbolize_names kwarg to MatchData#named_captures

core/src/main/java/org/jruby/ir/IRBuilder.java, core/src/main/java/org/jruby/ir/instructions/RuntimeHelperCall.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/runtime/RubyEvent.java
Discussed in CRuby core developer meeting May 10, 2023 at RubyKaigi.
One test exists for this in the 3.3 ruby/test_settracefunc.rb and will be merged in once we update CRuby tests.
See https://bugs.ruby-lang.org/issues/19572
=> Add support for a rescue trace event

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java, spec/ruby/core/module/attr_accessor_spec.rb, spec/ruby/core/module/attr_reader_spec.rb, spec/ruby/core/module/attr_spec.rb, spec/ruby/core/module/attr_writer_spec.rb, spec/ruby/core/module/shared/attr_added.rb
See Shopify/ruby-lsp#1263 for background on this.
When defining an attribute (`attr`, `attr_reader`, `attr_writer`, `attr_accessor`) on a metaclass or singleton object, we should be calling `singleton_method_added`. Instead, we were calling `method_added`.
The caused Shopify/ruby-lsp#1263 when an `attr_reader` in a metaclass body did not consume a Sorbet `sig` set up for it.
I've also factored out two other method hook cases in case they are needed other places in the future: `method_undefined` and `method_removed`.
=> Attribute definition on singleton should call singleton_method_added

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyEnumerable.java, core/src/main/java/org/jruby/RubyGlobal.java, core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/RubyRegexp.java, core/src/main/java/org/jruby/common/RubyWarnings.java, core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java, core/src/main/java/org/jruby/parser/RubyParserBase.java, core/src/main/java/org/jruby/util/StringSupport.java
This also marks syscall as not implemented (warns of pending deletion in CRuby) and modifies all RubyWarnings.warning* forms to no-op on verbose, as they used to (unsure when this changed).
=> Update some warnings to deprecated

core/src/main/java/org/jruby/RubyModule.java
This PR adds methods to expose all the `Refinement` objects that a `Module` have (if any), and 2 aliases for a method returning the refined class of a given `Refinement` module (one is deprecated and ear-marked for removal in MRI 3.4).
=> Added Module#refinements, Refinement#target and Refinement#refined_class

lib/pom.rb, lib/pom.xml
The issue arises when the `StringScanner` string is being modified while being scanned. In such a case, that string's buffers will be improperly shared, forcing a new buffer to be created each time it is modified. Meanwhile the ever-growing buffers are held in memory by the improperly shared return values.
This was fixed by https://github.com/ruby/strscan/issues/84 and strscan is updated in this PR.
=> Update strscan to fix improper sharing

core/src/main/java/org/jruby/RubyClass.java, lib/ruby/stdlib/jruby/core_ext/class.rb
When doing a `require 'jruby/core_ext/class.rb'` the `Class#subclasses` method gets re-defined and cause a deprecation warning. Rails 7.x relies on (the Ruby 3.1 feature) `Class#subclasses` causing a lot of warning under JRuby 9.4.
The javadoc should provide an explanation (history of `Class#subclasses`), here's the demonstration of the issue:
```
bin/jruby -v -rjruby/core_ext/class -e 'puts String.subclasses'
jruby 9.4.6.0-SNAPSHOT (3.1.4) 2024-01-25 98ca4a1a53 OpenJDK 64-Bit Server VM 11.0.14.1+1 on 11.0.14.1+1 +jit [x86_64-linux]
DidYouMean::ClassNameChecker::ClassName
```
:green_circle: no warning
```
bin/jruby -v -rjruby/core_ext/class -e 'puts String.subclasses'
jruby 9.4.6.0-SNAPSHOT (3.1.4) 2024-01-25 98ca4a1a53 OpenJDK 64-Bit Server VM 11.0.14.1+1 on 11.0.14.1+1 +jit …
```
=> [fix] avoid Class#subclasses deprecation with class.rb ext

core/src/main/java/org/jruby/ext/ffi/Platform.java, core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java, core/src/main/java/org/jruby/platform/Platform.java
In #8061 we found that Gradle is opening several core JDK packages to support the needs of Groovy. Unfortunately this causes some normally-inaccessible methods to be accessible to JRuby's Java integration layer. In the case of HashSet, a package-private `map` method gets bound that conflicts with the Ruby version, leading to the bug reported in #8061.
Gradle's behavior is unsanitary, but ultimately the fix we have settled on here is to never try to set package-private methods accessible since they are truly not intended for consumption outside the package. That fixes this issue without addressing the larger problem of Gradle opening up core JDK packages.
Fixes #8061
=> Rework visibility checks for Java integration

core/src/main/java/org/jruby/ir/IRBuilder.java
Extra splat instr which did nothing
Ultimately this was an extra static helper method which would end up just doing an instanceof and a call to .nil() but a waste nonetheless.
Also it makes it so much more obvious this can be optimized more for pass through calls where there is no use of the variable being splatted.  For that work we would have to determine if putting more logic into builder even makes sense.
=> Extra splat instr which did nothing

core/src/main/java/org/jruby/RubyIO.java
These are to be used by the io-wait library, but there will be some lag before I can figure out how to make them honor these values without breaking backward compatibility with 9.4.0.0.
=> Define IO::READABLE, WRITABLE, PRIORITY for IO#wait

core/src/main/java/org/jruby/RubyFileTest.java, core/src/main/java/org/jruby/RubyKernel.java
This uses more compatible native stat logic for comparing two files, only falling back on NIO options if native logic cannot be used.
Fixes #7151
=> Flip File.identical? logic to try native first

core/src/main/java/org/jruby/javasupport/ext/Module.java, spec/java_integration/module/java_import_spec.rb
there's a bug with `java_import` in the sense that it does not set the imported class constant on the target module/class if the Java type has been imported on Object already e.g.
```ruby
java_import 'java.util.ArrayList'
module Foo
java_import 'java.util.ArrayList' # :ArrayList constant not set
end
Object.send(:remove_const, :ArrayList)
Foo::ArrayList # should still work but does raise...
```
=> [ji] fix java_import when constant exists in Object

core/src/main/java/org/jruby/RubyMatchData.java, spec/tags/ruby/core/matchdata/begin_tags.txt, spec/tags/ruby/core/matchdata/values_at_tags.txt
Re-arrange indexerror string when matching group name cannot be found
=> Re-arrange indexerror string when matching group name cannot be found

core/src/main/java/org/jruby/RubyNameError.java, spec/tags/ruby/core/exception/name_error_tags.txt, spec/tags/ruby/core/exception/no_method_error_tags.txt
NameError and NoMethodError should be dup'ing receiver
=> NameError and NoMethodError should be dup'ing receiver

lib/pom.rb, lib/pom.xml
details at: https://github.com/jruby/jruby-openssl/releases/tag/v0.14.3
but namely Rails 7.1 (default configuration) compatibility - authenticated cipher
also `OpenSSL:PKey::EC` compatibility improvement such as `dsa_verify_asn1`
=> update jruby-openssl to 0.14.3

core/src/main/java/org/jruby/RubyClass.java, spec/ruby/core/class/subclasses_spec.rb
Fixes #8121 by handling prepended subclasses the same way as included subclasses.
=> Handle prepend in subclasses

core/src/main/java/org/jruby/parser/RubyParserBase.java, spec/tags/ruby/language/hash_tags.txt, spec/tags/ruby/language/symbol_tags.txt
EncodingError should be SyntaxError for bad symbols?
=> EncodingError should be SyntaxError for bad symbols?

core/src/main/java/org/jruby/RubyKernel.java, spec/tags/ruby/core/kernel/test_tags.txt
test flags for stats need to handle file instances as well as strings
=> test flags for stats need to handle file instances as well as strings

core/src/main/java/org/jruby/util/ClasspathLauncher.java
The old mechanism (which is still in this) only works for Java 8 and earlier. It walks all ClassLoaders and will cast to a unpublished type to ask for the URL for the jar the classloader represents.  Java 9+ cannot do this.
This fix only addresses the main Java jar by asking for a Resource for our Main class then getting a URI which we can make into a valid path to our jar.
What this does not do is walk all CLs.  It instead assumes all cp passed into the original Java process will work for a nested one.  This may not work for 9+ but it is already broken if so.  Java 8 continues to work the same way it always has.
This is part of a fix for #8135
=> Redo java commandline calculation to work with newer Java's

maven/jruby-complete/pom.rb
jruby-complete.jar needs some module opens to work in Java 11+
This is another fix for #8135.  This still may not fully solve the original issue as that executes through a gradle plugin but it definitely fixes calling complete via `java -jar jruby-complete.jar`.  So there is a chance it will address the gradle plugin problem as well.
=> Add-Opens for complete -jar runs as expected in later Java's

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/ext/date/RubyDate.java
Allow extended DateTime to still be constructed using DateTime.  Fixes #8139.
=> Allow extended DateTime to still be constructed using DateTime

bench/bench_block_given.rb, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/ir/IRVisitor.java, core/src/main/java/org/jruby/ir/Operation.java, core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java, core/src/main/java/org/jruby/ir/instructions/BlockGivenCallInstr.java, core/src/main/java/org/jruby/ir/instructions/BlockGivenInstr.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/InvocationCompiler.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/indy/BlockGivenSite.java, core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java, core/src/main/java/org/jruby/ir/targets/indy/IndyInvocationCompiler.java, core/src/main/java/org/jruby/ir/targets/simple/NormalInvocationCompiler.java
This PR reworks fcalls to `block_given?` as a custom instruction based on `BlockGivenInstr` used by the lighter-weight `defined?(yield)` form.
Instead of forcing a caller frame (so that the caller's received block can be accessed downstack), the new logic checks if the target method is the core version and uses `defined?(yield)` logic in that case. When the method is not from JRuby core, then we dispatch normally... but without the caller frame requirement, since only the core `block_given?` is allowed to have that access. All other call paths leading to `block_given?` continue to use the deoptimized logic, so we are not introducing any new incompatibility.
This makes the performance of `block_given?`-calling methods equivalent to those that use `defined?(yield)` and avoids the framing …
=> Implement block_given? call as optimized instruction

core/src/main/java/org/jruby/RubyFile.java, core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/api/API.java, core/src/main/java/org/jruby/api/MRI.java, core/src/main/java/org/jruby/util/io/EncodingUtils.java, core/src/main/java/org/jruby/util/io/PopenExecutor.java
This is a proof-of-concept of a new external API that meets the following needs:
* Simple static methods easily imported and used from extension code, similar to C functions.
* JRuby and MRI-friendly names for 1:1 matching with extension code when that makes porting easier.
* Update to modern JRuby standards with ThreadContext and call site cache support.
=> Refactor external API to ease extension porting

bench/bench_frame_name_methods.rb, core/src/main/java/org/jruby/RubySymbol.java, core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRBodyMethod.java, core/src/main/java/org/jruby/ir/IRVisitor.java, core/src/main/java/org/jruby/ir/Operation.java, core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java, core/src/main/java/org/jruby/ir/instructions/DefineClassInstr.java, core/src/main/java/org/jruby/ir/instructions/DefineModuleInstr.java, core/src/main/java/org/jruby/ir/instructions/FrameNameCallInstr.java, core/src/main/java/org/jruby/ir/interpreter/ExitableInterpreterEngine.java, core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java, core/src/main/java/org/jruby/ir/interpreter/StartupInterpreterEngine.java, core/src/main/java/org/jruby/ir/persistence/IRReaderStream.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java, core/src/main/java/org/jruby/ir/targets/InvocationCompiler.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/indy/FrameNameSite.java, core/src/main/java/org/jruby/ir/targets/indy/IndyInvocationCompiler.java, core/src/main/java/org/jruby/ir/targets/simple/NormalInvocationCompiler.java
This PR optimizes the `__method__` and `__callee__` methods by doing the following:
* Introduce the FrameNameInstr instruction that performs a lightweight, frameless operation when the target `__method__` or `__callee__` is the built-in version (similar to `block_given?` in #8170).
* Introduce a new mapping from AliasMethod compound names to the pair of symbols they would produce for `__method__` and `__callee__`, avoiding extra allocation of strings while parsing that compound string.
As with #8170, if either of the target methods have been replaced by a user, we fall back to a normal invocation. If either method is called via metaprogramming paths, they will force a frame and use it as before.
A benchmark is included, and shows that both forms are now much faster (due to them no longer …
=> Optimized __method__ and __callee__

core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/ir/builder/IRBuilder.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/ValueCompiler.java, core/src/main/java/org/jruby/ir/targets/indy/IndyValueCompiler.java, core/src/main/java/org/jruby/ir/targets/indy/RangeObjectSite.java, core/src/main/java/org/jruby/ir/targets/simple/NormalValueCompiler.java
Fixnum and String ranges can be reduced in complexity by doing all of the construction in one go rather than each piece individually. A Range of fixnum..fixnum now uses indy to pass the long values to the bootstrap, avoiding bytecode to construct the fixnum objects. A Range of string..string embeds the bytelist and CR into the bootstrap parameters, for the same result. Both also have simplified forms in the non-indy JIT mode.
From ideas list in #7588.
=> Simplify fixnum and string ranges

core/src/main/java/org/jruby/RubyThread.java
Amazingly this also crashes in Ruby 3.1.  Later MRI tests exercise this method but it would appear no one ever used it or they would see it crash.
I am fixing it for 9.4 just because I don't want us to ever crash.
=> Thread#pending_interupt? crashes

bench/bench_fixnum_to_s.rb, bench/bench_instance_variable_get.rb, bench/bench_string_conversions.rb, core/src/main/java/org/jruby/ObjectFlags.java, core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyFixnum.java, core/src/main/java/org/jruby/RubyFloat.java, core/src/main/java/org/jruby/RubyInteger.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/RubySymbol.java, core/src/main/java/org/jruby/ext/date/RubyDate.java, core/src/main/java/org/jruby/runtime/backtrace/RubyStackTraceElement.java, core/src/main/java/org/jruby/util/ConvertBytes.java, core/src/main/java/org/jruby/util/StringSupport.java
This cleans up some object flags in order to start flagging fstrings as such and use that to cache any symbol they might intern.
=> A few frozen string and symbol optimizations

core/src/main/java/org/jruby/ir/instructions/PutConstInstr.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
lhs of compound const would crash if not a Module/Class `jruby -e ':not_a_module::A = :value'`
=> lhs of compound const would crash if not a Module/Class

core/src/main/java/org/jruby/ir/builder/IRBuilder.java, core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java, spec/tags/ruby/language/assignments_tags.txt
side-effects in const op element assign by exec parent of lhs twice
=> side-effects in const op element assign by exec parent of lhs twice

core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java, spec/tags/ruby/language/assignments_tags.txt, spec/tags/ruby/language/variables_tags.txt
All passing (except favoring 3.2+ semantic for the only failer) correct evaluation order
This needs a lot of cleaning yet.
=> use left to right evaluation

core/src/main/java/org/jruby/RubyInstanceConfig.java, core/src/main/java/org/jruby/ir/IRScope.java, core/src/main/java/org/jruby/ir/builder/EnsureBlockInfo.java, core/src/main/java/org/jruby/ir/builder/IRBuilder.java, core/src/main/java/org/jruby/ir/builder/IRLoop.java, core/src/main/java/org/jruby/ir/representations/IGVCFGVisitor.java, core/src/main/java/org/jruby/ir/util/IGVDumper.java, core/src/main/java/org/jruby/util/cli/Options.java
do not emit labels which are not used while constructing loops.
Also update IGV to save to stdout and tooltip edges.
Additionally give more labels names to better express what a BB is for.
=> do not emit labels which are not used while constructing loops + IGV enhancements

core/src/main/java/org/jruby/ir/IRClosure.java, core/src/main/java/org/jruby/ir/IRScope.java, core/src/main/java/org/jruby/ir/builder/IRBuilder.java, core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java, core/src/main/java/org/jruby/ir/persistence/IRDumper.java, core/src/main/java/org/jruby/ir/representations/IGVCFGVisitor.java, core/src/main/java/org/jruby/ir/util/IGVDumper.java, core/src/main/java/org/jruby/ir/util/IGVHelper.java
Allow closures names of scopes to be more readable:
```retriable::CLOSURE_1::CLOSURE2```  now looks like ```retriable::times &|index|2::any? &|e|4```
Literal lambdas also print out with `->(a)1`.
=> rename all closures to more closely match a name you can read vs CLOSURE_2

lib/pom.rb, lib/pom.xml
a bunch of fixes and missing (compat) features: 
- https://github.com/jruby/jruby-openssl/releases/tag/v0.14.4
- https://github.com/jruby/jruby-openssl/releases/tag/v0.14.5
=> [deps] update jruby-openssl to 0.14.5

core/src/main/java/org/jruby/parser/RubyParserBase.java
This was adding begin line to coverage list whether it had been removed or not.  It should use the line of the node
it contained as the line to add for coverage.  This fixes #8173
=> begin node coverage line should not get added if it has been removed

core/src/main/java/org/jruby/runtime/load/LoadService.java, test/jruby/require_raising.rb, test/jruby/test_require.rb
This is an issue with Rails 7.x due some of the "smart" runtime feature detection they do.
Details are in the issue report: https://github.com/jruby/jruby/issues/8155
=> [fix] LoadError on require should not complete load

core/src/main/java/org/jruby/anno/AnnotationHelper.java
Also flag frame names with "!" for ostruct
The ostruct library aliases all methods from Object/Kernel with a bang suffix ("!") to allow them to be callable even though the OpenStruct should support them as field names. Because we use record these names in a table of known frame-aware methods, we have typically warned when aliasing them. This rarely comes up, since aliasing usually is accompanied by wrapping, which breaks their behavior on all implementations, but this aliasing in ostruct is unusual and pervasive, leading to issues like #8200.
This patch assumes we're going to have issues with ostruct forever and eagerly adds the "!" names alongside the regular names for all method names that match /[a-z_]/, so taht existing methods and future methods will behavior properly and not warn …
=> Mark frame-aware method names with bang suffix for ostruct

lib/pom.rb, lib/pom.xml
The current recommendation for Ruby 3.1 users is to update to rdoc 6.4.1.1 due to known issues.
=> bump rdoc dependency to 6.4.1.1

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/parser/StaticScope.java
In jruby/jruby#8095 (jruby/jruby@121c60fb) I optimized the JIT to statically compile in the logic for ruby2_keywords at the time of JIT. Unfortunately there turned out to be too many cases where this flag can change at runtime, leading to bugs like jruby/jruby#8119 where a previously-jitted scope gets flipped to ruby2_keywords later on.
This patch partially reverts that optimization and resumes passing in the live ruby2_keywords value from the scope. We can revisit this in the future when it is possible to throw out and re-compile scopes that get this flag set later on.
Fixes jruby/jruby#8119
=> Partially undo kwarg optz from #8095

core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java, core/src/main/java/org/jruby/ir/instructions/BSwitchInstr.java, spec/compiler/general_spec.rb
fixes #8157.  the int values we calculate are only valid for the runtime they are created in.  When loading AOT code we have to generate new int values.  This fix just saves the operands we are making the jump table for so we can regenerate new ints from them.
=> opted case needs to use updated ints when loaded into new runtime.

core/src/main/java/org/jruby/java/proxies/ConcreteJavaProxy.java
If these are delegated or wrapped by profiling, we will fail type comparisons later on. Those comparisons are fragile, but for now this is the simplest fix.
Fixes #8148
=> Always unwrap old initialize methods

core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/util/ClassDefiningClassLoader.java, core/src/main/java/org/jruby/util/ClassDefiningJRubyClassLoader.java, core/src/main/java/org/jruby/util/NClassClassLoader.java, core/src/main/java/org/jruby/util/OneShotClassLoader.java, spec/java_integration/reify/become_java_spec.rb, spec/regression/GH-1229_reified_parent_and_child_have_same_name_spec.rb, test/jruby/test_higher_javasupport.rb
an attempt at fixing proper re-reification of Java (sub-)class hierarchy... (https://github.com/jruby/jruby/issues/8141)
this version behaves the same 99% of production uses (Java class name is kept); but when a Java class gets re-reified it will start using a versioned suffix  (`@v1`) for the Java class name.
2 previous attempts:
- https://github.com/jruby/jruby/pull/8140
- https://github.com/jruby/jruby/pull/8147
=> [ji] support re-reifying class hierarchy

core/src/main/java/org/jruby/util/io/PopenExecutor.java
This is a bit hacky due to the way we handle chdir on top of posix_spawn. The logic for making the command line use sh and cd lives in execFillarg, since it must handle the case where the virtual CWD is not the same as the JVM CWD. In order to make sure that processing also happens for incoming chdir: options, this patch pre-processes the options hash just for chdir.
Fixes #8126
=> Process chdir option sooner so execFillarg sees it

core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/ir/passes/AddCallProtocolInstructions.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/runtime/IRBlockBody.java, core/src/main/java/org/jruby/runtime/Signature.java, spec/tags/ruby/core/proc/arity_tags.txt
arity for {|a,| } was -2 and should have been 1
We still use arity value for dispatch which led to four changes:
1.  anonrest which is after the `a` variable in first sentence means it is not really a rest so -2 (1+arity)*-1{rest} becomes 1
2. generic yield must always check on positive arity whether it should be spreadable or not
3. specific yields must also check spreadable
4. ACP should not specify single value it is spreadable (since it will have more than one value).
We need to transition to something instead of arityValue in signature.  I think an enum would likely simplify code and be more readable as well.
=> arity for {|a,| } was -2 and should have been 1

core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/RubySignalException.java, core/src/main/ruby/jruby/kernel/jruby/process_util.rb, test/mri/excludes/TestArity.rb
Simple string changes except for SignalException which was rearranged a little bit since it has a minimum arity of 1.
=> Fix some error messages to make MRI test pass

core/src/main/java/org/jruby/RubyException.java, core/src/main/java/org/jruby/runtime/backtrace/TraceType.java, spec/tags/ruby/core/exception/full_message_tags.txt
Exception#full_message is based on dispatching to detailed_message.  This PR implements detailed_message and makes the changes needed so full_message can be overriden by user-defined detailed_message.
=> Make Exception#detailed_message,full_message pass specs

core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java
Non-method scopes like classes and modules have issues with the frame name not properly propagating into the executing body, and blocks may be used for define_method which introduces similar complexities in getting the frame name. This patch temporarily narrows the frame name optimization to method bodies only.
=> Narrow frame name optimization to method scopes

core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/javasupport/ext/JavaLang.java, core/src/main/java/org/jruby/runtime/backtrace/TraceType.java
* java.lang.Throwable#full_message uses the same logic as Exception#full_message but without #detailed_message it did not include the exception message in output.
* Shared full_message logic did not insert newlines between backtrace lines.
=> Fix full_message formatting and Throwable impl

core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRBodyMethod.java, core/src/main/java/org/jruby/ir/instructions/DefineClassInstr.java, core/src/main/java/org/jruby/ir/instructions/DefineModuleInstr.java, core/src/main/java/org/jruby/ir/instructions/FrameNameCallInstr.java, core/src/main/java/org/jruby/ir/interpreter/ExitableInterpreterEngine.java, core/src/main/java/org/jruby/ir/interpreter/Interpreter.java, core/src/main/java/org/jruby/ir/interpreter/InterpreterEngine.java, core/src/main/java/org/jruby/ir/interpreter/StartupInterpreterEngine.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/indy/FrameNameSite.java
Mostly reverting places where I tried to null out or dig up the proper frame method name for non-method scopes, many of which have no frame method name. We need to re-example all frame name and binding name (which frequently doesn't match) logic to ensure we're passing an appropriate method name through for both backtraces and `__method__`.
=> More frame name fixes

bench/bench_block_given.rb, bench/bench_string_interpolation.rb, core/src/main/java/org/jruby/ir/targets/indy/BuildDynamicStringSite.java
The string interpolation optimizations in #8180 left some improvements on the table. This PR implements those missing bits.
* The buffer created for the initial string when starting from a static segment was re-copying the buffer twice.
* Encoding was being re-set multiple times for no reason.
I also added more logging of dstring forms in the indy site and some additional cases in the benchmark. It's now consistently much faster than the old logic.
=> More string interpolation optimizations

core/src/main/java/org/jruby/embed/variable/AbstractVariable.java, core/src/main/java/org/jruby/embed/variable/Argv.java
These fields are changed together but without any synchronization or atomicity. Simplest fix for now is to synchronize the methods and mark them as volatile.
Fixes #8178
I looked over other descendants of AbstractVariable but none of them had state changes like Argv.
I also tried to figure out a way to encapsulate those fields better but I will look at that a different time after learning why these variables work this way.
=> Synchronize state in AbstractVariable and Argv

core/src/main/java/org/jruby/RubyArgsFile.java, core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/util/io/Getline.java
Fix IO#each_line specs
This will also fix a few other incidental methods which share the same code in IO.
=> Fix IO#each_line specs

lib/ruby/stdlib/fiddle/jruby.rb
It seems that the `size` variable defined in `Fiddle::Pointer.to_ptr` is never used:
https://github.com/jruby/jruby/blob/2ff07a3c2b6823fc541fc08d924f5bb53d50a371/lib/ruby/stdlib/fiddle/jruby.rb#L158
This triggers an "assigned but unused variable" warning if this code is loaded in verbose mode.
=> Remove unused variable assignment from Fiddle::Pointer.to_ptr

core/src/main/java/org/jruby/RubyGlobal.java, test/mri/excludes/TestEnv.rb
Making excluded tests from` test/mri/ruby/test_env.rb` pass.
` ./bin/jruby test/mri/runner.rb  test/mri/ruby/test_env.rb `
=> Making excluded tests from` test/mri/ruby/test_env.rb` pass

test/mri/excludes/TestAssignment.rb, test/mri/excludes/TestAssignmentGen.rb
All tests from `test_assigment.rb `are passing, so I think we can remove the excluded ones:
`bin/jruby test/mri/runner.rb  test/mri/ruby/test_assignment.rb```
=> Remove skipped tests from TestAssignment

core/src/main/java/org/jruby/javasupport/ext/JavaLang.java
This fixes https://github.com/jruby/jruby/issues/8244
=> Remove redundant (and slightly broken) to_int and to_f aliases

spec/java_integration/fixtures/InheritsFromAbstractClass.java, spec/java_integration/fixtures/TrivialAbstractClass.java, spec/java_integration/methods/dispatch_spec.rb
Test exercising dispatch to a method on a Java object which is inherited from an
abstract class is failing with NoMethodError. Illustrates #6197
=> Add test for #6197

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, spec/regression/core/enumerable/reject_spec.rb
Should fix #8225.   This logic is the same as the overload of the same name so I think just a place I missed in previous PR which fixed arity for `|e,|`.
=> yield specific for interp should have same rest logic as other paths

core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
Fix #8183.  IPSocket#addr should report :: vs long unspecified address
=> Fix #8183.  IPSocket#addr should report :: vs long unspecified address

bench/bench_marshal_dump.rb, bench/bench_marshal_load.rb, core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyBignum.java, core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyComplex.java, core/src/main/java/org/jruby/RubyException.java, core/src/main/java/org/jruby/RubyFloat.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/RubyMarshal.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/RubyProcess.java, core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/RubyRational.java, core/src/main/java/org/jruby/RubyRegexp.java, core/src/main/java/org/jruby/RubyStruct.java, core/src/main/java/org/jruby/RubySymbol.java, core/src/main/java/org/jruby/RubySystemCallError.java, core/src/main/java/org/jruby/ext/set/RubySet.java, core/src/main/java/org/jruby/runtime/ObjectMarshal.java, core/src/main/java/org/jruby/runtime/builtin/IRubyObject.java, core/src/main/java/org/jruby/runtime/marshal/MarshalCache.java, core/src/main/java/org/jruby/runtime/marshal/MarshalCommon.java, core/src/main/java/org/jruby/runtime/marshal/NewMarshal.java, core/src/main/java/org/jruby/runtime/marshal/NewMarshalCache.java, core/src/main/java/org/jruby/util/collections/HashMapInt.java, core/src/main/java/org/jruby/util/io/TransparentByteArrayOutputStream.java
The Marshal.dump logic we have predates nearly all improvements we have made over time, including:
* Efficient instance variable storage
* Passing ThreadContext on the stack
* Caching dynamic method calls from Java
This PR refactors and overhauls MarshalStream for efficiency and reduced object allocation.
=> Rewrite Marshal.dump logic for efficiency

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/compiler/impl/SkinnyMethodAdapter.java, core/src/main/java/org/jruby/ir/operands/TemporaryLocalReplacementVariable.java, core/src/main/java/org/jruby/ir/targets/IRBytecodeAdapter.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/MethodData.java, core/src/main/java/org/jruby/runtime/builtin/IRubyObject.java, core/src/main/java/org/jruby/util/JavaNameMangler.java, core/src/main/java/org/jruby/util/cli/Options.java, core/src/main/java/org/jruby/util/collections/IntHashMap.java, spec/compiler/general_spec.rb
This PR will encompass several improvements to JRuby's representation of code and objects, in order to make JVM tooling more useful.
Among the ideas explored here:
* Cleaner representation of methods and class for stack traces and profiling.
* Always-on class reification to show real class names in JVM heap inspection tools.
* Better JIT configuration to allow JVM debugging tools to step through Ruby code and set breakpoints and such.
* This may include some changes to force larger scopes to JIT so they can be debugged, even if this means the JVM cannot native JIT them.
* Enhancements for JVM debuggers to better see into dynamic scopes, Ruby objects with instance variables, and core Ruby types with complicated internals.
=> Improved representation of JRuby for JVM tools

core/src/main/java/org/jruby/anno/AnnotationBinder.java, core/src/main/java/org/jruby/anno/IndyBinder.java, core/src/main/java/org/jruby/anno/JRubyMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/InvocationMethodFactory.java, core/src/main/java/org/jruby/internal/runtime/methods/InvokeDynamicMethodFactory.java, core/src/main/java/org/jruby/runtime/Visibility.java, core/src/test/java/org/jruby/test/TestMethodFactories.java
In jruby/jruby#8146 we saw that DelegateClass can be broken by JRuby extensions that do not explicitly set their initialize methods to Visibility.PRIVATE. This is an error-prone requirement as detailed in jruby/jruby#8210, since there's no indication that initialize is special and should always be private.
This patch introduces a "DEFAULT" visibility to be the default for the annotation. When binding methods using annotation processing, the DEFAULT visibility will translate itself to PRIVATE for the initialize method and PUBLIC for other cases. This ensures that initialize is always set to PRIVATE if no other visibility is specified, avoiding the bug. If initialize is set to some other visibility, it will keep that visibility.
Fixes jruby/jruby#8210
=> Introduce a DEFAULT visibility to indicate unspecified

bench/bench_print.rb, core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/ir/instructions/CallBase.java
This started out as a call site optimization to pass `$_` directly yo `Kernel#print` or `IO#print` rather than provide it through a heap frame, but the simpler change is to reduce the deoptimization to only zero-arity. There are unlikely to be many non-core case for calling `print` without any arguments other than for the core version.
If there is such a case in the wild, we can revisit the call site optimization.
The patch as written here eliminates the frame requirement for all non-zero arity calls to `print`.
=> Reduce deopt from print use of $_

core/src/main/java/org/jruby/RubyMethod.java, spec/tags/ruby/core/unboundmethod/equal_value_tags.txt
Unbound#== for aliases to be considered equal.
=> Unbound#== for aliases to be considered equal.

core/src/main/java/org/jruby/RubyEnumerable.java, spec/tags/ruby/core/enumerable/inject_tags.txt, spec/tags/ruby/core/enumerable/reduce_tags.txt
Enumerable#inject/reduce should show arg error with no arg or block
=> Enumerable#inject/reduce should show arg error with no arg or block

bench/bench_literal_array.rb, core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/ir/targets/ValueCompiler.java, core/src/main/java/org/jruby/ir/targets/indy/ArrayBootstrap.java, core/src/main/java/org/jruby/ir/targets/indy/IndyValueCompiler.java, core/src/main/java/org/jruby/ir/targets/simple/NormalValueCompiler.java, core/src/main/java/org/jruby/runtime/Helpers.java, core/src/main/java/org/jruby/specialized/RubyArrayOneObject.java, core/src/main/java/org/jruby/specialized/RubyArraySpecialized.java, core/src/main/java/org/jruby/specialized/RubyArrayTwoObject.java
This change detects when a literal array contains only fixnums or floats and uses indy to embed those values in a call site, greatly reducing the bytecode size for constructing the array. Arrays that are too large will not fit into the encoded String and prevent compilation, but they would not likely have fit into bytecode limits with the old logic anyway.
A benchmark is included.
=> Optimize literal fixnum and float arrays

core/src/main/java/org/jruby/RubyModule.java
It should be null unless something has been included.
Fixes #8275
=> Properly check for Module's superclass

core/src/main/java/org/jruby/compiler/JITCompiler.java, core/src/main/java/org/jruby/ir/builder/IRBuilder.java, core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java, core/src/main/java/org/jruby/ir/instructions/EQQInstr.java, core/src/main/java/org/jruby/ir/targets/JVMVisitor.java
This fixes two issues:
* #8283 
* `SyntaxError` raised lazily by IR building can happen during JIT at threshold=0 and the wrapping of it in NotCompileableException broke an expectation in the ruby specs.
=> Fix pattern JIT Hash match and SyntaxError

core/src/main/java/org/jruby/util/ShellLauncher.java
ENV.op_aref can only return nil or a string (no methods that are bound to Ruby should ever return null) so check both of those conditions to determine fallback on default PATH.
Fixes #8289
=> Check for empty string from ENV.op_aref

core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/RubyInteger.java, core/src/main/java/org/jruby/RubyRandomBase.java, core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/RubyRational.java, core/src/main/java/org/jruby/RubySignalException.java, core/src/main/java/org/jruby/RubyTime.java, core/src/main/java/org/jruby/api/Convert.java, core/src/main/java/org/jruby/ext/socket/Option.java, core/src/main/java/org/jruby/util/TypeConverter.java, core/src/main/java/org/jruby/util/io/EncodingUtils.java
checkToInteger - Same as TypeConverter but it replaces it integerAsInt - Works from knowing we have RubyInteger and bounds checks to
make sure we really have an int
integerAsLong - Works from knowing we have RubyInteger and bounds checks to
make sure we really have a long
Fallout from this is realizing we had two checkToInteger but whatever used the more generic form which allows to pass in converter is no longer used for anything but #to_int.  This PR deprecated both versions.
In refactoring to use these I noticed in two places we were not even checking to see if the value was safely an int/long.  The integerAs* provides this and is more direct/narrow in what it provides than num2int or num2long.
=> 3 new Convert API methods

core/src/main/java/org/jruby/RubyIO.java, spec/tags/ruby/core/io/popen_tags.txt
fixes #8278
Returns the value of the block for IO.popen and remove the test tag.
=> Return the value of the block for IO.popen

core/src/main/java/org/jruby/BasicObjectStub.java, core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyObject.java, core/src/main/java/org/jruby/embed/variable/InstanceVariable.java, core/src/main/java/org/jruby/runtime/builtin/InstanceVariables.java
This PR will replace the remaining uses of the `Variable` collections returned by methods like `InstanceVariables.getInstanceVariableList` so we can start deprecating those interfaces and fix users in the wild.
* `getInstanceVariableList` replaced with `forEachInstanceVariable`, eliminating a transient `Map` of `Variable` objects.
* `getInstanceVariableNameList` replaced with `forEachInstanceVariableName`, eliminating a transient `List<String>`.
Most of these do allocate a stateful Lambda, but I've made efforts to keep that cost to a minimum.
=> Eliminate last consumers of Variable logic

core/src/main/java/org/jruby/util/cli/Options.java
=> Disable eager constants in JRuby 10

core/src/main/java/org/jruby/ir/interpreter/FullInterpreterContext.java, core/src/main/java/org/jruby/ir/interpreter/InterpreterContext.java
There's potential for races while setting up the interpreter contexts after AOT deserialization or during some other phase transitions in the interpreter and JIT. This PR attempts to lock down those changes and avoid races.
=> Race fixes for AOT mode in 9.3

core/src/main/java/org/jruby/javasupport/ext/Module.java
This was originally done on purpose while working toward the possibility of lazy imports, but it's better for now to just let the class initialize and fail fast if there are linkage errors.
Fixes #8299
Resolves regression discussed in [#799](https://github.com/jruby/jruby/issues/799#issuecomment-2187125505) that prevented consistent error messages for unlinkable classes.
=> Eager initialize java_import'ed classes

core/src/main/java/org/jruby/util/io/SeekableByteChannelImpl.java
Changes in e8dbe9c26 broke this fallback by silencing errors from the old setAccessible (as part of becoming more module-friendly). This patch checks if the setAccessible was successful and returns null for any fields that could not be made accessible. This in turn allows the USABLE fallback to properly reflect actual usability.
=> Properly fall back if can't setAccessible

lib/pom.rb, lib/pom.xml, spec/ruby/library/net-ftp/shared/puttextfile.rb
Previous versions were missing our patch to disable OpenSSL session caching.
See ruby/net-ftp#38
=> Update net-ftp to JRuby-compatible 0.3.7

lib/pom.rb
jruby-openssl 0.15.0 release notes [here](https://github.com/jruby/jruby-openssl/blob/master/History.md#0150):
```
This version upgraded to latest Bouncy-Castle (1.78) and the minimum supported JRuby is now 9.2.
- [refactor] propagate IOError from selector exception
- [fix] convert IOException to Ruby exception correctly follow up on the fix (#242) in 0.14.6
- [fix] implement OpenSSL::PKey::EC::Point#mul and #add (#307)
- [fix] ASN.1 BitString pad bits being out of range
- [compat] support base64digest on OpenSSL::HMAC
- [compat] add Buffering#getbyte for SSLSocket
- [refactor] drop (unused) Config native impl
- [refactor] less locking when there's a shared SSLContext
- [fix] encoding of ASN1::Null primitive to_der
- [fix] ASN.1 tagged object tag-class encoding/decoding
- [fix] ASN1 …
```
=> update jruby-openssl to 0.15.0

core/src/main/java/org/jruby/runtime/encoding/EncodingService.java, core/src/main/java/org/jruby/util/cli/Options.java
This change was applied to CRuby in 3.0.
See https://bugs.ruby-lang.org/issues/12654
Fixes #7750
=> Default Windows filesystem encoding to UTF-8

core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/util/StringSupport.java
This should fix #8316
We were ignoring switching from a valid CR to broken one.  Why explicitly ignoring this?
=> We were ignoring switching from a valid CR to broken one

lib/pom.rb, lib/pom.xml
This upgrade addresses recent security issues in rexml. the issues are not critical, so this is not urgent.
=> upgrade rexml to 3.3.4

BUILDING.md, pom.rb, pom.xml, shaded/pom.rb, shaded/pom.xml
This is a series of patches to make a fast-as-possible incremental build profile.
Currently when doing a default build of JRuby, the three modules "core" (jruby-base, the actual JRuby sources), "shaded" (jruby-core, the combined JRuby and dependencies jar), and "lib" (jruby-stdlib) are always build. The "lib" module is expensive to build because it launches JRuby to conditionally fetch and unpack or install gems to populate the standard library. This can become tedious when iterating on source-only changes to JRuby.
The core and shaded jar files are always built with full compression, which is unnecessary and slow for local incremental builds. The shaded jar also builds a shaded sources jar which is useless for local development and produces warnings about duplicate files. We can make …
=> Speed up incremental builds

core/src/main/java/org/jruby/ext/socket/Addrinfo.java, core/src/main/java/org/jruby/ext/socket/SocketUtils.java
Fixes #8325
Makes new accept this address without raising and also marks it with our internal hack variable `looksLikeV4ButIsV6`.  by setting this variable we get other behavior like `ipv6?` will now return true.
I also updated inspect to re-add the ipv6 prefix which I think is ok?  If there is another magic prefix then this will inspect differently but I doubt this is very important from a semantic perspective.
=> Fixes #8325. Try and convince Ruby that our Java v4 address is really v6

core/src/main/java/org/jruby/parser/RubyParserBase.java, core/src/main/java/org/jruby/parser/StaticScope.java, core/src/main/java/org/jruby/runtime/Signature.java, spec/regression/language/keywords_spec.rb
index indicating start of keywords has no ending index so all local variables appeared to be keyword parameters.  This lead to not raising when a local variable happened to be passed as a keyword argument.
=> Fixes #8344.  Kwargs past must error if not kwarg params

core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyThread.java, spec/ruby/core/thread/wakeup_spec.rb, test/jruby/test_kernel.rb
* Previously sleep would only convert into milliseconds, so something like 0.0001 would get rounded to 0. 0 was a no-op in RubyKernel#sleep.
* Now it works in nanoseconds internally. RubyThread#sleep has also been expanded to have an overloaded signature which takes both milliseconds and nanoseconds. This supports existing calls expecting milliseconds only, while supporting nanosecond precision for sleep.
=> Allow nanosecond precision for Kernel#sleep

core/src/main/java/org/jruby/embed/jsr223/JRubyCompiledScript.java
The `preEval` calls are run later in `doEval` immediately before executing. Doing it here appears to have caused some issue in either the parse or the set-up of the scoping used by the parsed result (see jruby/jruby#8346). Removing these pre-parse `preEval` calls fixes the issue.
Fixes jruby/jruby#8346.
Edit: It turns out the `preEval` is actually necessary for the parse to pick up values properly, so instead we do a full `preEval` and `postEval` around the parse and again around the eval.
=> Properly set up binding for compiled JSR-223 scripts

core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java
Fixes intermittent EINVAL errors calling getsockopt by making the length a proper in/out pointer reference.
The error handling here is also improved, since strerror(-1) is not valid, and the error may not be EINVAL.
Fixes #8339.
=> Pass getsockopt length as an in/out reference

core/src/main/java/org/jruby/Ruby.java
If we found a vacated reference above, it could be removed from the ConcurrentWeakHashMap by the time we get to this point, resulting in a null return value from computeIfPresent. This new logic uses compute instead, either replacing the null or vacated reference with a new one or leaving in place any populated reference added in parallel somewhere else.
Fixes #8359
=> Ensure non-null reference when replacing

core/src/main/java/org/jruby/ext/ffi/jffi/DefaultMethodFactory.java
If a String is passed into an FFI function as an "out" pointer, we must ensure we use a mutable version. If the original string param is frozen, it must be duped to a non-frozen version, and if it is shared we must pre-modify it to avoid overwriting any shared buffers.
This may not be the best way to handle this. My instinct was to add logic into the "strategy" that can provide a mutable version of a given parameter, but this is a smaller localized change. We will want to revisit this logic and avoid type-specific logic in the marshaller when it should live in the strategy.
Fixes #8365
=> Ensure string-as-pointer is a mutable version

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/ir/persistence/IRDumper.java, core/src/main/java/org/jruby/ir/targets/indy/IndyValueCompiler.java, core/src/main/java/org/jruby/ir/targets/indy/StringBootstrap.java
Fixing the one failure (chilled strings should not be `frozen?`) led to some refactoring elsewhere in order to keep specs passing. All are green now.
=> Revisit chilled strings and pass all specs

core/src/main/ruby/jruby/kernel/enumerator.rb
Remaining specs are for #inspect which is not yet implemented.
See https://github.com/marcandre/backports/issues/194
=> Get most Enumerator::Product specs passing

core/src/main/java/org/jruby/java/proxies/JavaInterfaceTemplate.java, core/src/main/java/org/jruby/javasupport/Java.java, core/src/main/java/org/jruby/javasupport/JavaPackage.java, core/src/main/java/org/jruby/javasupport/JavaSupport.java, core/src/test/java/org/jruby/javasupport/TestJava.java
this is a second attempt at resolving (https://github.com/jruby/jruby/issues/8349) the slight regression introduced at https://github.com/jruby/jruby/commit/31f1ed6f7458acc42a545a032424580f5b22d746
the commit is reverted and the `-Xji.eager.constants` feature is re-implemented more conservatively (without effecting all `getProxyClass` callers).
also rename and cleaned up the method setting the actual proxy class constant, the tests are a bit futile but should prevent doing a similar `getProxyClass` refactoring, which would have undesired side effects.
=> re-implement the option to lazy bind Java:: constants

core/src/main/java/org/jruby/ir/targets/JVMVisitor.java, core/src/main/java/org/jruby/parser/RubyParserBase.java
* Don't freeze dynamic strings when concatenating two sequential string literals. (jruby/jruby#8380)
* For the sole remaining frozen DStr case, only freeze and do not create a debug frozen string.
Fixes jruby/jruby#8380
=> Fix issues relating to freezing dynamic strings

core/src/main/java/org/jruby/RubyEnumerable.java, spec/jruby/core/enumerable/tally_call_info_spec.rb, spec/jruby/core/enumerable/to_a_call_info_spec.rb, spec/jruby/core/enumerable/to_h_call_info_spec.rb
Enumerable#to_a does not take keywords but also was not handling any incoming callInfo bits. As a result an incoming CALL_KEYWORD_EMPTY bit can get stuck and propagte through to the next call. This does not process any kwargs because it is effectively a block with signature like |a, *b| but whether it should do more than clearing callInfo is unknown.
Fixes jruby/jruby#8382
=> Clear callInfo in Enumerable Java-based blocks

core/src/main/java/org/jruby/util/ShellLauncher.java, core/src/main/java/org/jruby/util/io/POSIXProcess.java
This avoids using reflection to access Process internals on JDK versions 9 and higher, reducing our our requirements for opening core JDK classes. In JRuby 10, we will remove all the reflective logic since that release targets at least Java 17.
This may help fix jruby/jruby#7515 by providing access to a real pid on Java 9+ regardless of reflection access.
=> Use Java 9+ Process.pid() to get pid

core/src/main/java/org/jruby/util/IOInputStream.java, test/jruby/test_zlib.rb
This includes two fixes for jruby/jruby#8391:
1. Don't blindly copy the resulting string bytes from a `read` call into the given buffer; we may have gotten more bytes than requested from a bad `read` implementation.
2. Fix a test fixture that potentially can produce more bytes than requested from a wrapped GzipReader `read` call.
The fix is targeted at jruby-9.3 in case we need to do any releases of that branch in the future, but the only planned release for now is 9.4.9.0.
=> Fix bugs from GzipReader wrapped IO-like test

core/src/main/java/org/jruby/ext/set/RubySet.java, spec/ruby/library/set/hash_spec.rb
set.rb is implemented in pure Ruby, so its @hash instance var will
start out as nil. If you attempt to #hash an uninitialized Set,
the resulting hashcode is that of nil, rather than raising an
exception as seen in https://github.com/jruby/jruby/issues/8393.
This fix emulates the nil hash. No other uses of the uninitialized
Set are fixed here, so it's still largely unusable until it has
been initialized.
See also https://github.com/jruby/jruby/issues/8352.
Fixes https://github.com/jruby/jruby/issues/8393.
=> Treat Set's internal Hash as nil when uninitialized

core/src/main/java/org/jruby/RubyThread.java, core/src/test/java/org/jruby/test/TestRubyThread.java
this is to support cases where e.g. a Java thread pool is running Ruby code.
if the ruby code uses any fiber/thread local state e.g. `Thread.current[:foo] = :bar` than there isn't an easy way to cleanup accumulated state in RubyThread's locals (and due the way foreign Java threads are adopted the state will stick around for when the Java thread is re-cycled).
=> [feat] support clearing of thread local state

core/src/main/java/org/jruby/RubyIO.java
6-7 specs failing because we do not call anything due to missing a path processing arity.
=> Fix foreach with mode: kwarg

core/src/main/java/org/jruby/java/proxies/JavaInterfaceTemplate.java, core/src/main/java/org/jruby/javasupport/Java.java, core/src/main/java/org/jruby/javasupport/JavaPackage.java, core/src/main/java/org/jruby/javasupport/JavaSupport.java, core/src/test/java/org/jruby/javasupport/TestJava.java
Reverts jruby/jruby#8368
This did not fix the `already initialized constant` issue fully (introduced by #8208) and led to several additional problems described in #8399. We are reverting this and #8208 all the way back and will attempt to fix #8156 a different way.
=> Revert "re-implement the option to lazy bind Java:: constants"

core/src/main/java/org/jruby/javasupport/Java.java, core/src/main/java/org/jruby/javasupport/JavaPackage.java, core/src/main/java/org/jruby/javasupport/JavaSupport.java, core/src/main/java/org/jruby/util/cli/Options.java
Reverts jruby/jruby#8208
This change was a bit half-baked and led to the "already initialized constant" issue. A subsequent attempt in #8368 failed to fix that issue and led to several additional problems described in https://github.com/jruby/jruby/issues/8399. We are reverting #8368 and this PR and will attempt to fix https://github.com/jruby/jruby/issues/8156 a different way.
=> Revert "Only set up Java:: constants when accessed directly"

core/src/main/java/org/jruby/RubyHash.java, core/src/test/java/org/jruby/test/TestRubyHash.java, spec/java_integration/types/map_spec.rb
Hash#inspect: no arrow for symbol keys.  add spacing to match C Ruby
=> Hash#inspect: no arrow for symbol keys.  add spacing to match C Ruby

lib/pom.rb, lib/pom.xml
due CVE reports (CVE-2024-49761 REXML ReDoS vulnerability)
```
Name: rexml
Version: 3.3.8
CVE: CVE-2024-49761
GHSA: GHSA-2rxp-v6pw-ch6m
Criticality: Unknown
URL: https://github.com/ruby/rexml/security/advisories/GHSA-2rxp-v6pw-ch6m
Title: REXML ReDoS vulnerability
Solution: update to '>= 3.3.9'
```
=> [deps] bump rexml default gem to 3.3.9

core/src/main/java/org/jruby/ext/thread/Mutex.java
Upon acquiring a lock, we should always check for interrupts that may have occurred while sleeping or acquiring the lock. This avoids proceeding with a critical section of code while there are interrupts pending.
Fixes jruby/jruby#8403
=> Always check for thread events after lock acquisition

lib/pom.rb
Seems to be issues launching these subprocesses via Maven. While we investigate that, temporarily disable extension building for default gems.
The problem manifests during the default gem install of the fiddle gem, which generates a dummy Makefile on JRuby because it uses the FFI version instead. The launch of extconf.rb exhibits problems in various environments:
* In CI, it ends up running with the system default Java rather than the one configured in JAVA_HOME.
* On local Linux environments, it fails to launch due to a "bad file descriptor: /bin/sh" error.
It seems that the subprocess launch is losing environment in some broken way.
=> Skip extension builds for default gems

core/src/main/java/org/jruby/ir/instructions/BSwitchInstr.java, spec/compiler/general_spec.rb
When deserializing a BSwitch we recalculate the values for the switch based on the new runtime, which mostly means getting new Symbol IDs. This was fixed in #8209. However we need to ensure that the jump table is sorted or the binary search for the switch will sometimes fail.
This patch sorts the related tables based on the new switch values.
Fixes #8421
=> Sort the jump tables based on new values

core/src/main/java/org/jruby/RubyThreadGroup.java
CRuby does not clear the ThreadGroup set in the Thread when the thread terminates. We do, which leads to some unpredictability in specs that check the group against a very short-lived thread. This patch removes the call to clear the thread's group.
=> Don't clear the ThreadGroup when Thread terminates

core/pom.rb, core/pom.xml, core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyObject.java, core/src/main/java/org/jruby/specialized/RubyObjectSpecializer.java, spec/java_integration/interfaces/implementation_spec.rb
The classes generated here need to be visible to other classes loaded and generated by JRuby, such as Ruby classes that implement Java interfaces. If the specialized class and a Java interface to implement come from different classloader hierarchies, the JVM classloading subsystem will be unable to resolve the impl class.
The fix here makes the RubyObjectSpecializer per-runtime, so the specialized classes live within the standard JRubyClassLoader hierarchy, visible to other classes loaded and generated by Ruby code at runtime.
An additional fix will pre-generate the first 50 specialized object classes, which will also fix the same issue (they will load into the same classloader as JRuby itself) and avoid re-generating these classes for each runtime instance.
Fixes #8412.
=> Root specialized object classloader at JRuby classloader

core/src/main/java/org/jruby/Main.java
For normal JRuby use, we let the main script finish and Main.main exits. If non-daemon threads remain running, they will keep the JVM alive. However a change for CRaC support accidentally introduced a hard exit(0) that is always encountered, even if the script did not request a hard exit using `exit` or similar Ruby calls.
This patch removes the hard exit(0) so that "casual" exit from the main script does not force the JVM to shut down. The runtime will still be torn down as usual, but non-daemon threads can keep the JVM alive after JRuby itself has exited.
Fixes #8416
=> Remove rogue exit(0) that shuts down JVM

bin/jruby.sh
Fixes #8441 by using an array to handle option files, who may have spaces in their path. Also avoids parsing option files twice when Java 9 is present.
=> jruby.sh: Use array to handle option files

bin/jruby.sh
Currently the `-sourcepath` command is not being passed correctly to jdb, causing an error when running. This PR separates jdb_args and prepends them to java args just before prepending JAVACMD to ensure the sourcepath command is recognised.
```
$ jruby --version
jruby 9.4.10.0-SNAPSHOT (3.1.4) 2024-11-29 ffffffffff Java HotSpot(TM) 64-Bit Server VM 23.0.1+11-39 on 23.0.1+11-39 +jit [arm64-darwin]
$ jruby --jdb foo.rb
Initializing jdb ...
> run
run @/Users/dani/projects/mine/jruby/bin/.jruby.java_opts @/Users/dani/projects/mine/jruby/bin/.jruby.module_opts -Xss2048k -Djffi.boot.library.path=/Users/dani/projects/mine/jruby/lib/jni -sourcepath /Users/dani/projects/mine/jruby/core/src/main/java:/Users/dani/projects/mine/jruby/lib/ruby/stdlib:. -Djava.security.egd=file:/dev/urandom …
```
=> fix --jdb -sourcepath command

core/src/main/java/org/jruby/RubySymbol.java
So many paths hit prepareID I am hoping everything will change to this error string when an expected a symbol/string and it isn't one.
=> Inspect wrong object when symbol/string wanted in error

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyDir.java, core/src/main/java/org/jruby/RubyFile.java, core/src/main/java/org/jruby/RubyFileStat.java, core/src/main/java/org/jruby/RubyIO.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/RubyThread.java, core/src/main/java/org/jruby/api/Check.java, core/src/main/java/org/jruby/ext/socket/Addrinfo.java, core/src/main/java/org/jruby/ext/socket/RubyUNIXServer.java, core/src/main/java/org/jruby/ext/socket/RubyUNIXSocket.java, core/src/main/java/org/jruby/runtime/load/LoadService.java, core/src/main/java/org/jruby/util/StringSupport.java, core/src/main/java/org/jruby/util/io/PopenExecutor.java
This one is confusing.  We have some Ruby impl but time.rb depends
on date.rb which is a stdlib loaded thing.  So we need to load it
after enough of JRuby it bootstrapped but we want this loaded
ultimately the same time as the Java impl of Time.  I just
put it at the end of Ruby#init but this is probably not right?
=> Make Time load its Ruby-impl side

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyGlobal.java, core/src/main/java/org/jruby/RubyThread.java, spec/tags/ruby/core/thread/report_on_exception_tags.txt
Avoid polling during propagation and report of a `Thread#raise` exception. If we dispatch dynamically to the configured stderr, we may hit additional polls that trigger new interrupts, wiping out the raise interrupt currently being handled.
Fixes #8479
=> Avoid re-polling while reporting a Thread#raise

bench/bench_subclasses.rb, core/src/main/java/org/jruby/RubyClass.java
For classes with many singletons, the Class#subclasses walk will cost significantly more than is warranted for the few concrete classes it will return. This can be eliminated by tracking whether each entry is concrete and adding a separate traversal link to the next concrete class in the chain.
Performance of such a case is significantly better:
Before:
```
1 thread Numeric.subclasses
1.315k (± 4.6%) i/s -      6.612k in   5.040800s
1 thread Object.subclasses
56.282 (± 3.6%) i/s -    285.000 in   5.074688s
1 thread Custom.subclasses with 1000 singletons
5.588 (± 0.0%) i/s -     28.000 in   5.021174s
```
After:
```
1 thread Numeric.subclasses
2.402k (± 3.4%) i/s -     11.990k in   4.998757s
1 thread Object.subclasses
189.977 (± 6.8%) i/s -    954.000 in   5.068134s
1 thread …
```
=> Provide concrete-only traversal for Class#subclasses

core/src/main/java/org/jruby/RubyArithmeticSequence.java, core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyBignum.java, core/src/main/java/org/jruby/RubyComplex.java, core/src/main/java/org/jruby/RubyFixnum.java, core/src/main/java/org/jruby/RubyFloat.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/RubyKernel.java, core/src/main/java/org/jruby/RubyMatchData.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/RubyRational.java, core/src/main/java/org/jruby/RubyRegexp.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/RubySymbol.java, core/src/main/java/org/jruby/RubyTime.java, core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java, core/src/main/java/org/jruby/ext/date/RubyDate.java, core/src/main/java/org/jruby/ext/pathname/RubyPathname.java, core/src/main/java/org/jruby/ext/set/RubySet.java, core/src/main/java/org/jruby/java/proxies/ArrayJavaProxy.java, core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java, core/src/main/java/org/jruby/javasupport/JavaObject.java, core/src/main/java/org/jruby/javasupport/JavaProxyMethods.java, core/src/main/java/org/jruby/javasupport/proxy/JavaProxyReflectionObject.java, core/src/main/java/org/jruby/runtime/Helpers.java
Audited and made sure no more hash() calls but if something still does it his RubyBasicObject#hash() which calls the ThreadContext version.
=> Make hash() always call to hash(ThreadContext) and deprecate

core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/ext/zlib/RubyZlib.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
Most of these were already dead.  Also made the IR consuming one become defineClassUnder like the native extension equivalent of this method.
=> Deprecate defineOrGetClassUnder

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyInstanceConfig.java, core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java, core/src/main/java/org/jruby/util/cli/Options.java, core/src/main/ruby/jruby/kernel/gem_prelude.rb, lib/ruby/stdlib/bundled_gems.rb
* New boot libraries: error_highlight and syntax_suggest
* New bundled_gems stdlib that warns for direct requires of libs that have been gemified.
* "New" rubyarchdir value in RbConfig::CONFIG to support the bundled_gems logic. We do not use this dir but it is defined for compatibility.
=> Update gem_prelude from Ruby 3.4

core/src/main/java/org/jruby/java/codegen/RealClassGenerator.java, core/src/main/java/org/jruby/javasupport/Java.java, test/jruby/test_higher_javasupport.rb
Yet another attempt at resolving https://github.com/jruby/jruby/issues/8349, for good.
Since the reverts done in JRuby 9.4.9.0 still generate the warnings.
Seems like there's more (related) stuff that changed (since 9.4.6.0) given the checks, changed in this PR, [were there](https://github.com/jruby/jruby/blob/9.4.6.0/core/src/main/java/org/jruby/javasupport/Java.java#L507-L509) but did not cause warnings :shrug:. 
Instead of chasing around I took an approach of marking `InterfaceImpl` generated classes synthetic and excluded those from being set in Ruby land...
=> [ji] do not expose InterfaceImpl classes in Ruby land

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/indy/ConstantLookupSite.java, core/src/main/java/org/jruby/ir/targets/simple/ConstantLookupSite.java
Some old guarded code with a comment made me think we don't need this check as we should always have a staticScope.
=> We should always have a valid staticScope

BUILDING.md
With rbenv installed on my system, the commands listed only work if I specify bin/jruby in all the commands given in BUILDING.md
=> specify bin/jruby in BUILDING doc

core/src/main/java/org/jruby/RubyNameError.java
This was weirdly hard to see in reading MRI's logic where it adds a break to jump past reinspecting the String it makes only for singletons (other cases still are module/classes to be inspected).  This fixes a single spec failure in ruby/language.
=> Extra "" around singleton in {Name|No}MethodError

core/src/main/java/org/jruby/RubyProc.java, core/src/main/java/org/jruby/runtime/Signature.java
The basic problem was we were not matching MRI in returning 1 for `|a, **k|` and instead returning -2.  There was some other issue which occurred where a weird signature is not being marked as rest and messing up arity for Proc#arity.  I plan on taking a stab at it in next commit but this fix is more important than that so this will land even if I cannot figure that out.
=> Fix arity specs for blocks in language

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
This fix is ugly but in recv_keyword we will notice that it is not really a keyword but an element of a rest arg.  In that case we will dup the kwarg into a normal hash argument.
The ugly part is this is handled while processing kwargs but if I went to figure out how this worked I would think the logic would be in recv_rest_arg.  Unfortunately, we no longer have the info available by that point (and honestly it would be painful to propagate to a later instruction).
=> Rest args dup keyword hash

core/src/main/java/org/jruby/RubyFile.java, core/src/main/java/org/jruby/RubyIO.java
When passing kwargs from a ruby2_keywords method to a core "real keywords" method, we lose the keywordiness of the incoming hash and raise an argument error for the arity mismatch. By using the same logic as IR here, we properly handle the incoming r2k hash.
This same patch could be applied generally to all core methods that accept keywords, but given the rarity of r2k to core "real keywords" methods we have chosen to only do targeted fixes. This reduces the potential impact (versus a new, more general solution) and the required work (9.4.10 is eagerly awaited). We will explore more reliable, general improvements to core method kwarg handling in JRuby 10.
Fixes #8398.
=> Use same logic as IR for kwarg handling in IO#write

core/src/main/java/org/jruby/RubyEnumerable.java
This change has been made other places, like Enumerable#map, but as reported in #8435, it was not done for at least Enumerable#uniq.
Fixes #8435
Other fixes may get added here before merge.
=> Pass Enumerable#uniq arguments properly

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubyNameError.java, core/src/main/java/org/jruby/util/cli/Options.java
This is a backport of the no-inspect NameError logic added to JRuby 10 in #8533, guarded by an option for users on JRuby 9.4.
On 9.4, the inspect logic is enabled by default, but can be disabled by with the option `-XnameError.inspect.object=false`. Because the object inspect is a specified behavior of Ruby 3.1, we can't disable it by default, but this allows users to opt out of the behavior.
JRuby 10 will ignore this logic and avoid inspecting the object attached to the NameError. The option will have no effect.
Using the example from #8384 with this new option:
```
$ jruby -w -J-Xmx250M -XnameError.inspect.object=false blah.rb
generating large obj
done
NameError: undefined local variable or method `nameerror' for an instance of Test
error at blah.rb:9
<main> at blah.rb:16
``` …
=> Backport no-inspect NameError logic

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/RubySymbol.java, core/src/main/java/org/jruby/embed/ScriptingContainer.java, core/src/main/java/org/jruby/runtime/load/LibrarySearcher.java, core/src/main/java/org/jruby/runtime/load/LoadService.java
Most of this would happen as part of GC clearing the runtime, but these changes help reduce that load and get the large collections and data structures releasable earlier.
Fixes jruby/jruby#8343
=> Additional teardown to aid GC and release resources

core/src/main/java/org/jruby/RubyModule.java
This warning is only supposed to show in verbose mode. Changing from `warn` to `warning` fixes this.
=> Use warning instead of warning when adding attr as module_function

core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java
This fix prevents the crash but the last source line output it gives does not match Ruby 3.1.  It does give the proper error message so this should not be confusing.
The reason for not fixing this is this output method is already not quite right in a couple of ways and the Prism parser is the future of our parsing.  Fixing the crash does give the important error line saying what is wrong so anyone who hits this will know what is wrong.
=> Fixes #8355: wallpaper crash in heredoc eof error

core/src/main/java/org/jruby/RubyThread.java, core/src/main/java/org/jruby/compiler/Compilable.java, core/src/main/java/org/jruby/compiler/JITCompiler.java, core/src/main/java/org/jruby/internal/runtime/AbstractIRMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java, core/src/main/java/org/jruby/internal/runtime/methods/MixedModeIRMethod.java, core/src/main/java/org/jruby/runtime/InterpretedIRBlockBody.java, core/src/main/java/org/jruby/runtime/MixedModeIRBlockBody.java
The block of code passed to Thread.new is frequently only executed once during a program's runtime, and in such cases there's often heavy lifting performed within the block such as an IO or Queue loop. Because we do not support any form of on-stack replacement, these blocks may never fully optimize and will remain in whatever execution mode JRuby starts them in (usually the slowest "startup" interpreter).
This patch adds logic from Thread.new into the block body to force completion of builds steps that would optimize the body. This is akin to the behavior of the command-line target script, which we also eagerly compile due to the great number of single-script utilities and benchmarks in the Ruby ecosystem.
This patch also plumbs that force-ability through the other "buildable" execution …
=> Force a Thread's block to optimize eagerly

lib/pom.rb, lib/pom.xml
This updates all gems we ship with the versions from Ruby 3.4.0.
There is an outstanding issue with the digest 3.2.0 gem not being released yet: https://github.com/ruby/digest/issues/83
=> Update Ruby 3.4 gems from release

core/pom.rb, core/pom.xml, core/src/main/java/org/jruby/anno/AnnotationBinder.java, core/src/main/java/org/jruby/anno/IndyBinder.java, maven/jruby-complete/pom.rb, spec/java_integration/fixtures/EveryTypeAnnotations.java, spec/java_integration/reify/annos_spec.rb, spec/java_integration/types/classgen_spec.rb, test/pom.rb
We only used this for the Generated anno, for generated code, and for the Resource anno in one test. Removed use of Generated and switched use of Resource to use Deprecated (for a test of Java integration with annotations).
=> Remove dependency on jakarta.annotation-api

lib/pom.rb, lib/pom.xml
In 9.4.10.0 we fixed the behavior of jar-dependencies to avoid activation until after other gems had booted, allowing jar-deps to be updated independently. That allowed us to release updates to jar-deps for users to install and use, but we could not release before having an upgradable version of JRuby.
This commit updates JRuby to jar-deps 0.5.3 for our 9.4.11.0 release, which should finally end issues with the older jar-deps and the older ruby-maven and ruby-maven-libs it was bound to.
See jruby/jruby#8593 for an example of continuing issues due to those older library versions being shipped in 9.4.10.0.
=> Update jar-dependencies to 0.5.3

lib/pom.rb, lib/pom.xml
At some point between RubyGems 3.3.26 and now, a Bundler release went out that is incompatible with that version. We have not updated either for JRuby 9.4 releases recently, so this gets them current.
Fixes jruby/jruby#8590
=> Update rubygems to 3.6.3 and bundler to 2.6.3

core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyModule.java
My implementation of a new subclasses structure in https://github.com/jruby/jruby/pull/8462
was a bit too "clever" leading to a potential leak of subclass
references. To avoid using a ReferenceQueue, I tied the "cleaning"
of the subclasses list to encountering a percentage of empty
subclass references during traversal. However if traversal only
walks concrete subclass references (via Class#subclasses),
empty non-concrete (singleton, included, prepended) subclass
references could accumulate. This would only be cleared out with
a full (not concrete-only) subclass walk, which only happened for
a few internal uses of this list.
The patch here reverts to the Map-based approach previously
used with two changes:
* Instead of a fully-concurrent or synchronized WeakHashMap, we
use read/write …
=> Eliminate leak of non-concrete subclass references

core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyModule.java, test/jruby.index, test/jruby/test_class_subclasses.rb
The new SubclassesWeakMap properly included read/write locking for the `put` and `forEach` methods, but unfortunately the `remove` and `isEmpty` methods were not overridden with locking. This went unnoticed until after the 9.4.11.0 release, leading to jruby/jruby#8602.
This patch makes two modifications to ensure proper locking:
* Instead of working with the full Map interface, and possibly missing other method uses in the future, this narrows the subclasses map interface to a RubyClassSet with only unique methods that we use. This guarantees only these methods can be called, and we can ensure they are implemented properly.
* Add the missing locking to the `remove` method, now named `removeClass`.
Fixes jruby/jruby#8602.
=> Ensure subclass set prevents concurrent modification

core/src/main/java/org/jruby/java/proxies/JavaProxy.java, core/src/main/java/org/jruby/runtime/ivars/AtomicVariableTable.java, core/src/main/java/org/jruby/runtime/ivars/NonvolatileVariableAccessor.java, core/src/main/java/org/jruby/runtime/ivars/StampedVariableAccessor.java, core/src/main/java/org/jruby/runtime/ivars/SynchronizedVariableAccessor.java, core/src/main/java/org/jruby/runtime/ivars/VariableTableManager.java, spec/java_integration/object/ivars_spec.rb, spec/java_integration/object/singleton_spec.rb, spec/java_integration/spec_helper.rb
This warning was lost when we optimized variable updates to skip RubyBasicObject's `setVariable` as reported in https://github.com/jruby/jruby/issues/8611. The changes here restore the warning:
* Move common logic for initializing the variable table to the VariableAccessor superclass.
* Ensure all places where a new variable table is created check for JavaProxy and warn appropriately.
Note that field-based variable access does not have this same proxy check because JavaProxy will never use field-based variables.
=> Warn when creating a new ivar table on JavaProxy wrapper

bin/jruby.sh
Fixes a bug in #8625 and relates to features discussed in #8610
=> Fix default arguments for generating AppCDS flag

core/src/main/java/org/jruby/parser/RubyParserBase.java
unused warnings became useless warnings
Removed a layer of warnings for a few immediate types.  Looks like a change from 3.3+
=> unused warnings became useless warnings

core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/specialized/RubyArraySpecialized.java
fillNil does a bunch of extra nil sets up to the capacity of the array whether those values ever end up getting used.
The rationale for this fix is anything >realSize should get nil'd only after we change realSize.  For appends this never happens.  The case where it does happen is in aset.  In this case we nil fill between oldRealSize and one less than new realSize.
From a performance analysis all arrays initially benefit from not pre- filling nil up to capacity (which is 16 by default).  For arrays which are doing arbitrary asets past the end of the array it could end up doing more fills but asets like this are pretty uncommon.  Most of the time I do not even think it would be doing more fills for this either.
Additionally I removed the unshift for one extra element for shaped arrays. …
=> Remove upfront fillNill in Array

core/src/main/java/org/jruby/RubyEncoding.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/util/StringSupport.java, core/src/main/java/org/jruby/util/io/ModeFlags.java
After working on getting the CRuby stringio tests green in ruby/stringio#116 I turned my attention to stringio specs. These fixes are intended to get the specs green as well.
=> Fixes to get stringio tests and specs green

lib/pom.rb, lib/pom.xml, spec/tags/ruby/library/stringio/each_line_tags.txt, spec/tags/ruby/library/stringio/each_tags.txt, spec/tags/ruby/library/stringio/initialize_tags.txt, spec/tags/ruby/library/stringio/reopen_tags.txt, spec/tags/ruby/library/stringio/set_encoding_by_bom_tags.txt, test/mri/excludes/TestStringIO.rb, test/mri/stringio/test_ractor.rb, test/mri/stringio/test_stringio.rb
This updates stringio to 3.1.5 which includes all the fixes from https://github.com/ruby/stringio/pull/116 and the regression https://github.com/ruby/stringio/issues/119 fixed by https://github.com/ruby/stringio/pull/121. All CRuby tests and ruby/spec specs for stringio are now green.
Tests are from v3.1.5 of the ruby/stringio repo.
=> Update stringio to 3.1.5

bin/jruby.sh
A previous version of this script was incorrectly assuming that an uninitialized variable would be initialized to a "false" value, but uninitialized variables typically evaluate to a blank string which is considered true. As a result of this, no-argument calls behaved improperly, breaking the ability to pipe code into the jruby command.
This commit enables `set -u` for the JRuby launcher script, to trigger an error whenever an uninitialized variable is accessed. Variables we expect to possibly be uninitialized (such as various JAVA variables used to override the location of the java command) have been modified to use the `${variable-}` format that does not trigger an error.
=> Use set -u to avoid accessing uninitialized variables

bin/jruby.sh
Should fix https://github.com/jruby/jruby-launcher/issues/44. Doesn't explicitly check if `java` is a directory but `command -v` will  fail because it's not a file that can be executed.
=> Handle errors whe looking for Java executable

core/pom.rb, core/pom.xml, spec/tags/ruby/library/rbconfig/unicode_emoji_version_tags.txt, spec/tags/ruby/library/rbconfig/unicode_version_tags.txt
jcodings 1.0.62:
* update unicode to 15.0 (jruby/jcodings#66)
joni 2.2.4:
* update jcodings to 1.0.62
* fix: char class casefold for certain chars (jruby/joni#85)
=> Update jcodings to 1.0.62 and joni to 2.2.4

core/src/main/java/org/jruby/ir/builder/IRBuilderAST.java
parser passes block node vs only single last value to when
```ruby
p    case 'a'
when ('a'; 'b')
:wrong_called
when ('b'; 'a')
:called
end
```
=> parser passes block node vs only single last value to when

core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java
It seems Ruby removed the behavior where a non ruby2 keywords method receiving a ruby2 keywords hash would not preserve that and unmark the hash.
=> Ruby 3.4 seems to have simplified ruby2_keywords_hash

core/src/main/java/org/jruby/RubySymbol.java, core/src/main/java/org/jruby/util/IdUtil.java
Depends on #8677.
* Align logic for calculating ATTRSET more closely with the C code.
* Make type immutable and do not update it for encoding changes.
The second item here is a strange one; I'm not sure it should be possible to `setEncoding` on a `RubySymbol` (it should not be mutable and should not change type) but I don't think I want to make it an error or warning.
=> Symbol type calculation tweaks

test/mri.core.index, test/mri/excludes/TestCaseMappingPreliminary.rb
Updating the list of MRI core tests (mri.core.index) and tagging off failures. We'll address them like we do other excludes.
=> Update MRI core tests and tag failures

core/src/main/java/org/jruby/util/io/EncodingUtils.java, spec/java_integration/utilities/io_spec.rb
Logic in strTranscode evolved over the years to allow same-encoding requests to be no-ops. Those changes were never applied to rbByteEncode, resulting in same-encoding requests triggering errors when the transcoding subsystem saw nothing would be done. This complicated efforts to solve jruby/jruby#8682 by passing an encoding to the IOOutputStream constructor (ruby/json#759 and ruby/json#760).
This patch allows using IOOutputStream and the byte[] IO API it calls with an externally-encoded IO by passing in an expected encoding for incoming bytes. All bytes will be treated as being encoded properly, and if the source and destination encoding is the same, rbByteEncode will return null to indicate no-op.
Note that this misses some functionality of strTranscode in that it does not scrub the …
=> Handle encoding checks as in strTranscode

shaded/pom.rb, shaded/pom.xml
just specify a version to silence the warning
```
[WARNING] Some problems were encountered while building the effective model for org.jruby:jruby-core:jar:10.0.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for com.coderplus.maven.plugins:copy-rename-maven-plugin is missing.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```
=> copy-rename-maven-plugin version

core/src/main/java/org/jruby/RubyArray.java, core/src/main/java/org/jruby/RubyBignum.java, core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyComplex.java, core/src/main/java/org/jruby/RubyData.java, core/src/main/java/org/jruby/RubyException.java, core/src/main/java/org/jruby/RubyFixnum.java, core/src/main/java/org/jruby/RubyFloat.java, core/src/main/java/org/jruby/RubyHash.java, core/src/main/java/org/jruby/RubyMarshal.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/RubyProcess.java, core/src/main/java/org/jruby/RubyRange.java, core/src/main/java/org/jruby/RubyRational.java, core/src/main/java/org/jruby/RubyRegexp.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/RubyStruct.java, core/src/main/java/org/jruby/RubySymbol.java, core/src/main/java/org/jruby/RubySystemCallError.java, core/src/main/java/org/jruby/api/Error.java, core/src/main/java/org/jruby/ext/set/RubySet.java, core/src/main/java/org/jruby/runtime/ObjectMarshal.java, core/src/main/java/org/jruby/runtime/builtin/IRubyObject.java, core/src/main/java/org/jruby/runtime/marshal/MarshalDumper.java, core/src/main/java/org/jruby/runtime/marshal/MarshalLoader.java, core/src/main/java/org/jruby/runtime/marshal/UnmarshalCache.java, core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java, core/src/main/java/org/jruby/util/io/RubyInputStream.java
* Propagate context and stream through stack.
* Privatize methods that don't need to be public.
* Deprecate UnmarshalStream for removal.
* Rename Dumper to MarshalDumper
* Add default impls of deprecated ObjectMarshal methods so they can be dropped by ext authors over time
=> MarshalLoader to match dumper

core/src/main/java/org/jruby/ext/tracepoint/TracePoint.java
tracepoint ends up dyncalling into a Ruby method and that method basically replaces the original callInfo for the method you will call right after calling your tracepoint ruby code.  The fix is to just save it off until you are done and restore it before the traced method is called.  
This should be generalized for all tracepoint events since the fix is in the main events method.
Fixes #8688
=> Save original callers callInfo in tracepoint

core/src/main/java/org/jruby/RubyString.java
A chilled string was warning on itself in a StringIO which was calling itself somehow (inspectin value?) and it would recursively go back to warning about chill on itself.  The scenario why is not 100% solid for me but the reason is.
=> was recursively warning on itself

core/src/main/java/org/jruby/RubyMethod.java
Fixes #8698.  I made similar logic for blocks as the internal arity value which execution decides things is different than the external arity that #arity provides.
=> Add missing logic I added for procs to methods for ruby-facing arity

core/src/main/java/org/jruby/RubyString.java
MRI test passes in `capacity: -1` into String#initialize.  Simple fix.
=> Negative capa

bin/jruby.sh
The launcher now detects the Java version and uses the appropriate AppCDS flags. If I researched correctly, AppCDS is supported on Java 10+ and the AutoCreateSharedArchive flag on 19+. The modification time of the JRuby JAR is used to determine if the AppCDS archive should be explicitly regenerated.
The Java version currently does not factor into the regeneration calculation. The easiest solution would be to have an archive for every Java version, which would only involve sticking the relevant version in the filename, but could get unwieldy without a way to clean up old archives. We could also store the last-used version in a sidecar file, which also wouldn't be too bad since we already need access to the JRuby folder. I could use some input on what strategy we would prefer.
=> Refactor launcher AppCDS logic

bin/.jruby.module_opts, bin/jruby.sh
This adds flags for native access and unsafe memory functions and cleans up some of the launcher logic around Java version detection.
Relates to #8696.
=> Apply Java version-specific flags in launcher script

core/src/main/ruby/jruby/kernel/gem_prelude.rb
* Don't bother trying to load did_you_mean and syntax_suggest if gems are not enabled.
* Clear gem paths after load when gems are enabled.
Fixes jruby/jruby#8712
=> Restructure gem_prelude to fit JRuby's needs

core/src/main/java/org/jruby/parser/RubyParserBase.java
In any eval anywhere `it` was failing to be made properly.  It was because previous fix only checked if it was not an eval parse and not whether the block scope was not specifically an eval itself (evals are modelled as blocks from a scoping perspective).
=> Fixes #8735.  it in eval broken

core/src/main/java/org/jruby/javasupport/JavaUtil.java
Blurry-eyed editing for new JRuby API ended up making a simple mistake.  Fixes #8740
=> NUMERIC_TO_OBJECT was making BigDecimal a Long

core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java, test/jruby/test_higher_javasupport.rb, test/org/jruby/javasupport/test/TestConcurrentMap.java, test/org/jruby/javasupport/test/TestConcurrentMapFactory.java
The test case is mirrored after a real-world Map impl from Guava:
```ruby
map = com.google.common.cache.CacheBuilder.new_builder.build.as_map 
map.compute(:foo) { |_, value| 42 }
```
leading to a false-positive warning:
```
(RuntimeError) multiple Java methods found, dumping backtrace and choosing compute(java.lang.Object,java.util.function.BiFunction)
```
upon inspection of the `CallableSelector` there were 2 methods:
- `public default java.lang.Object java.util.concurrent.ConcurrentMap.compute(java.lang.Object,java.util.function.BiFunction)` 
- `public default java.lang.Object java.util.Map.compute(java.lang.Object,java.util.function.BiFunction)]`
=> [ji] avoid false duplicate method warning

core/src/main/java/org/jruby/RubyClass.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/runtime/opto/FailoverSwitchPointInvalidator.java, core/src/main/java/org/jruby/runtime/opto/GenerationAndSwitchPointInvalidator.java, core/src/main/java/org/jruby/runtime/opto/GenerationInvalidator.java, core/src/main/java/org/jruby/runtime/opto/Invalidator.java, core/src/main/java/org/jruby/runtime/opto/ObjectIdentityInvalidator.java, core/src/main/java/org/jruby/runtime/opto/SwitchPointInvalidator.java
JRuby 10 enables invokedynamic for all optimization by default. Unfortunately, some of the plumbing around invokedynamic use has never seen much in the way of profiling and optimization. This can impact early boot times for applications and early execution performance and warmup.
This PR will be a pass over the key parts of indy infrastructure with a goal of "harm reduction" when boot-time and early runtime common cases hit this plumbing heavily.
Optimizations included:
* Reduce overhead from hierarchy-based invalidation by right-sizing lists and avoiding re-invalidation of unused SwitchPoints.
=> Reduce overhead of indy plumbing

.gitignore
For me, this one is (currently) named like `jruby-java21.0.6.jsa`
=> More broad jsa gitignore

core/src/main/java/org/jruby/util/Sprintf.java, spec/ruby/core/kernel/shared/sprintf.rb
In that case, nothing is written. It's documented: https://docs.ruby-lang.org/en/3.4/format_specifications_rdoc.html#:~:text=if%20the%20precision%20is%200%20and%20the%20value%20is%200%2C%20nothing%20is%20written
NOTE: I found this code quite hard to follow and there was at least one other place I contemplated implementing a fix. Not sure if what I chose is in fact the best place for a fix.
=> Fix `sprinf` with explicit zero precision and zero value

core/src/main/java/org/jruby/parser/RubyParserBase.java, spec/ruby/language/block_spec.rb
parameterless blocks must check for `it` outside the block in case it exists already
Fixes #8767
=> parameterless blocks must check for `it` outside the block in case it exists already

core/src/main/java/org/jruby/parser/RubyParserBase.java
== and === need to support endless method definitions
Fixes #8776
=> == and === need to support endless method definitions

core/src/main/java/org/jruby/ext/ffi/jffi/NativeClosureProxy.java
ffi LONG/ULONG call different value methods.  Fixes #8780.
During threadcontext/API work I accidentally combined long with unsigned long logic.
=> ffi LONG/ULONG call different value methods

core/src/main/java/org/jruby/parser/RubyParserBase.java
Fixes #8796
There is a magic function `dyna_in_block` and it was using the hard containing lexiical scope (`scopeType`) and not the actual current scope (`type`).  Very confusing naming to the point I melded these two fields into only being a single field.
=> `it` broken in irb. Used wrong scope type field in parser.

core/src/main/java/org/jruby/RubyModule.java
All of these paths always passed true to cache any "undef" result, to avoid re-searching when we know nothing is there. This commit unifies all those paths and avoids a non-caching path altogether, which laterally fixes the potential (but never observed) NPE that was reported in #8805.
This could be an alternate fix for #8805 but I wanted to get more eyes on it.
=> Always cache undef along these paths

core/src/main/java/org/jruby/parser/RubyParser.java, core/src/main/java/org/jruby/parser/RubyParser.y, core/src/main/java/org/jruby/parser/RubyParserBase.java
As it turns out the problem is that JRuby grammar file arg_splat is not made into a splatNode whereas it is in MRI (this involves dual use of this grammar file with ripper but I do not want to try and fix whatever the underlying problem is).  The production `args ',' arg_splat {` was not creating the splatnode for arg_splat.  This in turn joined some tree values together instead of nesting them.
Will make separate PR for 9.4 as the grammar file will not cleanly apply
=> Missing splatNode creation

.github/workflows/ci.yml, core/src/main/java/org/jruby/javasupport/JavaSupport.java, core/src/main/java/org/jruby/javasupport/JavaSupportImpl.java, core/src/main/java/org/jruby/javasupport/binding/ClassInitializer.java, core/src/main/java/org/jruby/util/cli/Options.java, core/src/main/java/org/jruby/util/collections/ClassValue.java, core/src/main/java/org/jruby/util/collections/ClassValueCalculator.java, core/src/main/java/org/jruby/util/collections/Java7ClassValue.java, core/src/main/java/org/jruby/util/collections/StableClassValue.java, spec/regression/GH-8842_interface_impl_duck_typed_classes_do_not_unload.rb
JRuby includes two versions of ClassValue: one with a hard- referenced Map from Class to value, and one based on a normal ClassValue but with the added oddity that it hard-references its values while storing them in the ClassValue slot weakly. This was originally intended to allow the values to collect properly when the ClassValue collected, but on recent testing it seems to just leak in a different way.
This change siwtches everything to normal ClassValue. Given this change, the example cases in #8842 no longer leak, nor does a more aggressive torture test that also spins up and tears down JRuby runtimes as well as interface implementations. A 30-minute run of that test uses a lot of memory and GCs heavily, but does level off in both heap and metaspace. Forced GCs reduce both nearly back …
=> Use a normal ClassValue for all such cases

core/src/main/java/org/jruby/javasupport/JavaSupport.java, core/src/main/java/org/jruby/util/collections/StableClassValue.java
Because the proxy calculation tends to recurse for classes, there may be multiple StableValue preparing proxies at the same time. Depending on the ordering of the classes encountered, this can lead to deadlocks.
This fixes the deadlock by matching MapBasedClassValue's one lock per ClassValue instance, and also properly double-checks the value which was missing in the previous version.
=> Fix locking of stable class values for JI proxies

.github/workflows/ci.yml, .github/workflows/manual-snapshot-publish-21.yml, .github/workflows/manual-snapshot-publish.yml, .github/workflows/nightly-snapshot-publish-21.yml, .github/workflows/nightly-snapshot-publish.yml, .github/workflows/snapshot-publish.yml, maven/jruby-complete/pom.rb, pom.rb, pom.xml
There's a number of changes here to support deploying snapshots locally or automatically on GHA:
* Moving GPG signing to the `snapshots` profile and using that profile to create snapshots instead of `release`.
* Switching jruby-complete's source jar generation to use the contents of jruby-base instead of jruby-core (which was empty and now seems to be failing to generate altogether).
* Updates to the maven configuration in the GHA jobs to use the "central" repository name.
This appears to be working to deploy snapshots now locally and on GHA, but I have some doubts:
* Why did the jruby-complete use of jruby-core sources work before but suddenly fail. Why did it release ok for 9.4.13.0 and simply publish no sources jar (something I thought Maven Central rejected)?
* I'm pretty sure …
=> Update snapshot deploy to use new maven infrastructure

core/src/main/java/org/jruby/util/io/EncodingUtils.java
The changes here improve the handling of different `String#encode` arities, specifically fixing the simple replacement issue reported in #8872 but also reducing the duplicated work along the different arity paths.
Fixes #8872.
=> Handle simple transcoding replacement correctly

core/src/main/java/org/jruby/RubyTime.java, spec/regression/GH-8854_time_new_with_empty_keywords_spec.rb, test/jruby/test_time.rb
Fixes #8854 and #8860.
```
#8854
irb> Time.new(2025, 4, 3, **{})
org.jruby.dist/org.jruby.RubyTime.initialize(RubyTime.java:1758):
Cannot load from object array because "opts" is null (Java::JavaLang::NullPointerException)
#8860
irb> Time.new(2025, 4, 3, in: 'UTC')
=> 2025-04-01 00:00:00 +0000
```
The [`travel_to` test helper from ActiveSupport](https://github.com/rails/rails/blob/v7.1.5.1/activesupport/lib/active_support/testing/time_helpers.rb#L185) triggers the empty keywords issue.
As a result of fixing the NullPointerException and writing a regression test, it actually triggered the other issue of losing the last argument when using keywords.
I realised that if keywords was empty, `hasKeywords` still returns true and `extractKeywordArgs` returns null, and `args` doesn't have the Hash …
=> Fix `Time.new` when using (empty) keywords (2 issues)

core/src/main/java/org/jruby/RubyString.java, spec/compiler/general_spec.rb
Chilled strings are constructed much like frozen strings, reusing the same bytelist for each new instance. But unlike frozen strings, chilled strings may still be mutated for now. We mark all such strings as having a shared ByteList to ensure that it is copied before making modifications.
Fixes #8861
=> Always set chilled strings as sharing bytelist

lib/ruby/stdlib/win32/registry.rb
The library was renamed to `win32api` some time ago and this require was never updated. A recent change to resolv.rb (77471759d) now triggers loading win32/registry.rb, which in turn hits this incorrectly-cased require.
Whether the path should require successfully on Windows is a separate debate, but we mostly use JDK classes to check for the target file. That logic may not consider the two paths identical and not find the file on Windows.
When running inside a jar, all paths must be cased properly, so this will also fix the situation of running with jruby-complete on a Windows system.
Fixes #8866
=> Require the correct case for this library

core/src/main/java/org/jruby/util/io/PopenExecutor.java, spec/ruby/core/io/popen_spec.rb
The value passed to IO.popen for the chdir keyword argument should be coerced like other paths.
Fixes #8859.
=> Coerce the chdir for popen

lib/pom.rb, lib/pom.xml, pom.rb, pom.xml
This fixes issues with downloads (of poms, gems, etc) sometimes garbling the output and including null bytes (jruby/jruby-maven-plugins@fea0a42502af8bb94e9dc6c9e4a2d7aa394a08cf) as well as updating to latest JRuby 9.4 and a few other small fixes.
=> Update maven plugins to latest

spec/tags/ruby/library/stringscanner/check_until_tags.txt, spec/tags/ruby/library/stringscanner/exist_tags.txt, spec/tags/ruby/library/stringscanner/scan_until_tags.txt, spec/tags/ruby/library/stringscanner/search_full_tags.txt, spec/tags/ruby/library/stringscanner/skip_until_tags.txt, test/mri/strscan/test_ractor.rb, test/mri/strscan/test_stringscanner.rb
My update of strscan to latest (3.1.5) did not include updates to the tests. I do that here:
* CRuby tests updated to `v3.1.5` version of strscan tests from ruby/strscan.
* Ruby specs must be tagged since they are guarded on Ruby version and continue to run old specs on newer strscan.
=> Get strscan tests passing again

core/src/main/java/org/jruby/RubyArray.java, spec/ruby/core/array/insert_spec.rb
This PR addresses #8902 in two ways:
* Always try to coerce the position argument in the varargs path of `Array#insert`, matching behavior changed for https://bugs.ruby-lang.org/issues/13558.
* Also route specific-arity calls one the variable-arity path to their specific-arity forms. This largely eliminates the need for the first change above, but is more consistent with other places we have both specific and variable-arity method bindings.
=> Always check array insert pos

core/src/main/java/org/jruby/ext/rbconfig/RbConfigLibrary.java
In order to support an upcoming patch to RubyGems that will ignore the platform version (e.g. darwin-22), we make the following tweaks to our RbConfig::CONFIG['arch'] value:
* Add a hyphen before the Java version.
* Normalize Java 1.8 to 8 so all possible versions are integers.
This does not fix rubygems/rubygems#3520 but will support a future fix.
=> Normalize arch to universal-java-version

core/src/main/java/org/jruby/RubyModule.java, spec/ruby/core/module/const_defined_spec.rb
The fix here is a little bit form-fitting but largely avoids inheriting constants from Object when doing String-based constant lookups and skips the additional search of Object if we are doing a path search.
=> Don't include Object for pathed constant searches

core/src/main/java/org/jruby/ir/targets/indy/InvokeSite.java
Native methods that don't accept formal keyword arguments and Ruby methods that are ruby2_keywords will not use callInfo to handle formal keyword arguments. We clear it here so any incoming kwargs flags do not get stuck and interfere with other calls.
Fixes #8782
=> Don't set callInfo when target does not use kwargs

core/src/main/java/org/jruby/runtime/load/ExternalScript.java, core/src/main/java/org/jruby/runtime/load/LoadServiceResourceInputStream.java
Just a few tweaks based on some recent profiling of JRuby 10, both doing a simple hello world `jruby -e gets` and spinning up JRuby instances in a tight loop.
=> Tweaks to further improve startup speed and memory use

core/src/main/java/org/jruby/ir/targets/indy/InvokeSite.java, spec/ruby/core/module/ruby2_keywords_spec.rb, spec/tags/ruby/core/module/ruby2_keywords_tags.txt
In https://github.com/jruby/jruby/issues/8918 we attempted to fix an issue where the keyword arguments `callInfo` flags were getting stuck passing through a native method that did not formally accept keyword arguments. Unfortunately that change incorrectly included Ruby-based `ruby2_keywords` methods in the set of methods considered to not accept formal keywords and require `callInfo` clearing. This led to #8920 where a `ruby2_keywords` method fails to properly forward incoming keyword arguments to a non-`ruby2_keywords` method.
The fix here narrows the `callInfo` clearing to only native methods that do not formally accept keywords, preventing such flags from propagating to other calls but avoiding the `callInfo` clearing previously done for `ruby2_keywords` Ruby-based methods.
=> Don't clear callInfo for Ruby methods

core/src/main/java/org/jruby/util/Pack.java, spec/ruby/core/string/unpack/m_spec.rb, spec/ruby/core/string/unpack/u_spec.rb, spec/ruby/core/string/unpack1_spec.rb
This fixes https://github.com/jruby/jruby/issues/8933
=> Fix integer overflow in buffer length calculation for unpack('m') and unpack('u')

core/src/main/java/org/jruby/runtime/load/LibrarySearcher.java, core/src/main/java/org/jruby/runtime/load/LoadService.java
This was changed in CRuby in 2010.
See https://github.com/ruby/ruby/commit/208a51ffa3551bc7548aa878a46ebb72901110a1
This fixes the remaining two failures running mustermann specs.
See https://github.com/sinatra/mustermann/pull/145
=> Update ArgumentError for missing file to match CRuby

core/src/main/java/org/jruby/ext/ffi/AbstractMemory.java
At some point during JRuby 10 we decided to pre-alloc get_array_of_string.  Later JRuby API changes made it appear like those new APIs caused this but it was pre-alloc.
The problem is sassc (or FFI) decides to ask for an array or strings and the size of the memory alloced is MAX_LONG (big question on why unrelated to this issue).  get_array_of_strings has an if check for null memory and immediately exits the fill loop and basically makes a zero length array.  By pre-allocing we basically do not ever see that this is a small array.
I reverted to using an empty array like 9.4 still does.
=> Fixes #8948. SassC - array size too big

core/src/main/java/org/jruby/RubyRange.java, spec/ruby/core/range/count_spec.rb
Logic installed to prevent large ranges from manually iterating to calculate a count (79ee9204d6786a587509acd500fbd4e8831c3a16) short-circuited the fallback on `Enumerable#count` logic. That broke `count` when passed a block (as described in #8955). Additionally, we did not handle the case where `Range#count` is passed an argument.
This PR fixes both cases and adds specs.
=> Handle argument or block passed to Range#count

core/src/main/java/org/jruby/RubyBasicObject.java, core/src/main/java/org/jruby/RubyMatchData.java, core/src/main/java/org/jruby/RubyModule.java, core/src/main/java/org/jruby/RubyNameError.java, core/src/main/java/org/jruby/RubyString.java, core/src/main/java/org/jruby/api/Convert.java, core/src/main/java/org/jruby/ir/runtime/IRRuntimeHelpers.java, core/src/main/java/org/jruby/ir/targets/indy/BuildDynamicStringSite.java, spec/compiler/general_spec.rb, spec/ruby/language/string_spec.rb
Logic for "AsString" in a dynamic string must verify the result of calling to_s is a String, or else use anyToString on the original object. Previous logic here only called to_s and did not verify the result, proceeding to append non-string values like Integer or Float rather than falling back. The patch here adds an additional guard around the to_s call to perform this check and fallback.
This only affects the rare case where someone has implemented a to_s method that does not return a String, and is only observable once the dstring has been optimized and invoked twice.
As this is a bit invasive, I'm marking it for 10.0.3.0 so we can create more specs and do more verification that it works correctly before release.
=> Verify to_s is string or fall back on anyToString

core/src/main/java/org/jruby/util/cli/Options.java, spec/jruby/options/console_color_spec.rb
This uses the new `isTerminal` method when running on JDK 22+ due to that version now always returning a non-null `Console` from `System.console()`.
I may modify the handling of these color-configuring properties such that "true" means "use color if we are outputting to a terminal", defaulting to true.
Fixes #8934.
=> New check for System.console tty on JDK 22+

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, USERS.md, maven/jruby-dist/src/main/assembly/common.xml
Several open source projects have a list of users or use cases in their repository, so it's easily accessible and included in the source or binary distributions. This is an initial version of that list based on one from the Cilium project: https://github.com/cilium/cilium/blob/main/USERS.md
TODO:
Once it is in place, we can send a blast out on social media for current users to add themselves.
=> Add a USERS.md file to track JRuby users

BUILDING.md, lib/pom.rb, lib/pom.xml
Bump cgi version to fix CVE-2025-27220 and CVE-2025-27219
=> Secuity: Bump cgi to 0.4.2. CVE-2025-27220 CVE-2025-27219

core/src/main/java/org/jruby/runtime/load/LibrarySearcher.java, core/src/test/java/org/jruby/runtime/load/TestLoadService.java
The code here is intended to walk the incoming feature, looking for either '.' or '/' in order to break up the feature into a path and filename. This is then compared with the load path to find a match, indicating that the feature has been loaded via those paths.
The bug is that it should find one of those characters or leave the search index 'e' at the beginning of the feature string for a subsequent check, but it was ported incorrectly from the original C code. Index of stopping at the beginning of the string, it allows one more decrement leaving 'e' as -1, and String.charAt raises.
This is normally only triggered for features that are being required at the same time across threads, and which have not yet been expanded to their full load path form. With the unexpanded feature in flight, …
=> Fix index -1 error while searching for feature path

.mvn/extensions.xml, lib/pom.rb, lib/pom.xml
The lib hack here put a blank openssl.rb into lib/target/lib and added that directory to the LOAD_PATH of the polyglot JRuby runtime. This was done many years ago, perhaps before we had refined how standard libraries could be loaded from released JRuby stdlib jars, and does not appear to be necessary now for a successful build. In jruby/jruby#8634 we learned that because newer RubyGems depends on OpenSSL at runtime, and we're feeding it a bogus openssl.rb, newer polyglot versions that depends on newer JRuby versions cannot successfully build JRuby from repo.
This PR removes the openssl.rb lib hack altogether and does not appear to break local builds of JRuby while allowing polyglot to be upgraded to latest.
Fixes jruby/jruby#8634
=> Upgrade polyglot and remove openssl lib hack

core/src/main/java/org/jruby/RubyEnumerable.java
When incoming argument list contains arguments of the form ([1, 2], 3), ensure the first element is passed as an array to the to_h block, rather than yielded as a splattable argument list.
Fixes part of jruby/jruby#8435
See ruby/spec#1283 for some discussion about how to write a spec for this behavior.
=> Pass multi-elt array key for to_h using yieldArray

.rubocop-pom.yml, bench/pom.rb, core/pom.rb, lib/pom.rb, maven/jruby-complete/pom.rb, maven/jruby-complete/src/templates/osgi_many_bundles_with_embedded_gems/gems-bundle/pom.rb, maven/jruby-complete/src/templates/osgi_many_bundles_with_embedded_gems/pom.rb, maven/jruby-complete/src/templates/osgi_many_bundles_with_embedded_gems/scripts-bundle/pom.rb, maven/jruby-complete/src/templates/osgi_many_bundles_with_embedded_gems/test/pom.rb, maven/jruby-dist/pom.rb, maven/jruby-jars/src/it/extended/pom.rb, maven/jruby/pom.rb, maven/jruby/src/it/extended/pom.rb, maven/jruby/src/it/j2ee_jetty/pom.rb, maven/jruby/src/it/j2ee_tomcat/pom.rb, maven/jruby/src/it/j2ee_wildfly/pom.rb, maven/jruby/src/it/many_jars_with_embedded_gems/app/pom.rb, maven/jruby/src/it/many_jars_with_embedded_gems/pom.rb, maven/jruby/src/it/many_jars_with_embedded_gems/zip_gem/pom.rb, maven/jruby/src/it/many_jars_with_embedded_gems_ng/app/pom.rb, maven/jruby/src/it/many_jars_with_embedded_gems_ng/gem1/pom.rb, maven/jruby/src/it/many_jars_with_embedded_gems_ng/gem2/pom.rb, maven/jruby/src/it/many_jars_with_embedded_gems_ng/pom.rb, maven/jruby/src/it/tomcat/pom.rb, maven/jruby/src/templates/j2ee_wlp/pom.rb, maven/jruby/src/templates/osgi_all_inclusive/pom.rb, maven/pom.rb, pom.rb, shaded/pom.rb, test/pom.rb
Clean up all polyglot pom files using automated tools. These changes are highly unlikely to merge across branches, so we'll run this process against 9.4 and 10 separately.
=> Use RuboCop to clean up poms (9.4)

core/src/main/java/org/jruby/parser/RubyParserBase.java, spec/tags/ruby/language/assignments_tags.txt
error string changed for ```            eval "obj[:a, &block] = 2"```
=> Fix language spec where error string changed

bin/jruby.sh
Added some checks to the launcher to handle missing `HOME`, `JAVA_HOME`, or argument to `-{C,e,I,S}`
Fixes #8747
=> Launcher: Defensive fixes

core/src/main/java/org/jruby/runtime/invokedynamic/InvokeDynamicSupport.java, spec/compiler/general_spec.rb
Edit: a previous version of this patch attempted to switch these lookups to `publicLookup()`, but that broke several tests and internal logic that needed "more than public" access. The new patch was proposed by our friends on the core-libs-dev OpenJDK list.
The Lookup acquired from MethodHandles.lookup appears to produce
IllegalAccessException for cases that publicLookup does not. This
appears to be due to a JDK bug, but we can work around it by'
explicitly requesting read access to the target class's module.
There have been similar bugs relating to the use of
MethodHandles.lookup versus MethodHandles.publicLookup. The most
recent bug was filed in https://github.com/jruby/jruby/issues/8987. Related JRuby bugs and
an OpenJDK bug filed by me are also referenced from there. There's
also a …
=> Explicitly request access before Lookup.find*

core/src/main/java/org/jruby/Ruby.java, core/src/main/java/org/jruby/javasupport/binding/MethodGatherer.java, core/src/main/java/org/jruby/runtime/invokedynamic/InvokeDynamicSupport.java
This PR is an alternative (and probably more correct) fix for #8987, and does the following:
* Removes the old fix to add new modules reads before acquiring method handles (#8989).
* Avoids binding classes that are not **both** in a readable module and public, rather than just basing that determination on Java class visibility.
This fixes the issues in #8987 without adding new module reads for every method handle acquisition.
See the following OpenJDK core-libs-dev discussion for details: https://mail.openjdk.org/pipermail/core-libs-dev/2025-September/151017.html
=> Avoid binding unreadable modules' classes

core/src/main/java/org/jruby/runtime/load/LibrarySearcher.java, core/src/main/java/org/jruby/runtime/load/LoadService.java
Backport of #8929, since this message change appears to have happened long ago in CRuby.
Does not fix anything significant but 9.4.x will now also be green on mustermann specs (cc @dentarg).
Mentioned along with the kwargs regression fix (#8922, backported as #9001) in #9000.
=> Backport ArgumentError message update from 2010

core/src/main/java/org/jruby/RubyKernel.java, spec/ruby/core/kernel/warn_spec.rb
Ruby simply ignores the nil uplevel (it is the default value), JRuby tries to convert it to an integer.
I wanted to write such code for a polyfill in https://github.com/ruby/prism/pull/3647 but had to change it around to make work on jruby.
=> Handle `warn(foo, uplevel: nil`)

lib/pom.rb, lib/pom.xml
=> Rexml security updateUpdate rexml gem to solve CVE-2025-58767 (9.4)

core/src/main/java/org/jruby/ext/ripper/HeredocTerm.java, core/src/main/java/org/jruby/lexer/yacc/HeredocTerm.java
We need to remove \r from heredoc strings.  This should fix #9018.  There may be a followup in StringTerm if it also does the wrong thing in multiline strings.
=> We need to remove \r from heredoc strings

core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java, core/src/main/java/org/jruby/ext/ripper/RubyLexer.java, core/src/main/java/org/jruby/lexer/yacc/RubyLexer.java, core/src/main/java/org/jruby/util/ConvertDouble.java, core/src/main/java/org/jruby/util/SafeDecimalParser.java, core/src/main/java/org/jruby/util/SafeDoubleParser.java, core/src/main/java/org/jruby/util/SafeFloatParser.java
This came about when an old version of Java had a CVE and would end up in an endless loop processing a number (numbers?).  This was fixed in Java 1.6.
Here is a reference to it being fixed:
https://www.exploringbinary.com/fpupdater-fixes-the-java-2-2250738585072012e-308-bug/
This should get rid of multiple scans and simplify the overall codepath of converting a string to a double/bigdecimal.
=> Retire safe double processing utilities
